'use strict';
(()=>{
 const model=RoomStudyModel,canvas=document.getElementById('scene'),ui=id=>document.getElementById(id),renderer=new RoomStudyRenderer(canvas,model),{V}=RSMath;
 const state={mode:'orbit',time:15.5,day:266,lat:30,north:0,theme:'oak',cutaway:true,quality:1,lamps:'auto'};
 const orbit={target:[5.5,.45,3.35],az:.55,el:.82,r:15.8};let player={p:[7.85,1.62,6.0],yaw:0,pitch:0},keys={},drag=null,joy=[0,0],last=0,playing=false,selected=null;
 function sunCalc(){const g=2*Math.PI/365*(state.day-1),dec=.409*Math.sin(g-1.39),lat=state.lat*Math.PI/180,H=(state.time-12)*Math.PI/12,up=Math.sin(lat)*Math.sin(dec)+Math.cos(lat)*Math.cos(dec)*Math.cos(H),east=-Math.cos(dec)*Math.sin(H),north=Math.cos(lat)*Math.sin(dec)-Math.sin(lat)*Math.cos(dec)*Math.cos(H),a=state.north*Math.PI/180,dir=V.norm([east*Math.cos(a)-north*Math.sin(a),up,-east*Math.sin(a)-north*Math.cos(a)]),alt=Math.asin(Math.max(-1,Math.min(1,up)))*180/Math.PI,daylight=Math.max(0,Math.min(1,(alt+6)/26)),warm=Math.max(0,Math.min(1,alt/35));return{dir,alt,power:alt>0?.8+2.7*Math.sqrt(Math.max(up,0)):0,ambient:.08+.72*daylight,sky:[.35+.35*daylight,.39+.39*daylight,.48+.38*daylight],sunColor:[1,.55+.38*warm,.30+.55*warm],bg:[.14+.58*daylight,.17+.58*daylight,.24+.55*daylight]}}
 function camera(){if(state.mode==='orbit'){const r=orbit.r;return{eye:V.add(orbit.target,[Math.sin(orbit.az)*Math.cos(orbit.el)*r,Math.sin(orbit.el)*r,Math.cos(orbit.az)*Math.cos(orbit.el)*r]),target:orbit.target,fov:.72}}const f=[-Math.sin(player.yaw)*Math.cos(player.pitch),Math.sin(player.pitch),-Math.cos(player.yaw)*Math.cos(player.pitch)];return{eye:player.p,target:V.add(player.p,f),fov:1.05}}
 function canStand(x,z,r=.17){const b=model.bounds;if(x<b.minX+r||x>b.maxX-r||z<b.minZ+r||z>b.maxZ-r)return false;for(const c of model.colliders){const nx=Math.max(c.minX,Math.min(x,c.maxX)),nz=Math.max(c.minZ,Math.min(z,c.maxZ));if((nx-x)**2+(nz-z)**2<r*r)return false}return true}
 function move(dx,dz){const n=Math.max(1,Math.ceil(Math.hypot(dx,dz)/.05));for(let i=0;i<n;i++){const sx=dx/n,sz=dz/n;if(canStand(player.p[0]+sx,player.p[2]))player.p[0]+=sx;if(canStand(player.p[0],player.p[2]+sz))player.p[2]+=sz}}
 function gotoRoom(id){const r=model.rooms.find(x=>x.id===id);if(!r)return;state.mode='walk';player.p=[...r.p];const d=V.norm(V.sub(r.target,r.p));player.yaw=Math.atan2(-d[0],-d[2]);player.pitch=Math.asin(Math.max(-.9,Math.min(.9,d[1])));document.body.classList.add('walk');updateMode();}
 function updateMode(){ui('orbitBtn').classList.toggle('active',state.mode==='orbit');ui('walkBtn').classList.toggle('active',state.mode==='walk');ui('hint').textContent=state.mode==='orbit'?'拖动旋转 · 滚轮缩放 · 双击进入房间':'WASD 移动 · 鼠标拖动环顾 · Shift 加速 · Esc 返回总览';}
 function updateUI(){ui('timeValue').textContent=`${String(Math.floor(state.time)).padStart(2,'0')}:${String(Math.round((state.time%1)*60)).padStart(2,'0')}`;const d=new Date(Date.UTC(2026,0,state.day));ui('dateValue').textContent=`${d.getUTCMonth()+1} 月 ${d.getUTCDate()} 日`;ui('latValue').textContent=`${state.lat}°`;ui('altValue').textContent=`${sunCalc().alt.toFixed(1)}°`;for(const id of ['time','day','lat','north']){const e=ui(id);e.style.setProperty('--p',`${(+e.value-+e.min)/(+e.max-+e.min)*100}%`)}}
 function roomFromPoint(x,z){if(z<3.55){if(x<5.2)return'master';if(x>7.75)return'kitchen';return'entry'}if(x<3.45)return'study';if(x>9.55)return'bath';return'living'}
 function rayGround(clientX,clientY){const r=canvas.getBoundingClientRect(),c=camera(),x=(clientX-r.left)/r.width*2-1,y=1-(clientY-r.top)/r.height*2,f=V.norm(V.sub(c.target,c.eye)),right=V.norm(V.cross(f,[0,1,0])),up=V.cross(right,f),dir=V.norm(V.add(f,V.add(V.scale(right,x*r.width/r.height*Math.tan(c.fov/2)),V.scale(up,y*Math.tan(c.fov/2)))));if(dir[1]>=-.001)return null;const t=-c.eye[1]/dir[1];return V.add(c.eye,V.scale(dir,t))}
 function pickFurniture(x,z){let best=null,bd=Infinity;for(const o of model.objects){if(!o.selectable||o.kind==='floor'||o.kind==='wall')continue;const d=Math.hypot(o.p[0]-x,o.p[2]-z);if(d<Math.max(o.size[0],o.size[2])*.8&&d<bd){best=o;bd=d}}selected=best;if(best){ui('selection').classList.add('show');ui('selName').textContent=best.name;ui('selNote').textContent=best.note||'基础几何与材质示意。';ui('selDim').textContent=`约 ${best.size[0].toFixed(2)} × ${best.size[2].toFixed(2)} × ${best.size[1].toFixed(2)} m`}else ui('selection').classList.remove('show')}
 for(const r of model.rooms){const b=document.createElement('button');b.textContent=r.name;b.onclick=()=>gotoRoom(r.id);ui('roomNav').appendChild(b)}
 ui('time').oninput=e=>{state.time=+e.target.value;playing=false;updateUI()};ui('day').oninput=e=>{state.day=+e.target.value;updateUI()};ui('lat').oninput=e=>{state.lat=+e.target.value;updateUI()};ui('north').oninput=e=>{state.north=+e.target.value;updateUI()};
 document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{state.theme=b.dataset.theme;document.querySelectorAll('[data-theme]').forEach(x=>x.classList.toggle('active',x===b))});
 ui('playDay').onclick=()=>{playing=!playing;ui('playDay').textContent=playing?'暂停时间流转':'播放一天'};ui('orbitBtn').onclick=()=>{state.mode='orbit';document.body.classList.remove('walk');updateMode()};ui('walkBtn').onclick=()=>gotoRoom('living');ui('cutaway').onclick=()=>{state.cutaway=!state.cutaway;ui('cutaway').classList.toggle('active',state.cutaway)};ui('shot').onclick=()=>{const a=document.createElement('a');a.download='room-study.png';a.href=canvas.toDataURL('image/png');a.click()};ui('full').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();ui('sourceBtn').onclick=()=>ui('sourceModal').classList.add('show');ui('helpBtn').onclick=()=>ui('helpModal').classList.add('show');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('.modal').classList.remove('show'));
 canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,sx:e.clientX,sy:e.clientY,button:e.button}};canvas.onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.x=e.clientX;drag.y=e.clientY;if(state.mode==='orbit'){orbit.az-=dx*.005;orbit.el=Math.max(.2,Math.min(1.45,orbit.el+dy*.004))}else{player.yaw-=dx*.004;player.pitch=Math.max(-1.25,Math.min(1.25,player.pitch-dy*.004))}};canvas.onpointerup=e=>{if(drag&&Math.hypot(e.clientX-drag.sx,e.clientY-drag.sy)<5){const p=rayGround(e.clientX,e.clientY);if(p)pickFurniture(p[0],p[2])}drag=null};canvas.onwheel=e=>{e.preventDefault();if(state.mode==='orbit')orbit.r=Math.max(7,Math.min(26,orbit.r*Math.exp(e.deltaY*.001)))},{passive:false};canvas.ondblclick=e=>{if(state.mode!=='orbit')return;const p=rayGround(e.clientX,e.clientY);if(p&&canStand(p[0],p[2]))gotoRoom(roomFromPoint(p[0],p[2]))};canvas.oncontextmenu=e=>e.preventDefault();
 document.onkeydown=e=>{if(['INPUT','SELECT'].includes(e.target.tagName))return;keys[e.code]=true;if(e.code==='Escape'&&state.mode==='walk'){state.mode='orbit';document.body.classList.remove('walk');updateMode()}};document.onkeyup=e=>keys[e.code]=false;
 const j=ui('joystick'),knob=ui('knob');function jm(e){const r=j.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,l=Math.max(1,Math.hypot(dx,dy)),m=Math.min(30,l);joy=[dx/l*m/30,-dy/l*m/30];knob.style.transform=`translate(${joy[0]*30}px,${-joy[1]*30}px)`}j.onpointerdown=e=>{j.setPointerCapture(e.pointerId);jm(e)};j.onpointermove=e=>{if(j.hasPointerCapture(e.pointerId))jm(e)};j.onpointerup=j.onpointercancel=e=>{joy=[0,0];knob.style.transform='none'};
 function tick(t){const dt=Math.min(.05,(t-last)/1000||.016);last=t;if(playing){state.time=(state.time+dt*.40)%24;ui('time').value=state.time;updateUI()}if(state.mode==='walk'){let f=(keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0)+joy[1],s=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0)+joy[0];if(f||s){const speed=(keys.ShiftLeft||keys.ShiftRight?2.4:1.45)*dt;move((-Math.sin(player.yaw)*f+Math.cos(player.yaw)*s)*speed,(-Math.cos(player.yaw)*f-Math.sin(player.yaw)*s)*speed)}}renderer.render(state,camera(),sunCalc());requestAnimationFrame(tick)}
 window.roomStudy={state,model,renderer,gotoRoom,canStand,sunCalc};updateUI();updateMode();requestAnimationFrame(tick);
})();
