'use strict';
window.RoomStudyRenderer=class RoomStudyRenderer{
 constructor(canvas,model){this.canvas=canvas;this.model=model;const gl=this.gl=canvas.getContext('webgl2',{antialias:true,alpha:false});if(!gl)throw new Error('WebGL 2 unavailable');
  this.program=this._program(`#version 300 es\nlayout(location=0)in vec3 p;layout(location=1)in vec3 n;uniform mat4 model,viewProj,lightVP;out vec3 wp,wn;out vec4 sp;void main(){vec4 w=model*vec4(p,1.);wp=w.xyz;wn=normalize(mat3(model)*n);sp=lightVP*w;gl_Position=viewProj*w;}`,
  `#version 300 es\nprecision highp float;precision highp sampler2DShadow;in vec3 wp,wn;in vec4 sp;uniform vec3 baseColor,sunDir,sunColor,skyColor,eye;uniform float ambient,sunPower,alpha;uniform sampler2DShadow shadowMap;out vec4 outColor;float shadow(){vec3 q=sp.xyz/sp.w*.5+.5;if(q.x<0.||q.x>1.||q.y<0.||q.y>1.||q.z>1.)return 1.;float s=0.;vec2 px=1./vec2(textureSize(shadowMap,0));for(int x=-1;x<=1;x++)for(int y=-1;y<=1;y++)s+=texture(shadowMap,vec3(q.xy+vec2(x,y)*px,q.z-.0015));return s/9.;}void main(){vec3 N=normalize(wn);float nl=max(dot(N,normalize(sunDir)),0.);vec3 c=baseColor*(skyColor*ambient+sunColor*sunPower*nl*shadow());float rim=pow(1.-max(dot(normalize(eye-wp),N),0.),3.);c+=rim*.035;outColor=vec4(pow(c,vec3(1./2.2)),alpha);}`);
  this.depthProgram=this._program(`#version 300 es\nlayout(location=0)in vec3 p;uniform mat4 model,lightVP;void main(){gl_Position=lightVP*model*vec4(p,1.);}`,`#version 300 es\nprecision highp float;void main(){}`);
  this.u=this._uniforms(this.program);this.du=this._uniforms(this.depthProgram);this._cube();this._shadow();gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.enable(gl.CULL_FACE);gl.cullFace(gl.BACK);
 }
 _program(vs,fs){const gl=this.gl,compile=(t,s)=>{const sh=gl.createShader(t);gl.shaderSource(sh,s);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(sh));return sh},p=gl.createProgram(),v=compile(gl.VERTEX_SHADER,vs),f=compile(gl.FRAGMENT_SHADER,fs);gl.attachShader(p,v);gl.attachShader(p,f);gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));return p}
 _uniforms(p){const gl=this.gl,o={};for(let i=0;i<gl.getProgramParameter(p,gl.ACTIVE_UNIFORMS);i++){const a=gl.getActiveUniform(p,i);o[a.name]=gl.getUniformLocation(p,a.name)}return o}
 _cube(){const gl=this.gl;const a=[];const face=(n,p0,p1,p2,p3)=>{for(const q of [p0,p1,p2,p0,p2,p3])a.push(...q,...n)};face([1,0,0],[.5,-.5,-.5],[.5,.5,-.5],[.5,.5,.5],[.5,-.5,.5]);face([-1,0,0],[-.5,-.5,.5],[-.5,.5,.5],[-.5,.5,-.5],[-.5,-.5,-.5]);face([0,1,0],[-.5,.5,-.5],[-.5,.5,.5],[.5,.5,.5],[.5,.5,-.5]);face([0,-1,0],[-.5,-.5,.5],[-.5,-.5,-.5],[.5,-.5,-.5],[.5,-.5,.5]);face([0,0,1],[-.5,-.5,.5],[.5,-.5,.5],[.5,.5,.5],[-.5,.5,.5]);face([0,0,-1],[.5,-.5,-.5],[-.5,-.5,-.5],[-.5,.5,-.5],[.5,.5,-.5]);this.vao=gl.createVertexArray();gl.bindVertexArray(this.vao);const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(a),gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,3,gl.FLOAT,false,24,12);this.count=a.length/6;gl.bindVertexArray(null)}
 _shadow(){const gl=this.gl,s=1536;this.shadowSize=s;this.shadowTex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,this.shadowTex);gl.texImage2D(gl.TEXTURE_2D,0,gl.DEPTH_COMPONENT24,s,s,0,gl.DEPTH_COMPONENT,gl.UNSIGNED_INT,null);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_COMPARE_MODE,gl.COMPARE_REF_TO_TEXTURE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_COMPARE_FUNC,gl.LEQUAL);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);this.shadowFbo=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,this.shadowFbo);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.TEXTURE_2D,this.shadowTex,0);gl.drawBuffers([gl.NONE]);gl.bindFramebuffer(gl.FRAMEBUFFER,null)}
 resize(quality=1){const d=Math.min(devicePixelRatio||1,quality?1.6:1),w=Math.max(1,Math.floor(this.canvas.clientWidth*d)),h=Math.max(1,Math.floor(this.canvas.clientHeight*d));if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h}}
 colorFor(o,theme){return this.model.fixed[o.mat]||this.model.themes[theme][o.mat]||[.6,.6,.6]}
 render(state,cam,sun){const {M,V}=RSMath,gl=this.gl;this.resize(state.quality);const aspect=this.canvas.width/this.canvas.height,vp=M.mul(M.perspective(cam.fov,aspect,.04,100),M.lookAt(cam.eye,cam.target));const center=[5.6,.7,3.4],le=V.add(center,V.scale(sun.dir,22)),lvp=M.mul(M.ortho(-9,9,-9,9,.1,50),M.lookAt(le,center,Math.abs(sun.dir[1])>.95?[0,0,1]:[0,1,0]));const visible=o=>!(state.mode==='orbit'&&state.cutaway&&o.kind==='wall'&&o.p[1]>.9);
  gl.bindFramebuffer(gl.FRAMEBUFFER,this.shadowFbo);gl.viewport(0,0,this.shadowSize,this.shadowSize);gl.clear(gl.DEPTH_BUFFER_BIT);gl.useProgram(this.depthProgram);gl.uniformMatrix4fv(this.du.lightVP,false,lvp);gl.bindVertexArray(this.vao);for(const o of this.model.objects){if(!visible(o)||o.mat==='glass')continue;gl.uniformMatrix4fv(this.du.model,false,M.trs(o.p,o.size,o.yaw));gl.drawArrays(gl.TRIANGLES,0,this.count)}
  gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.clearColor(...sun.bg,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(this.program);gl.uniformMatrix4fv(this.u.viewProj,false,vp);gl.uniformMatrix4fv(this.u.lightVP,false,lvp);gl.uniform3fv(this.u.sunDir,sun.dir);gl.uniform3fv(this.u.sunColor,sun.sunColor);gl.uniform3fv(this.u.skyColor,sun.sky);gl.uniform3fv(this.u.eye,cam.eye);gl.uniform1f(this.u.ambient,sun.ambient);gl.uniform1f(this.u.sunPower,sun.power);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,this.shadowTex);gl.uniform1i(this.u.shadowMap,0);gl.bindVertexArray(this.vao);
  const solid=this.model.objects.filter(o=>o.mat!=='glass'&&visible(o)),glass=this.model.objects.filter(o=>o.mat==='glass'&&visible(o));gl.disable(gl.BLEND);for(const o of solid)this._draw(o,state);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);for(const o of glass)this._draw(o,state,.22);gl.depthMask(true);gl.disable(gl.BLEND);this.viewProj=vp;
 }
 _draw(o,state,alpha=1){const gl=this.gl,{M}=RSMath;gl.uniformMatrix4fv(this.u.model,false,M.trs(o.p,o.size,o.yaw));gl.uniform3fv(this.u.baseColor,this.colorFor(o,state.theme));gl.uniform1f(this.u.alpha,alpha);gl.drawArrays(gl.TRIANGLES,0,this.count)}
};
