import './review.css';
import React,{useEffect,useState} from 'react';
import type {Project} from '../../../api/model.js';
import type {LayoutReviewFinding} from '../../../packages/contracts/alva/layout-review.js';
const labels={geometry:'几何',navigation:'通行路径',behavior:'风格与行为',requirement:'原需求冲突',furniture:'家具合理性'};
export type LocateReview=(finding:LayoutReviewFinding)=>void;
export function ReviewPanel({project,disabled,onProject,onLocate}:{project:Project;disabled:boolean;onProject:(p:Project)=>void;onLocate?:LocateReview}){
 const [verified,setVerified]=useState(''),[error,setError]=useState(''),[working,setWorking]=useState(false),[notes,setNotes]=useState<Record<string,string>>({});
 const key=`${project.id}:${project.revision}:${project.layoutReview?.id||''}`,current=verified===key;
 useEffect(()=>{let cancelled=false;if(!project.scene){setVerified('');return}void fetch('/api/layout-review').then(async r=>{const data=await r.json();if(!cancelled){setVerified(r.ok&&data.current&&data.review?.id===project.layoutReview?.id?key:'');setError(r.ok?'':data.error)}}).catch(e=>{if(!cancelled){setVerified('');setError(e.message)}});return()=>{cancelled=true}},[key]);
 const post=async(path:string,body:unknown)=>{setWorking(true);setError('');try{const r=await fetch('/api/layout-review/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),p=await r.json();if(!r.ok)throw new Error(p.error);onProject(p)}catch(e){setError((e as Error).message)}finally{setWorking(false)}};
 const review=project.layoutReview;
 return <section className="layout-review-panel" aria-label="布局复核"><h3>布局复核</h3><button disabled={disabled||working||!project.scene} onClick={()=>void post('prepare',{expectedRevision:project.revision})}>{working?'正在处理…':'复核当前布局'}</button>{error&&<p role="alert">{error}</p>}{review&&<><p role="status" data-review-current={current}>{current?'当前布局与需求仍适用':'输入已变化或尚未核验，请重新复核'} · 实际分析版本 {review.projectRevision}</p>{Object.entries(review.checks).map(([kind,check])=><small key={kind}>{labels[kind as keyof typeof labels]}：{check.status==='checked'?'已检查':'资料待补充'} </small>)}{review.findings.map(f=><article key={f.id} data-review-rule={f.ruleId}><strong>{f.title}</strong><p>{f.reason}</p><p>{f.suggestion}</p><small>{f.status==='acknowledged'?'已确认取舍':'待处理'} · {f.confidence}</small>{onLocate&&(f.roomIds.length>0||f.objectIds.length>0||f.path)&&<button disabled={!current} onClick={()=>onLocate(f)}>定位</button>}<label>取舍说明<input disabled={disabled||working||!current} value={notes[f.id]??review.decisions.find(d=>d.findingId===f.id)?.note??''} onChange={e=>setNotes({...notes,[f.id]:e.target.value})}/></label>{(['accept_tradeoff','defer'] as const).map(decision=><button key={decision} disabled={disabled||working||!current||decision==='accept_tradeoff'&&f.kind==='professional'} onClick={()=>void post('decide',{requestId:crypto.randomUUID(),expectedRevision:project.revision,reviewId:review.id,findingId:f.id,decision,note:notes[f.id]??review.decisions.find(d=>d.findingId===f.id)?.note??'',confirmed:true})}>{decision==='accept_tradeoff'?'确认保留并记录取舍':'保留待核实'}</button>)}</article>)}{!review.findings.length&&<p>当前规则未发现问题；这不构成施工或性能保证。</p>}<small>{review.limitations.join(' ')}</small></>}</section>;
}
