import React,{useEffect,useState} from 'react';
import type {Project} from '../../../api/model.js';
export function ReviewPanel({project,disabled,onProject,onLocate}:{project:Project;disabled:boolean;onProject:(p:Project)=>void;onLocate?:(roomId:string,objectId:string)=>void}){
 const [current,setCurrent]=useState(false),[error,setError]=useState(''),[working,setWorking]=useState(false),[notes,setNotes]=useState<Record<string,string>>({});
 useEffect(()=>{let cancelled=false;if(!project.scene)return;void fetch('/api/layout-review').then(async r=>{const data=await r.json();if(!cancelled){if(!r.ok){setCurrent(false);setError(data.error);return}setCurrent(data.current);setError('')}}).catch(e=>{if(!cancelled)setError(e.message)});return()=>{cancelled=true}},[project.id,project.revision]);
 const post=async(path:string,body:unknown)=>{setWorking(true);setError('');try{const r=await fetch('/api/layout-review/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),p=await r.json();if(!r.ok)throw new Error(p.error);onProject(p)}catch(e){setError((e as Error).message)}finally{setWorking(false)}};
 const review=project.layoutReview;
 return <section className="layout-review-panel" aria-label="布局复核"><h3>布局复核</h3><button disabled={disabled||working||!project.scene} onClick={()=>void post('prepare',{expectedRevision:project.revision})}>{working?'正在处理…':'复核当前布局'}</button>{error&&<p role="alert">{error}</p>}{review&&<><p role="status">{current?'当前布局与需求仍适用':'输入已变化或尚未核验，请重新复核'} · 实际分析版本 {review.projectRevision}</p>{Object.entries(review.checks).map(([kind,check])=><small key={kind}>{kind}：{check.status==='checked'?'已检查':'资料待补充'} </small>)}{review.findings.map(f=><article key={f.id}><strong>{f.title}</strong><p>{f.reason}</p><p>{f.suggestion}</p><small>{f.status==='acknowledged'?'已确认取舍':'待处理'} · {f.confidence}</small>{onLocate&&<button onClick={()=>onLocate(f.roomIds[0]||'',f.objectIds[0]||'')}>定位</button>}<label>取舍说明<input value={notes[f.id]??review.decisions.find(d=>d.findingId===f.id)?.note??''} onChange={e=>setNotes({...notes,[f.id]:e.target.value})}/></label>{(['accept_tradeoff','defer'] as const).map(decision=><button key={decision} disabled={disabled||working||!current||decision==='accept_tradeoff'&&f.kind==='professional'} onClick={()=>void post('decide',{requestId:crypto.randomUUID(),expectedRevision:project.revision,reviewId:review.id,findingId:f.id,decision,note:notes[f.id]??review.decisions.find(d=>d.findingId===f.id)?.note??'',confirmed:true})}>{decision==='accept_tradeoff'?'确认保留并记录取舍':'保留待核实'}</button>)}</article>)}{!review.findings.length&&<p>当前规则未发现问题；这不构成施工或性能保证。</p>}<small>{review.limitations.join(' ')}</small></>}</section>;
}
