import React,{useEffect,useState} from 'react';
import type {Project} from '../../../api/model.js';

type Classification={id:string;wallId:string;structural:'unknown'|'loadbearing'|'protected'|'nonloadbearing';evidenceText:string;operatorId:string;authority:string;grantId:string;createdAt:string};
type Grant={id:string;operatorId:string;authority:string;grantEvidence:string;status:'active'|'revoked';grantedBy:string;grantedAt:string;revokedBy?:string;revokedAt?:string};
type Props={project:Project;selected:string;mutate:(path:string,body:Record<string,unknown>)=>Promise<any>};
async function get(path:string){const r=await fetch('/api'+path),d=await r.json();if(!r.ok)throw new Error(d.error||'请求失败');return d}
const label=(value:string)=>({unknown:'未知',loadbearing:'承重墙',protected:'受保护墙',nonloadbearing:'非承重墙'} as Record<string,string>)[value]||value;
export function ProfessionalWallPanel({project,selected,mutate}:Props){
 const [role,setRole]=useState(''),[grants,setGrants]=useState<Grant[]>([]),[classifications,setClassifications]=useState<Classification[]>([]),[wallId,setWallId]=useState(selected),[structural,setStructural]=useState<Classification['structural']>('unknown'),[evidenceText,setEvidenceText]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState('');
 const walls=project.scene?.walls||[],wall=walls.find(w=>w.id===wallId)||walls.find(w=>w.id===selected)||walls[0],history=classifications.filter(c=>c.wallId===wall?.id);
 const load=async()=>{try{const s=await get('/session');setRole(s.role);if(s.role==='designer')return;const [a,w]=await Promise.all([get('/professional/access'),get('/professional/walls')]);setGrants(a.grants||[]);setClassifications(w.classifications||[])}catch(e){setError((e as Error).message)}};
 useEffect(()=>{void load()},[project.revision]);useEffect(()=>{if(selected&&walls.some(w=>w.id===selected))setWallId(selected)},[selected,project.revision]);
 if(role==='designer')return <section className="professional-wall-panel"><h3>墙体专业依据</h3><p>设计师只读角色不包含专业墙体分类或专业授权详情。</p></section>;
 const classify=async()=>{if(!wall||!evidenceText.trim())return;setError('');try{await mutate('/professional/walls/classify',{wallId:wall.id,structural,evidenceText:evidenceText.trim()});setEvidenceText('');await load()}catch(e){setError((e as Error).message)}};
 const remove=async()=>{if(!wall||!reason.trim())return;setError('');try{await mutate('/professional/walls/remove',{wallId:wall.id,reason:reason.trim(),confirmed:true});setReason('');await load()}catch(e){setError((e as Error).message)}};
 return <section className="professional-wall-panel"><h3>墙体分类与专业依据</h3><p>比例校准只确认尺度，不构成拆改许可。未知、承重或受保护墙禁止正式拆改；只有带可追溯专业依据的非承重墙可由已授权专业角色执行正式移除。</p>
  {role==='owner'&&<div className="professional-grants"><h4>专业授权记录</h4>{grants.length?grants.map(g=><article key={g.id}><b>{g.operatorId}</b><small>{g.authority} · {g.status==='active'?'有效':'已撤销'}</small><p>{g.grantEvidence}</p><small>授予：{g.grantedBy} · {new Date(g.grantedAt).toLocaleString()}</small>{g.revokedAt&&<small>撤销：{g.revokedBy} · {new Date(g.revokedAt).toLocaleString()}</small>}</article>):<small>当前没有专业授权记录。专业授权只能由服务器管理员配置。</small>}</div>}
  {walls.length>0&&<><label>查看墙体<select aria-label="专业墙体选择" value={wall?.id||''} onChange={e=>setWallId(e.target.value)}>{walls.map((w,i)=><option key={w.id} value={w.id}>墙 {i+1} · {w.id.slice(0,12)} · {label(w.structural)}</option>)}</select></label>{wall&&<div className="wall-classification-summary"><b>当前分类：{label(wall.structural)}</b><small>墙体证据标记：{wall.evidence.length?wall.evidence.join('；'):'暂无专业分类证据'}</small></div>}
  {history.length>0&&<div className="wall-classification-history"><h4>分类来源</h4>{history.map(c=><article key={c.id}><b>{label(c.structural)}</b><p>{c.evidenceText}</p><small>操作者：{c.operatorId} · 授权：{c.authority}</small><small>{new Date(c.createdAt).toLocaleString()} · {c.id}</small></article>)}</div>}
  {role==='professional'&&wall&&<><fieldset><legend>录入专业分类</legend><label>墙体分类<select aria-label="专业墙体分类" value={structural} onChange={e=>setStructural(e.target.value as Classification['structural'])}><option value="unknown">未知 / 仍需核实</option><option value="loadbearing">承重墙</option><option value="protected">受保护墙</option><option value="nonloadbearing">非承重墙</option></select></label><label>分类依据<textarea aria-label="专业分类依据" value={evidenceText} onChange={e=>setEvidenceText(e.target.value)} placeholder="例如：结构图编号、现场核验记录、专业判断范围。"/></label><button disabled={!evidenceText.trim()} onClick={()=>void classify()}>提交专业分类</button></fieldset><fieldset><legend>正式拆改</legend><label>拆改原因<textarea aria-label="专业拆改原因" value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={wall.structural!=='nonloadbearing'||!wall.evidence.some(e=>e.startsWith('professional-classification:'))||!reason.trim()} onClick={()=>void remove()}>确认移除已核实非承重墙</button></fieldset></>}
  </>}{error&&<p className="error" role="alert">{error}</p>}</section>
}
