import {projectFetch as fetch} from '../projects/session.js';
import React,{useEffect,useMemo,useState} from 'react';
import type {Project,SceneData} from '../../../api/model.js';
import {SceneView} from '../SceneView.js';

type Migration={openingId:string;targetWallId:string;offset:number};
type Preview={scene:SceneData;removedWallId:string;migrations:Migration[];baseRevision:number;baseTopologyId:string;baseTopologyVersion:number;previewFingerprint:string};
type Props={project:Project;mutate:(path:string,body:Record<string,unknown>)=>Promise<any>;readOnly:boolean;selected:string};
const label=(wall:SceneData['walls'][number])=>wall.structural==='nonloadbearing'?'非承重墙':wall.structural==='loadbearing'?'承重墙':wall.structural==='protected'?'受保护墙':'未知';
async function previewApi(body:unknown){const r=await fetch('/api/professional/remodel/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'无法生成改造预览');return d as Preview}

export function RemodelPanel({project,mutate,readOnly,selected}:Props){
 const scene=project.scene, walls=scene?.walls||[];
 const candidates=useMemo(()=>walls.filter(w=>w.structural==='nonloadbearing'&&w.evidence.some(e=>e.startsWith('professional-classification:'))),[project.revision]);
 const [wallId,setWallId]=useState(''),[migrations,setMigrations]=useState<Record<string,{targetWallId:string;offset:string}>>({}),[reason,setReason]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const wall=candidates.find(w=>w.id===wallId)||candidates.find(w=>w.id===selected)||candidates[0];
 useEffect(()=>{if(wall&&wall.id!==wallId){setWallId(wall.id);setPreview(null)}},[wall?.id]);
 useEffect(()=>{if(!wall)return;const next:Record<string,{targetWallId:string;offset:string}>={};for(const opening of scene?.openings.filter(o=>o.wallId===wall.id)||[])next[opening.id]={targetWallId:'',offset:String(opening.offset)};setMigrations(next);setPreview(null)},[wall?.id,project.revision]);
 if(!scene)return <section className="remodel-panel"><h3>墙体改造预览</h3><p>请先完成并确认户型拓扑。</p></section>;
 const openingIds=Object.keys(migrations),migrationPayload=openingIds.map(id=>({openingId:id,targetWallId:migrations[id].targetWallId,offset:Number(migrations[id].offset)}));
 const runPreview=async()=>{setError('');setBusy(true);try{if(migrationPayload.some(m=>!m.targetWallId||!Number.isFinite(m.offset)))throw new Error('请为每个门窗选择目标墙段并填写有效位置');setPreview(await previewApi({expectedRevision:project.revision,wallId:wall!.id,migrations:migrationPayload}))}catch(e){setError((e as Error).message);setPreview(null)}finally{setBusy(false)}};
 const confirm=async()=>{if(!preview||!reason.trim())return;setError('');setBusy(true);try{await mutate('/professional/remodel/confirm',{wallId:preview.removedWallId,migrations:preview.migrations,baseTopologyId:preview.baseTopologyId,previewFingerprint:preview.previewFingerprint,reason:reason.trim(),confirmed:true});setPreview(null);setReason('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <section className="remodel-panel" aria-label="非承重墙改造"><h3>非承重墙改造与开口迁移</h3><p>只有已由专业角色提供可追溯依据的非承重墙可进入预览。门窗必须逐个指定目标墙段和位置，预览确认后才会原子保存。</p>{candidates.length===0?<p className="remodel-empty">当前没有带专业证据的可改造墙体。请先在“墙体证据”中由授权专业角色分类。</p>:<><label>待改造墙体<select aria-label="改造墙体" value={wall?.id||''} onChange={e=>setWallId(e.target.value)}>{candidates.map(w=><option key={w.id} value={w.id}>{w.id} · {label(w)}</option>)}</select></label>{openingIds.length>0?<fieldset><legend>门窗迁移（必须全部明确）</legend>{openingIds.map(id=>{const opening=scene.openings.find(o=>o.id===id)!;return <div className="remodel-opening" key={id}><b>{opening.kind==='door'?'门':'窗'} · {id}</b><label>目标墙段<select aria-label={`门窗 ${id} 目标墙段`} value={migrations[id].targetWallId} onChange={e=>setMigrations({...migrations,[id]:{...migrations[id],targetWallId:e.target.value}})}><option value="">选择目标墙段</option>{walls.filter(w=>w.id!==wall?.id).map(w=><option key={w.id} value={w.id}>{w.id} · {label(w)}</option>)}</select></label><label>目标位置比例<input aria-label={`门窗 ${id} 目标位置`} type="number" min="0" max="1" step=".01" value={migrations[id].offset} onChange={e=>setMigrations({...migrations,[id]:{...migrations[id],offset:e.target.value}})}/></label></div>})}</fieldset>:<p>该墙没有门窗，无需迁移；仍会校验整体几何。</p>}<button disabled={readOnly||busy||!wall} onClick={()=>void runPreview()}>生成改造预览</button>{preview&&<div className="remodel-preview"><h4>改造候选 · 尚未保存</h4><p>将移除墙 {preview.removedWallId}，保留门窗稳定 ID 并迁移到指定墙段。来源拓扑 v{preview.baseTopologyVersion}。</p><div className="remodel-preview-scene"><SceneView scene={preview.scene} mode="3d"/></div><label>确认原因<textarea aria-label="改造确认原因" value={reason} onChange={e=>setReason(e.target.value)} placeholder="例如：专业复核确认该隔墙可移除，开口按现场尺寸迁移。"/></label><div className="button-row"><button className="primary" disabled={readOnly||busy||!reason.trim()} onClick={()=>void confirm()}>确认并保存改造</button><button disabled={busy} onClick={()=>setPreview(null)}>取消预览</button></div></div>}{error&&<p className="error" role="alert">{error}</p>}</>}</section>;
}
