import {raw as untranslated} from '../i18n/language.js';
import {projectFetch as fetch} from '../projects/session.js';
import React,{useMemo,useState} from 'react';
import type {Project,SceneData} from '../../../api/model.js';
import {SceneView} from '../SceneView.js';

type Conflict={kind:'question'|'room-style';key:string;message:string;options:{sourceRoomId:string;label:string;locked?:boolean}[]};
type Preview={scene:SceneData;mergedRoom:SceneData['rooms'][number];sourceRooms:{id:string;name:string;purpose:string;locked:boolean}[];openingContinuity:{openingId:string;wallId:string;unchanged:boolean}[];conflicts:Conflict[];readyToConfirm:boolean;baseTopologyId:string;baseTopologyVersion:number;previewFingerprint:string};
type Props={project:Project;mutate:(path:string,body:Record<string,unknown>)=>Promise<any>;readOnly:boolean};
async function previewApi(body:unknown){const r=await fetch('/api/rooms/merge/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'无法生成空间合并预览');return d as Preview}

export function RoomMergePanel({project,mutate,readOnly}:Props){
 const scene=project.scene;
 const [selected,setSelected]=useState<string[]>([]),[name,setName]=useState(''),[purpose,setPurpose]=useState(''),[locked,setLocked]=useState(false),[styleSource,setStyleSource]=useState<string>(''),[resolutions,setResolutions]=useState<Record<string,string>>({}),[preview,setPreview]=useState<Preview|null>(null),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const rooms=scene?.rooms||[],selectedRooms=useMemo(()=>rooms.filter(r=>selected.includes(r.id)),[project.revision,selected.join('|')]);
 if(!scene||!project.confirmedTopology)return <section className="remodel-panel" aria-label="空间合并"><h3>空间合并</h3><p>请先完成并确认户型拓扑。</p></section>;
 const toggle=(id:string,on:boolean)=>{const next=on?[...selected,id]:selected.filter(x=>x!==id);setSelected(next);const picked=rooms.filter(r=>next.includes(r.id));setLocked(picked.some(r=>r.locked));setPreview(null)};
 const payload=()=>({expectedRevision:project.revision,sourceRoomIds:selected,name:name.trim(),purpose:purpose.trim(),locked,roomStyleSourceRoomId:styleSource||null,questionResolutions:Object.entries(resolutions).map(([questionId,sourceRoomId])=>({questionId,sourceRoomId}))});
 const run=async()=>{setError('');setBusy(true);try{if(selected.length<2)throw new Error('请至少选择两个要合并的连续空间');if(!name.trim()||!purpose.trim())throw new Error('请明确合并后的空间名称和用途');setPreview(await previewApi(payload()))}catch(e){setError((e as Error).message);setPreview(null)}finally{setBusy(false)}};
 const confirm=async()=>{if(!preview||!preview.readyToConfirm||!reason.trim())return;setError('');setBusy(true);try{await mutate('/rooms/merge/confirm',{...payload(),baseTopologyId:preview.baseTopologyId,previewFingerprint:preview.previewFingerprint,reason:reason.trim(),confirmed:true});setSelected([]);setPreview(null);setReason('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <section className="remodel-panel" aria-label="空间合并"><h3>空间合并与需求迁移</h3><p>先比较合并边界和来源关系。家具、问卷、原话、锁定状态与房间级偏好会一起迁移；有冲突时必须先选择保留来源。</p><fieldset><legend>来源空间</legend>{rooms.map(r=><label className="inline" key={r.id}><input type="checkbox" checked={selected.includes(r.id)} disabled={readOnly||busy} onChange={e=>toggle(r.id,e.target.checked)}/>{untranslated(r.name)} · {r.id}{r.locked?' · 已锁定':''}</label>)}</fieldset><label>合并后名称<input aria-label="合并后空间名称" value={name} onChange={e=>{setName(e.target.value);setPreview(null)}}/></label><label>合并后用途<input aria-label="合并后空间用途" value={purpose} onChange={e=>{setPurpose(e.target.value);setPreview(null)}}/></label><label className="inline"><input type="checkbox" checked={locked} disabled={readOnly||selectedRooms.some(r=>r.locked)} onChange={e=>setLocked(e.target.checked)}/>合并后保持锁定</label><button disabled={readOnly||busy||selected.length<2} onClick={()=>void run()}>生成空间合并预览</button>{preview&&<div className="remodel-preview"><h4>空间合并候选 · 尚未保存</h4><p>{preview.sourceRooms.map(r=>r.name+' ['+r.id+']').join(' + ')} → {untranslated(preview.mergedRoom.name)} [{preview.mergedRoom.id}]；来源拓扑 v{preview.baseTopologyVersion}。</p><p>门窗继续绑定原墙段：{preview.openingContinuity.length} 个开口未改变 ID。</p><div className="remodel-preview-scene"><SceneView scene={preview.scene} mode="3d"/></div>{preview.conflicts.length>0&&<fieldset><legend>必须先解决的来源冲突</legend>{preview.conflicts.map(c=><label key={c.kind+':'+c.key}>{c.message}<select aria-label={'冲突 '+c.key} value={c.kind==='room-style'?styleSource:(resolutions[c.key]||'')} onChange={e=>{if(c.kind==='room-style')setStyleSource(e.target.value);else setResolutions({...resolutions,[c.key]:e.target.value});setPreview(null)}}><option value="">选择保留来源</option>{c.options.map(o=><option key={o.sourceRoomId} value={o.sourceRoomId}>{o.label}{o.locked?' · 已锁定':''}</option>)}</select></label>)}</fieldset>}{preview.readyToConfirm&&<><label>确认原因<textarea aria-label="空间合并确认原因" value={reason} onChange={e=>setReason(e.target.value)} placeholder="例如：拆除隔断后将客厅与书房作为同一开放空间使用。"/></label><div className="button-row"><button className="primary" disabled={readOnly||busy||!reason.trim()} onClick={()=>void confirm()}>确认并一次性迁移</button><button disabled={busy} onClick={()=>setPreview(null)}>取消预览</button></div></>}</div>}{error&&<p className="error" role="alert">{error}</p>}</section>;
}
