import {t,raw as untranslated} from '../i18n/language.js';
import React from 'react';
import {House,Sparkles,Hammer,PanelsTopLeft,Lightbulb,DoorOpen,Sofa,CookingPot,Utensils,BedDouble,Bath,Monitor,Blocks,Baby,WashingMachine,Trees,Building2,Landmark,Flame,Waves,ScanEye,Sun,Coffee,PartyPopper,Gem,Zap,Leaf,HeartHandshake,LayoutGrid,Palette,Paintbrush,Layers3,Moon,SlidersHorizontal,ToggleLeft,BookOpen,Lamp,Check,ShieldCheck,Wallet,Sprout,Clock3,Droplets} from 'lucide-react';
import {type Item,type Value,type Answers,raw,values,flags,options,condition,prompt,picked,items,selectedRooms} from '../../../packages/contracts/alva/home-vision/flow.js';
const palettes=[['#F4EFE6','#D9C2A0','#E8DFD2','#B89B74'],['#E6DCCD','#8A6546','#C9B8A1','#5C4331'],['#F2F3F5','#C9CDD2','#9AA1A9','#5F666E'],['#FAFAFA','#E4E4E4','#F2B134','#2F6FDB'],['#283330','#5B2E35','#1F2A44','#B08D57'],['#E9DCC8','#C2693E','#7C8456','#D8B98C']];
const icons:Record<string,typeof House>={new_home:House,refresh:Sparkles,renovate:Hammer,one_room:PanelsTopLeft,exploring:Lightbulb,whole_home:House,entry:DoorOpen,living:Sofa,kitchen:CookingPot,dining:Utensils,bedroom:BedDouble,bathroom:Bath,office:Monitor,kids:Blocks,nursery:Baby,laundry:WashingMachine,guest:BedDouble,outdoor:Trees,single_family:House,detached:House,semi:House,townhouse:House,landed:House,apartment:Building2,condo:Building2,co_op:Building2,hdb:Building2,mansion:Building2,period:Landmark};
const choiceIcons:Record<string,typeof House>={
 'Q06a.cozy':Flame,'Q06a.calm':Waves,'Q06a.uncluttered':ScanEye,'Q06a.bright':Sun,'Q06a.lived_in':Coffee,'Q06a.playful':PartyPopper,'Q06a.elegant':Gem,'Q06a.bold':Zap,'Q06a.natural':Leaf,'Q06a.welcoming':HeartHandshake,
 'Q10a.high_gloss':Sparkles,'Q10a.shiny_gold':Gem,'Q10a.mirrored':ScanEye,'Q10a.open_shelving':LayoutGrid,'Q10a.all_gray':Palette,'Q10a.wallpaper':Paintbrush,'Q10a.carpet':Layers3,'Q10a.dark_rooms':Moon,
 'Q26a.soft_warm':Flame,'Q26a.bright':Sun,'Q26a.moods':SlidersHorizontal,'Q26a.one_switch':ToggleLeft,'Q26b.too_dark':Moon,'Q26b.harsh':Lightbulb,'Q26b.task':BookOpen,'Q26b.glare':Sun,'Q26b.wrong_place':Lamp,'Q26b.fine':Check,
 'Q32a.natural':Leaf,'Q32a.durable':ShieldCheck,'Q32a.budget_alt':Wallet,'Q32a.sustainable':Sprout,'Q32a.local_craft':Hammer,'Q32a.vintage':Clock3,'Q32a.performance':Droplets,
};
export const object=(v:Value|undefined):Record<string,Value>=>v&&typeof v==='object'&&!Array.isArray(v)?v:{};
function StyleArt({index}:{index:number}){const colors=palettes[index%6];return <svg className="hv-style-art" viewBox="0 0 200 110" role="img" aria-label="Style illustration"><rect width="200" height="110" fill={colors[0]}/><path d="M0 86H200V110H0" fill={colors[1]}/><rect x="24" y="48" width="94" height="36" rx={index%3===0?2:12} fill={colors[2]}/><rect x="20" y="65" width="102" height="24" rx="5" fill={colors[3]}/><path d="M146 38V89M135 89H157" stroke={colors[3]} strokeWidth="3"/><path d="M132 39L140 18H152L160 39Z" fill={colors[1]}/><rect x="38" y="12" width="37" height="24" rx={index%2?0:10} fill={colors[2]}/></svg>}
export function Field({item:i,answers:a,put,disabled=false,hideTitle=false}:{item:Item;answers:Answers;put:(id:string,v:Value,state?:'answered'|'unknown'|'skipped')=>void;disabled?:boolean;hideTitle?:boolean}){
 const f=flags(a),v=raw(a,i.id),o=object(v),opts=options(i,a,f),stored=values(v),single=i.type==='single'||i.id==='Q05a'&&f.has('ONE_ROOM'),max=single?1:i.max;
 const sel=i.id==='Q05a'&&f.has('ONE_ROOM')&&(stored.length!==1||stored.includes('Q05a.whole_home'))?[]:stored.filter(id=>opts.some(option=>option.id===id)||id===i.id+'.other');
 const set=(x:Value)=>put(i.id,x);const update=(k:string,x:Value)=>set({...o,[k]:x});
 const choose=(id:string,exclusive?:boolean)=>{if(single){set(id);return}let next=sel.includes(id)?sel.filter(x=>x!==id):exclusive?[id]:[...sel.filter(x=>!opts.find(o=>o.id===x)?.exclusive&&!x.endsWith('.other')),id];if(max&&next.length>max)return;set(next)};
 const upload=async(files:FileList|null)=>{if(!files)return;const previous=Array.isArray(v)?v:[];let total=JSON.stringify(a).length;const added:Value[]=[];for(const file of Array.from(files)){if(!/^(image\/(png|jpeg|webp)|application\/pdf|audio\/)/.test(file.type)){window.alert(t('Choose a PNG, JPEG, WebP, PDF or audio file.'));continue}if(file.size>2000000||total+file.size*1.4>5500000){window.alert(t('Use files under 2 MB, up to 4 MB in total.'));continue}const data=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file)});added.push({name:file.name,data,mime:file.type});total+=data.length;}set([...previous,...added])};
 const fileList=(list:Value[])=>list.map((entry,index)=>{const file=object(entry);return <div className="hv-upload" key={index}>{String(file.mime).startsWith('image/')&&<img src={String(file.data)} alt={String(file.name)}/>}<span>{untranslated(String(file.name||file.url))}</span>{file.url&&<a href={String(file.url)} target="_blank" rel="noreferrer"> Open link</a>}<button type="button" disabled={disabled} className="hv-ghost" onClick={()=>set(list.filter((_,n)=>n!==index))}>Remove</button></div>});
 let content:React.ReactNode;
 if(['single','multi'].includes(i.type))content=<><div className={(i.id==='Q05b'?'hv-chips':i.display==='image_cards'?'hv-palette':i.type==='multi'?'hv-grid':'hv-options')+(single?'':' hv-multi')} role={single?'radiogroup':'group'} aria-label={prompt(i,a,f)} onKeyDown={e=>{if(single&&['ArrowDown','ArrowRight','ArrowUp','ArrowLeft'].includes(e.key)){const buttons=Array.from(e.currentTarget.querySelectorAll<HTMLButtonElement>('button:not(:disabled)'));const current=buttons.indexOf(document.activeElement as HTMLButtonElement);const n=(current+(['ArrowUp','ArrowLeft'].includes(e.key)?-1:1)+buttons.length)%buttons.length;buttons[n]?.focus();buttons[n]?.click();e.preventDefault()}}}>
 {opts.map((option,n)=>{const on=sel.includes(option.id),Icon=choiceIcons[option.id]||icons[option.id.split('.')[1]],palette=i.id==='Q07a'&&n<6,style=i.id==='Q08a'&&n>0,visual=palette||style,note=Object.entries(option.note_if||{}).find(([e])=>condition(e,a,f))?.[1];return <button type="button" key={option.id} role={single?'radio':'checkbox'} aria-checked={on} disabled={disabled||(!on&&!option.exclusive&&!single&&!!max&&sel.length>=max&&!opts.some(o=>o.exclusive&&sel.includes(o.id)))} className={'hv-opt '+(on?'on ':'')+(option.id.endsWith('whole_home')?'hv-whole ':'')+(i.display==='image_cards'&&!visual?'hv-samples ':'')} onClick={()=>choose(option.id,option.exclusive)}>
 {palette&&<span className="hv-swatches" aria-hidden="true"><span><i style={{background:palettes[n][0]}}/><i style={{background:palettes[n][1]}}/></span><span><i style={{background:palettes[n][2]}}/><i style={{background:palettes[n][3]}}/></span></span>}{style&&<StyleArt index={n}/>}
 {!visual&&i.display!=='image_cards'&&Icon&&<span className="hv-icon"><Icon size={22} strokeWidth={1.5}/></span>}
 {visual||i.display==='image_cards'?<span className="hv-cap"><span className="hv-opt-label">{option.label}{option.helper&&<small>{option.helper}</small>}</span><span className="hv-check" aria-hidden="true">{on?'✓':''}</span></span>:<><span className="hv-opt-label">{option.label}{option.helper&&<small>{option.helper}</small>}{note&&<small>{note}</small>}{i.id==='Q35a'&&f.has('RENOVATING')&&['Q35a.renovation','Q35a.remodel'].includes(option.id)&&<small className="hv-recommended">Based on your plans — select to confirm</small>}</span><span className="hv-check" aria-hidden="true">{on?'✓':''}</span></>}
 </button>})}</div>{max&&!single&&<p className="hv-note">{sel.length} of {max} selected</p>}{i.other!==false&&<details open={sel.includes(i.id+'.other')||undefined}><summary>Something else? Add your own answer</summary><textarea className="hv-field" placeholder="Type your answer here" disabled={disabled} aria-label={prompt(i,a)+' — other'} maxLength={3000} value={String(o.text||'')} onChange={e=>set({choice:i.id+'.other',text:e.target.value})}/></details>}</>;
 else if(i.type==='country_city')content=<div className="hv-row"><label>Country<select aria-label="Country" disabled={disabled} className="hv-field" value={String(o.country||'')} onChange={e=>update('country',e.target.value)}><option value="">Select country</option>{['United States','United Kingdom','Singapore','Japan','Other'].map(x=><option key={x} value={x}>{x}</option>)}</select>{o.country==='Other'&&<input className="hv-field" aria-label="Country name" value={String(o.otherCountry||'')} disabled={disabled} placeholder="Country name" onChange={e=>update('otherCountry',e.target.value)}/>}</label><label>City<input aria-label="City" disabled={disabled} className="hv-field" value={String(o.city||'')} onChange={e=>update('city',e.target.value)} maxLength={150}/></label></div>;
 else if(i.type==='group')content=<div className="hv-items">{i.fields?.filter(field=>condition(field.show_if,a,f)).map(field=><Field key={field.id} item={field} answers={{...a,[field.id]:{state:'answered',value:o[field.id]??null}}} put={(id,value)=>update(id,value)} disabled={disabled}/>)}</div>;
 else if(i.type==='number_unit')content=<div className="hv-row"><input className="hv-field" aria-label={prompt(i,a)+' amount'} type="number" min="0" value={String(o.amount??'')} disabled={disabled} onChange={e=>update('amount',e.target.value===''?'':Number(e.target.value))}/><select className="hv-field" aria-label="Area unit" value={String(o.unit||'')} disabled={disabled} onChange={e=>update('unit',e.target.value)}><option value="">Choose unit</option>{i.units?.map(u=><option key={u} value={u}>{u==='sqft'?'sq ft':'m²'}</option>)}</select></div>;
 else if(i.type==='repeat_group'){const rows=Array.isArray(v)?v:[];content=<>{rows.map((row,n)=><div className="hv-upload hv-items" key={n}>{i.fields?.filter(field=>!field.show_if||field.id!=='C3a.size'||['dog','cat','other'].includes(String(object(row)['C3a.type']))).map(field=><Field key={field.id} item={{...field,other:false}} answers={{...a,[field.id]:{state:'answered',value:object(row)[field.id]??null}}} put={(id,value)=>set(rows.map((r,index)=>index===n?{...object(r),[id]:value}:r))} disabled={disabled}/>)}<button className="hv-ghost" disabled={disabled} onClick={()=>set(rows.filter((_,index)=>index!==n))}>Remove pet</button></div>)}<button className="hv-ghost" disabled={disabled} onClick={()=>set([...rows,{}])}>+ Add pet</button></>}
 else if(i.type==='currency_range')content=<><div className="hv-row"><label>Currency<select aria-label="Currency" className="hv-field" value={String(o.currency||'')} disabled={disabled} onChange={e=>update('currency',e.target.value)}><option value="">Choose currency{object(raw(a,'Q02a')).country?' (suggested: '+({'United States':'USD','United Kingdom':'GBP',Singapore:'SGD',Japan:'JPY'}[String(object(raw(a,'Q02a')).country)]||'confirm locally')+')':''}</option>{['USD','GBP','SGD','JPY','EUR','AUD','CAD','CNY','Other'].map(x=><option key={x} value={x}>{x}</option>)}</select>{o.currency==='Other'&&<input className="hv-field" aria-label="Currency code" placeholder="Currency code" value={String(o.currencyCode||'')} disabled={disabled} onChange={e=>update('currencyCode',e.target.value.toUpperCase())}/>}</label>{['comfortable','maximum'].map(k=><label key={k}>{k==='comfortable'?'Comfortable amount':'Maximum amount'}<input className="hv-field" type="number" min="0" value={String(o[k]??'')} disabled={disabled} onChange={e=>set({...o,choice:'',[k]:e.target.value===''?'':Number(e.target.value)})}/></label>)}</div><div className="hv-controls">{opts.map(option=><button className={'hv-ghost '+(sel.includes(option.id)?'on':'')} disabled={disabled} key={option.id} onClick={()=>set({choice:option.id})}>{option.label}</button>)}</div></>;
 else if(i.type==='date_rows'){const rows=Array.isArray(v)?v:[];const milestones=(i.milestones||[]).filter(m=>condition(m.show_if,a,f));content=<>{rows.map((row,n)=>{const data=object(row);const up=(k:string,x:Value)=>set(rows.map((r,index)=>index===n?{...object(r),[k]:x}:r));return <div className="hv-upload" key={n}><label>Milestone<select className="hv-field" value={String(data.milestone||'')} disabled={disabled} onChange={e=>up('milestone',e.target.value)}><option value="">Choose milestone</option>{milestones.map(m=><option value={m.id} key={m.id}>{m.label}</option>)}</select></label><div className="hv-row"><label>Date<input type="date" className="hv-field" disabled={disabled} value={String(data.date||'')} onChange={e=>up('date',e.target.value)}/></label>{data.milestone==='Q40a.blackout'&&<label>End date<input type="date" className="hv-field" disabled={disabled} value={String(data.end||'')} onChange={e=>up('end',e.target.value)}/></label>}<label>Timing<select className="hv-field" disabled={disabled} value={String(data.flexibility||'')} onChange={e=>up('flexibility',e.target.value)}><option value="">Choose</option><option value="fixed">Fixed</option><option value="flexible">Flexible</option></select></label></div>{data.milestone==='Q40a.baby_due'&&raw(a,'Q04c')&&<button className="hv-ghost" disabled={disabled} onClick={()=>up('date',raw(a,'Q04c')!)}>Use due date: {String(raw(a,'Q04c'))}</button>}<button className="hv-ghost" disabled={disabled} onClick={()=>set(rows.filter((_,index)=>index!==n))}>Remove date</button></div>})}<button className="hv-ghost" disabled={disabled} onClick={()=>set([...rows,{}])}>+ Add a date</button></>}
 else if(i.type==='per_room_single'){const roomItem=items.find(x=>x.id==='Q05a')!;content=<div className="hv-items">{options(roomItem,a,f).filter(r=>selectedRooms(a).includes(r.id)).map(room=><Field key={room.id} item={{...i,id:room.id,type:'single',prompt:room.label}} answers={{...a,[room.id]:{state:'answered',value:o[room.id]??null}}} disabled={disabled} put={(id,value)=>update(id,value)}/>)}</div>}
 else if(i.type==='per_upload_text'){const refs=raw(a,'Q09a');content=<>{(Array.isArray(refs)?refs:[]).map((r,n)=><div className="hv-upload" key={n}><b>{untranslated(String(object(r).name||object(r).url))}</b>{i.prompt_pairs?.map((p,k)=><label key={p}>{p}<textarea className="hv-field" disabled={disabled} value={String(o[n+'-'+k]||'')} onChange={e=>update(n+'-'+k,e.target.value)} maxLength={3000}/></label>)}</div>)}</>}
 else if(i.type==='upload')content=<><input aria-label={prompt(i,a)+' files'} disabled={disabled} type="file" accept={i.accepts?.includes('audio')?'audio/*':i.accepts?.includes('pdf')?'image/png,image/jpeg,image/webp,application/pdf':'image/png,image/jpeg,image/webp'} multiple onChange={e=>void upload(e.target.files)}/><p className="hv-note">Up to 2 MB per file, 4 MB total. Links are saved as references; their contents are not automatically reviewed.</p>{fileList(Array.isArray(v)?v:[])}<input className="hv-field" type="url" placeholder="Paste a reference link and press Enter" aria-label="Reference link" disabled={disabled} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();try{const u=new URL(e.currentTarget.value);if(!['https:','http:'].includes(u.protocol))return;set([...(Array.isArray(v)?v:[]),{url:u.href}]);e.currentTarget.value=''}catch{e.currentTarget.setCustomValidity(t('Enter a valid https:// link'));e.currentTarget.reportValidity()}}}}/></>;
 else if(i.type==='text_with_photo'||i.allow_voice_note)content=<><textarea className="hv-field" disabled={disabled} value={String(o.text||'')} maxLength={3000} onChange={e=>update('text',e.target.value)} aria-label={prompt(i,a)}/><Field item={{id:i.id+'.photos',type:'upload',prompt:i.allow_voice_note?'Attach a voice note (optional)':'Add a photo (optional)',accepts:i.allow_voice_note?['audio']:['image']}} answers={{...a,[i.id+'.photos']:{state:'answered',value:o.photos||[]}}} put={(_,x)=>update('photos',x)} disabled={disabled}/></>;
 else content=i.type==='date'||i.type==='number'||i.id==='Q07b'?<input className="hv-field" type={i.id==='Q07b'?'text':i.type} min={i.type==='number'?'0':undefined} disabled={disabled} aria-label={prompt(i,a)} value={typeof v==='number'||typeof v==='string'?v:''} onChange={e=>set(i.type==='number'&&e.target.value!==''?Number(e.target.value):e.target.value)}/>:<textarea className="hv-field" disabled={disabled} aria-label={prompt(i,a)} value={typeof v==='string'?v:''} maxLength={3000} onChange={e=>set(e.target.value)}/>;
 const body=<div className="hv-field-group"><fieldset className="hv-item" disabled={disabled}>{!hideTitle&&<legend>{prompt(i,a,f)}</legend>}{i.helper&&!hideTitle&&<p className="hv-note">{i.helper==='Collapsed by default.'?'Optional details':i.helper}</p>}{content}</fieldset>{!i.id.includes('.')&&<div className="hv-controls"><button type="button" className={'hv-ghost '+(a[i.id]?.state==='unknown'?'on':'')} disabled={disabled} onClick={()=>put(i.id,null,'unknown')}>Not sure yet</button>{a[i.id]?.state==='unknown'&&<small className="hv-note">Saved as undecided</small>}</div>}</div>;
 return i.collapsed||i.expanded_if||i.type==='group'?<details open={i.expanded_if&&condition(i.expanded_if,a,f)||undefined}><summary>{prompt(i,a,f)}</summary>{body}</details>:body;
}
