import React,{useEffect,useState} from 'react';
import type {Project} from '../../../api/model.js';
import type {ChatAction,ChatStage} from '../../../packages/contracts/alva/chat-actions.js';
type Action=ChatAction&{stale:boolean};
export function StageControls({project,busy,readOnly,request,onProject,onStage,onError}:{project:Project;busy:boolean;readOnly:boolean;request:(path:string,body?:unknown)=>Promise<any>;onProject:(p:Project)=>void;onStage:(stage:ChatStage)=>void;onError:(message:string)=>void}){
 const [stage,setStage]=useState<ChatStage>('floorplan'),[actions,setActions]=useState<Action[]>([]),[working,setWorking]=useState(false),[entryWarning,setEntryWarning]=useState('');
 const refresh=async()=>{const [state,list]=await Promise.all([request('/chat/stages'),request('/chat/actions')]);setEntryWarning(state.entryWarning?.message||'');setStage(state.active);onStage(state.active);setActions(list.filter((a:Action)=>a.status==='pending'))};
 useEffect(()=>{void refresh().catch(e=>onError(e.message))},[project.id,project.revision,busy]);
 const switchTo=async(next:ChatStage)=>{setWorking(true);try{const state=await request('/chat/stages/switch',{stage:next,expectedRevision:project.revision});setEntryWarning(state.entryWarning?.message||'');setStage(state.active);onStage(state.active)}catch(e){onError((e as Error).message)}finally{setWorking(false)}};
 const decide=async(action:Action,confirmed:boolean)=>{setWorking(true);try{const result=await request('/chat/actions/'+(confirmed?'confirm':'reject'),confirmed?{id:action.id,expectedRevision:project.revision,confirmed:true}:{id:action.id});if(confirmed)onProject(result);await refresh()}catch(e){onError((e as Error).message)}finally{setWorking(false)}};
 return <section aria-label="设计阶段" className="chat-stages"><div className="segmented">{(['floorplan','living'] as const).map(value=><button key={value} className={stage===value?'active':''} disabled={busy||working||readOnly||value===stage||(value==='living'&&!project.confirmedBuilding)} onClick={()=>void switchTo(value)}>{value==='floorplan'?'户型导入':'生活设计'}</button>)}</div><small>{stage==='floorplan'?'先核对户型，确认建筑后进入生活设计。':'家具与房间方案须由你确认后采用。'}</small>{entryWarning&&<div role="alert">阶段已切换，Agent交接尚未完成：{entryWarning}<button disabled={busy||working||readOnly} onClick={()=>void switchTo(stage)}>重试送达阶段交接</button></div>}{actions.filter(a=>a.stage===stage).map(action=><article key={action.id} className="chat-confirmation" data-action-kind={action.kind}><strong>{action.title}</strong><p>{action.description}</p>{action.stale&&<p role="status">项目已变化，请让顾问重新生成确认请求。</p>}<button disabled={busy||working||readOnly||action.stale} onClick={()=>void decide(action,true)}>{action.title.startsWith('确认')?action.title:'确认'+action.title}</button><button disabled={busy||working||readOnly} onClick={()=>void decide(action,false)}>暂不执行</button></article>)}</section>;
}
