import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import {createTopologyVersion} from '../api/topology/calibration.js';
import type {SceneData} from '../api/model.js';

const code='alva033-remodel-code-123456';
const scene=():SceneData=>({walls:[
 {id:'bottom-left',a:{x:0,y:0},b:{x:3,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]},
 {id:'bottom-right',a:{x:3,y:0},b:{x:6,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]},
 {id:'right',a:{x:6,y:0},b:{x:6,y:4},thickness:.15,height:2.8,structural:'unknown',evidence:[]},
 {id:'top-right',a:{x:6,y:4},b:{x:3,y:4},thickness:.15,height:2.8,structural:'unknown',evidence:[]},
 {id:'top-left',a:{x:3,y:4},b:{x:0,y:4},thickness:.15,height:2.8,structural:'unknown',evidence:[]},
 {id:'left',a:{x:0,y:4},b:{x:0,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]},
 {id:'divider',a:{x:3,y:0},b:{x:3,y:4},thickness:.15,height:2.8,structural:'nonloadbearing',evidence:['professional-classification:class-033']},
],rooms:[
 {id:'left-room',name:'客厅',purpose:'生活',polygon:[{x:0,y:0},{x:3,y:0},{x:3,y:4},{x:0,y:4}],locked:false},
 {id:'right-room',name:'书房',purpose:'工作',polygon:[{x:3,y:0},{x:6,y:0},{x:6,y:4},{x:3,y:4}],locked:false},
],openings:[{id:'door-033',wallId:'divider',kind:'door',offset:.5,width:.9,height:2,sill:0}],items:[],calibration:{wallId:'bottom-left',length:3,source:'现场测量',confirmed:true},geography:{latitude:31,north:0,assumption:'test'}});

async function fixture(){
 const prior=process.env.ALVA_ACCESS_CODE;process.env.ALVA_ACCESS_CODE=code;const store=new AlvaStore();await store.init();const created=await store.create('ALVA-033');
 await store.ensureAccessCode(created.project.id);
 const seeded=await store.mutate(created.project.id,randomUUID(),0,'seed',{},p=>{const s=scene(),topology=createTopologyVersion(p,s);p.scene=structuredClone(s);p.confirmedTopology=topology;p.topologyVersions=[topology];p.confirmedBuilding={topologyFingerprint:topology.sourceFingerprint} as any;p.buildingState={status:'confirmed',topologyVersion:topology.version,topologyFingerprint:topology.sourceFingerprint,attempts:1,updatedAt:new Date().toISOString()}});
 const invite=await store.invite(created.project.id,'designer');const app=await buildAlva(store,{assets:false,origin:'http://localhost'});const login=await app.inject({method:'POST',url:'/api/access',headers:{origin:'http://localhost'},payload:{code}});const designer=await app.inject({method:'POST',url:'/api/access',headers:{origin:'http://localhost'},payload:{code,inviteToken:invite.token}});return {prior,store,app,project:created.project,seeded,headers:{cookie:`alva_session=${login.cookies[0].value}`,origin:'http://localhost'},designerHeaders:{cookie:`alva_session=${designer.cookies[0].value}`,origin:'http://localhost'}};
}
async function cleanup(x:any){await x.app.close();await x.store.close();if(x.prior===undefined)delete process.env.ALVA_ACCESS_CODE;else process.env.ALVA_ACCESS_CODE=x.prior}
const migration={openingId:'door-033',targetWallId:'bottom-left',offset:.5};

test('ALVA-033 preview is read-only and returns a topology-bound migrated opening',async()=>{const x=await fixture();try{const before=await x.store.get(x.project.id);const r=await x.app.inject({method:'POST',url:'/api/professional/remodel/preview',headers:x.headers,payload:{expectedRevision:before.revision,wallId:'divider',migrations:[migration]}});assert.equal(r.statusCode,200,r.body);const preview=r.json();assert.equal(preview.scene.walls.some((w:any)=>w.id==='divider'),false);assert.equal(preview.scene.openings[0].id,'door-033');assert.equal(preview.scene.openings[0].wallId,'bottom-left');assert.equal((await x.store.get(x.project.id)).revision,before.revision);assert.equal((await x.store.get(x.project.id)).scene!.walls.some((w:any)=>w.id==='divider'),true)}finally{await cleanup(x)}});

test('ALVA-033 confirmation atomically creates a new topology, keeps opening identity, and expires old building',async()=>{const x=await fixture();try{const before=await x.store.get(x.project.id);const preview=(await x.app.inject({method:'POST',url:'/api/professional/remodel/preview',headers:x.headers,payload:{expectedRevision:before.revision,wallId:'divider',migrations:[migration]}})).json();const payload={requestId:randomUUID(),expectedRevision:before.revision,wallId:'divider',migrations:[migration],baseTopologyId:preview.baseTopologyId,previewFingerprint:preview.previewFingerprint,reason:'专业复核确认隔断可移除，门洞迁移至左侧墙段',confirmed:true};const r=await x.app.inject({method:'POST',url:'/api/professional/remodel/confirm',headers:x.headers,payload});assert.equal(r.statusCode,200,r.body);const out=r.json();assert.equal(out.confirmedTopology.version,before.confirmedTopology!.version+1);assert.equal(out.scene.walls.some((w:any)=>w.id==='divider'),false);assert.equal(out.scene.openings.find((o:any)=>o.id==='door-033').wallId,'bottom-left');assert.equal(out.buildingState.status,'expired');assert.match(out.buildingState.error,/旧建筑结果已过期/);assert.equal(out.confirmedBuilding.topologyFingerprint,before.confirmedBuilding!.topologyFingerprint);assert.match(out.changes.at(-1).context.join(' '),/door-033/)}finally{await cleanup(x)}});

test('ALVA-033 rejects missing/illegal migrations, stale previews, and designer access without pollution',async()=>{const x=await fixture();try{const before=await x.store.get(x.project.id);const missing=await x.app.inject({method:'POST',url:'/api/professional/remodel/preview',headers:x.headers,payload:{expectedRevision:before.revision,wallId:'divider',migrations:[]}});assert.equal(missing.statusCode,422);const illegal=await x.app.inject({method:'POST',url:'/api/professional/remodel/preview',headers:x.headers,payload:{expectedRevision:before.revision,wallId:'divider',migrations:[{...migration,targetWallId:'divider'}]}});assert.equal(illegal.statusCode,422);const denied=await x.app.inject({method:'POST',url:'/api/professional/remodel/preview',headers:x.designerHeaders,payload:{expectedRevision:before.revision,wallId:'divider',migrations:[migration]}});assert.equal(denied.statusCode,403);const preview=(await x.app.inject({method:'POST',url:'/api/professional/remodel/preview',headers:x.headers,payload:{expectedRevision:before.revision,wallId:'divider',migrations:[migration]}})).json();await x.store.mutate(x.project.id,randomUUID(),before.revision,'unrelated',{},p=>{p.name='并发修改'});const stale=await x.app.inject({method:'POST',url:'/api/professional/remodel/confirm',headers:x.headers,payload:{requestId:randomUUID(),expectedRevision:before.revision,wallId:'divider',migrations:[migration],baseTopologyId:preview.baseTopologyId,previewFingerprint:preview.previewFingerprint,reason:'过期测试',confirmed:true}});assert.equal(stale.statusCode,409);const after=await x.store.get(x.project.id);assert.equal(after.scene!.walls.some((w:any)=>w.id==='divider'),true)}finally{await cleanup(x)}});

test('ALVA-033 confirmation is idempotent for the same request',async()=>{const x=await fixture();try{const before=await x.store.get(x.project.id);const preview=(await x.app.inject({method:'POST',url:'/api/professional/remodel/preview',headers:x.headers,payload:{expectedRevision:before.revision,wallId:'divider',migrations:[migration]}})).json();const payload={requestId:randomUUID(),expectedRevision:before.revision,wallId:'divider',migrations:[migration],baseTopologyId:preview.baseTopologyId,previewFingerprint:preview.previewFingerprint,reason:'重复提交测试',confirmed:true};const first=await x.app.inject({method:'POST',url:'/api/professional/remodel/confirm',headers:x.headers,payload});const second=await x.app.inject({method:'POST',url:'/api/professional/remodel/confirm',headers:x.headers,payload});assert.equal(first.statusCode,200,first.body);assert.equal(second.statusCode,200,second.body);assert.equal(second.json().revision,first.json().revision);assert.equal((await x.store.get(x.project.id)).topologyVersions.length,2)}finally{await cleanup(x)}});
