import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import {createTopologyVersion} from '../api/topology/calibration.js';
import {assertFormalWallChangeAllowed,listProfessionalGrants,listWallClassifications} from '../api/topology/professional-access.js';
import type {SceneData} from '../api/model.js';

const code='alva032-shared-code-123456';
const scene=():SceneData=>({walls:[{id:'north',a:{x:0,y:0},b:{x:6,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]},{id:'east',a:{x:6,y:0},b:{x:6,y:4},thickness:.15,height:2.8,structural:'unknown',evidence:[]},{id:'south',a:{x:6,y:4},b:{x:0,y:4},thickness:.15,height:2.8,structural:'unknown',evidence:[]},{id:'west',a:{x:0,y:4},b:{x:0,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]}],rooms:[{id:'living',name:'客厅',purpose:'生活',polygon:[{x:0,y:0},{x:6,y:0},{x:6,y:4},{x:0,y:4}],locked:false}],openings:[],items:[],calibration:{wallId:'north',length:6,source:'现场测量',confirmed:true},geography:{latitude:31,north:0,assumption:'test'}});
const headers=(r:any)=>({cookie:`alva_session=${r.cookies[0].value}`,origin:'http://localhost'});
async function fixture(){const prior=process.env.ALVA_ACCESS_CODE;process.env.ALVA_ACCESS_CODE=code;const store=new AlvaStore();await store.init();const created=await store.create('ALVA-032');await store.ensureAccessCode(created.project.id);const seeded=await store.mutate(created.project.id,randomUUID(),0,'seed',{},p=>{const s=scene(),topology=createTopologyVersion(p,s);p.scene=structuredClone(s);p.confirmedTopology=topology;p.topologyVersions=[topology]});const grant=await store.grantProfessional(created.project.id,'engineer-lexie-test','注册结构工程师·墙体分类','项目服务端核验资质文件 TEST-032','acceptance-admin');const designerInvite=await store.invite(created.project.id,'designer');const app=await buildAlva(store,{assets:false,origin:'http://localhost'});const owner=await app.inject({method:'POST',url:'/api/access',headers:{origin:'http://localhost'},payload:{code}}),professional=await app.inject({method:'POST',url:'/api/access',headers:{origin:'http://localhost'},payload:{code,inviteToken:grant.token}}),designer=await app.inject({method:'POST',url:'/api/access',headers:{origin:'http://localhost'},payload:{code,inviteToken:designerInvite.token}});return {prior,store,app,created,seeded,grant,owner,professional,designer,oh:headers(owner),ph:headers(professional),dh:headers(designer)}}
async function done(x:any){await x.app.close();await x.store.close();if(x.prior===undefined)delete process.env.ALVA_ACCESS_CODE;else process.env.ALVA_ACCESS_CODE=x.prior}

test('ALVA-032 professional grant is distinct from owner/designer and classification preserves operator/source audit',async()=>{const x=await fixture();try{assert.equal(x.owner.json().role,'owner');assert.equal(x.professional.json().role,'professional');assert.equal(x.designer.json().role,'designer');const ownerFake=await x.app.inject({method:'POST',url:'/api/professional/walls/classify',headers:x.oh,payload:{requestId:randomUUID(),expectedRevision:x.seeded.revision,wallId:'north',structural:'nonloadbearing',evidenceText:'owner cannot self certify'}});assert.equal(ownerFake.statusCode,403);const designerRead=await x.app.inject({url:'/api/professional/walls',headers:x.dh});assert.equal(designerRead.statusCode,403);const blockedWrite=await x.app.inject({method:'POST',url:'/api/answers',headers:x.ph,payload:{requestId:randomUUID(),expectedRevision:x.seeded.revision,answer:{questionId:'Q01',roomId:null,text:'x',state:'answered',locked:false,confirmed:true}}});assert.equal(blockedWrite.statusCode,403);assert.match(blockedWrite.json().error,/专业角色仅可执行受控墙体专业操作/);
 const classified=await x.app.inject({method:'POST',url:'/api/professional/walls/classify',headers:x.ph,payload:{requestId:randomUUID(),expectedRevision:x.seeded.revision,wallId:'north',structural:'loadbearing',evidenceText:'结构图 S-01 标注 + 现场核验'}});assert.equal(classified.statusCode,200,classified.body);const p=classified.json(),wall=p.scene.walls.find((w:any)=>w.id==='north'),topWall=p.confirmedTopology.scene.walls.find((w:any)=>w.id==='north');assert.equal(wall.structural,'loadbearing');assert.ok(wall.evidence[0].startsWith('professional-classification:'));assert.equal(topWall.structural,'loadbearing');const rows=await listWallClassifications(x.store,x.created.project.id);assert.equal(rows.length,1);assert.equal(rows[0].operatorId,'engineer-lexie-test');assert.equal(rows[0].authority,'注册结构工程师·墙体分类');assert.equal(rows[0].evidenceText,'结构图 S-01 标注 + 现场核验');const grants=await listProfessionalGrants(x.store,x.created.project.id);assert.equal(grants[0].grantedBy,'acceptance-admin');assert.equal(grants[0].grantEvidence,'项目服务端核验资质文件 TEST-032');const ownerView=await x.app.inject({url:'/api/professional/walls',headers:x.oh});assert.equal(ownerView.statusCode,200);assert.equal(ownerView.json().classifications[0].operatorId,'engineer-lexie-test')
 }finally{await done(x)}});

test('ALVA-032 calibration never grants demolition; unknown/loadbearing/protected all reject, traced nonloadbearing can be removed only by professional',async()=>{const x=await fixture();try{let revision=x.seeded.revision;const remove=async(wallId:string,expectedRevision=revision)=>x.app.inject({method:'POST',url:'/api/professional/walls/remove',headers:x.ph,payload:{requestId:randomUUID(),expectedRevision,wallId,reason:'专业确认后的拆改测试',confirmed:true}}),classify=async(structural:string,evidenceText:string)=>{const r=await x.app.inject({method:'POST',url:'/api/professional/walls/classify',headers:x.ph,payload:{requestId:randomUUID(),expectedRevision:revision,wallId:'north',structural,evidenceText}});assert.equal(r.statusCode,200,r.body);revision=r.json().revision;return r.json()};
 let r=await remove('north');assert.equal(r.statusCode,403);assert.match(r.json().error,/未知、承重或受保护墙禁止正式拆改/);await classify('loadbearing','结构图确认承重');r=await remove('north');assert.equal(r.statusCode,403);await classify('protected','物业文件要求保留');r=await remove('north');assert.equal(r.statusCode,403);const p=await classify('nonloadbearing','结构工程师核对图纸与现场，确认非承重');const before=p.scene.walls.length;r=await remove('north');assert.equal(r.statusCode,200,r.body);const after=r.json();assert.equal(after.scene.walls.length,before-1);assert.equal(after.confirmedTopology,undefined);assert.equal(after.confirmedBuilding,undefined);assert.equal(after.zones.length,0);assert.match(after.changes.at(-1).context.join(' '),/操作者 engineer-lexie-test/)
 }finally{await done(x)}});

test('ALVA-032 server-admin revocation is audited and immediately invalidates professional session/invite',async()=>{const x=await fixture();try{assert.equal((await x.app.inject({url:'/api/professional/access',headers:x.ph})).statusCode,200);const revoked=await x.store.revokeProfessional(x.created.project.id,x.grant.grantId,'acceptance-revoker');assert.equal(revoked,true);assert.equal((await x.app.inject({url:'/api/project',headers:x.ph})).statusCode,401);assert.equal((await x.app.inject({method:'POST',url:'/api/access',headers:{origin:'http://localhost'},payload:{code,inviteToken:x.grant.token}})).statusCode,401);const grants=await listProfessionalGrants(x.store,x.created.project.id);assert.equal(grants[0].status,'revoked');assert.equal(grants[0].revokedBy,'acceptance-revoker');assert.ok(grants[0].revokedAt);assert.equal(await x.store.revokeProfessional(x.created.project.id,x.grant.grantId,'again'),false)}finally{await done(x)}});

test('ALVA-032 formal-change guard rejects calibrated-but-unclassified evidence and owner/model-style nonprofessional calls',()=>{assert.throws(()=>assertFormalWallChangeAllowed({structural:'nonloadbearing',evidence:['calibration:measured-wall']},true),/缺少可追溯的专业分类证据/);assert.throws(()=>assertFormalWallChangeAllowed({structural:'nonloadbearing',evidence:['professional-classification:test']},false),/已授权专业角色/);assert.doesNotThrow(()=>assertFormalWallChangeAllowed({structural:'nonloadbearing',evidence:['professional-classification:test']},true))});
