import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import {createTopologyVersion} from '../api/topology/calibration.js';
import {roomSplitTools} from '../api/topology/room-split.js';
import type {SceneData} from '../api/model.js';

const code=process.env.ALVA035_TEST_CODE;if(!code)throw new Error('ALVA035_TEST_CODE must be provided');
const scene=():SceneData=>({walls:[
 {id:'bottom',a:{x:0,y:0},b:{x:4,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]},
 {id:'right',a:{x:4,y:0},b:{x:4,y:4},thickness:.15,height:2.8,structural:'unknown',evidence:[]},
 {id:'top',a:{x:4,y:4},b:{x:0,y:4},thickness:.15,height:2.8,structural:'unknown',evidence:[]},
 {id:'left',a:{x:0,y:4},b:{x:0,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]},
],rooms:[{id:'studio',name:'工作室',purpose:'工作',polygon:[{x:0,y:0},{x:4,y:0},{x:4,y:4},{x:0,y:4}],locked:false}],openings:[{id:'window-035',wallId:'top',kind:'window',offset:.25,width:1,height:1.2,sill:.9}],items:[
 {id:'desk-035',assetId:'alva-table',roomId:'studio',name:'书桌',x:1,y:2,width:1.4,depth:.65,height:.75,rotation:0,color:'#b49a75',material:'wood',clearance:0,locked:false},
 {id:'cabinet-035',assetId:'alva-cabinet',roomId:'studio',name:'收纳柜',x:3,y:2,width:1.2,depth:.45,height:1.8,rotation:0,color:'#bca68a',material:'wood',clearance:0,locked:true},
],calibration:{wallId:'bottom',length:4,source:'现场测量',confirmed:true},geography:{latitude:31,north:0,assumption:'测试图上方为北'}});
async function fixture(){const prior=process.env.ALVA_ACCESS_CODE;process.env.ALVA_ACCESS_CODE=code;const store=new AlvaStore();await store.init();const created=await store.create('ALVA-035');await store.ensureAccessCode(created.project.id);const seeded=await store.mutate(created.project.id,randomUUID(),0,'seed',{},p=>{const s=scene(),topology=createTopologyVersion(p,s);p.scene=s;p.confirmedTopology=topology;p.topologyVersions=[topology];p.answers=[{questionId:'Q035',roomId:'studio',text:'需要安静工作区',state:'answered',locked:true,confirmed:true,evidenceId:'e-035'}];p.evidence=[{id:'e-035',quote:'我需要一个安静工作区',source:'questionnaire',roomId:'studio',createdAt:new Date().toISOString()}];p.findings=[{id:'f-035',kind:'requirement',title:'安静工作区',reason:'需要减少干扰',suggestion:'划分独立工作区',objectIds:['desk-035'],roomIds:['studio'],evidenceIds:['e-035'],confidence:'high',status:'pending',stage:'intake'}];p.roomStyles={studio:{tags:['安静'],wall:{color:'#ded6cb',material:'paint'},floor:{color:'#ad997c',material:'wood'}}};p.buildingState={status:'confirmed',topologyVersion:topology.version,topologyFingerprint:topology.sourceFingerprint,attempts:1,updatedAt:new Date().toISOString()};p.confirmedBuilding={topologyVersion:topology.version,topologyFingerprint:topology.sourceFingerprint,components:[],camera:{position:{x:8,y:8,z:8},target:{x:2,y:2,z:0}}} as any});const app=await buildAlva(store,{assets:false,origin:'http://localhost'});const session=await store.issueInternalSession(created.project.id);const invite=await store.invite(created.project.id,'designer');const designer=await app.inject({method:'POST',url:'/api/access',headers:{origin:'http://localhost'},payload:{code,inviteToken:invite.token}});return {prior,store,app,projectId:created.project.id,headers:{cookie:'alva_session='+session.token,origin:'http://localhost'},designerHeaders:{cookie:'alva_session='+designer.cookies[0].value,origin:'http://localhost'},seeded}}
async function cleanup(x:any){await x.app.close();await x.store.close();if(x.prior===undefined)delete process.env.ALVA_ACCESS_CODE;else process.env.ALVA_ACCESS_CODE=x.prior}
const base=(revision:number)=>({expectedRevision:revision,sourceRoomId:'studio',splitLine:{a:{x:2,y:-1},b:{x:2,y:5}},children:[{name:'工作区',purpose:'安静工作',locked:false},{name:'储物区',purpose:'收纳',locked:false}],assignments:[]});

test('ALVA-035 preview is read-only and requires explicit assignments',async()=>{const x=await fixture();try{const before=await x.store.get(x.projectId),r=await x.app.inject({method:'POST',url:'/api/rooms/split/preview',headers:x.headers,payload:base(before.revision)});assert.equal(r.statusCode,200,r.body);const preview=r.json();assert.equal(preview.scene.rooms.length,2);assert.equal(preview.readyToConfirm,false);assert.ok(preview.missing.some((m:any)=>m.kind==='item'));assert.ok(preview.missing.some((m:any)=>m.kind==='opening'));assert.ok(preview.missing.some((m:any)=>m.kind==='answer'));assert.equal((await x.store.get(x.projectId)).revision,before.revision);assert.equal((await x.store.get(x.projectId)).scene!.rooms[0].id,'studio')}finally{await cleanup(x)}});

test('ALVA-035 confirmation preserves provenance, locks and snapshot restore',async()=>{const x=await fixture();try{let p:any=await x.store.get(x.projectId);p=await x.store.mutate(x.projectId,randomUUID(),p.revision,'save',{confirmed:true},()=>{});const first=(await x.app.inject({method:'POST',url:'/api/rooms/split/preview',headers:x.headers,payload:base(p.revision)})).json();const assignments=first.assignmentRequirements.map((r:any)=>({kind:r.kind,id:r.id,childIndex:r.kind==='item'?(r.id==='desk-035'?0:1):r.kind==='opening'?0:r.kind==='answer'||r.kind==='evidence'?0:1}));const input={...base(p.revision),assignments};const preview=(await x.app.inject({method:'POST',url:'/api/rooms/split/preview',headers:x.headers,payload:input})).json();assert.equal(preview.readyToConfirm,true);const response=await x.app.inject({method:'POST',url:'/api/rooms/split/confirm',headers:x.headers,payload:{...input,requestId:randomUUID(),baseTopologyId:preview.baseTopologyId,previewFingerprint:preview.previewFingerprint,reason:'按需求将工作室拆为工作区与储物区',confirmed:true}});assert.equal(response.statusCode,200,response.body);p=response.json();const childIds=p.scene.rooms.map((r:any)=>r.id);assert.equal(childIds.length,2);assert.equal(p.scene.items.find((i:any)=>i.id==='desk-035').roomId,childIds[0]);assert.equal(p.scene.items.find((i:any)=>i.id==='cabinet-035').roomId,childIds[1]);assert.equal(p.scene.items.find((i:any)=>i.id==='cabinet-035').locked,true);assert.equal(p.answers[0].roomId,childIds[0]);assert.equal(p.evidence[0].roomId,childIds[0]);assert.equal(p.roomSplitHistory[0].sourceRoomId,'studio');assert.deepEqual(p.roomSplitHistory[0].childRoomIds,childIds);assert.equal(p.buildingState.status,'expired');assert.equal(p.confirmedBuilding,undefined);p=await x.store.mutate(x.projectId,randomUUID(),p.revision,'save',{confirmed:true},()=>{});let restored=await x.app.inject({method:'POST',url:'/api/restore',headers:x.headers,payload:{requestId:randomUUID(),expectedRevision:p.revision,version:1,confirmed:true}});assert.equal(restored.statusCode,200,restored.body);assert.deepEqual(restored.json().scene.rooms.map((r:any)=>r.id),['studio']);restored=await x.app.inject({method:'POST',url:'/api/restore',headers:x.headers,payload:{requestId:randomUUID(),expectedRevision:restored.json().revision,version:2,confirmed:true}});assert.equal(restored.statusCode,200,restored.body);assert.deepEqual(restored.json().scene.rooms.map((r:any)=>r.id),childIds)}finally{await cleanup(x)}});

test('ALVA-035 rejects locked downgrade and designer access',async()=>{const x=await fixture();try{let p=await x.store.get(x.projectId);await x.store.mutate(x.projectId,randomUUID(),p.revision,'lock',{},state=>{state.scene!.rooms[0].locked=true});p=await x.store.get(x.projectId);const denied=await x.app.inject({method:'POST',url:'/api/rooms/split/preview',headers:x.headers,payload:base(p.revision)});assert.equal(denied.statusCode,422);const designerResponse=await x.app.inject({method:'POST',url:'/api/rooms/split/preview',headers:x.designerHeaders,payload:base(p.revision)});assert.equal(designerResponse.statusCode,403)}finally{await cleanup(x)}});

test('ALVA-035 exposes guarded floorplan MCP tools',async()=>{const x=await fixture();try{assert.deepEqual(roomSplitTools(x.store,x.projectId).map(t=>t.name),['preview_room_split','confirm_room_split'])}finally{await cleanup(x)}});
