import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import type {Project,Proposal,SceneData,Change} from '../api/model.js';

const scene=():SceneData=>({walls:[{id:'w',a:{x:0,y:0},b:{x:8,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]}],rooms:[{id:'room',name:'客厅',purpose:'生活',polygon:[{x:0,y:0},{x:8,y:0},{x:8,y:5},{x:0,y:5}],locked:false}],openings:[],items:[{id:'sofa',assetId:'alva-sofa',roomId:'room',name:'沙发',x:2,y:2,width:2.1,depth:.9,height:.8,rotation:0,color:'#9da991',material:'fabric',clearance:0,locked:false},{id:'table',assetId:'alva-table',roomId:'room',name:'书桌',x:5,y:2,width:1.4,depth:.65,height:.75,rotation:0,color:'#b49a75',material:'wood',clearance:0,locked:true},{id:'plant',assetId:'alva-plant',roomId:'room',name:'绿植',x:6.5,y:4,width:.45,depth:.45,height:1.2,rotation:0,color:'#648268',material:'wood',clearance:0,locked:false}],calibration:null,geography:{latitude:1.3,north:0,assumption:'test'}});
const proposal=(id:string,groupId:string,baseRevision:number,changes:Change[],referenceIds:string[]=[]):Proposal=>({id,groupId,title:id,rationale:'真实差异候选',evidenceIds:[],baseRevision,changes,status:'proposed',referenceIds});
async function setup(){const old=process.env.ALVA_ACCESS_CODE;process.env.ALVA_ACCESS_CODE='alva047-lexie-test-code';const store=new AlvaStore();await store.init();const {project}=await store.create('ALVA-047');await store.ensureAccessCode(project.id);const p=await store.mutate(project.id,randomUUID(),0,'seed',{},q=>{q.scene=scene()});const app=await buildAlva(store,{assets:false,origin:'http://localhost'}),session=await store.issueInternalSession(project.id);return {old,store,app,id:project.id,h:{cookie:'alva_session='+session.token},p}}
async function close(x:any){await x.app.close();await x.store.close();if(x.old===undefined)delete process.env.ALVA_ACCESS_CODE;else process.env.ALVA_ACCESS_CODE=x.old}

async function setGroup(x:any,group:Proposal[]){return x.store.mutate(x.id,randomUUID(),null,'seed-group',{},(p:Project)=>{p.proposals=group})}

test('ALVA-047 group preview compares two real variants, excludes locked targets and keeps surrounding references unselected',async()=>{const x=await setup();try{const groupId='g-preview';const seeded=await setGroup(x,[proposal('A',groupId,x.p.revision+1,[{action:'update',targetId:'sofa',values:{x:2.6}},{action:'update',targetId:'table',values:{x:5.5}}],['plant']),proposal('B',groupId,x.p.revision+1,[{action:'update',targetId:'sofa',values:{x:3.2}}],['plant'])]);const r=await x.app.inject({url:'/api/proposal-groups/'+groupId,headers:x.h});assert.equal(r.statusCode,200,r.body);const body=r.json();assert.equal(body.variants.length,2);assert.notEqual(JSON.stringify(body.variants[0].scene),JSON.stringify(body.variants[1].scene));assert.deepEqual(body.variants[0].selectableIds,['sofa']);assert.deepEqual(body.variants[0].referenceIds,['plant']);assert.equal(body.variants[0].scene.items.find((i:any)=>i.id==='table').x,5);assert.deepEqual(body.variants[0].excludedLockedIds,['table']);assert.equal((await x.store.get(x.id)).revision,seeded.revision)}finally{await close(x)}});

test('ALVA-047 group adoption is selected-only, idempotent and creates no automatic snapshot; explicit restore returns saved state',async()=>{const x=await setup();try{let p=await x.store.mutate(x.id,randomUUID(),x.p.revision,'save',{confirmed:true},()=>{});assert.equal((await x.store.versions(x.id)).length,1);const groupId='g-accept',newId=randomUUID();p=await setGroup(x,[proposal('A',groupId,p.revision+1,[{action:'update',targetId:'sofa',values:{x:2.7}},{action:'update',targetId:'table',values:{x:5.6}}]),proposal('B',groupId,p.revision+1,[{action:'add',targetId:'room',values:{assetId:'alva-chair',roomId:'room',x:4,y:4,newId}}])]);const req=randomUUID(),accept=await x.app.inject({method:'POST',url:'/api/proposal-groups/accept',headers:x.h,payload:{requestId:req,expectedRevision:p.revision,groupId,proposalId:'B',selectedIds:['room'],confirmed:true}});assert.equal(accept.statusCode,200,accept.body);const adopted=accept.json();assert.equal(adopted.scene.items.some((i:any)=>i.id===newId),true);assert.equal(adopted.scene.items.find((i:any)=>i.id==='sofa').x,2);assert.equal(adopted.proposals.find((v:any)=>v.id==='B').status,'accepted');assert.equal(adopted.proposals.find((v:any)=>v.id==='A').status,'rejected');assert.equal((await x.store.versions(x.id)).length,1);const replay=await x.app.inject({method:'POST',url:'/api/proposal-groups/accept',headers:x.h,payload:{requestId:req,expectedRevision:p.revision,groupId,proposalId:'B',selectedIds:['room'],confirmed:true}});assert.equal(replay.statusCode,200,replay.body);assert.deepEqual(replay.json(),adopted);assert.equal((await x.store.versions(x.id)).length,1);const restore=await x.app.inject({method:'POST',url:'/api/restore',headers:x.h,payload:{requestId:randomUUID(),expectedRevision:adopted.revision,version:1,confirmed:true}});assert.equal(restore.statusCode,200,restore.body);assert.equal(restore.json().scene.items.some((i:any)=>i.id===newId),false);assert.equal((await x.store.versions(x.id)).length,1)}finally{await close(x)}});

test('ALVA-047 invalid group is all-or-nothing and stale group conflicts leave furniture untouched',async()=>{const x=await setup();try{const bad='g-bad';let p=await setGroup(x,[proposal('A',bad,x.p.revision+1,[{action:'update',targetId:'sofa',values:{x:2.8}},{action:'update',targetId:'missing',values:{x:3}}]),proposal('B',bad,x.p.revision+1,[{action:'update',targetId:'sofa',values:{x:3.3}}])]);const before=JSON.stringify(p.scene),failed=await x.app.inject({method:'POST',url:'/api/proposal-groups/accept',headers:x.h,payload:{requestId:randomUUID(),expectedRevision:p.revision,groupId:bad,proposalId:'A',selectedIds:['sofa','missing'],confirmed:true}});assert.equal(failed.statusCode,422,failed.body);let after=await x.store.get(x.id);assert.equal(after.revision,p.revision);assert.equal(JSON.stringify(after.scene),before);assert.equal(after.proposals.every(v=>v.status==='proposed'),true);
 const stale='g-stale';p=await setGroup(x,[proposal('C',stale,after.revision+1,[{action:'update',targetId:'sofa',values:{x:2.9}}]),proposal('D',stale,after.revision+1,[{action:'update',targetId:'sofa',values:{x:3.4}}])]);const base=p.revision;p=await x.store.mutate(x.id,randomUUID(),p.revision,'unrelated',{},q=>{q.name='updated'});const conflict=await x.app.inject({method:'POST',url:'/api/proposal-groups/accept',headers:x.h,payload:{requestId:randomUUID(),expectedRevision:p.revision,groupId:stale,proposalId:'C',selectedIds:['sofa'],confirmed:true}});assert.equal(conflict.statusCode,409,conflict.body);after=await x.store.get(x.id);assert.equal(after.scene!.items.find(i=>i.id==='sofa')!.x,2);assert.equal(after.proposals.find(v=>v.id==='C')!.baseRevision,base)}finally{await close(x)}});

test('ALVA-047 rejects fake one-variant or duplicate groups before adoption',async()=>{const x=await setup();try{let p=await setGroup(x,[proposal('solo','g-solo',x.p.revision+1,[{action:'update',targetId:'sofa',values:{x:2.2}}])]);let r=await x.app.inject({url:'/api/proposal-groups/g-solo',headers:x.h});assert.equal(r.statusCode,422);p=await setGroup(x,[proposal('a','g-dupe',p.revision+1,[{action:'update',targetId:'sofa',values:{x:2.2}}]),proposal('b','g-dupe',p.revision+1,[{action:'update',targetId:'sofa',values:{x:2.2}}])]);r=await x.app.inject({url:'/api/proposal-groups/g-dupe',headers:x.h});assert.equal(r.statusCode,422);assert.match(r.json().error,/真实差异/)}finally{await close(x)}});
