import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {AlvaStore} from '../api/store.js';import {buildAlva} from '../api/api.js';import {validateScene,calibrate,type SceneData} from '../api/model.js';
export const rectangularFixture=():SceneData=>({walls:[{id:'n',a:{x:0,y:0},b:{x:5,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]},{id:'e',a:{x:5,y:0},b:{x:5,y:4},thickness:.15,height:2.8,structural:'unknown',evidence:[]},{id:'s',a:{x:5,y:4},b:{x:0,y:4},thickness:.15,height:2.8,structural:'unknown',evidence:[]},{id:'w',a:{x:0,y:4},b:{x:0,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]}],rooms:[{id:'room',name:'合成测试房间',purpose:'待确认',polygon:[{x:0,y:0},{x:5,y:0},{x:5,y:4},{x:0,y:4}],locked:false}],openings:[{id:'door',wallId:'s',kind:'door',offset:.5,width:.9,height:2.1,sill:0}],items:[],calibration:null,geography:{latitude:31,north:0,assumption:'合成测试，不是用户户型'}});
test('alva topology rejects self-intersection/non-finite coordinates; measured wall scales consistently',()=>{const scene=rectangularFixture();const calibrated=calibrate(scene,'n',10,'合成测量记录');assert.equal(calibrated.walls[0].b.x,10);assert.equal(calibrated.rooms[0].polygon[2].y,8);assert.equal(calibrated.openings[0].width,1.8);assert.equal(scene.calibration,null);const bad=rectangularFixture();bad.rooms[0].polygon=[{x:0,y:0},{x:5,y:4},{x:5,y:0},{x:0,y:4}];assert.throws(()=>validateScene(bad),/自交|面积/);bad.walls[0].a.x=Infinity;assert.throws(()=>validateScene(bad));});
test('alva revoked project links, read-only designer, atomic failed save, retry and complete snapshot restore',async()=>{
 const previousCode=process.env.ALVA_ACCESS_CODE;process.env.ALVA_ACCESS_CODE='test-unified-code-123456';
 const store=new AlvaStore();await store.init();const app=await buildAlva(store,{assets:false});
 try{const a=await store.create('A'),b=await store.create('B');await store.ensureAccessCode(a.project.id);assert.ok(a.token.length>=32);const auth=await app.inject({method:'POST',url:'/api/access',payload:{code:'test-unified-code-123456'}});assert.equal(auth.statusCode,200);const headers={cookie:`alva_session=${auth.cookies[0].value}`};
 assert.equal((await app.inject({url:`/api/projects/${b.project.id}`,headers})).statusCode,403);assert.equal((await app.inject({url:'/api/project'})).statusCode,401);
 let current=await store.mutate(a.project.id,randomUUID(),0,'fixture',{},p=>{p.candidate=rectangularFixture()});const command=()=>({requestId:randomUUID(),expectedRevision:current.revision});
 assert.equal((await app.inject({method:'POST',url:'/api/candidate/confirm',headers,payload:{...command(),confirmed:true}})).statusCode,422);
 let response=await app.inject({method:'POST',url:'/api/candidate/calibrate',headers,payload:{...command(),wallId:'n',length:10,source:'测试已知墙长'}});assert.equal(response.statusCode,200);current=response.json();
 response=await app.inject({method:'POST',url:'/api/candidate/confirm',headers,payload:{...command(),confirmed:true}});assert.equal(response.statusCode,200);current=response.json();const draft=structuredClone(current);store.failNextSave=true;const save={...command(),confirmed:true};
 response=await app.inject({method:'POST',url:'/api/save',headers,payload:save});assert.equal(response.statusCode,500);assert.deepEqual(await store.get(a.project.id),draft);assert.equal((await store.versions(a.project.id)).length,0);
 response=await app.inject({method:'POST',url:'/api/save',headers,payload:save});assert.equal(response.statusCode,200);current=response.json();assert.equal(current.savedVersion,1);assert.equal(current.dirty,false);assert.equal((await app.inject({method:'POST',url:'/api/save',headers,payload:save})).json().savedVersion,1);
 current=await store.mutate(a.project.id,randomUUID(),current.revision,'alter-test',{},p=>{p.answers=[];p.scene!.rooms[0].purpose='changed';p.name='changed';p.dirty=true});const restored=await app.inject({method:'POST',url:'/api/restore',headers,payload:{...command(),version:1,confirmed:true}});assert.equal(restored.statusCode,200);current=restored.json();assert.deepEqual(current.scene,draft.scene);assert.equal(current.name,draft.name);assert.deepEqual(current.answers,draft.answers);assert.equal(current.savedVersion,1);assert.equal(current.dirty,true);
 const invite=await store.invite(a.project.id,'designer');const designer=await app.inject({method:'POST',url:'/api/access',payload:{code:'test-unified-code-123456',inviteToken:invite.token}});const readonly={cookie:`alva_session=${designer.cookies[0].value}`};assert.equal(designer.json().role,'designer');assert.equal((await app.inject({url:'/api/project',headers:readonly})).statusCode,200);assert.equal((await app.inject({method:'POST',url:'/api/save',headers:readonly,payload:{...command(),confirmed:true}})).statusCode,403);
 await store.revoke(a.project.id,invite.linkId);assert.equal((await app.inject({url:'/api/project',headers:readonly})).statusCode,401);
 const faults=(await store.db.query<{operation:string}>('SELECT operation FROM alva_failures')).rows;assert.ok(faults.some(f=>f.operation==='save'));
 }finally{await app.close();await store.close();if(previousCode===undefined)delete process.env.ALVA_ACCESS_CODE;else process.env.ALVA_ACCESS_CODE=previousCode}
});
