import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {cards,flags,path,options,items,answered,activeAnswers,validation,condition,type Answers} from '../packages/contracts/alva/home-vision/flow.js';
import {AlvaStore} from '../api/store.js';import {buildAlva} from '../api/api.js';
const a=(entries:Record<string,any>):Answers=>Object.fromEntries(Object.entries(entries).map(([k,v])=>[k,{state:'answered',value:v}]));
test('all supplied cards and ZIP copy; stage paths are bounded and conditional',()=>{assert.equal(cards.length,57);assert.equal(cards[0].items[0].prompt,'What brings you here?');assert.equal(cards[0].items[0].options?.[1]&&typeof cards[0].items[0].options[1]==='object'?cards[0].items[0].options[1].label:'','Giving my current home a new style');let answers=a({Q01a:'Q01a.one_room',Q05a:['Q05a.bedroom'],Q04a:['Q04a.children']});assert.deepEqual(path(answers).filter(c=>c.stage==='S3').map(c=>c.card),['Q18','Q19','Q26','Q27','Q28']);answers=a({Q01a:'Q01a.exploring',Q35a:'Q35a.renovation'});assert.deepEqual(path(answers).filter(c=>c.stage==='S5').map(c=>c.card),['Q34']);assert.deepEqual(path(answers).filter(c=>c.stage==='S6').map(c=>c.card),['Q43']);assert(!flags(answers).has('BUILD_WORK'))});
test('whole-home expansion, pet/child filters, hidden old choices do not set flags',()=>{const answers=a({Q04a:['Q04a.children','Q04a.pets'],Q04b:['Q04b.under3'],Q05a:['Q05a.whole_home'],C3a:[{'C3a.type':'cat'}]});assert(flags(answers).has('ROOM_KIDS'));assert(path(answers).some(c=>c.card==='C3'));assert(condition('C3a.type includes cat',answers,flags(answers)));assert(!options(items.find(i=>i.id==='Q05a')!,answers).some(o=>o.id==='Q05a.kids'));answers.Q04a={state:'answered',value:['Q04a.just_me']};assert(!flags(answers).has('CHILD_UNDER3'));assert(!path(answers).some(c=>c.card==='C3'));assert(!activeAnswers(answers).C3a)});
test('rental, no-cooking, spend/save and unknown semantics',()=>{const answers=a({Q05a:['Q05a.kitchen'],Q15a:'Q15a.takeout',Q34a:'Q34a.rent',Q35a:'Q35a.remodel',Q46a:['Q46a.sofa']});assert(!flags(answers).has('BUILD_WORK'));assert(!path(answers).some(c=>c.card==='Q16'));assert(!options(items.find(i=>i.id==='Q46b')!,answers).some(o=>o.id==='Q46b.sofa'));assert(validation(a({Q06a:['Q06a.cozy','Q06a.calm','Q06a.bold','Q06a.bright']})).length);assert(!flags({Q01a:{state:'unknown',value:'Q01a.new_home'}}).has('NEW_HOME'))});
test('authenticated per-person saving, conflict and retry; no snapshots or legacy overwrite',async()=>{process.env.ALVA_ACCESS_CODE='alva057-synthetic-validation-code';const store=new AlvaStore();await store.init();const {project}=await store.create('Synthetic home vision');await store.ensureAccessCode(project.id);const owner=await store.issueInternalSession(project.id);const app=await buildAlva(store,{assets:false});try{const cookie='alva_session='+owner.token,id=randomUUID(),body={requestId:randomUUID(),id,name:'Alex',expectedVersion:0,cursor:'Q02',answers:a({Q01a:'Q01a.new_home'})};assert.equal((await app.inject({method:'GET',url:'/api/intake/vision'})).statusCode,401);const request=()=>app.inject({method:'POST',url:'/api/intake/vision',headers:{cookie},payload:body});assert.equal((await request()).statusCode,200);assert.equal((await request()).json().homeVision.responses[0].version,1);body.requestId=randomUUID();assert.equal((await request()).statusCode,409);body.id=randomUUID();body.name='Sam';assert.equal((await request()).statusCode,200);const p=await store.get(project.id);assert.equal(p.homeVision?.responses.length,2);assert.equal(p.savedVersion,0);assert.equal(p.answers.length,0);assert.equal((await store.versions(project.id)).length,0);assert.equal((await app.inject({method:'GET',url:'/api/intake/vision/brief',headers:{cookie}})).json().responses.length,2)}finally{await app.close();await store.close()}});

test('empty optional groups and other text remain unanswered',()=>{assert.equal(answered(a({Q10a:{choice:'Q10a.other',text:'  '}}),'Q10a'),false);assert.equal(answered(a({C3a:[{}]}),'C3a'),false);assert.equal(answered(a({Q10a:{choice:'Q10a.other',text:'Avoid velvet'}}),'Q10a'),true)});
