import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import type {SceneData} from '../api/model.js';

const code='alva031-shared-code-123456';
const scene:SceneData={walls:[{id:'w1',a:{x:0,y:0},b:{x:4,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]},{id:'w2',a:{x:4,y:0},b:{x:4,y:3},thickness:.15,height:2.8,structural:'unknown',evidence:[]},{id:'w3',a:{x:4,y:3},b:{x:0,y:3},thickness:.15,height:2.8,structural:'unknown',evidence:[]},{id:'w4',a:{x:0,y:3},b:{x:0,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]}],rooms:[{id:'living',name:'客厅',purpose:'生活',polygon:[{x:0,y:0},{x:4,y:0},{x:4,y:3},{x:0,y:3}],locked:false}],openings:[],items:[],calibration:null,geography:{latitude:31,north:0,assumption:'test'}};
const cookie=(r:any)=>({cookie:`alva_session=${r.cookies[0].value}`,origin:'http://localhost'});

async function fixture(){const prior=process.env.ALVA_ACCESS_CODE;process.env.ALVA_ACCESS_CODE=code;const store=new AlvaStore();await store.init();const created=await store.create('ALVA-031');await store.ensureAccessCode(created.project.id);const seeded=await store.mutate(created.project.id,randomUUID(),0,'seed',{},p=>{p.scene=structuredClone(scene)});const other=await store.create('OTHER');const app=await buildAlva(store,{assets:false,origin:'http://localhost'});return {prior,store,app,created,seeded,other}}
async function done(x:any){await x.app.close();await x.store.close();if(x.prior===undefined)delete process.env.ALVA_ACCESS_CODE;else process.env.ALVA_ACCESS_CODE=x.prior}

test('ALVA-031 designer requires shared code plus invite and remains read-only across direct write APIs',async()=>{const x=await fixture();try{const owner=await x.app.inject({method:'POST',url:'/api/access',headers:{origin:'http://localhost'},payload:{code}});assert.equal(owner.statusCode,200);assert.equal(owner.json().role,'owner');const ownerHeaders=cookie(owner);const invite=await x.app.inject({method:'POST',url:'/api/invites',headers:ownerHeaders,payload:{}});assert.equal(invite.statusCode,200,invite.body);const token=invite.json().token,linkId=invite.json().linkId;
 assert.equal((await x.app.inject({method:'POST',url:'/api/access',headers:{origin:'http://localhost'},payload:{inviteToken:token}})).statusCode,400);
 assert.equal((await x.app.inject({method:'POST',url:'/api/access',headers:{origin:'http://localhost'},payload:{code:'wrong-wrong-wrong-1234',inviteToken:token}})).statusCode,401);
 const designer=await x.app.inject({method:'POST',url:'/api/access',headers:{origin:'http://localhost'},payload:{code,inviteToken:token}});assert.equal(designer.statusCode,200,designer.body);assert.equal(designer.json().role,'designer');const h=cookie(designer);assert.equal((await x.app.inject({url:'/api/session',headers:h})).json().role,'designer');assert.equal((await x.app.inject({url:'/api/project',headers:h})).statusCode,200);
 const writes:[string,any][]=[['/api/save',{requestId:randomUUID(),expectedRevision:x.seeded.revision,confirmed:true}],['/api/restore',{requestId:randomUUID(),expectedRevision:x.seeded.revision,version:1,confirmed:true}],['/api/commands',{requestId:randomUUID(),expectedRevision:x.seeded.revision,changes:[],confirmed:true}],['/api/proposals/accept',{requestId:randomUUID(),expectedRevision:x.seeded.revision,id:'missing',selectedIds:['x'],confirmed:true}],['/api/answers',{requestId:randomUUID(),expectedRevision:x.seeded.revision,answer:{questionId:'Q01',roomId:null,text:'x',state:'answered',locked:false,confirmed:true}}],['/api/invites',{}]];
 for(const [url,payload] of writes){const r=await x.app.inject({method:'POST',url,headers:h,payload});assert.equal(r.statusCode,403,`${url}: ${r.body}`);assert.match(r.json().error,/设计师入口为只读/)}
 assert.equal((await x.app.inject({url:`/api/projects/${x.other.project.id}`,headers:h})).statusCode,403);
 const list=await x.app.inject({url:'/api/invites',headers:ownerHeaders});assert.equal(list.statusCode,200,list.body);const row=list.json().invites.find((v:any)=>v.id===linkId);assert.equal(row.revoked,false);assert.equal(row.active_sessions,1);
 }finally{await done(x)}});

test('ALVA-031 owner can revoke designer access; active session and old invite immediately stop working, designer can logout',async()=>{const x=await fixture();try{const owner=await x.app.inject({method:'POST',url:'/api/access',headers:{origin:'http://localhost'},payload:{code}}),oh=cookie(owner),invite=(await x.app.inject({method:'POST',url:'/api/invites',headers:oh,payload:{}})).json(),designer=await x.app.inject({method:'POST',url:'/api/access',headers:{origin:'http://localhost'},payload:{code,inviteToken:invite.token}}),dh=cookie(designer);const logout=await x.app.inject({method:'POST',url:'/api/logout',headers:dh,payload:{}});assert.equal(logout.statusCode,200,logout.body);assert.equal((await x.app.inject({url:'/api/project',headers:dh})).statusCode,401);
 const designer2=await x.app.inject({method:'POST',url:'/api/access',headers:{origin:'http://localhost'},payload:{code,inviteToken:invite.token}}),dh2=cookie(designer2);assert.equal((await x.app.inject({url:'/api/project',headers:dh2})).statusCode,200);const revoke=await x.app.inject({method:'POST',url:`/api/invites/${invite.linkId}/revoke`,headers:oh,payload:{}});assert.equal(revoke.statusCode,200,revoke.body);assert.equal((await x.app.inject({url:'/api/project',headers:dh2})).statusCode,401);assert.equal((await x.app.inject({method:'POST',url:'/api/access',headers:{origin:'http://localhost'},payload:{code,inviteToken:invite.token}})).statusCode,401);const listed=(await x.app.inject({url:'/api/invites',headers:oh})).json().invites.find((v:any)=>v.id===invite.linkId);assert.equal(listed.revoked,true);assert.equal((await x.app.inject({method:'POST',url:`/api/invites/${randomUUID()}/revoke`,headers:oh,payload:{}})).statusCode,404);
 }finally{await done(x)}});

test('ALVA-031 invite management is owner-only even though list is GET',async()=>{const x=await fixture();try{const owner=await x.app.inject({method:'POST',url:'/api/access',headers:{origin:'http://localhost'},payload:{code}}),oh=cookie(owner),invite=(await x.app.inject({method:'POST',url:'/api/invites',headers:oh,payload:{}})).json(),designer=await x.app.inject({method:'POST',url:'/api/access',headers:{origin:'http://localhost'},payload:{code,inviteToken:invite.token}}),dh=cookie(designer);const list=await x.app.inject({url:'/api/invites',headers:dh});assert.equal(list.statusCode,403,list.body);assert.match(list.json().error,/仅业主可管理设计师访问/)}finally{await done(x)}});
