import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import {createTopologyVersion} from '../api/topology/calibration.js';
import {assertNoDanglingRoomReferences,roomMergeTools} from '../api/topology/room-merge.js';
import {prepareSnapshotRestore} from '../api/snapshots/state.js';
import {sections} from '../api/export.js';
import type {Project,SceneData} from '../api/model.js';

const code='alva034-lexie-test-code';
const styleA={tags:['暖色'],wall:{color:'#ded6cb',material:'paint' as const},floor:{color:'#ad997c',material:'wood' as const}};
const styleB={tags:['冷色'],wall:{color:'#d8e0e6',material:'paint' as const},floor:{color:'#aaaaaa',material:'concrete' as const}};
const scene=():SceneData=>({walls:[
 {id:'bottom-left',a:{x:0,y:0},b:{x:3,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]},
 {id:'bottom-right',a:{x:3,y:0},b:{x:6,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]},
 {id:'right',a:{x:6,y:0},b:{x:6,y:4},thickness:.15,height:2.8,structural:'unknown',evidence:[]},
 {id:'top-right',a:{x:6,y:4},b:{x:3,y:4},thickness:.15,height:2.8,structural:'unknown',evidence:[]},
 {id:'top-left',a:{x:3,y:4},b:{x:0,y:4},thickness:.15,height:2.8,structural:'unknown',evidence:[]},
 {id:'left',a:{x:0,y:4},b:{x:0,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]},
],rooms:[
 {id:'left-room',name:'客厅',purpose:'生活',polygon:[{x:0,y:0},{x:3,y:0},{x:3,y:4},{x:0,y:4}],locked:false},
 {id:'right-room',name:'书房',purpose:'工作',polygon:[{x:3,y:0},{x:6,y:0},{x:6,y:4},{x:3,y:4}],locked:false},
],openings:[{id:'window-034',wallId:'top-left',kind:'window',offset:.5,width:1,height:1.2,sill:.9}],items:[
 {id:'sofa-034',assetId:'alva-sofa',roomId:'left-room',name:'沙发',x:1.5,y:2,width:2.1,depth:.9,height:.8,rotation:0,color:'#9da991',material:'fabric',clearance:0,locked:true},
 {id:'desk-034',assetId:'alva-table',roomId:'right-room',name:'书桌',x:4.5,y:2,width:1.4,depth:.65,height:.75,rotation:0,color:'#b49a75',material:'wood',clearance:0,locked:false},
],calibration:{wallId:'bottom-left',length:3,source:'合成验收尺寸',confirmed:true},geography:{latitude:31,north:0,assumption:'test'}});

async function fixture(){
 const prior=process.env.ALVA_ACCESS_CODE;process.env.ALVA_ACCESS_CODE=code;const store=new AlvaStore();await store.init();const created=await store.create('ALVA-034');await store.ensureAccessCode(created.project.id);
 let seeded=await store.mutate(created.project.id,randomUUID(),0,'seed',{},p=>{const s=scene(),topology=createTopologyVersion(p,s);p.scene=s;p.confirmedTopology=topology;p.topologyVersions=[topology];p.answers=[
  {questionId:'QROOM',roomId:'left-room',text:'保留阅读区',state:'answered',locked:true,confirmed:true,evidenceId:'e-left'},
  {questionId:'QROOM',roomId:'right-room',text:'保留工作区',state:'answered',locked:false,confirmed:true,evidenceId:'e-right'},
 ];p.evidence=[{id:'e-left',quote:'我想保留阅读区',source:'questionnaire',roomId:'left-room',createdAt:new Date().toISOString()},{id:'e-right',quote:'我还需要工作区',source:'questionnaire',roomId:'right-room',createdAt:new Date().toISOString()}];p.findings=[{id:'f-034',kind:'requirement',title:'双用途',reason:'阅读与工作',suggestion:'合并后分区',objectIds:['sofa-034','desk-034'],roomIds:['left-room','right-room'],evidenceIds:['e-left','e-right'],confidence:'high',status:'pending',stage:'intake'}];p.userContextEntries=[{id:'ctx-034',category:'requirements',text:'阅读',quote:'我想保留阅读区',sourceMessageIds:[],sourceEvidenceIds:['e-left'],sourceQuestionIds:['QROOM'],roomIds:['left-room'],objectIds:['sofa-034'],status:'confirmed',updatedAt:new Date().toISOString()}];p.zones=[{id:'zone-034',roomId:'right-room',name:'工作角',polygon:[{x:4,y:1},{x:5,y:1},{x:5,y:2},{x:4,y:2}],boundary:{kind:'virtual',a:{x:4,y:1},b:{x:5,y:1}},source:'divider',createdAt:new Date().toISOString()}];p.purposeConfirmations=[{id:'pc-034',roomId:'left-room',purpose:'生活',evidenceId:'e-left',confirmedAt:new Date().toISOString()}];p.scopeRequests=[{id:'scope-034',status:'confirmed',reason:'两个房间',roomIds:['left-room','right-room'],itemIds:['sofa-034'],excludedRoomIds:[],excludedItemIds:[],baseRevision:0,createdAt:new Date().toISOString()}];p.answerRecommendations=[{id:'rec-034',questionId:'QROOM',roomId:'right-room',evidenceId:'e-right',status:'pending',createdAt:new Date().toISOString()}];p.roomStyles={'left-room':styleA,'right-room':styleB};p.roomStyleCandidates=[{id:'style-candidate-034',roomId:'right-room',style:styleB,reason:'候选',basis:'test',status:'pending',createdAt:new Date().toISOString()}];p.intakeProgress={drafts:[{questionId:'QDRAFT',roomId:'left-room',text:'相同草稿',state:'answered'},{questionId:'QDRAFT',roomId:'right-room',text:'相同草稿',state:'answered'}],cursor:{questionId:'QDRAFT',roomId:'right-room'},updatedAt:new Date().toISOString()};p.proposals=[{id:'proposal-034',title:'用途建议',rationale:'test',evidenceIds:[],baseRevision:0,changes:[{action:'purpose',targetId:'left-room',values:{purpose:'开放空间'}}],status:'proposed'}];p.buildingState={status:'confirmed',topologyVersion:topology.version,topologyFingerprint:topology.sourceFingerprint,attempts:1,updatedAt:new Date().toISOString()};p.confirmedBuilding={topologyVersion:topology.version,topologyFingerprint:topology.sourceFingerprint,components:[],camera:{position:{x:8,y:8,z:8},target:{x:3,y:0,z:2}}} as any;});
 await store.db.query("INSERT INTO alva_reference_batches(id,project_id,request_id,room_id,filename,mime,image_data,source_text,status,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,now())",['ref-034',created.project.id,randomUUID(),'left-room','ref.jpg','image/jpeg','x','喜欢这个感觉','confirmed']);
 await store.putChatAction({id:'action-034',projectId:created.project.id,stage:'living',kind:'confirm_purpose',title:'用途',description:'确认',status:'confirmed',version:1,details:{roomId:'right-room',purpose:'工作'},createdAt:new Date().toISOString(),finishedAt:new Date().toISOString()});
 seeded=await store.mutate(created.project.id,randomUUID(),seeded.revision,'save',{confirmed:true},()=>{});
 const session=await store.issueInternalSession(created.project.id),app=await buildAlva(store,{assets:false,origin:'http://localhost'});
 return {prior,store,app,projectId:created.project.id,headers:{cookie:'alva_session='+session.token,origin:'http://localhost'},seeded};
}
async function cleanup(x:any){await x.app.close();await x.store.close();if(x.prior===undefined)delete process.env.ALVA_ACCESS_CODE;else process.env.ALVA_ACCESS_CODE=x.prior}
const base=(revision:number)=>({expectedRevision:revision,sourceRoomIds:['left-room','right-room'],name:'开放起居工作区',purpose:'生活与工作',locked:false,questionResolutions:[]});

test('ALVA-034 preview shows merged boundary/source relation and requires explicit conflict choices',async()=>{const x=await fixture();try{const before=await x.store.get(x.projectId),response=await x.app.inject({method:'POST',url:'/api/rooms/merge/preview',headers:x.headers,payload:base(before.revision)});assert.equal(response.statusCode,200,response.body);const preview=response.json();assert.equal(preview.scene.rooms.length,1);assert.equal(preview.sourceRooms.map((r:any)=>r.id).sort().join(','),'left-room,right-room');assert.equal(preview.mergedRoom.polygon.length,4);assert.equal(preview.openingContinuity[0].openingId,'window-034');assert.equal(preview.readyToConfirm,false);assert.deepEqual(new Set(preview.conflicts.map((c:any)=>c.kind)),new Set(['question','room-style']));assert.equal((await x.store.get(x.projectId)).revision,before.revision)}finally{await cleanup(x)}});

test('ALVA-034 confirm migrates room-scoped data atomically, preserves locks, saves/restores and leaves no dangling references',async()=>{const x=await fixture();try{let p=await x.store.get(x.projectId);const input={...base(p.revision),roomStyleSourceRoomId:'left-room',questionResolutions:[{questionId:'QROOM',sourceRoomId:'left-room'}]};const preview=(await x.app.inject({method:'POST',url:'/api/rooms/merge/preview',headers:x.headers,payload:input})).json();assert.equal(preview.readyToConfirm,true);const response=await x.app.inject({method:'POST',url:'/api/rooms/merge/confirm',headers:x.headers,payload:{...input,requestId:randomUUID(),baseTopologyId:preview.baseTopologyId,previewFingerprint:preview.previewFingerprint,reason:'隔断已移除，确认作为一个开放空间使用',confirmed:true}});assert.equal(response.statusCode,200,response.body);const mergedProject:any=response.json();p=mergedProject;const merged=mergedProject.scene.rooms[0].id;assert.match(merged,/^room-merge-/);assert.equal(mergedProject.scene.items.every((i:any)=>i.roomId===merged),true);assert.equal(mergedProject.scene.items.find((i:any)=>i.id==='sofa-034').locked,true);assert.equal(mergedProject.answers.length,1);assert.equal(mergedProject.answers[0].roomId,merged);assert.equal(mergedProject.answers[0].text,'保留阅读区');assert.equal(mergedProject.answers[0].locked,true);assert.equal(mergedProject.evidence.every((e:any)=>e.roomId===merged),true);assert.deepEqual(mergedProject.findings[0].roomIds,[merged]);assert.equal(mergedProject.userContextEntries[0].roomIds[0],merged);assert.equal(mergedProject.zones[0].roomId,merged);assert.equal(mergedProject.scopeRequests[0].roomIds.length,1);assert.equal(mergedProject.scopeRequests[0].roomIds[0],merged);assert.equal(mergedProject.intakeProgress.drafts.length,1);assert.equal(mergedProject.intakeProgress.drafts[0].roomId,merged);assert.equal(mergedProject.intakeProgress.cursor.roomId,merged);assert.deepEqual(mergedProject.roomStyles[merged],styleA);assert.equal(mergedProject.roomStyleCandidates[0].roomId,merged);assert.equal(mergedProject.roomStyleCandidates[0].status,'expired');assert.equal(mergedProject.proposals[0].changes[0].targetId,merged);assert.equal(mergedProject.confirmedBuilding,undefined);assert.equal(mergedProject.buildingState.status,'expired');assert.equal(mergedProject.confirmedTopology.version,2);assert.equal(mergedProject.roomMergeHistory[0].mergedRoomId,merged);assert.doesNotThrow(()=>assertNoDanglingRoomReferences(mergedProject,new Set(['left-room','right-room'])));
 const batch=(await x.store.db.query<any>('SELECT room_id FROM alva_reference_batches WHERE id=$1',['ref-034'])).rows[0];assert.equal(batch.room_id,merged);assert.equal((await x.store.chatActions(x.projectId))[0].details?.roomId,merged);
 const designer=sections(p,'designer');assert.match((designer.find(([name])=>name==='D03 房间任务书')![1] as string[]).join('\\n'),/合并来源：客厅 \+ 书房/);assert.match((designer.find(([name])=>name==='D06 方案决策与取舍')![1] as string[]).join('\\n'),/空间合并：客厅 \+ 书房/);
 p=await x.store.mutate(x.projectId,randomUUID(),p.revision,'save',{confirmed:true},()=>{});assert.equal(p.savedVersion,2);
 let restored=await x.app.inject({method:'POST',url:'/api/restore',headers:x.headers,payload:{requestId:randomUUID(),expectedRevision:p.revision,version:1,confirmed:true}});assert.equal(restored.statusCode,200,restored.body);assert.deepEqual(restored.json().scene.rooms.map((r:any)=>r.id).sort(),['left-room','right-room']);
 restored=await x.app.inject({method:'POST',url:'/api/restore',headers:x.headers,payload:{requestId:randomUUID(),expectedRevision:restored.json().revision,version:2,confirmed:true}});assert.equal(restored.statusCode,200,restored.body);const restoredProject=restored.json();assert.equal(restoredProject.scene.rooms.length,1);assert.equal(restoredProject.scene.rooms[0].id,merged);assert.doesNotThrow(()=>assertNoDanglingRoomReferences(restoredProject,new Set(['left-room','right-room'])))}finally{await cleanup(x)}});

test('ALVA-034 rejects disconnected rooms, stale confirmation and unresolved confirmation without partial mutation',async()=>{const x=await fixture();try{let p=await x.store.get(x.projectId);await x.store.mutate(x.projectId,randomUUID(),p.revision,'separate-room',{},state=>{state.scene!.rooms.find(r=>r.id==='right-room')!.polygon=state.scene!.rooms.find(r=>r.id==='right-room')!.polygon.map(q=>({x:q.x+10,y:q.y}))});p=await x.store.get(x.projectId);const disconnected=await x.app.inject({method:'POST',url:'/api/rooms/merge/preview',headers:x.headers,payload:base(p.revision)});assert.equal(disconnected.statusCode,422);assert.equal((await x.store.get(x.projectId)).scene!.rooms.length,2)}finally{await cleanup(x)}});

test('ALVA-034 floorplan MCP exposes read-only preview and guarded confirmation tools',async()=>{const x=await fixture();try{const names=roomMergeTools(x.store,x.projectId).map(t=>t.name);assert.deepEqual(names,['preview_room_merge','confirm_room_merge']);const p=await x.store.get(x.projectId);const preview=await roomMergeTools(x.store,x.projectId)[0].run({...base(p.revision),roomStyleSourceRoomId:'left-room',questionResolutions:[{questionId:'QROOM',sourceRoomId:'left-room'}]}) as any;assert.equal(preview.readyToConfirm,true);assert.equal((await x.store.get(x.projectId)).revision,p.revision)}finally{await cleanup(x)}});
