import test from 'node:test';
import assert from 'node:assert/strict';
import {canWalkAt,doorPassages,movementVector,roomWalkStart} from '../web/src/scene/walkthrough/collision.js';
import type {SceneData} from '../api/model.js';
const scene:SceneData={walls:[{id:'bottom',a:{x:0,y:0},b:{x:6,y:0},thickness:.16,height:2.8,structural:'unknown',evidence:[]},{id:'right',a:{x:6,y:0},b:{x:6,y:4},thickness:.16,height:2.8,structural:'unknown',evidence:[]},{id:'top',a:{x:6,y:4},b:{x:0,y:4},thickness:.16,height:2.8,structural:'unknown',evidence:[]},{id:'left',a:{x:0,y:4},b:{x:0,y:0},thickness:.16,height:2.8,structural:'unknown',evidence:[]},{id:'middle',a:{x:3,y:0},b:{x:3,y:4},thickness:.16,height:2.8,structural:'unknown',evidence:[]}],rooms:[{id:'living',name:'客厅',purpose:'生活',polygon:[{x:0,y:0},{x:3,y:0},{x:3,y:4},{x:0,y:4}],locked:false},{id:'bed',name:'卧室',purpose:'休息',polygon:[{x:3,y:0},{x:6,y:0},{x:6,y:4},{x:3,y:4}],locked:false}],openings:[{id:'door',wallId:'middle',kind:'door',offset:.5,width:1,height:2.1,sill:0},{id:'window',wallId:'top',kind:'window',offset:.5,width:1.2,height:1.2,sill:.9}],items:[{id:'sofa',roomId:'living',assetId:'alva-sofa',name:'沙发',x:1.5,y:2,width:1.8,depth:.8,height:.8,rotation:30,material:'fabric',color:'#999999',clearance:.05,locked:false}],calibration:{wallId:'bottom',length:6,source:'test',confirmed:true},geography:{latitude:1,north:0,assumption:'test'}};
test('ALVA-039 walls and furniture block while the real door passage remains walkable',()=>{assert.equal(canWalkAt(scene,{x:3,z:1}),false);assert.equal(canWalkAt(scene,{x:3,z:2}),true);assert.equal(canWalkAt(scene,{x:3,z:3}),false);assert.equal(canWalkAt(scene,{x:3,z:4}),false);assert.equal(canWalkAt(scene,{x:1.5,z:2}),false);assert.equal(canWalkAt(scene,{x:2.4,z:3}),true);const gap=doorPassages(scene,'middle');assert.equal(gap.length,1);assert.ok(gap[0].start<2&&gap[0].end>2)});
test('ALVA-039 window opening never becomes a floor-level passage',()=>{assert.equal(doorPassages(scene,'top').length,0);assert.equal(canWalkAt(scene,{x:3,z:4}),false)});
test('ALVA-039 WASD/arrow movement follows yaw and supports strafing',()=>{const forward=movementVector(new Set(['w']),0,2,1);assert.ok(Math.abs(forward.dx)<1e-9);assert.equal(forward.dz,-2);const right=movementVector(new Set(['d']),0,2,1);assert.equal(right.dx,2);assert.ok(Math.abs(right.dz)<1e-9);const diagonal=movementVector(new Set(['w','d']),0,2,1);assert.ok(Math.hypot(diagonal.dx,diagonal.dz)<=2.000001);const turned=movementVector(new Set(['w']),Math.PI/2,2,1);assert.ok(turned.dx<-1.99)});
test('ALVA-039 room navigation yields a stable in-room walkthrough start and falls back to first room',()=>{assert.deepEqual(roomWalkStart(scene,'bed'),{x:4.5,z:2});const start=roomWalkStart(scene,'missing');assert.equal(canWalkAt(scene,start),true);assert.ok(start.x>=0&&start.x<=3&&start.z>=0&&start.z<=4)});
