import {ensureCurrentReview} from '../api/review/service.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import {prepareSnapshotRestore,snapshotProject} from '../api/snapshots/state.js';
import {seedSnapshotProject} from './fixtures/alva/snapshot.js';

const code='alva038-restore-code-123456';
const h=(login:any)=>({cookie:`alva_session=${login.cookies[0].value}`,origin:'http://localhost'});
async function fixture(){const previous=process.env.ALVA_ACCESS_CODE;process.env.ALVA_ACCESS_CODE=code;const store=new AlvaStore();await store.init();const {project}=await store.create('ALVA-038');await store.ensureAccessCode(project.id);let seeded=await store.mutate(project.id,randomUUID(),0,'seed-rich',{},seedSnapshotProject);const app=await buildAlva(store,{assets:false,origin:'http://localhost'});const login=await app.inject({method:'POST',url:'/api/access',headers:{origin:'http://localhost'},payload:{code}});return {previous,store,app,project,seeded,headers:h(login)}}
async function done(x:any){await x.app.close();await x.store.close();if(x.previous===undefined)delete process.env.ALVA_ACCESS_CODE;else process.env.ALVA_ACCESS_CODE=x.previous}

test('ALVA-038 explicit restore replaces the whole global draft from an existing manual snapshot and creates no archive point',async()=>{const x=await fixture();try{let p=await ensureCurrentReview(x.store,x.project.id,x.seeded.revision);const save=await x.app.inject({method:'POST',url:'/api/save',headers:x.headers,payload:{requestId:randomUUID(),expectedRevision:p.revision,confirmed:true}});assert.equal(save.statusCode,200,save.body);p=save.json();const snap=await x.store.snapshot(x.project.id,1),beforeVersions=await x.store.versions(x.project.id);assert.equal(beforeVersions.length,1);
 const current=await x.store.mutate(x.project.id,randomUUID(),p.revision,'diverge-everything',{},d=>{d.name='当前完全不同的工作稿';d.scene=null;d.confirmedTopology=undefined;d.topologyVersions=[];d.confirmedBuilding=undefined;d.buildingCandidate=undefined;d.answers=[];d.evidence=[];d.findings=[];d.messages=[];d.proposals=[];d.zones=[];d.roomLabelPositions={};d.changes=[];d.lastAnalysisEvidence=0;d.dirty=true});
 const restored=await x.app.inject({method:'POST',url:'/api/restore',headers:x.headers,payload:{requestId:randomUUID(),expectedRevision:current.revision,version:1,confirmed:true}});assert.equal(restored.statusCode,200,restored.body);const out=restored.json();assert.deepEqual(out.scene,snap.scene);assert.deepEqual(out.confirmedTopology,snap.confirmedTopology);assert.deepEqual(out.topologyVersions,snap.topologyVersions);assert.deepEqual(out.confirmedBuilding,snap.confirmedBuilding);assert.deepEqual(out.answers,snap.answers);assert.deepEqual(out.evidence,snap.evidence);assert.deepEqual(out.findings,snap.findings);assert.deepEqual(out.messages,snap.messages);assert.deepEqual(out.roomLabelPositions,snap.roomLabelPositions);assert.equal(out.name,snap.name);assert.equal(out.savedVersion,1);assert.equal(out.dirty,true);assert.equal(out.revision,current.revision+1);assert.equal((await x.store.versions(x.project.id)).length,1);assert.deepEqual(await x.store.snapshot(x.project.id,1),snap);assert.match(out.changes.at(-1).description,/恢复到保存版本1/);assert.match(out.changes.at(-1).context.join(' '),/不会创建新的快照/)
 }finally{await done(x)}});

test('ALVA-038 missing snapshot, stale revision and database failure never partially mutate current draft or versions',async()=>{const x=await fixture();try{let p=await ensureCurrentReview(x.store,x.project.id,x.seeded.revision);const saved=await x.app.inject({method:'POST',url:'/api/save',headers:x.headers,payload:{requestId:randomUUID(),expectedRevision:p.revision,confirmed:true}});p=saved.json();const current=await x.store.mutate(x.project.id,randomUUID(),p.revision,'later-edit',{},d=>{d.name='必须保留的当前草稿';d.dirty=true}),before=JSON.stringify(current),versions=JSON.stringify(await x.store.versions(x.project.id)),snap=JSON.stringify(await x.store.snapshot(x.project.id,1));
 const missing=await x.app.inject({method:'POST',url:'/api/restore',headers:x.headers,payload:{requestId:randomUUID(),expectedRevision:current.revision,version:999,confirmed:true}});assert.equal(missing.statusCode,404);assert.equal(JSON.stringify(await x.store.get(x.project.id)),before);
 const stale=await x.app.inject({method:'POST',url:'/api/restore',headers:x.headers,payload:{requestId:randomUUID(),expectedRevision:current.revision-1,version:1,confirmed:true}});assert.equal(stale.statusCode,409);assert.equal(JSON.stringify(await x.store.get(x.project.id)),before);
 const requestId=randomUUID();await x.store.db.exec(`CREATE FUNCTION alva038_fail_restore() RETURNS trigger AS $$ BEGIN IF NEW.request_id='${requestId}' THEN RAISE EXCEPTION 'ALVA038 restore receipt fault'; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql; CREATE TRIGGER alva038_restore_fault AFTER INSERT ON alva_commands FOR EACH ROW EXECUTE FUNCTION alva038_fail_restore();`);try{const failed=await x.app.inject({method:'POST',url:'/api/restore',headers:x.headers,payload:{requestId,expectedRevision:current.revision,version:1,confirmed:true}});assert.equal(failed.statusCode,500);assert.equal(JSON.stringify(await x.store.get(x.project.id)),before);assert.equal(JSON.stringify(await x.store.versions(x.project.id)),versions);assert.equal(JSON.stringify(await x.store.snapshot(x.project.id,1)),snap)}finally{await x.store.db.exec('DROP TRIGGER alva038_restore_fault ON alva_commands; DROP FUNCTION alva038_fail_restore();')}
 }finally{await done(x)}});

test('ALVA-038 restore invalidates stale legacy building output instead of reusing it',async()=>{const x=await fixture();try{let p=x.seeded;const malformed=structuredClone(p);malformed.confirmedBuilding={...malformed.confirmedBuilding!,topologyFingerprint:'b'.repeat(64)};malformed.buildingState={...malformed.buildingState,topologyFingerprint:'b'.repeat(64),status:'confirmed'};await x.store.db.query(`INSERT INTO alva_versions(project_id,version,summary,state) VALUES($1,1,$2,$3)`,[x.project.id,'legacy malformed snapshot',JSON.stringify(snapshotProject(malformed))]);await x.store.mutate(x.project.id,randomUUID(),p.revision,'advance',{},d=>{d.name='current'});p=await x.store.get(x.project.id);const restored=await x.app.inject({method:'POST',url:'/api/restore',headers:x.headers,payload:{requestId:randomUUID(),expectedRevision:p.revision,version:1,confirmed:true}});assert.equal(restored.statusCode,200,restored.body);const out=restored.json();assert.equal(out.confirmedBuilding,undefined);assert.equal(out.buildingCandidate,undefined);assert.equal(out.buildingState.status,'expired');assert.equal(out.buildingState.topologyFingerprint,out.confirmedTopology.sourceFingerprint);assert.match(out.buildingState.error,/建筑结果与保存时拓扑不一致/)
 }finally{await done(x)}});

test('ALVA-038 prepareSnapshotRestore keeps current counters and does not mutate the saved object',async()=>{const x=await fixture();try{const saved=structuredClone(x.seeded),before=JSON.stringify(saved),restored=prepareSnapshotRestore(saved,77,9);assert.equal(restored.revision,77);assert.equal(restored.savedVersion,9);assert.equal(restored.dirty,true);assert.equal(JSON.stringify(saved),before)}finally{await done(x)}});
