import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import {confirmedReferencePreferencesFromProject,confirmedReferencePreferencesTool,createReferenceBatch,listConfirmedReferencePreferences,listReferenceBatches} from '../api/references.js';
import {sections} from '../api/export.js';
import type {CodexInput} from '../api/codex.js';
import type {SceneData} from '../api/model.js';

const code='alva042-test-code-123456',png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';
const scene:SceneData={walls:[{id:'w1',a:{x:0,y:0},b:{x:4,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]},{id:'w2',a:{x:4,y:0},b:{x:4,y:3},thickness:.15,height:2.8,structural:'unknown',evidence:[]},{id:'w3',a:{x:4,y:3},b:{x:0,y:3},thickness:.15,height:2.8,structural:'unknown',evidence:[]},{id:'w4',a:{x:0,y:3},b:{x:0,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]}],rooms:[{id:'living',name:'客厅',purpose:'生活',polygon:[{x:0,y:0},{x:4,y:0},{x:4,y:3},{x:0,y:3}],locked:false}],openings:[],items:[],calibration:null,geography:{latitude:31,north:0,assumption:'test'}};
function headers(login:any){return {cookie:'alva_session='+login.cookies[0].value,origin:'http://localhost'}}
async function setup(chatCodex?:(input:CodexInput)=>Promise<string>){const prior=process.env.ALVA_ACCESS_CODE;process.env.ALVA_ACCESS_CODE=code;const store=new AlvaStore();await store.init();const created=await store.create('ALVA-042');await store.ensureAccessCode(created.project.id);const seeded=await store.mutate(created.project.id,randomUUID(),0,'seed',{},p=>{p.scene=structuredClone(scene);const evidenceId=randomUUID();p.evidence.push({id:evidenceId,quote:'我希望保留这个锁定答案',source:'questionnaire',createdAt:new Date().toISOString()});p.answers.push({questionId:'Q01',roomId:null,text:'锁定答案',state:'answered',locked:true,confirmed:true,evidenceId})});const app=await buildAlva(store,{assets:false,origin:'http://localhost',chatCodex});const login=await app.inject({method:'POST',url:'/api/access',headers:{origin:'http://localhost'},payload:{code}});return {prior,store,app,created,seeded,h:headers(login)}}
async function teardown(ctx:any){await ctx.app.close();await ctx.store.close();if(ctx.prior===undefined)delete process.env.ALVA_ACCESS_CODE;else process.env.ALVA_ACCESS_CODE=ctx.prior}
async function makeBatch(store:AlvaStore,projectId:string,sourceText:string,feature:string,status:'confirm'|'pending'='pending'){const p=await store.get(projectId),batch=await createReferenceBatch(store,{projectId,requestId:randomUUID(),roomId:'living',filename:sourceText.includes('确认')?'confirmed.png':'pending.png',image:{mime:'image/png',data:png},sourceText,candidates:[{origin:'manual',preference:'like',feature}]});return {p,batch,status}}

test('ALVA-042 explicit confirmation enters requirements without overwriting locked answers',async()=>{const c=await setup();try{const {p,batch}=await makeBatch(c.store,c.created.project.id,'确认：我喜欢浅色留白','浅色留白');const beforeAnswer=structuredClone(p.answers[0]);const r=await c.app.inject({method:'POST',url:'/api/references/confirm',headers:c.h,payload:{requestId:randomUUID(),expectedRevision:p.revision,batchId:batch.id,annotationIds:[batch.annotations[0].id],confirmed:true}});assert.equal(r.statusCode,200,r.body);const out=r.json();assert.deepEqual(out.answers[0],beforeAnswer);assert.equal(out.answers[0].locked,true);const prefs=await listConfirmedReferencePreferences(c.store,c.created.project.id,'living');assert.equal(prefs.length,1);assert.equal(prefs[0].sourceText,'确认：我喜欢浅色留白');assert.equal(prefs[0].roomName,'客厅');assert.equal(prefs[0].sourceLabel,'reference-image-confirmed');assert.ok(prefs[0].evidenceIds.length===1)}finally{await teardown(c)}});

test('ALVA-042 confirmation rejects a stale/wrong room and leaves the batch pending',async()=>{const c=await setup();try{const {p,batch}=await makeBatch(c.store,c.created.project.id,'确认：客厅喜欢圆角家具','圆角家具');const changed=await c.store.mutate(c.created.project.id,randomUUID(),p.revision,'replace-room',{},project=>{project.scene={...structuredClone(scene),rooms:[{id:'bedroom',name:'卧室',purpose:'休息',polygon:[{x:0,y:0},{x:4,y:0},{x:4,y:3},{x:0,y:3}],locked:false}]}});const beforeEvidence=changed.evidence.length,beforeFindings=changed.findings.length;const r=await c.app.inject({method:'POST',url:'/api/references/confirm',headers:c.h,payload:{requestId:randomUUID(),expectedRevision:changed.revision,batchId:batch.id,annotationIds:[batch.annotations[0].id],confirmed:true}});assert.equal(r.statusCode,409,r.body);assert.match(r.json().error,/作用房间已变化/);const after=await c.store.get(c.created.project.id);assert.equal(after.evidence.length,beforeEvidence);assert.equal(after.findings.length,beforeFindings);assert.equal((await listReferenceBatches(c.store,c.created.project.id)).find(x=>x.id===batch.id)?.status,'pending')}finally{await teardown(c)}});

test('ALVA-042 confirmed-only query/tool excludes pending references and delivery marks them as reference-only',async()=>{const c=await setup();try{let p=await c.store.get(c.created.project.id);const confirmed=await createReferenceBatch(c.store,{projectId:c.created.project.id,requestId:randomUUID(),roomId:'living',filename:'confirmed.png',image:{mime:'image/png',data:png},sourceText:'确认：喜欢低饱和暖色',candidates:[{origin:'model',preference:'like',feature:'低饱和暖色'}]});await createReferenceBatch(c.store,{projectId:c.created.project.id,requestId:randomUUID(),roomId:'living',filename:'pending.png',image:{mime:'image/png',data:png},sourceText:'还没确认：可能喜欢高亮金色',candidates:[{origin:'model',preference:'like',feature:'高亮金色'}]});const r=await c.app.inject({method:'POST',url:'/api/references/confirm',headers:c.h,payload:{requestId:randomUUID(),expectedRevision:p.revision,batchId:confirmed.id,annotationIds:[confirmed.annotations[0].id],confirmed:true}});assert.equal(r.statusCode,200,r.body);p=r.json();const direct=await listConfirmedReferencePreferences(c.store,c.created.project.id,'living');assert.deepEqual(direct.map(x=>x.feature),['低饱和暖色']);const tool=confirmedReferencePreferencesTool(c.store,c.created.project.id,'living'),toolResult:any=await tool.run({});assert.equal(toolResult.status,'confirmed_only');assert.deepEqual(toolResult.preferences.map((x:any)=>x.feature),['低饱和暖色']);assert.equal(JSON.stringify(toolResult).includes('高亮金色'),false);const projected=confirmedReferencePreferencesFromProject(p);assert.equal(projected.length,1);const delivery=JSON.stringify(sections(p,'designer'));assert.match(delivery,/参考图偏好·仅参考/);assert.match(delivery,/低饱和暖色/);assert.equal(delivery.includes('高亮金色'),false);assert.match(delivery,/不得作为尺寸、结构或材料性能证据/)}finally{await teardown(c)}});

test('ALVA-042 real main Chat snapshot sees confirmed reference source but never pending analysis',async()=>{let snapshotResult:any;const chatCodex=async(input:CodexInput)=>{const call=input.tools?.find(t=>t.name==='mcp_call_tool');assert.ok(call);const raw:any=await call!.run({name:'get_snapshot',arguments:{}});snapshotResult=raw.snapshot?.project||raw.project||raw.snapshot||raw;const finding=snapshotResult.findings.find((f:any)=>f.objectIds?.some((id:string)=>id.startsWith('reference:')));assert.ok(finding);const evidence=snapshotResult.evidence.find((e:any)=>finding.evidenceIds.includes(e.id));assert.ok(evidence);assert.equal(JSON.stringify(snapshotResult).includes('未确认的亮金色候选'),false);const answer=`我会参考已确认偏好。来源：${evidence.quote}`;input.onDelta?.(answer);return answer};const c=await setup(chatCodex);try{let p=await c.store.get(c.created.project.id);const confirmed=await createReferenceBatch(c.store,{projectId:c.created.project.id,requestId:randomUUID(),roomId:'living',filename:'chat-confirmed.png',image:{mime:'image/png',data:png},sourceText:'我确认喜欢柔和的木质感',candidates:[{origin:'manual',preference:'like',feature:'柔和木质感'}]});await createReferenceBatch(c.store,{projectId:c.created.project.id,requestId:randomUUID(),roomId:'living',filename:'chat-pending.png',image:{mime:'image/png',data:png},sourceText:'未确认的亮金色候选',candidates:[{origin:'model',preference:'like',feature:'亮金色'}]});const confirm=await c.app.inject({method:'POST',url:'/api/references/confirm',headers:c.h,payload:{requestId:randomUUID(),expectedRevision:p.revision,batchId:confirmed.id,annotationIds:[confirmed.annotations[0].id],confirmed:true}});assert.equal(confirm.statusCode,200,confirm.body);p=confirm.json();const response=await c.app.inject({method:'POST',url:'/api/chat',headers:c.h,payload:{requestId:randomUUID(),expectedRevision:p.revision,text:'基于我已经确认的参考偏好，客厅后续建议要注意什么？',roomId:'living',model:'gemini-3.8-flash-high'}});assert.equal(response.statusCode,200,response.body);assert.ok(snapshotResult);const after=await c.store.get(c.created.project.id),message=after.messages.at(-1)?.text||'';assert.match(message,/我确认喜欢柔和的木质感/);assert.equal(message.includes('未确认的亮金色候选'),false)}finally{await teardown(c)}});
