import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import {createReferenceBatch} from '../api/references.js';
import {assets} from '../api/model.js';
import {sections} from '../api/export.js';

const code='alva046-lexie-test-code';
const png=Buffer.from([137,80,78,71,13,10,26,10,0,0,0,0]).toString('base64');
async function setup(){const prior=process.env.ALVA_ACCESS_CODE;process.env.ALVA_ACCESS_CODE=code;const store=new AlvaStore();await store.init();const {project}=await store.create('ALVA-046');await store.ensureAccessCode(project.id);let p=await store.mutate(project.id,randomUUID(),0,'seed',{},q=>{q.scene={walls:[{id:'w1',a:{x:0,y:0},b:{x:6,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]},{id:'w2',a:{x:6,y:0},b:{x:6,y:5},thickness:.15,height:2.8,structural:'unknown',evidence:[]},{id:'w3',a:{x:6,y:5},b:{x:0,y:5},thickness:.15,height:2.8,structural:'unknown',evidence:[]},{id:'w4',a:{x:0,y:5},b:{x:0,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]}],rooms:[{id:'living',name:'客厅',purpose:'会客',polygon:[{x:0,y:0},{x:6,y:0},{x:6,y:5},{x:0,y:5}],locked:false}],openings:[],items:[],calibration:{wallId:'w1',length:6,source:'test',confirmed:true},geography:{latitude:1.3,north:0,assumption:'test'}}});const batch=await createReferenceBatch(store,{projectId:project.id,requestId:randomUUID(),roomId:'living',filename:'sofa-ref.png',image:{mime:'image/png',data:png},sourceText:'喜欢这张图里的轻盈沙发，即使图片看起来像9米也不要照图估尺寸',candidates:[{origin:'manual',preference:'like',feature:'轻盈沙发造型'}]});await store.db.query("UPDATE alva_reference_batches SET status='confirmed' WHERE id=$1",[batch.id]);await store.db.query("UPDATE alva_reference_annotations SET status='confirmed',confirmed_at=now() WHERE batch_id=$1",[batch.id]);const app=await buildAlva(store,{assets:false,origin:'http://localhost'}),login=await app.inject({method:'POST',url:'/api/access',headers:{origin:'http://localhost'},payload:{code}}),cookie=login.cookies[0].name+'='+login.cookies[0].value;return {prior,store,app,projectId:project.id,batchId:batch.id,headers:{cookie,origin:'http://localhost'}}}
async function done(x:any){await x.app.close();await x.store.close();if(x.prior===undefined)delete process.env.ALVA_ACCESS_CODE;else process.env.ALVA_ACCESS_CODE=x.prior}

test('ALVA-046 compares only licensed catalogue assets and never treats reference image as reliable geometry',async()=>{const x=await setup();try{const response=await x.app.inject({url:`/api/reference-furniture/${x.batchId}/candidates`,headers:x.headers});assert.equal(response.statusCode,200,response.body);const body=response.json();assert.equal(body.status,'comparison_only');assert.match(body.rule,/参考图不提供可靠几何/);assert.ok(body.candidates.length>=1);const sofa=body.candidates.find((c:any)=>c.assetId==='alva-sofa');assert.ok(sofa);assert.equal(sofa.license,assets.find(a=>a.id==='alva-sofa')!.license);assert.equal(sofa.width,2.1);assert.notEqual(sofa.width,9);assert.equal(sofa.dimensionBasis,'licensed-asset-defaults');assert.equal(sofa.measurementStatus,'not-measured');assert.equal(sofa.referenceGeometryReliable,false);assert.match(sofa.matchReasons.join(' '),/沙发/)}finally{await done(x)}});

test('ALVA-046 reject is scene-noop; confirm creates a new UUID with source/license metadata, remains editable and survives save/delivery',async()=>{const x=await setup();try{let p=await x.store.get(x.projectId),before=structuredClone(p.scene);const reject=await x.app.inject({method:'POST',url:'/api/reference-furniture/reject',headers:x.headers,payload:{requestId:randomUUID(),expectedRevision:p.revision,batchId:x.batchId,assetId:'alva-sofa',confirmed:true}});assert.equal(reject.statusCode,200,reject.body);assert.equal(reject.json().sceneChanged,false);p=await x.store.get(x.projectId);assert.deepEqual(p.scene!,before);const confirmed=await x.app.inject({method:'POST',url:'/api/reference-furniture/confirm',headers:x.headers,payload:{requestId:randomUUID(),expectedRevision:p.revision,batchId:x.batchId,assetId:'alva-sofa',roomId:'living',x:3,y:2.5,rotation:0,confirmed:true}});assert.equal(confirmed.statusCode,200,confirmed.body);p=confirmed.json();assert.equal(p.scene!.items.length,1);const item=p.scene!.items[0]!;assert.match(item.id,/^[0-9a-f-]{36}$/);assert.notEqual(item.id,'alva-sofa');assert.equal(item.sourceId,`reference:${x.batchId}`);assert.equal(item.referenceSource!.batchId,x.batchId);assert.equal(item.referenceSource!.assetId,'alva-sofa');assert.match(item.referenceSource!.license,/CC0/);assert.equal(item.referenceSource!.measurementStatus,'not-measured');assert.equal(item.referenceSource!.referenceGeometryReliable,false);
 const edited=await x.app.inject({method:'POST',url:'/api/commands',headers:x.headers,payload:{requestId:randomUUID(),expectedRevision:p.revision,changes:[{action:'update',targetId:item.id,values:{color:'#112233',rotation:15}}],confirmed:true,reason:'编辑参考家具实例'}});assert.equal(edited.statusCode,200,edited.body);p=edited.json();assert.equal(p.scene!.items[0]!.color,'#112233');assert.equal(p.scene!.items[0]!.referenceSource!.batchId,x.batchId);
 const saved=await x.store.mutate(x.projectId,randomUUID(),p.revision,'save',{confirmed:true},()=>{});const snap=await x.store.snapshot(x.projectId,saved.savedVersion),source=(snap.scene!.items[0] as any).referenceSource;assert.equal(source.batchId,x.batchId);const delivery=JSON.stringify(sections(snap,'designer'));assert.match(delivery,/参考家具来源 batch/);assert.match(delivery,/许可 CC0/);assert.match(delivery,/未实测/);assert.match(delivery,/参考图几何不可靠/)}finally{await done(x)}});

test('ALVA-046 fails explicitly when no usable project-licensed assets exist and arbitrary asset confirmation cannot change scene',async()=>{const x=await setup();try{let p=await x.store.get(x.projectId),before=structuredClone(p.scene);const arbitrary=await x.app.inject({method:'POST',url:'/api/reference-furniture/confirm',headers:x.headers,payload:{requestId:randomUUID(),expectedRevision:p.revision,batchId:x.batchId,assetId:'invented-sofa',roomId:'living',x:3,y:2.5,confirmed:true}});assert.equal(arbitrary.statusCode,422);assert.deepEqual((await x.store.get(x.projectId)).scene,before);p=await x.store.mutate(x.projectId,randomUUID(),p.revision,'remove-license-pool',{},q=>{q.assets=[]});const none=await x.app.inject({url:`/api/reference-furniture/${x.batchId}/candidates`,headers:x.headers});assert.equal(none.statusCode,422);assert.match(none.json().error,/没有可用的许可家具资产/);assert.equal((await x.store.get(x.projectId)).scene!.items.length,0)}finally{await done(x)}});
