import type {FastifyInstance} from 'fastify';import {z} from 'zod';import {randomUUID} from 'node:crypto';
import {runCodex,type BusinessTool} from './codex.js';import {AlvaStore,type Session} from './store.js';import {catalogue,applyAnswer,applyChanges,ChangeSchema,review} from './business.js';import {reject,DomainError,type Project,type Proposal,type Change} from './model.js';
const Command=z.object({requestId:z.string().uuid(),expectedRevision:z.number().int().min(0)});
export function registerConsultation(app:FastifyInstance,store:AlvaStore,session:(r:object)=>Session,active:Map<string,AbortController>){
 const owner=(r:object)=>{const s=session(r);if(s.role!=='owner')reject('仅业主可修改',403);return s.projectId};
 const mutate=(req:object,b:any,op:string,fn:(p:Project)=>void|Promise<void>)=>store.mutate(owner(req),b.requestId,b.expectedRevision,op,b,fn);
 app.get('/api/questions',async()=>catalogue);
 app.get('/api/models',async()=>({models:['gpt-5.5'],evidence:'gpt-5.5已通过本轮真实Codex调用'}));
 app.post('/api/answers',async req=>{const b=Command.extend({answer:z.unknown()}).parse(req.body);return mutate(req,b,'answer',p=>applyAnswer(p,b.answer))});
 app.post('/api/answers/unlock',async req=>{const b=Command.extend({questionId:z.string(),roomId:z.string().nullable(),confirmed:z.literal(true)}).parse(req.body);return mutate(req,b,'unlock-answer',p=>{const a=p.answers.find(a=>a.questionId===b.questionId&&a.roomId===b.roomId);if(a)a.locked=false})});
 app.post('/api/budget',async req=>{const b=Command.extend({budget:z.object({amount:z.number().nonnegative().nullable(),ceiling:z.number().nonnegative().nullable(),currency:z.string().nullable(),scope:z.string()}),confirmed:z.literal(true)}).parse(req.body);return mutate(req,b,'budget',p=>{p.budget=b.budget;p.dirty=true})});
 app.post('/api/analyze',async req=>{const b=Command.parse(req.body);return mutate(req,b,'analyze',p=>{if(p.evidence.length!==p.lastAnalysisEvidence){p.findings=[...p.findings.filter(f=>f.stage!=='intake'),...review(p,'intake')];p.lastAnalysisEvidence=p.evidence.length}})});
 app.post('/api/review',async req=>{const b=Command.parse(req.body);return mutate(req,b,'review',p=>{p.findings=[...p.findings.filter(f=>f.stage!=='review'),...review(p,'review')]})});
 app.post('/api/findings/acknowledge',async req=>{const b=Command.extend({id:z.string(),confirmed:z.literal(true)}).parse(req.body);return mutate(req,b,'acknowledge',p=>{const f=p.findings.find(f=>f.id===b.id);if(!f)reject('提示已更新');if(f!.kind==='professional')reject('偏好确认不能关闭专业待核实项');f!.status='acknowledged'})});
 app.post('/api/commands',async req=>{const b=Command.extend({changes:z.array(ChangeSchema).min(1).max(100),confirmed:z.literal(true),reason:z.string().optional()}).parse(req.body);return mutate(req,b,'edit',p=>{if(!p.scene)reject('请先确认户型');p.scene=applyChanges(p.scene!,b.changes);p.dirty=true;p.findings=[...p.findings.filter(f=>f.stage!=='review'),...review(p,'review')];p.changes.push({id:randomUUID(),description:b.reason||b.changes.map(c=>c.action).join('、'),evidenceIds:[],context:p.messages.filter(m=>m.role==='user').slice(-3).map(m=>m.text),createdAt:new Date().toISOString()})})});
 app.post('/api/locks',async req=>{const b=Command.extend({id:z.string(),locked:z.boolean(),confirmed:z.literal(true)}).parse(req.body);return mutate(req,b,'lock',p=>{const target=[...p.scene?.rooms||[],...p.scene?.items||[]].find(t=>t.id===b.id);if(!target)reject('对象不存在');target!.locked=b.locked;p.dirty=true})});
 app.get('/api/proposals/:id/preview',async req=>{const p=await store.get(session(req).projectId),proposal=p.proposals.find(v=>v.id===(req.params as {id:string}).id);if(!proposal||!p.scene)reject('方案不存在',404);return {scene:applyChanges(p.scene!,proposal!.changes),proposal}});
 app.post('/api/proposals/accept',async req=>{const b=Command.extend({id:z.string(),selectedIds:z.array(z.string()).min(1),confirmed:z.literal(true)}).parse(req.body);return mutate(req,b,'accept',p=>{const proposal=p.proposals.find(v=>v.id===b.id);if(!proposal||proposal.status!=='proposed'||!p.scene)reject('方案已处理或不存在');if(proposal!.baseRevision!==p.revision)reject('方案所依版本已变化，请重新生成',409);const valid=new Set(proposal!.changes.map(c=>c.targetId));if(b.selectedIds.some(id=>!valid.has(id)))reject('勾选范围不属于此方案');const changes=proposal!.changes.filter(c=>b.selectedIds.includes(c.targetId));p.scene=applyChanges(p.scene!,changes);proposal!.status='accepted';p.dirty=true;p.findings=[...p.findings.filter(f=>f.stage!=='review'),...review(p,'review')];p.changes.push({id:randomUUID(),description:proposal!.title,evidenceIds:proposal!.evidenceIds,context:proposal!.evidenceIds.length?[]:p.messages.filter(m=>m.role==='user').slice(-3).map(m=>m.text),createdAt:new Date().toISOString()})})});
 app.post('/api/transcribe',async req=>{
  owner(req);const b=z.object({data:z.string().max(12_000_000),format:z.literal('wav')}).parse(req.body);const bytes=Buffer.from(b.data,'base64');if(bytes.length<44||bytes.subarray(0,4).toString()!=='RIFF'||bytes.subarray(8,12).toString()!=='WAVE')reject('录音内容不是有效WAV');
  const r=await fetch(`${process.env.OPENAI_BASE_URL||'https://chat.huiyuanxp.com/v1'}/chat/completions`,{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gemini-3-flash',messages:[{role:'user',content:[{type:'text',text:'只逐字转写此录音，保留原语言，不添加建议。'},{type:'input_audio',input_audio:{data:b.data,format:b.format}}]}]}),signal:AbortSignal.timeout(60000)});
  if(!r.ok){await store.failure(session(req).projectId,'transcribe','模型转写服务失败');throw new DomainError(503,'转写失败，请重试')}const result=await r.json() as any;const text=result.choices?.[0]?.message?.content;if(typeof text!=='string'||!text.trim())reject('未识别到文字，请重试');return {text};
 });
 app.post('/api/chat',async(req,reply)=>{
  const id=owner(req);const b=Command.extend({text:z.string().min(1).max(6000),roomId:z.string().nullable(),model:z.literal('gpt-5.5'),image:z.object({mime:z.enum(['image/png','image/jpeg']),data:z.string().max(12_000_000)}).optional()}).parse(req.body);
  if(active.has(id))reject('已有进行中的请求',409);const current=await store.get(id);if(b.roomId&&!current.scene?.rooms.some(r=>r.id===b.roomId))reject('房间不存在');
  const assistantId=randomUUID(),evidenceId=randomUUID();const started=await store.mutate(id,b.requestId,b.expectedRevision,'chat-start',b,p=>{if(p.messages.some(m=>m.id===b.requestId))reject('请使用重试按钮发起新请求',409);p.messages.push({id:b.requestId,role:'user',text:b.text,status:'completed',createdAt:new Date().toISOString()},{id:assistantId,role:'assistant',text:'',status:'running',createdAt:new Date().toISOString()});p.evidence.push({id:evidenceId,quote:b.text,source:'chat',...(b.roomId?{roomId:b.roomId}:{}),createdAt:new Date().toISOString()});p.dirty=true});
  // A replay returns the stored start response but never starts another model run.
  if(current.messages.some(m=>m.id===b.requestId))return reply.code(409).send({error:'该消息已经发送，请读取项目或使用新的重试请求'});
  const controller=new AbortController();active.set(id,controller);reply.hijack();reply.raw.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive','X-Accel-Buffering':'no'});const emit=(event:string,data:unknown)=>{if(!reply.raw.destroyed)reply.raw.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`)};emit('project',started);
  let streamed='';const proposals:Proposal[]=[],pendingAnswers:{questionId:string;roomId:string|null;text:string;quote:string}[]=[],asked:string[]=[];const questionCards:{questionId:string;reason:string}[]=[];
  const tools:BusinessTool[]=[
   {name:'get_snapshot',description:'Read this project snapshot, locked rooms/items, answers and available licensed assets. No writes.',inputSchema:{type:'object',properties:{},additionalProperties:false},run:async()=>({project:{...started,sourceImage:undefined,messages:started.messages.slice(-12)},roomId:b.roomId,questions:catalogue.filter(q=>q.enabled&&!started.answers.some(a=>a.questionId===q.id&&a.roomId===(q.scope==='project'?null:b.roomId)))})},
   {name:'ask_question',description:'Ask one catalogue question with A recommended + B/C/D alternatives and free input; never confirm an answer.',inputSchema:{type:'object',properties:{questionId:{type:'string'},reason:{type:'string'}},required:['questionId','reason'],additionalProperties:false},run:async args=>{const q=z.object({questionId:z.string(),reason:z.string()}).parse(args);const def=catalogue.find(d=>d.id===q.questionId);if(!def?.enabled||asked.length>=2||started.answers.some(a=>a.questionId===q.questionId&&a.roomId===(def.scope==='project'?null:b.roomId)))reject('问题已处理、已禁用或超过本轮两题');asked.push(q.questionId);questionCards.push(q);return {question:def,reason:q.reason,status:'awaiting_owner_click'}}},
   {name:'propose_answer',description:'Extract an answer supported by an exact quote from the latest user message. Keep pending; never overwrite locked fields.',inputSchema:{type:'object',properties:{questionId:{type:'string'},text:{type:'string'},quote:{type:'string'}},required:['questionId','text','quote'],additionalProperties:false},run:async args=>{const a=z.object({questionId:z.string(),text:z.string(),quote:z.string().min(1)}).parse(args);const def=catalogue.find(q=>q.id===a.questionId);if(!def?.enabled||!b.text.includes(a.quote))reject('答案必须有本轮原话依据');const roomId=def!.scope==='project'?null:b.roomId;if(started.answers.some(old=>old.questionId===a.questionId&&old.roomId===roomId&&old.locked))reject('该回答已锁定');pendingAnswers.push({...a,roomId});return {status:'pending_owner_confirmation'}}},
   {name:'propose_changes',description:'Propose local design alternatives without changing the scene. Ambiguous requests need at least two distinct variants. Locked rooms/items are excluded. Each change uses an existing targetId or a unique add target, and action add/update/remove/copy/transfer/purpose. Changes require explicit owner selection.',inputSchema:{type:'object',properties:{variants:{type:'array',items:{type:'object',properties:{title:{type:'string'},rationale:{type:'string'},changes:{type:'array',items:{type:'object',properties:{action:{type:'string'},targetId:{type:'string'},values:{type:'object'}},required:['action','targetId','values']}}},required:['title','rationale','changes']}}},required:['variants']},run:async args=>{const result=z.object({variants:z.array(z.object({title:z.string(),rationale:z.string(),changes:z.array(ChangeSchema).min(1).max(30)})).min(1).max(3)}).parse(args);if(new Set(result.variants.map(v=>JSON.stringify(v.changes))).size!==result.variants.length)reject('候选方案必须有不同的实际更改');if(!started.scene)reject('先完成户型');const precise=/#([0-9a-f]{6})\b|\d+(\.\d+)?\s*(米|厘米|cm|m)\b/i.test(b.text);if(!precise&&result.variants.length<2)reject('模糊请求需要至少两个不同方案');for(const v of result.variants){for(const c of v.changes)if(['add','copy','transfer'].includes(c.action))c.values.newId=randomUUID();applyChanges(started.scene!,v.changes);proposals.push({id:randomUUID(),...v,evidenceIds:[evidenceId],baseRevision:started.revision+1,status:'proposed'})}return {status:'proposed_only',variants:proposals.map(p=>({id:p.id,title:p.title}))}}}
  ];
  reply.raw.on('close',()=>{if(!reply.raw.writableEnded)controller.abort()});const pulse=setInterval(()=>emit('status',{text:'正在结合当前项目整理…'}),12000);
  try{const text=await runCodex({text:`你是alva生活需求顾问。读取快照后回应用户。用户未提供户型时引导上传图，不编造已建模。
当前房间：${b.roomId||'全屋'}。优先每轮1题，只有直接相关时最多2题。使用ask_question显示选择卡；提取原话用propose_answer留待点击确认。模糊家具修改调用propose_changes给至少2种不同方案；大范围或指代不唯一先明确范围，不自动扩大。默认排除所有锁定项，房间用途与布局分开。不要编造健康/身份/预算，不下结构安全结论。不要声明正式保存或采用。
用户原话：${b.text}`,model:b.model,tools,images:b.image?[`data:${b.image.mime};base64,${b.image.data}`]:[],signal:controller.signal,onDelta:t=>{streamed+=t;emit('delta',{id:assistantId,text:t})},onEvent:(e:any)=>{if(e.method==='item/tool/call')emit('status',{text:'正在核对项目资料与建议范围…'})}});
   const result=await store.mutate(id,randomUUID(),started.revision,'chat-complete',{assistantId},p=>{const m=p.messages.find(m=>m.id===assistantId)!;m.text=text;m.status='completed';p.proposals.push(...proposals);(p as any).questionCards=questionCards;(p as any).pendingAnswers=pendingAnswers.map(a=>({...a,id:randomUUID(),evidenceId}));});emit('project',result);emit('done',{ok:true});
  }catch(e){const result=await store.mutate(id,randomUUID(),null,'chat-failed',{assistantId},p=>{const m=p.messages.find(m=>m.id===assistantId)!;m.text=streamed;m.status=controller.signal.aborted?'cancelled':'failed';m.error=controller.signal.aborted?'已取消':'模型处理失败，请重试'});await store.failure(id,'chat',controller.signal.aborted?'取消':'模型失败');emit('project',result);emit('error',{error:controller.signal.aborted?'已取消，已保留输入':'模型处理失败，已保留输入，请重试'});
  }finally{clearInterval(pulse);active.delete(id);reply.raw.end()}
 });
 app.post('/api/pending-answers/confirm',async req=>{const b=Command.extend({id:z.string(),confirmed:z.literal(true)}).parse(req.body);return mutate(req,b,'confirm-extraction',p=>{const a=(p as any).pendingAnswers?.find((a:any)=>a.id===b.id);if(!a)reject('提取建议不存在');applyAnswer(p,{questionId:a.questionId,roomId:a.roomId,text:a.text,state:'answered',locked:false,confirmed:true});(p as any).pendingAnswers=(p as any).pendingAnswers.filter((x:any)=>x.id!==b.id)})});
}
