import {raw as untranslated,t} from '../i18n/language.js';
import {projectFetch as fetch} from '../projects/session.js';
import React,{useEffect,useState} from 'react';
import type {Project} from '../../../api/model.js';
import './reference-preferences.css';

type Annotation={id:string;batchId:string;origin:'model'|'manual';preference:'like'|'dislike';feature:string;status:'pending'|'confirmed'|'cancelled'};
type Batch={id:string;roomId:string|null;filename:string;mime:string;sourceText:string;status:'pending'|'confirmed'|'cancelled';createdAt:string;annotations:Annotation[]};
type FurnitureCandidate={assetId:string;name:string;license:string;width:number;depth:number;height:number;material:string;color:string;matchReasons:string[];dimensionBasis:'licensed-asset-defaults';measurementStatus:'not-measured';referenceGeometryReliable:false};
type Props={project:Project;roomId:string;mutate:(path:string,body:Record<string,unknown>)=>Promise<any>;readOnly:boolean};
async function request(path:string,method='GET',body?:unknown){const response=await fetch('/api'+path,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw new Error(data.error||'请求失败');return data}
function fileData(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)})}
export function ReferencePreferences({project,roomId,mutate,readOnly}:Props){
 const [batches,setBatches]=useState<Batch[]>([]),[sourceText,setSourceText]=useState(''),[targetRoom,setTargetRoom]=useState<string>(roomId||''),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[manual,setManual]=useState<Record<string,string>>({}),[manualPreference,setManualPreference]=useState<Record<string,'like'|'dislike'>>({}),[selected,setSelected]=useState<Record<string,boolean>>({}),[furniture,setFurniture]=useState<Record<string,FurnitureCandidate[]>>({});
 const load=()=>request('/references').then((rows:Batch[])=>{setBatches(rows);setSelected(prev=>{const next={...prev};for(const batch of rows)for(const a of batch.annotations)if(a.status==='pending'&&next[a.id]===undefined)next[a.id]=true;return next})}).catch(e=>setError(e.message));
 useEffect(()=>{void load()},[project.revision]);useEffect(()=>setTargetRoom(roomId||''),[roomId]);
 const post=async(path:string,body:Record<string,unknown>)=>request(path,'POST',{requestId:crypto.randomUUID(),expectedRevision:project.revision,...body});
 const analyze=async()=>{if(!file||!sourceText.trim())return;setBusy(true);setError('');try{const mime=file.type==='image/png'?'image/png':file.type==='image/jpeg'?'image/jpeg':'';if(!mime)throw new Error('仅支持 PNG/JPEG 参考图');const data=await fileData(file);await post('/references/analyze',{roomId:targetRoom||null,filename:file.name,sourceText:sourceText.trim(),image:{mime,data}});setFile(null);setSourceText('');await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const addManual=async(batch:Batch)=>{const feature=(manual[batch.id]||'').trim();if(!feature)return;setBusy(true);setError('');try{await post(`/references/${batch.id}/manual`,{preference:manualPreference[batch.id]||'like',feature});setManual(old=>({...old,[batch.id]:''}));await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const confirm=async(batch:Batch)=>{const annotationIds=batch.annotations.filter(a=>a.status==='pending'&&selected[a.id]).map(a=>a.id);if(!annotationIds.length)return;setBusy(true);setError('');try{await mutate('/references/confirm',{batchId:batch.id,annotationIds,confirmed:true});await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const cancel=async(batch:Batch)=>{setBusy(true);setError('');try{await post(`/references/${batch.id}/cancel`,{});await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const compareFurniture=async(batch:Batch)=>{setBusy(true);setError('');try{const result=await request(`/reference-furniture/${batch.id}/candidates`);setFurniture(old=>({...old,[batch.id]:result.candidates||[]}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const confirmFurniture=async(batch:Batch,candidate:FurnitureCandidate)=>{const rid=batch.roomId||roomId,room=project.scene?.rooms.find(r=>r.id===rid);if(!room)return setError('请先选择有效房间');const x=room.polygon.reduce((sum,p)=>sum+p.x,0)/room.polygon.length,y=room.polygon.reduce((sum,p)=>sum+p.y,0)/room.polygon.length;setBusy(true);setError('');try{await mutate('/reference-furniture/confirm',{batchId:batch.id,assetId:candidate.assetId,roomId:rid,x,y,rotation:0,confirmed:true});setFurniture(old=>({...old,[batch.id]:[]}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const rejectFurniture=async(batch:Batch,candidate:FurnitureCandidate)=>{setBusy(true);setError('');try{await post('/reference-furniture/reject',{batchId:batch.id,assetId:candidate.assetId,confirmed:true});setFurniture(old=>({...old,[batch.id]:(old[batch.id]||[]).filter(c=>c.assetId!==candidate.assetId)}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}};

 return <section className="reference-preferences" aria-label="参考图片偏好标注"><h3>参考图片偏好</h3><p>参考图只用于记录视觉偏好。模型分析和你的手工标注会分开显示；只有你确认的项目才进入需求。参考图不会作为尺寸、结构、真实材料或材料性能证据。</p>
  <div className="reference-upload"><label>作用范围<select aria-label="参考图作用房间" value={targetRoom} disabled={readOnly||busy} onChange={e=>setTargetRoom(e.target.value)}><option value="">全屋</option>{project.scene?.rooms.map(room=><option key={room.id} value={room.id}>{untranslated(room.name)}</option>)}</select></label><label>你的原话<textarea aria-label="参考图原话" value={sourceText} disabled={readOnly||busy} onChange={e=>setSourceText(e.target.value)} placeholder="例如：我喜欢这张图的浅色、轻盈家具和留白，不喜欢吊灯太复杂。"/></label><label>参考图片<input aria-label="上传参考图片" type="file" accept="image/png,image/jpeg" disabled={readOnly||busy} onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button disabled={readOnly||busy||!file||!sourceText.trim()} onClick={()=>void analyze()}>{busy?'处理中…':'分析为待确认候选'}</button></div>
  {error&&<p className="error" role="alert">{error}</p>}
  <div className="reference-batches">{batches.map(batch=><article key={batch.id} className={`reference-batch ${batch.status}`}><header><img src={`/api/references/${batch.id}/image`} alt={batch.filename}/><div><b>{untranslated(batch.filename)}</b><small>{batch.roomId?project.scene?.rooms.find(r=>r.id===batch.roomId)?.name||'原房间':'全屋'} · {batch.status==='pending'?'待确认':batch.status==='confirmed'?'已确认':'已取消'}</small><p>原话：{untranslated(batch.sourceText)}</p></div></header>{batch.annotations.map(a=><label key={a.id} className={`reference-annotation ${a.origin}`}><input type="checkbox" disabled={batch.status!=='pending'||a.status!=='pending'||readOnly} checked={!!selected[a.id]&&a.status==='pending'} onChange={e=>setSelected(old=>({...old,[a.id]:e.target.checked}))}/><span className="origin">{a.origin==='model'?'模型候选':'手工标注'}</span><span className={a.preference}>{a.preference==='like'?'喜欢':'不喜欢'}</span><span>{a.feature}</span></label>)}{batch.status==='confirmed'&&<div className="reference-furniture"><button data-testid={`reference-furniture-compare-${batch.id}`} disabled={readOnly||busy} onClick={()=>void compareFurniture(batch)}>匹配许可家具候选</button>{(furniture[batch.id]||[]).length>0&&<><p><b>候选比较</b>：参考图不提供可靠几何；以下尺寸来自许可资产目录默认值，均未实测。</p><div className="reference-furniture-grid">{(furniture[batch.id]||[]).map(c=><article key={c.assetId} data-testid={`reference-furniture-candidate-${c.assetId}`}><b>{c.name}</b><small>许可：{c.license}</small><small>目录尺寸：{c.width}×{c.depth}×{c.height}m · 未实测</small><small>材质标签：{c.material} · {c.color}</small><small>{c.matchReasons.join('；')}</small><div className="reference-actions"><button disabled={readOnly||busy} onClick={()=>void confirmFurniture(batch,c)}>确认生成新实例</button><button disabled={readOnly||busy} onClick={()=>void rejectFurniture(batch,c)}>不采用此候选</button></div></article>)}</div></>}</div>}{batch.status==='pending'&&<><div className="manual-reference"><select aria-label={`手工偏好-${batch.id}`} value={manualPreference[batch.id]||'like'} disabled={readOnly||busy} onChange={e=>setManualPreference(old=>({...old,[batch.id]:e.target.value as 'like'|'dislike'}))}><option value="like">喜欢</option><option value="dislike">不喜欢</option></select><input aria-label={`手工特征-${batch.id}`} value={manual[batch.id]||''} disabled={readOnly||busy} onChange={e=>setManual(old=>({...old,[batch.id]:e.target.value}))} placeholder="手工补充一个视觉特征"/><button disabled={readOnly||busy||!(manual[batch.id]||'').trim()} onClick={()=>void addManual(batch)}>添加手工标注</button></div><div className="reference-actions"><button disabled={readOnly||busy||!batch.annotations.some(a=>a.status==='pending'&&selected[a.id])} onClick={()=>void confirm(batch)}>确认选中偏好</button><button disabled={readOnly||busy} onClick={()=>void cancel(batch)}>取消整批候选</button></div></>}</article>)}</div>
 </section>
}
