import React,{useEffect,useState} from 'react';import type {Project,SceneData,Proposal} from '../../alva/model.js';import {SceneView} from './SceneView.js';
type Props={project:Project;roomId:string;selected:string;onSelect:(id:string)=>void;mutate:(path:string,body:Record<string,unknown>)=>Promise<any>;readOnly:boolean};
const call=async(path:string)=>{const r=await fetch('/api'+path);const d=await r.json();if(!r.ok)throw new Error(d.error);return d};
export function QuestionCard({project,roomId,mutate,readOnly,definition}:{project:Project;roomId:string;mutate:Props['mutate'];readOnly:boolean;definition:any}){
 const [text,setText]=useState(''),[locked,setLocked]=useState(false);const rid=definition.scope==='project'?null:roomId;const previous=project.answers.find(a=>a.questionId===definition.id&&a.roomId===rid);
 useEffect(()=>{setText(previous?.text||'');setLocked(previous?.locked||false)},[definition.id,previous?.text,previous?.locked,rid]);
 const answer=(text:string,state='answered')=>void mutate('/answers',{answer:{questionId:definition.id,roomId:rid,text,state,locked,confirmed:true}}).catch(()=>{});
 return <section className="question-card"><span className="eyebrow">{definition.id} · {definition.group}</span><h3>{definition.question}</h3>{!definition.enabled?<p>该问题保留编号，本期已禁用。</p>:<><div className="choices">{definition.choices.map((choice:string,i:number)=><button key={i} disabled={readOnly||previous?.locked} onClick={()=>answer(choice)}><span>{String.fromCharCode(65+i)}{i===0?' · 推荐':''}</span>{choice}</button>)}</div><label>自己的想法<textarea aria-label={`${definition.id}自由回答`} value={text} onChange={e=>setText(e.target.value)}/></label><label className="inline"><input type="checkbox" checked={locked} disabled={!!previous?.locked||readOnly} onChange={e=>setLocked(e.target.checked)}/>锁定此回答，避免被建议覆盖</label><button disabled={readOnly||previous?.locked||!text.trim()} onClick={()=>answer(text)}>确认回答</button>{previous?.locked&&<button disabled={readOnly} onClick={()=>void mutate('/answers/unlock',{questionId:definition.id,roomId:rid,confirmed:true}).catch(()=>{})}>解除锁定</button>}<div className="answer-states">{[['unknown','暂不确定'],['skipped','跳过'],['not_applicable','不适用']].map(([state,label])=><button key={state} disabled={readOnly||previous?.locked} onClick={()=>answer('',state)}>{label}</button>)}</div>{previous&&<p>已记录：{previous.state==='answered'?previous.text:({unknown:'暂不确定',skipped:'已跳过',not_applicable:'不适用'} as any)[previous.state]}</p>}</>}</section>
}
export function WorkspacePanel({project,roomId,selected,onSelect,mutate,readOnly}:Props){
 const [tab,setTab]=useState('questions'),[questions,setQuestions]=useState<any[]>([]),[qid,setQid]=useState(''),[assetId,setAssetId]=useState(project.assets[0].id),[targetRoom,setTargetRoom]=useState(roomId),[purpose,setPurpose]=useState(''),[form,setForm]=useState<Record<string,any>>({}),[budget,setBudget]=useState(project.budget);
 const scene=project.scene!,room=scene.rooms.find(r=>r.id===roomId)||scene.rooms[0],item=scene.items.find(i=>i.id===selected);
 useEffect(()=>{void call('/questions').then(setQuestions)},[]);useEffect(()=>{if(item){setForm({...item});setTab('objects')}},[selected]);useEffect(()=>{setPurpose(room?.purpose||'');setTargetRoom(room?.id||'')},[room?.id]);
 const q=questions.find(q=>q.id===qid)||questions.find(q=>q.enabled&&!project.answers.some(a=>a.questionId===q.id&&a.roomId===(q.scope==='project'?null:room.id)))||questions[0];
 const edit=(changes:unknown[],reason?:string)=>void mutate('/commands',{changes,confirmed:true,...(reason?{reason}:{})}).catch(()=>{});
 const center=room?{x:room.polygon.reduce((s,p)=>s+p.x,0)/room.polygon.length,y:room.polygon.reduce((s,p)=>s+p.y,0)/room.polygon.length}:{x:0,y:0};
 return <><div className="panel-tabs">{[['questions','需求'],['objects','家具'],['review','审查']].map(([id,name])=><button className={tab===id?'active':''} key={id} onClick={()=>{if(tab==='questions'&&id!=='questions'&&!readOnly)void mutate('/analyze',{}).catch(()=>{});setTab(id)}}>{name}</button>)}</div>
 {tab==='questions'&&<><label>房间用途<input aria-label="房间用途" value={purpose} onChange={e=>setPurpose(e.target.value)} /></label><button disabled={readOnly||room.locked} onClick={()=>edit([{action:'purpose',targetId:room.id,values:{purpose}}],'确认房间用途')}>只确认用途</button><button disabled={readOnly} onClick={()=>void mutate('/locks',{id:room.id,locked:!room.locked,confirmed:true}).catch(()=>{})}>{room.locked?'解除房间锁定':'锁定房间'}</button><label>问卷问题<select aria-label="问卷问题" value={q?.id||''} onChange={e=>setQid(e.target.value)}>{questions.map(q=><option key={q.id} value={q.id}>{q.id} {q.question}{!q.enabled?'（已禁用）':''}</option>)}</select></label>{q&&<QuestionCard project={project} roomId={room.id} mutate={mutate} readOnly={readOnly} definition={q}/>}
 <details><summary>预算边界</summary><label>金额<input type="number" value={budget.amount??''} onChange={e=>setBudget({...budget,amount:e.target.value===''?null:+e.target.value})}/></label><label>币种<input value={budget.currency||''} onChange={e=>setBudget({...budget,currency:e.target.value||null})}/></label><label>预算上限<input type="number" value={budget.ceiling??''} onChange={e=>setBudget({...budget,ceiling:e.target.value===''?null:+e.target.value})}/></label><label>包含范围<textarea value={budget.scope} onChange={e=>setBudget({...budget,scope:e.target.value})}/></label><button disabled={readOnly} onClick={()=>void mutate('/budget',{budget,confirmed:true}).catch(()=>{})}>确认预算边界</button></details></>}
 {tab==='objects'&&<><h3>家具库</h3><p>这里的家具是有许可的参数化预览。移除实例后，家具库仍保留。</p><select aria-label="家具资产" value={assetId} onChange={e=>setAssetId(e.target.value)}>{project.assets.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><button disabled={readOnly||room.locked} onClick={()=>edit([{action:'add',targetId:crypto.randomUUID(),values:{assetId,roomId:room.id,...center}}],'从家具库添加实例')}>添加到当前房间</button><label>选中家具<select value={selected} onChange={e=>onSelect(e.target.value)}><option value="">请选择</option>{scene.items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label>{item&&<><h3>{item.name}</h3>{[['x','横向位置（m）'],['y','纵向位置（m）'],['width','宽度（m）'],['depth','深度（m）'],['height','高度（m）'],['rotation','旋转（°）'],['clearance','底部空隙（m）']].map(([key,label])=><label key={key}>{label}<input aria-label={label} type="number" step={key==='rotation'?15:.05} value={form[key]??0} onChange={e=>setForm({...form,[key]:+e.target.value})}/></label>)}<label>颜色<input type="color" value={form.color||'#aaaaaa'} onChange={e=>setForm({...form,color:e.target.value})}/></label><label>材质<select value={form.material||'wood'} onChange={e=>setForm({...form,material:e.target.value})}>{[['wood','木质'],['fabric','织物'],['stone','石材'],['metal','金属'],['glass','玻璃']].map(([v,t])=><option value={v} key={v}>{t}</option>)}</select></label><button disabled={readOnly||item.locked} onClick={()=>{const {x,y,width,depth,height,rotation,color,material,clearance}=form;edit([{action:'update',targetId:item.id,values:{x:Math.round(x*20)/20,y:Math.round(y*20)/20,width,depth,height,rotation,color,material,clearance}}],'调整家具属性')}}>确认属性（位置吸附5cm）</button><button disabled={readOnly} onClick={()=>void mutate('/locks',{id:item.id,locked:!item.locked,confirmed:true}).catch(()=>{})}>{item.locked?'解除家具锁定':'锁定家具'}</button><label>转移 / 复制目标房间<select value={targetRoom} onChange={e=>setTargetRoom(e.target.value)}>{scene.rooms.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></label><button disabled={readOnly||item.locked} onClick={()=>edit([{action:'copy',targetId:item.id,values:{roomId:targetRoom,x:item.x+.4,y:item.y+.4}}],'复制家具实例')}>复制为新实例</button><button disabled={readOnly||item.locked} onClick={()=>{const target=scene.rooms.find(r=>r.id===targetRoom)!;edit([{action:'transfer',targetId:item.id,values:{roomId:targetRoom,x:target.polygon.reduce((s,p)=>s+p.x,0)/target.polygon.length,y:target.polygon.reduce((s,p)=>s+p.y,0)/target.polygon.length}}],'跨房间转移家具')}}>确认转移</button><button disabled={readOnly||item.locked} onClick={()=>edit([{action:'remove',targetId:item.id,values:{}}],'移回家具库，保留原话依据')}>移回家具库</button></>}</>}
 {tab==='review'&&<><h3>审查与未决问题</h3><button disabled={readOnly} onClick={()=>void mutate('/review',{}).catch(()=>{})}>重新审查当前布局</button>{project.findings.map(f=><article className="finding" key={f.id}><small>{f.kind==='professional'?'待专业核实':f.kind} · {f.stage==='intake'?'首次分析':'保存前审查'}</small><h4>{f.title}</h4><p>{f.reason}</p><p>{f.suggestion}</p><button onClick={()=>onSelect(f.objectIds[0]||f.roomIds[0])}>定位</button>{f.kind!=='professional'&&<button disabled={readOnly||f.status==='acknowledged'} onClick={()=>void mutate('/findings/acknowledge',{id:f.id,confirmed:true}).catch(()=>{})}>{f.status==='acknowledged'?'已知悉':'知悉此取舍'}</button>}</article>)}<h4>未回答的问题</h4>{questions.filter(q=>q.enabled&&!project.answers.some(a=>a.questionId===q.id)).map(q=><button className="unanswered" key={q.id} onClick={()=>{setQid(q.id);setTab('questions')}}>{q.id} {q.question}</button>)}<details><summary>变更依据</summary>{project.changes.map(c=><article key={c.id}><b>{c.description}</b><p>{c.evidenceIds.map(id=>project.evidence.find(e=>e.id===id)?.quote).join('；')||c.context.join('；')||'未提供独立依据'}</p></article>)}</details></>}
 </>;
}
export function ProposalCard({proposal,onAccept}:{proposal:Proposal;onAccept:(ids:string[])=>void}){const [scene,setScene]=useState<SceneData|null>(null),[error,setError]=useState(''),[ids,setIds]=useState([...new Set(proposal.changes.map(c=>c.targetId))]);useEffect(()=>{void call(`/proposals/${proposal.id}/preview`).then(r=>setScene(r.scene)).catch(e=>setError(e.message))},[proposal.id]);return <article className="proposal"><h3>{proposal.title}</h3><p>{proposal.rationale}</p>{scene&&<div className="proposal-scene"><SceneView scene={scene} focusRoom={scene.items.find(i=>ids.includes(i.id))?.roomId||scene.rooms.find(r=>ids.includes(r.id))?.id}/></div>}{error&&<p>{error}</p>}{[...new Set(proposal.changes.map(c=>c.targetId))].map(id=><label className="inline" key={id}><input type="checkbox" checked={ids.includes(id)} onChange={e=>setIds(e.target.checked?[...ids,id]:ids.filter(x=>x!==id))}/>{scene?.items.find(i=>i.id===id)?.name||scene?.rooms.find(r=>r.id===id)?.name||'新增实例'}</label>)}<small>周边对象用于参照，不会自动选中。</small><button disabled={!ids.length||!!error} onClick={()=>onAccept(ids)}>仅确认勾选范围</button></article>}
