import {chromium} from '@playwright/test';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {createHash,randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
const origin='https://prod.huiyuanxp.com',out='evidence/'+new Date().toISOString().replace(/[-:.]/g,'')+'-ALVA068-production-public';await mkdir(out,{recursive:true});
const result:any={passed:false,origin},errors:string[]=[];
const browser=await chromium.launch({headless:true,args:['--disable-dev-shm-usage','--renderer-process-limit=1','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{const page=await browser.newPage({viewport:{width:1280,height:900}});page.setDefaultTimeout(30000);page.on('pageerror',e=>errors.push(e.message));
await page.goto(origin);const assets=await page.locator('script[type="module"][src],link[rel="stylesheet"][href]').evaluateAll(ns=>ns.map(n=>n.getAttribute('src')||n.getAttribute('href')||'').filter(s=>s.startsWith('/assets/')));assert.equal(assets.length,2);result.assets={};
for(const asset of assets){const r=await page.evaluate(async(asset)=>{const r=await fetch(asset);const bytes=await r.arrayBuffer();const digest=await crypto.subtle.digest('SHA-256',bytes);return {status:r.status,hash:Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('')}},asset);assert.equal(r.status,200);const local=createHash('sha256').update(await readFile('/home/ubuntu/Alva-worktrees/ALVA-068-codex-outcome-questions/web/dist'+asset)).digest('hex');assert.equal(r.hash,local);result.assets[asset]=r.hash;}
await page.getByLabel('统一验证码').fill((await readFile('.runtime/alva068-release/access-code','utf8')).trim());const access=page.waitForResponse(r=>r.url().endsWith('/api/access'));await page.getByRole('button',{name:'验证并进入 →'}).click();assert.equal((await access).status(),200);await page.getByLabel('咨询消息').waitFor();result.authenticated=true;
const state=await page.evaluate(async()=>await(await fetch('/api/chat/stages')).json());result.activeStage=state.active;const tool=state.active==='living'?'read_question_context':'inspect_topology';result.questionnaireMcp=state.active==='living'?'checking':'当前生产项目处于户型阶段；不自动确认建筑或切换阶段，问卷MCP完整链使用已通过的隔离验收。';
const before=await page.evaluate(async()=>{const p=await(await fetch('/api/project')).json();(window as any).__before=JSON.stringify([p.scene,p.homeVision,p.answers,p.visionQuestions,p.answerRecommendations,p.savedVersion,p.proposals,p.roomStyles]);return {revision:p.revision,person:p.homeVision?.responses?.[0]?.id,room:p.scene?.rooms?.[0]?.id}});
const reply=await page.evaluate(async({before,id,tool})=>{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:id,expectedRevision:before.revision,respondentId:before.person,roomId:before.room,model:'gemini-3.8-flash-high',text:`生产发布只读验收：请实际调用 ${tool}，不传questionId，只读取当前阶段状态。只回复读取是否成功。不要出题、记录需求、生成候选、确认答案、修改设计或保存。`})});const s=await r.text();return {status:r.status,done:s.includes('event: done')}},{before,id:randomUUID(),tool});assert.equal(reply.status,200);assert.equal(reply.done,true);
const after=await page.evaluate(async()=>{const p=await(await fetch('/api/project')).json(),m=p.messages.filter((m:any)=>m.role==='assistant').at(-1);return {unchanged:(window as any).__before===JSON.stringify([p.scene,p.homeVision,p.answers,p.visionQuestions,p.answerRecommendations,p.savedVersion,p.proposals,p.roomStyles]),status:m?.status,tools:m?.toolCalls?.map((t:any)=>({name:t.name,isError:t.isError,stage:t.stage}))}});result.mcp=after;assert.equal(after.unchanged,true);assert.equal(after.status,'completed');assert.ok(after.tools?.some((t:any)=>t.name===tool&&!t.isError));result.mcp=after;
await page.reload();await page.getByLabel('咨询消息').waitFor();await page.getByRole('button',{name:'Your Home Vision',exact:true}).click();await page.locator('dialog[open]').waitFor();result.independentQuestionnaireVisible=true;
assert.deepEqual(errors,[]);result.pageErrors=errors;result.passed=true;
}catch(e){result.error=String(e);throw e}finally{await browser.close();await writeFile(out+'/result.json',JSON.stringify(result,null,2));console.log(JSON.stringify({out,...result}));}
