import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {resolve} from 'node:path';
import {z} from 'zod';
import {Scene,validateScene} from '../../api/model.js';
import {normalizeStructuredOutput} from '../../api/import.js';
import {parseLayoutOutput,LayoutOutputError,layoutRepairPrompt} from '../../api/import/response.js';
import {validateTopology} from '../../api/topology/validate.js';
import {analyzeTopology} from '../../api/topology/diagnostics.js';
import {verifyMiMoRepairSource,summarizeMiMoOutcome} from '../../scripts/lib/mimo-probe.js';
import {buildMiMoArgs} from '../../scripts/lib/mimo-profile.js';
const hash=(x:string|Buffer)=>createHash('sha256').update(x).digest('hex');
const parentId='20260925T074740232Z-ALVA056-mimo-0b62e3',childId='20260925T075949811Z-ALVA056-mimo-1947ac';
const parent=JSON.parse(await readFile(`evidence/${parentId}/result.json`,'utf8')),child=JSON.parse(await readFile(`evidence/${childId}/result.json`,'utf8'));
const before=await readFile(`.runtime/${parentId}/raw-response.txt`,'utf8'),raw=await readFile(`.runtime/${childId}/raw-response.txt`,'utf8');
const image=await readFile('references/room-study-handoff/public/floorplan.png');
const schema=z.toJSONSchema(Scene);function strict(x:any){if(!x||typeof x!=='object')return;if(x.properties){x.required=Object.keys(x.properties);x.additionalProperties=false}delete x.default;for(const v of Object.values(x))if(Array.isArray(v))v.forEach(strict);else strict(v)}strict(schema);const schemaText=JSON.stringify(schema,null,2);
verifyMiMoRepairSource(parent,{runId:parentId,imageSha256:hash(image),rawSha256:hash(before),schemaSha256:hash(schemaText)});
let err:LayoutOutputError|undefined;try{parseLayoutOutput(normalizeStructuredOutput(before))}catch(e){assert.ok(e instanceof LayoutOutputError);err=e}assert.ok(err);
const prompt=layoutRepairPrompt(before,err);assert.equal(prompt,await readFile(`.runtime/${childId}/prompt.txt`,'utf8'));
const effective=prompt+'\n\n输出schema（只作JSON对象结构约束；返回纯JSON对象，不要Markdown围栏）：\n'+schemaText;
assert.equal(effective,await readFile(`.runtime/${childId}/effective-prompt.txt`,'utf8'));assert.equal(hash(effective),child.effectivePromptSha256);
const pd=resolve('.runtime',childId),args=buildMiMoArgs({metadata:child.profileMetadata,privateDir:pd,imagePath:resolve('references/room-study-handoff/public/floorplan.png'),lastMessage:resolve(pd,'raw-response.txt'),schemaPath:resolve(pd,'output-schema.json'),outputMode:'schema-in-prompt'});assert.deepEqual(args,child.invocation.args);
const scene=parseLayoutOutput(normalizeStructuredOutput(raw));validateScene(scene);validateTopology(scene);const diagnostics=analyzeTopology(scene);assert.equal(diagnostics.status,'complete');assert.equal(diagnostics.issues.length,0);
const eventText=await readFile(resolve(pd,'codex-events.jsonl'),'utf8');const events=eventText.split('\n').filter(Boolean).map(x=>JSON.parse(x));assert.ok(events.some(x=>x.type==='turn.completed'));assert.equal(events.some(x=>x.item?.type&&!['reasoning','agent_message'].includes(x.item.type)),false);
const phases={productionParser:{ok:true},schema:{ok:true},content:{ok:true},geometry:{ok:true},confirmationTopology:{ok:true},diagnostics:{ok:true,status:diagnostics.status,counts:{}}};assert.equal(summarizeMiMoOutcome(true,null,phases).validCandidate,true);
const sources:any={};for(const [f,sha] of Object.entries(child.sourceFiles)){const current=hash(await readFile(f));sources[f]={live:sha,current,same:current===sha};if(f.startsWith('api/')||f.endsWith('mimo-profile.ts'))assert.equal(current,sha)}
assert.equal(hash(await readFile('api/import.ts')),child.importSourceSha256);
const result={kind:'offline replay of preserved real output through final provenance guard, identical prompt/schema/CLI args, and unchanged business validators; NOT a new model call',parentId,childId,passed:true,rawSha256:hash(raw),sourceHashes:sources,inputProvenanceVerified:true,effectivePromptIdentical:true,cliArgumentsIdentical:true,allBusinessValidatorHashesIdentical:true,validCandidate:true,diagnosticIssues:0,productionMutations:false,newProviderCalls:0,verifiedAt:new Date().toISOString()};
await writeFile(process.argv[2],JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passed:true,newProviderCalls:0,validCandidate:true,inputProvenanceVerified:true}));
