import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdir,rm,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import type {SceneData} from '../api/model.js';
const runId=process.env.ALVA_RUN_ID||`${Date.now()}-ALVA018-round1`,port=Number(process.env.ALVA_PORT||4218),origin=`http://127.0.0.1:${port}`,root=resolve('.runtime',runId),evidence=resolve('evidence',runId),code='alva018-round1-code-123456';
assert.ok(process.env.OPENAI_API_KEY);process.env.ALVA_ACCESS_CODE=code;process.env.ALVA_AGENT_DIR=resolve(root,'agent');await rm(root,{recursive:true,force:true});await mkdir(root,{recursive:true,mode:0o700});await mkdir(evidence,{recursive:true});
const scene:SceneData={walls:[{id:'n',a:{x:0,y:0},b:{x:5,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]}],rooms:[{id:'living',name:'客厅',purpose:'生活',polygon:[{x:0,y:0},{x:5,y:0},{x:5,y:4},{x:0,y:4}],locked:false}],openings:[],items:[],calibration:null,geography:{latitude:1.3,north:0,assumption:'synthetic'}};
const store=new AlvaStore(resolve(root,'db'));await store.init();const created=await store.create('ALVA-018 Round1');await store.ensureAccessCode(created.project.id);await store.mutate(created.project.id,randomUUID(),0,'seed',{},p=>{p.scene=structuredClone(scene)});const app=await buildAlva(store,{assets:false,origin});await app.listen({host:'127.0.0.1',port});
let cookie='';const post=async(path:string,body:any)=>fetch(origin+path,{method:'POST',headers:{...(cookie?{cookie}:{}),origin,'content-type':'application/json'},body:JSON.stringify(body)});const get=async(path:string)=>fetch(origin+path,{headers:{cookie}});
const parseEvents=(body:string)=>body.split('\n\n').filter(Boolean).map(frame=>({event:frame.match(/^event: (.+)$/m)?.[1],data:JSON.parse(frame.match(/^data: (.+)$/m)?.[1]||'{}')}));
try{
 const login=await post('/api/access',{code});assert.equal(login.status,200);cookie=(login.headers.get('set-cookie')||'').split(';')[0];assert.ok(cookie);const models=await (await get('/api/models')).json() as any,model=models.models[0];let p=await (await get('/api/project')).json() as any;const beforeScene=JSON.stringify(p.scene),text='我喜欢阅读。请先讨论是否把客厅改成阅读区，并提出候选，不要直接采用。';
 const first=await post('/api/chat',{requestId:randomUUID(),expectedRevision:p.revision,text,roomId:'living',model});assert.equal(first.status,200);const cancel=await post('/api/chat/cancel',{});assert.equal(cancel.status,200);assert.equal((await cancel.json() as any).cancelled,true);const firstEvents=parseEvents(await first.text());assert.ok(firstEvents.some(e=>e.event==='error'&&String(e.data.error).includes('已取消')));
 p=await (await get('/api/project')).json();assert.equal(p.messages.at(-1)?.status,'cancelled');assert.equal(JSON.stringify(p.scene),beforeScene);assert.equal(p.answers.length,0);assert.equal(p.proposals.filter((x:any)=>x.status==='accepted').length,0);assert.equal((p.pendingAnswers||[]).length,0);
 const cancelledRevision=p.revision;const second=await post('/api/chat',{requestId:randomUUID(),expectedRevision:cancelledRevision,text,roomId:'living',model});assert.equal(second.status,200);const secondEvents=parseEvents(await second.text());assert.ok(secondEvents.some(e=>e.event==='done'&&e.data.ok===true));assert.ok(secondEvents.filter(e=>e.event==='delta'&&e.data.text).length>=2);p=await (await get('/api/project')).json();assert.equal(p.messages.at(-1)?.status,'completed');assert.equal(JSON.stringify(p.scene),beforeScene);assert.equal(p.answers.length,0);assert.equal(p.proposals.filter((x:any)=>x.status==='accepted').length,0);
 const result={ticket:'ALVA-018',runId,pass:true,model,checks:{cancelled:true,cancel_error_visible:true,scene_unchanged_after_cancel:true,no_answer_side_effect:true,no_accepted_proposal:true,no_pending_answer_after_cancel:true,retry_completed:true,retry_deltas:secondEvents.filter(e=>e.event==='delta'&&e.data.text).length,retry_scene_unchanged:true}};await writeFile(resolve(evidence,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{await app.close();await store.close();await rm(root,{recursive:true,force:true})}
