import {chromium,expect} from '@playwright/test';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const origin='https://prod.huiyuanxp.com',dir='evidence/'+new Date().toISOString().replace(/[:.]/g,'')+'-ALVA067-public';await mkdir(dir,{recursive:true});
if(process.argv[2])process.env.ALVA_RELEASE_ACCESS_CODE=(await readFile(process.argv[2],'utf8')).trim();
const browser=await chromium.launch({headless:true,args:['--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:1440,height:900}}),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
const result:Record<string,unknown>={origin,ok:false,authenticated:false};
try{
 const health=await page.goto(origin+'/healthz');if(!health?.ok())throw new Error('HTTPS health failed');await page.goto(origin);await expect(page.getByPlaceholder('输入项目发起人提供的验证码')).toBeVisible();
 const assets=await page.locator('script[type="module"][src^="/assets/"],link[rel="stylesheet"][href^="/assets/"]').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('src')||n.getAttribute('href')||''));if(assets.length!==2)throw new Error('Expected app JS and CSS');const hashes:Record<string,string>={};
 for(const asset of assets){if(!/^\/assets\/[\w.-]+\.(js|css)$/.test(asset))throw new Error('Unexpected asset path');const remote=await page.evaluate(async url=>{const r=await fetch(url);return {status:r.status,bytes:Array.from(new Uint8Array(await r.arrayBuffer()))}},asset);if(remote.status!==200)throw new Error('Asset unavailable: '+asset+' status '+remote.status);const local=await readFile('web/dist'+asset),body=Buffer.from(remote.bytes),hash=(b:Buffer)=>createHash('sha256').update(b).digest('hex');if(hash(local)!==hash(body))throw new Error('Asset hash mismatch');hashes[asset]=hash(body);if(asset.endsWith('.js')&&!body.includes(Buffer.from('chat-progress')))throw new Error('Progress component absent');}
 result.assets=hashes;result.health=health.status();result.pageErrors=errors;result.unauthenticatedModels=await page.evaluate(async()=>(await fetch('/api/models')).status);if(result.unauthenticatedModels!==401)throw new Error('Models auth boundary changed');
 if(process.env.ALVA_RELEASE_ACCESS_CODE){const response=page.waitForResponse(r=>r.url().endsWith('/api/access')&&r.request().method()==='POST');await page.getByPlaceholder('输入项目发起人提供的验证码').fill(process.env.ALVA_RELEASE_ACCESS_CODE);await page.getByRole('button',{name:'验证并进入 →'}).click();if(!(await response).ok())throw new Error('Access code rejected');await expect(page.getByLabel('咨询模型')).toHaveValue('gemini-3.8-flash-high');const before=await page.evaluate(async()=>{const p=await(await fetch('/api/project')).json();return p.revision});result.models=await page.evaluate(async()=>await(await fetch('/api/models')).json());const after=await page.evaluate(async()=>{const p=await(await fetch('/api/project')).json();return p.revision});if(before!==after)throw new Error('Unexpected revision change');result.authenticated=true;result.noBusinessWrites=true;}
 else result.authenticatedBlocker='Current access code pending; stored old code rejected before release';
 if(errors.length)throw new Error('Browser page errors');result.ok=true;if(!result.authenticated)await page.screenshot({path:dir+'/public.png'});
}catch(e){result.error=String(e);throw e}finally{await browser.close();await writeFile(dir+'/result.json',JSON.stringify(result,null,2));console.log(JSON.stringify({dir,...result}));}
