import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdir,rm,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {chromium} from '@playwright/test';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import type {SceneData} from '../api/model.js';
const runId=process.env.ALVA_RUN_ID||`${Date.now()}-ALVA015-round2`,port=Number(process.env.ALVA_PORT||4215),origin=`http://127.0.0.1:${port}`,root=resolve('.runtime',runId),evidence=resolve('evidence',runId),code='alva015-browser-code-123456';
assert.ok(process.env.OPENAI_API_KEY);process.env.ALVA_ACCESS_CODE=code;process.env.ALVA_AGENT_DIR=resolve(root,'agent');await rm(root,{recursive:true,force:true});await mkdir(root,{recursive:true,mode:0o700});await mkdir(evidence,{recursive:true});
const scene:SceneData={walls:[{id:'n',a:{x:0,y:0},b:{x:5,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]}],rooms:[{id:'living',name:'客厅',purpose:'生活',polygon:[{x:0,y:0},{x:5,y:0},{x:5,y:4},{x:0,y:4}],locked:false}],openings:[],items:[],calibration:null,geography:{latitude:1.3,north:0,assumption:'synthetic'}};
const store=new AlvaStore(resolve(root,'db'));await store.init();const created=await store.create('ALVA-015 Browser');await store.ensureAccessCode(created.project.id);await store.mutate(created.project.id,randomUUID(),0,'seed',{},p=>{p.scene=structuredClone(scene)});const app=await buildAlva(store,{assets:true,origin});await app.listen({host:'127.0.0.1',port});
const executablePath=process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||'/home/ubuntu/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',browser=await chromium.launch({headless:true,executablePath,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']}),page=await browser.newPage({viewport:{width:1600,height:1000}});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
try{
 await page.goto(origin);await page.getByLabel('统一验证码').fill(code);await page.getByRole('button',{name:/验证并进入/}).click();await page.getByText('ALVA-015 Browser',{exact:true}).waitFor();errors.length=0;await page.waitForFunction(()=>!!document.querySelector<HTMLSelectElement>('select[aria-label="咨询模型"]')?.value);
 const quote='我平时主要在客厅读书和休息',composer=page.getByLabel('咨询消息');await composer.fill(`针对Q25，这句话就是我的回答：“${quote}”。请提取为待确认答案，不要直接写入问卷。`);await page.getByRole('button',{name:'发送 ↑'}).click();await page.getByRole('button',{name:'取消'}).waitFor();await page.getByText('待你确认 · Q25').waitFor({timeout:120000});await page.getByRole('button',{name:'发送 ↑'}).waitFor({timeout:120000});let state=await page.request.get(`${origin}/api/project`).then(r=>r.json());assert.equal(state.answers.some((a:any)=>a.questionId==='Q25'),false);const pendingCard=page.getByText('待你确认 · Q25').locator('..');assert.ok((await pendingCard.innerText()).includes(quote));await pendingCard.getByRole('button',{name:'确认写入问卷'}).click();await page.getByText('待你确认 · Q25').waitFor({state:'detached'});state=await page.request.get(`${origin}/api/project`).then(r=>r.json());const q25=state.answers.find((a:any)=>a.questionId==='Q25'&&a.roomId==='living'),q25Evidence=state.evidence.find((e:any)=>e.id===q25.evidenceId);assert.equal(q25Evidence.quote,quote);assert.equal(q25Evidence.source,'chat');
 const questionSelect=page.getByLabel('问卷问题');await questionSelect.selectOption('Q01');const token='MANUAL-UI-ALVA015-7721';await page.getByLabel('Q01自由回答').fill(token);const lock=page.locator('.question-card input[type="checkbox"]');await lock.check();await page.getByRole('button',{name:'确认回答'}).click();await page.getByText(`已记录：${token}`).waitFor();await page.getByRole('button',{name:'解除锁定'}).waitFor();state=await page.request.get(`${origin}/api/project`).then(r=>r.json());const q01=state.answers.find((a:any)=>a.questionId==='Q01');assert.equal(q01.locked,true);assert.equal(state.evidence.find((e:any)=>e.id===q01.evidenceId).source,'questionnaire');
 await composer.fill('读取项目快照，Q01已经确认的回答是什么？请在回复中完整包含该回答。');const before=await page.locator('.message.assistant').count();await page.getByRole('button',{name:'发送 ↑'}).click();await page.getByRole('button',{name:'取消'}).waitFor();await page.getByRole('button',{name:'发送 ↑'}).waitFor({timeout:120000});const replies=page.locator('.message.assistant');assert.ok(await replies.count()>before);const reply=(await replies.last().innerText()).trim();assert.ok(reply.includes(token),reply);
 await page.getByRole('button',{name:'解除锁定'}).click();await page.getByRole('button',{name:'解除锁定'}).waitFor({state:'detached'});state=await page.request.get(`${origin}/api/project`).then(r=>r.json());assert.equal(state.answers.find((a:any)=>a.questionId==='Q01').locked,false);assert.deepEqual(errors,[]);await page.screenshot({path:resolve(evidence,'chat-answer-confirmation.png'),fullPage:true});const result={ticket:'ALVA-015',runId,pass:true,checks:{real_codex_pending_ui:true,unconfirmed_not_written:true,click_confirm:true,exact_quote_preserved:true,chat_evidence:true,manual_answer:true,manual_lock_visible:true,later_chat_reads_manual:true,explicit_unlock:true,console_errors:errors}};await writeFile(resolve(evidence,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{await browser.close();await app.close();await store.close();await rm(root,{recursive:true,force:true})}
