import {chromium,expect} from '@playwright/test';import {readFile,writeFile,mkdir} from 'node:fs/promises';import {randomUUID,createHash} from 'node:crypto';import {unzipSync,strFromU8} from 'fflate';import mammoth from 'mammoth';
const origin=process.env.ALVA_TEST_ORIGIN||'http://127.0.0.1:4180';
const run=`evidence/${new Date().toISOString().replace(/[-:.]/g,'')}-${randomUUID().slice(0,8)}`;await mkdir(run,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const checks:{name:string;ok:boolean;detail?:unknown}[]=[];let phase='login';
try{
 const entry=new URL((await readFile('.runtime/alva-data/initial-access-link','utf8')).trim());await page.goto(origin+'/'+entry.hash);await expect(page.locator('.project-name')).toBeVisible({timeout:20000});
 const created=await page.evaluate(async()=>{const r=await fetch('/api/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'浏览器验收 · 合成项目'})});return r.json()});await page.goto(`${origin}/#access=${created.token}`);await page.reload();await expect(page.locator('.project-name')).toHaveText('浏览器验收 · 合成项目');await page.screenshot({path:`${run}/01-entry.png`});checks.push({name:'project-specific entry',ok:true});
 phase='real import';await page.locator('input[type=file][accept="image/png,image/jpeg,application/pdf"]').setInputFiles('references/room-study-handoff/public/floorplan.png');await expect(page.getByRole('button',{name:'按这条长度校准'})).toBeVisible({timeout:260000});
 await page.getByLabel('真实墙长').fill('8');await page.getByLabel('测量依据').fill('自动化验收合成墙长，非原户型实测');await page.getByRole('button',{name:'按这条长度校准'}).click();await expect(page.getByRole('button',{name:'确认户型，开始规划 →'})).toBeEnabled();await page.screenshot({path:`${run}/02-calibration.png`});await page.getByRole('button',{name:'确认户型，开始规划 →'}).click();await expect(page.getByTestId('scene-view')).toBeVisible();checks.push({name:'real image import and explicit calibration',ok:true});
 phase='furniture';await page.getByRole('button',{name:'家具',exact:true}).click();await page.getByLabel('家具资产').selectOption('alva-table');await page.getByRole('button',{name:'添加到当前房间'}).click();await expect(page.locator('.save-state')).toContainText('未保存');await page.screenshot({path:`${run}/03-workspace.png`});checks.push({name:'manual asset instance edit',ok:true});
 phase='real chat';await page.getByLabel('咨询消息').fill('我每天喝咖啡，希望有方便清理的咖啡角。请先确认一条相关需求，不要改变家具。');await page.getByRole('button',{name:'发送 ↑'}).click();await expect(page.locator('.message.assistant')).not.toHaveText('alva · 空间顾问',{timeout:120000});await expect(page.getByRole('button',{name:'取消',exact:true})).toHaveCount(0,{timeout:150000});
 const afterChat=await page.evaluate(async()=>{const r=await fetch('/api/project');return r.json()});if(afterChat.messages.at(-1).status!=='completed')throw Error('real chat did not complete');await page.screenshot({path:`${run}/04-chat.png`});checks.push({name:'real Codex consultation',ok:true,detail:afterChat.messages.at(-1).text});
 phase='save/export';await page.getByRole('button',{name:'保存版本',exact:true}).click();await expect(page.locator('.save-state')).toContainText('已保存 · v1');const downloadEvent=page.waitForEvent('download',{timeout:150000});await page.getByRole('button',{name:'交付包',exact:true}).click();const download=await downloadEvent;await download.saveAs(`${run}/delivery.zip`);const files=unzipSync(await readFile(`${run}/delivery.zip`)),manifest=JSON.parse(strFromU8(files['manifest.json']));for(const [name,meta] of Object.entries(manifest.files) as [string,{sha256:string}][])if(createHash('sha256').update(files[name]).digest('hex')!==meta.sha256)throw Error(`hash mismatch ${name}`);
 const doc=await mammoth.extractRawText({buffer:Buffer.from(files['designer.docx'])});if(!doc.value.includes('D10')||!doc.value.includes('我每天喝咖啡'))throw Error('DOCX missing editable sections or quote');if(Buffer.from(files['owner.pdf']).subarray(0,5).toString()!=='%PDF-')throw Error('invalid PDF');checks.push({name:'same-version export and editable DOCX',ok:true,detail:{version:manifest.version,files:Object.keys(files)}});
 checks.push({name:'console and page errors',ok:errors.length===0,detail:errors});
}catch(error){checks.push({name:phase,ok:false,detail:String(error)});await page.screenshot({path:`${run}/failure.png`}).catch(()=>{})}finally{await browser.close();await writeFile(`${run}/result.json`,JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({run,checks,errors}));process.exitCode=checks.every(c=>c.ok)?0:1}
