import {mkdir,rm,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import {sections} from '../api/export.js';
import type {CodexInput} from '../api/codex.js';
import type {SceneData} from '../api/model.js';
const run=process.env.ALVA042_RUN||`alva042-${Date.now()}`,root=resolve('.runtime',run),evidenceDir=resolve('evidence',run),port=Number(process.env.ALVA042_PORT||43142),origin=`http://127.0.0.1:${port}`,code='alva042-round2-code-123456',png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';
await rm(root,{recursive:true,force:true});await mkdir(root,{recursive:true});await mkdir(evidenceDir,{recursive:true});process.env.ALVA_ACCESS_CODE=code;
const wall=(id:string,ax:number,ay:number,bx:number,by:number)=>({id,a:{x:ax,y:ay},b:{x:bx,y:by},thickness:.15,height:2.8,structural:'unknown' as const,evidence:[]});const scene:SceneData={walls:[wall('w1',0,0,4,0),wall('w2',4,0,4,3),wall('w3',4,3,0,3),wall('w4',0,3,0,0)],rooms:[{id:'living',name:'客厅',purpose:'生活',polygon:[{x:0,y:0},{x:4,y:0},{x:4,y:3},{x:0,y:3}],locked:false}],openings:[],items:[],calibration:null,geography:{latitude:31,north:0,assumption:'test'}};
let snapshotSeen:any;const model=async(input:CodexInput)=>{if(input.tools?.length){const snap=input.tools.find(t=>t.name==='get_snapshot');snapshotSeen=await snap!.run({});const f=snapshotSeen.project.findings.find((x:any)=>x.objectIds?.some((id:string)=>id.startsWith('reference:'))),e=snapshotSeen.project.evidence.find((x:any)=>f.evidenceIds.includes(x.id));const answer=`后续建议会参考这条已确认偏好。来源：${e.quote}`;input.onDelta?.(answer);return answer}return JSON.stringify({annotations:[{preference:'like',feature:'柔和木质感和低饱和暖色'}]})};
async function start(){const store=new AlvaStore(resolve(root,'db'));await store.init();const app=await buildAlva(store,{origin,chatCodex:model});await app.listen({host:'127.0.0.1',port});return {store,app}}
async function req(path:string,method='GET',body?:unknown,cookie=''){const r=await fetch(origin+path,{method,headers:{origin,...(cookie?{cookie}:{}),...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const text=await r.text();let data:any;try{data=JSON.parse(text)}catch{data=text}if(!r.ok)throw new Error(`${method} ${path} ${r.status}: ${text}`);return {r,data}}
let s=await start();let cookie='';try{const created=await s.store.create('ALVA-042 round2');await s.store.ensureAccessCode(created.project.id);const seeded=await s.store.mutate(created.project.id,randomUUID(),0,'seed',{},p=>{p.scene=scene;const evidenceId=randomUUID();p.evidence.push({id:evidenceId,quote:'锁定答案来源',source:'questionnaire',createdAt:new Date().toISOString()});p.answers.push({questionId:'Q01',roomId:null,text:'锁定答案',state:'answered',locked:true,confirmed:true,evidenceId})});const login=await req('/api/access','POST',{code});cookie=(login.r.headers.get('set-cookie')||'').split(';')[0];const analyzed=(await req('/api/references/analyze','POST',{requestId:randomUUID(),expectedRevision:seeded.revision,roomId:'living',filename:'round2.png',sourceText:'我确认喜欢柔和木质感和低饱和暖色。',image:{mime:'image/png',data:png}},cookie)).data;const confirmed=(await req('/api/references/confirm','POST',{requestId:randomUUID(),expectedRevision:seeded.revision,batchId:analyzed.id,annotationIds:[analyzed.annotations[0].id],confirmed:true},cookie)).data;if(confirmed.answers[0].text!=='锁定答案'||!confirmed.answers[0].locked)throw new Error('locked answer changed');await req('/api/references/analyze','POST',{requestId:randomUUID(),expectedRevision:confirmed.revision,roomId:'living',filename:'pending.png',sourceText:'未确认：亮金色',image:{mime:'image/png',data:png}},cookie);const saved=(await req('/api/save','POST',{requestId:randomUUID(),expectedRevision:confirmed.revision,confirmed:true},cookie)).data;if(saved.savedVersion!==1)throw new Error('save failed');await s.app.close();await s.store.close();
 s=await start();const project=(await req('/api/project','GET',undefined,cookie)).data,confirmedOnly=(await req('/api/references/confirmed?roomId=living','GET',undefined,cookie)).data,snapshot=(await req('/api/versions/1','GET',undefined,cookie)).data;if(confirmedOnly.preferences.length!==1||confirmedOnly.preferences[0].feature!=='柔和木质感和低饱和暖色')throw new Error('confirmed preference persistence mismatch');if(JSON.stringify(confirmedOnly).includes('亮金色'))throw new Error('pending leaked into confirmed query');const delivery=JSON.stringify(sections(snapshot,'designer'));if(!delivery.includes('参考图偏好·仅参考')||!delivery.includes('柔和木质感和低饱和暖色')||delivery.includes('亮金色'))throw new Error('delivery reference marker mismatch');const chat=await fetch(origin+'/api/chat',{method:'POST',headers:{origin,cookie,'content-type':'application/json'},body:JSON.stringify({requestId:randomUUID(),expectedRevision:project.revision,text:'请基于我已确认的参考偏好给客厅后续建议，并说明来源。',roomId:'living',model:'gemini-3.1-flash-lite'})});if(chat.status!==200)throw new Error('chat failed '+await chat.text());await chat.text();const after=await s.store.get(project.id),reply=after.messages.at(-1)?.text||'';if(!reply.includes('我确认喜欢柔和木质感和低饱和暖色'))throw new Error('chat did not cite confirmed source');if(JSON.stringify(snapshotSeen).includes('未确认：亮金色'))throw new Error('pending leaked into chat snapshot');const result={ok:true,run,savedVersion:snapshot.savedVersion,confirmedCount:confirmedOnly.preferences.length,pendingExcluded:true,lockedAnswerPreserved:snapshot.answers[0].locked&&snapshot.answers[0].text==='锁定答案',deliveryMarkedReference:delivery.includes('参考图偏好·仅参考'),chatCitedConfirmedSource:reply.includes('我确认喜欢柔和木质感和低饱和暖色'),serviceRestartReload:true};await writeFile(resolve(evidenceDir,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2))}finally{await s.app.close().catch(()=>{});await s.store.close().catch(()=>{});await rm(root,{recursive:true,force:true})}
