import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdir,rm,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {chromium} from '@playwright/test';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import {applyAnswer} from '../api/business.js';
import type {SceneData} from '../api/model.js';
const runId=process.env.ALVA_RUN_ID||`${Date.now()}-ALVA016-round2`,port=Number(process.env.ALVA_PORT||4216),origin=`http://127.0.0.1:${port}`,root=resolve('.runtime',runId),evidenceDir=resolve('evidence',runId),code='alva016-browser-code-123456';assert.ok(process.env.OPENAI_API_KEY);process.env.ALVA_ACCESS_CODE=code;process.env.ALVA_AGENT_DIR=resolve(root,'agent');await rm(root,{recursive:true,force:true});await mkdir(root,{recursive:true,mode:0o700});await mkdir(evidenceDir,{recursive:true});
const scene:SceneData={walls:[{id:'n',a:{x:0,y:0},b:{x:6,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]}],rooms:[{id:'living',name:'客厅',purpose:'生活',polygon:[{x:0,y:0},{x:3,y:0},{x:3,y:3},{x:0,y:3}],locked:false},{id:'study',name:'书房',purpose:'工作',polygon:[{x:3,y:0},{x:6,y:0},{x:6,y:3},{x:3,y:3}],locked:false}],openings:[],items:[],calibration:null,geography:{latitude:1.3,north:0,assumption:'synthetic'}};
const store=new AlvaStore(resolve(root,'db'));await store.init();const created=await store.create('ALVA-016 Browser');await store.ensureAccessCode(created.project.id);await store.mutate(created.project.id,randomUUID(),0,'seed',{},p=>{p.scene=structuredClone(scene);applyAnswer(p,{questionId:'Q01',roomId:null,text:'先形成需求任务书',state:'answered',locked:false,confirmed:true});applyAnswer(p,{questionId:'Q25',roomId:'living',text:'阅读和休息',state:'answered',locked:false,confirmed:true});p.lastAnalysisEvidence=p.evidence.length});const app=await buildAlva(store,{assets:true,origin});await app.listen({host:'127.0.0.1',port});
const executablePath=process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||'/home/ubuntu/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',browser=await chromium.launch({headless:true,executablePath,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']}),page=await browser.newPage({viewport:{width:1600,height:1000}});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
try{await page.goto(origin);await page.getByLabel('统一验证码').fill(code);await page.getByRole('button',{name:/验证并进入/}).click();await page.getByText('ALVA-016 Browser',{exact:true}).waitFor();errors.length=0;await page.waitForFunction(()=>!!document.querySelector<HTMLSelectElement>('select[aria-label="咨询模型"]')?.value);
 await page.getByRole('button',{name:'审查',exact:true}).click();const projectGroup=page.getByTestId('unanswered-project'),livingGroup=page.getByTestId('unanswered-living'),studyGroup=page.getByTestId('unanswered-study');await projectGroup.waitFor();assert.ok((await projectGroup.innerText()).includes('全屋'));assert.equal((await projectGroup.innerText()).includes('Q01 '),false);assert.equal((await livingGroup.innerText()).includes('Q25 '),false);assert.equal((await studyGroup.innerText()).includes('Q25 '),true);for(const id of ['Q19','Q20','Q21','Q22','Q58','Q60'])assert.equal((await page.locator('.details').innerText()).includes(id+' '),false);
 await studyGroup.getByRole('button',{name:/Q25 .*去咨询/}).click();const composer=page.getByLabel('咨询消息');const draft=await composer.inputValue();assert.ok(draft.includes('Q25'));assert.ok(draft.includes('书房'));assert.equal(await page.getByLabel('定位房间').inputValue(),'study');assert.equal(await composer.evaluate(el=>document.activeElement===el),true);
 const before=await page.locator('.message.assistant').count();await page.getByRole('button',{name:'发送 ↑'}).click();await page.getByRole('button',{name:'取消'}).waitFor();await page.getByRole('button',{name:'发送 ↑'}).waitFor({timeout:120000});assert.ok(await page.locator('.message.assistant').count()>before);const state=await page.request.get(`${origin}/api/project`).then(r=>r.json()),lastUser=state.messages.filter((m:any)=>m.role==='user').at(-1);assert.ok(lastUser.text.includes('Q25'));assert.ok(lastUser.text.includes('书房'));assert.deepEqual(errors,[]);
 await page.screenshot({path:resolve(evidenceDir,'unanswered-followup.png'),fullPage:true});const result={ticket:'ALVA-016',runId,pass:true,checks:{project_scope_group:true,living_scope_independent:true,study_scope_independent:true,disabled_excluded:true,click_prefills_chat:true,room_context_study:true,composer_focused:true,real_chat_from_unanswered:true,console_errors:errors}};await writeFile(resolve(evidenceDir,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{await browser.close();await app.close();await store.close();await rm(root,{recursive:true,force:true})}
