import {mkdir,rm,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
import {chromium} from 'playwright';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import {seedSnapshotProject} from '../tests/fixtures/alva/snapshot.js';
const run=process.env.ALVA039_RUN||`alva039-${Date.now()}`,root=resolve('.runtime',run),evidence=resolve('evidence',run),port=Number(process.env.ALVA039_PORT||43139),origin=`http://127.0.0.1:${port}`,code='alva039-round2-code-123456';
await rm(root,{recursive:true,force:true});await mkdir(root,{recursive:true});await mkdir(evidence,{recursive:true});process.env.ALVA_ACCESS_CODE=code;process.env.ALVA_AGENT_DIR=resolve(root,'agents');process.env.OPENAI_API_KEY||=process.env.NEWAPI_KEY;
const store=new AlvaStore(resolve(root,'db'));await store.init();const {project}=await store.create('ALVA-039 browser');await store.ensureAccessCode(project.id);await store.mutate(project.id,randomUUID(),0,'seed',{},p=>{seedSnapshotProject(p);const scene=p.scene!;scene.rooms.push({id:'room-next',name:'相邻房间',purpose:'休息',locked:false,polygon:[{x:0,y:4},{x:5,y:4},{x:5,y:8},{x:0,y:8}]});const points=[{x:5,y:4},{x:5,y:8},{x:0,y:8},{x:0,y:4}];scene.walls.push(...points.slice(0,3).map((a,i)=>({id:'next-'+i,a,b:points[i+1],height:2.8,thickness:.15,structural:'unknown' as const,evidence:[]})));scene.openings.push({id:'window',wallId:'wall-0',kind:'window',offset:.5,width:1.2,height:1.2,sill:.9});});const app=await buildAlva(store,{origin});await app.listen({host:'127.0.0.1',port});
global.gc?.();const browser=await chromium.launch({headless:true,executablePath:'/home/ubuntu/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage','--renderer-process-limit=1','--single-process','--no-zygote','--js-flags=--max-old-space-size=96']});const context=await browser.newContext({viewport:{width:1440,height:1000}});const consoleErrors:string[]=[];const page=await context.newPage();await context.addInitScript('globalThis.__name = (value) => value');page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});page.on('pageerror',e=>consoleErrors.push(`pageerror: ${e.message}`));
try{
 const auth=await context.request.post(origin+'/api/access',{data:{code},headers:{origin}});if(!auth.ok())throw new Error('login failed '+await auth.text());await page.goto(origin,{waitUntil:'networkidle'});
 await page.getByRole('button',{name:'全屋',exact:true}).click();
 await page.waitForFunction(()=>!!(document.querySelector('[data-testid="scene-view"]') as any)?.alvaView);
 const signature=()=>page.evaluate(()=>{const v=(document.querySelector('[data-testid="scene-view"]') as any).alvaView;return v.world.children.filter((o:any)=>o.isMesh).map((o:any)=>({id:o.userData.id,position:o.position.toArray(),rotation:o.rotation.toArray(),vertices:Array.from(o.geometry.attributes.position.array),indices:o.geometry.index?Array.from(o.geometry.index.array):null}));});
 const wholeRoom=await signature();await page.screenshot({path:resolve(evidence,'whole-room.png')});
 await page.getByRole('button',{name:'漫游',exact:true}).click();await page.locator('[data-testid="scene-view"] canvas').waitFor({state:'visible'});await page.getByTestId('walkthrough-status').waitFor();await page.waitForFunction(()=>!!(document.querySelector('[data-testid="scene-view"]') as any)?.alvaWalk);
 if(JSON.stringify(await signature())!==JSON.stringify(wholeRoom))throw new Error('whole room and walkthrough geometry differ');
 if(await page.getByTestId('building-canvas').count())throw new Error('legacy renderer remains');
 const geometry=await page.evaluate(()=>{const v=(document.querySelector('[data-testid="scene-view"]') as any).alvaView;const occupied=(id:string,x:number,y:number)=>v.world.children.filter((o:any)=>o.userData.id===id).some((o:any)=>Math.abs(o.position.x-x)<o.geometry.parameters.width/2&&Math.abs(o.position.y-y)<o.geometry.parameters.height/2);return {door:occupied('wall-2',2.5,1),header:occupied('wall-2',2.5,2.5),window:occupied('wall-0',2.5,1.5),sill:occupied('wall-0',2.5,.4),glass:v.world.children.some((o:any)=>o.userData.id==='window')};});
 if(JSON.stringify(geometry)!==JSON.stringify({door:false,header:true,window:false,sill:true,glass:true}))throw new Error('door/window geometry mismatch '+JSON.stringify(geometry));
 const canvas=page.locator('[data-testid="scene-view"] canvas');await canvas.click({position:{x:300,y:500}});await page.waitForTimeout(120);let locked=await page.evaluate(()=>!!document.pointerLockElement);if(!locked){await page.evaluate(()=>{const c=document.querySelector('[data-testid="scene-view"] canvas') as HTMLCanvasElement;return c.requestPointerLock()});await page.waitForTimeout(120);locked=await page.evaluate(()=>!!document.pointerLockElement)}if(!locked)throw new Error('pointer lock did not activate');
 const before=await page.evaluate(()=>{const h=document.querySelector('[data-testid="scene-view"]') as any;return {x:h.alvaView.camera.position.x,z:h.alvaView.camera.position.z,yaw:h.alvaView.camera.rotation.y}});await page.keyboard.down('w');await page.waitForTimeout(80);const during=await page.evaluate(()=>{const h=document.querySelector('[data-testid="scene-view"]') as any,c=h.alvaView.camera;return {keys:[...h.alvaWalk.keys],x:c.position.x,z:c.position.z,yaw:c.rotation.y,locked:h.alvaWalk.isLocked(),next:h.alvaWalk.canWalkAt(c.position.x,c.position.z-.2)}});await page.waitForTimeout(240);await page.keyboard.up('w');const afterMove=await page.evaluate(()=>{const h=document.querySelector('[data-testid="scene-view"]') as any;return {x:h.alvaView.camera.position.x,z:h.alvaView.camera.position.z}});if(Math.hypot(afterMove.x-before.x,afterMove.z-before.z)<.05)throw new Error('WASD did not move camera: '+JSON.stringify({before,during,afterMove}));
 await page.evaluate(()=>{const e=new MouseEvent('mousemove',{bubbles:true});Object.defineProperty(e,'movementX',{value:120});Object.defineProperty(e,'movementY',{value:-20});window.dispatchEvent(e)});await page.waitForTimeout(100);const yaw=await page.evaluate(()=>{const h=document.querySelector('[data-testid="scene-view"]') as any;return h.alvaView.camera.rotation.y});if(Math.abs(yaw-before.yaw)<.05)throw new Error('mouse did not change view yaw');
 const collision=await page.evaluate(()=>{const h=document.querySelector('[data-testid="scene-view"]') as any;return {wall:h.alvaWalk.canWalkAt(0,1),door:h.alvaWalk.canWalkAt(2.5,4),furniture:h.alvaWalk.canWalkAt(2,2),free:h.alvaWalk.canWalkAt(4,2),window:h.alvaWalk.canWalkAt(2.5,0)}});if(collision.wall!==false||collision.door!==true||collision.furniture!==false||collision.free!==true||collision.window!==false)throw new Error('collision result mismatch '+JSON.stringify(collision));
 // Traverse the rendered door into the second room using actual keyboard input.
 await page.evaluate(()=>{const v=(document.querySelector('[data-testid="scene-view"]') as any).alvaView;v.camera.position.set(2.5,1.62,3.4);const e=new MouseEvent('mousemove',{bubbles:true});Object.defineProperty(e,'movementX',{value:-120});Object.defineProperty(e,'movementY',{value:20});window.dispatchEvent(e)});
 await page.keyboard.down('s');await page.waitForFunction(()=>((document.querySelector('[data-testid="scene-view"]') as any).alvaView.camera.position.z)>4.6);await page.keyboard.up('s');
 const crossed=await page.evaluate(()=>((document.querySelector('[data-testid="scene-view"]') as any).alvaView.camera.position.toArray()));
 await page.screenshot({path:resolve(evidence,'through-door.png')});
 await page.keyboard.down('w');await page.waitForFunction(()=>((document.querySelector('[data-testid="scene-view"]') as any).alvaView.camera.position.z)<3.4);await page.keyboard.up('w');
 // Input focus clears keys and prevents drift.
 await page.evaluate(()=>{const c=document.querySelector('[data-testid=\"scene-view\"] canvas') as HTMLCanvasElement;return c.requestPointerLock()});await page.waitForTimeout(100);await page.keyboard.down('w');await page.waitForTimeout(80);const textarea=page.locator('textarea[aria-label="咨询消息"]');await textarea.focus();await page.waitForTimeout(120);const focused=await page.evaluate(()=>{const h=document.querySelector('[data-testid="scene-view"]') as any;return {keys:h.alvaWalk.keys.size,pos:{x:h.alvaView.camera.position.x,z:h.alvaView.camera.position.z}}});await page.waitForTimeout(220);const focusedLater=await page.evaluate(()=>{const h=document.querySelector('[data-testid="scene-view"]') as any;return {keys:h.alvaWalk.keys.size,pos:{x:h.alvaView.camera.position.x,z:h.alvaView.camera.position.z}}});await page.keyboard.up('w');if(focused.keys!==0||focusedLater.keys!==0||Math.hypot(focusedLater.pos.x-focused.pos.x,focusedLater.pos.z-focused.pos.z)>.03)throw new Error('input focus did not stop movement');
 // Window blur also clears movement state.
 await page.evaluate(()=>{const c=document.querySelector('[data-testid=\"scene-view\"] canvas') as HTMLCanvasElement;return c.requestPointerLock()});await page.waitForTimeout(100);await page.keyboard.down('d');await page.waitForTimeout(70);await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await page.waitForTimeout(100);const blurKeys=await page.evaluate(()=>{const h=document.querySelector('[data-testid="scene-view"]') as any;return h.alvaWalk.keys.size});await page.keyboard.up('d');if(blurKeys!==0)throw new Error('window blur did not clear keys');
 // Escape exits pointer lock and clears movement; re-entering never resumes old motion.
 await page.evaluate(()=>{const c=document.querySelector('[data-testid=\"scene-view\"] canvas') as HTMLCanvasElement;return c.requestPointerLock()});await page.waitForTimeout(100);await page.keyboard.down('w');await page.waitForTimeout(80);await page.keyboard.press('Escape');await page.waitForTimeout(120);await page.keyboard.up('w');const escaped=await page.evaluate(()=>{const h=document.querySelector('[data-testid="scene-view"]') as any;return {keys:h.alvaWalk.keys.size,locked:h.alvaWalk.isLocked(),pos:{x:h.alvaView.camera.position.x,z:h.alvaView.camera.position.z}}});await page.waitForTimeout(220);const escapedLater=await page.evaluate(()=>{const h=document.querySelector('[data-testid="scene-view"]') as any;return {pos:{x:h.alvaView.camera.position.x,z:h.alvaView.camera.position.z}}});if(escaped.keys!==0||escaped.locked||Math.hypot(escapedLater.pos.x-escaped.pos.x,escapedLater.pos.z-escaped.pos.z)>.03)throw new Error('Esc pause failed');
 // Room / whole-home navigation stays available.
 const roomSelect=page.getByLabel('定位房间');await roomSelect.selectOption('room-next');if(await roomSelect.inputValue()!=='room-next')throw new Error('room navigation failed');await roomSelect.selectOption('');if(await roomSelect.inputValue()!=='')throw new Error('whole-home reset failed');
 if(process.env.ALVA079_REAL_CHAT==='1'){
  await page.getByRole('button',{name:'全屋',exact:true}).click();const prior=(await store.get(project.id)).messages.length;
  const receipts:unknown[]=[];page.on('response',async response=>{if(response.url().endsWith('/api/chat/ui-receipts'))receipts.push({status:response.status(),body:response.request().postDataJSON()})});
  await page.getByLabel('咨询消息').fill('请实际调用 set_view 工具，将当前页面切换为漫游，参数 kind=view, mode=walk。等待页面 applied 回执。只切换视图，不修改设计，不生成问卷或建议。');await page.getByRole('button',{name:'发送 ↑',exact:true}).click();
  await page.waitForFunction(()=>!!document.querySelector('[data-testid="walkthrough-status"]'),{},{timeout:120000});
  const started=Date.now();while(Date.now()-started<120000){const p=await store.get(project.id);const message=p.messages.slice(prior).find(m=>m.role==='assistant');if(message?.status==='completed'){if(!message.toolCalls?.some(t=>t.name==='set_view'&&!t.isError))throw new Error('real chat did not invoke set_view');await writeFile(resolve(evidence,'real-chat.json'),JSON.stringify({toolCalls:message.toolCalls,receipts},null,2));break}if(message?.status==='failed')throw new Error(message.text);await new Promise(r=>setTimeout(r,500))}
  if(!receipts.some((r:any)=>r.status===200&&r.body.status==='applied'&&r.body.applied.mode==='walk'))throw new Error('missing real walkthrough receipt');
 }
 await page.screenshot({path:resolve(evidence,'walkthrough-desktop.png'),fullPage:true});const result={ok:true,run,sameGeometry:true,geometry,crossed,returnedThroughDoor:true,pointerLock:true,wasdDistance:Math.hypot(afterMove.x-before.x,afterMove.z-before.z),mouseYawChanged:true,collision,inputFocusClearsKeys:true,windowBlurClearsKeys:true,escapePausesWithoutDrift:true,roomNavigation:true,wholeHomeReturn:true,consoleErrors};await writeFile(resolve(evidence,'result.json'),JSON.stringify(result,null,2));await writeFile(resolve(evidence,'console.json'),JSON.stringify(consoleErrors,null,2));if(consoleErrors.length)throw new Error('console errors: '+consoleErrors.join(' | '));console.log(JSON.stringify(result,null,2));
}catch(error){await writeFile(resolve(evidence,'failure.json'),JSON.stringify({error:String(error),consoleErrors},null,2));throw error}finally{await browser.close();await app.close();await store.close();await rm(root,{recursive:true,force:true})}
