import {execFileSync} from 'node:child_process';
import {mkdir,rm,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import {createTopologyVersion} from '../api/topology/calibration.js';
import type {SceneData} from '../api/model.js';

const run=process.env.ALVA032_RUN||`alva032-${Date.now()}`,root=resolve('.runtime',run),evidenceDir=resolve('evidence',run),port=Number(process.env.ALVA032_PORT||43132),origin=`http://127.0.0.1:${port}`,code='alva032-round2-code-123456';
await rm(root,{recursive:true,force:true});await mkdir(root,{recursive:true});await mkdir(evidenceDir,{recursive:true});process.env.ALVA_ACCESS_CODE=code;process.env.ALVA_DATA_DIR=root;
const wall=(id:string,ax:number,ay:number,bx:number,by:number)=>({id,a:{x:ax,y:ay},b:{x:bx,y:by},thickness:.15,height:2.8,structural:'unknown' as const,evidence:[]});const scene:SceneData={walls:[wall('north',0,0,6,0),wall('east',6,0,6,4),wall('south',6,4,0,4),wall('west',0,4,0,0)],rooms:[{id:'living',name:'客厅',purpose:'生活',polygon:[{x:0,y:0},{x:6,y:0},{x:6,y:4},{x:0,y:4}],locked:false}],openings:[],items:[],calibration:{wallId:'north',length:6,source:'现场测量',confirmed:true},geography:{latitude:31,north:0,assumption:'test'}};
let seed=new AlvaStore(resolve(root,'db'));await seed.init();const created=await seed.create('ALVA-032 round2');await seed.ensureAccessCode(created.project.id);await seed.mutate(created.project.id,randomUUID(),0,'seed',{},p=>{const topology=createTopologyVersion(p,scene);p.scene=structuredClone(scene);p.confirmedTopology=topology;p.topologyVersions=[topology]});await seed.close();
const tsx=resolve('/home/ubuntu/Alva/node_modules/.bin/tsx'),admin=resolve('scripts/alva-professional-access-admin.ts');
const grantRaw=execFileSync(tsx,[admin,'grant',created.project.id,'engineer-round2','注册结构工程师·墙体分类','SERVER-CONFIG-AUTH-032'],{cwd:process.cwd(),env:{...process.env,ALVA_DATA_DIR:root},encoding:'utf8'}),grant=JSON.parse(grantRaw);
async function start(){const store=new AlvaStore(resolve(root,'db'));await store.init();const app=await buildAlva(store,{origin});await app.listen({host:'127.0.0.1',port});return {store,app}}
async function req(path:string,method='GET',body?:unknown,cookie=''){const r=await fetch(origin+path,{method,headers:{origin,...(cookie?{cookie}:{}),...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const text=await r.text();let data:any;try{data=JSON.parse(text)}catch{data=text}return {r,data,text}}
let s=await start(),ownerCookie='',professionalCookie='';
try{const home=await fetch(origin);if(home.status!==200)throw new Error('home not 200');const html=await home.text(),asset=html.match(/assets\/index-[^"']+\.js/)?.[0];if(!asset)throw new Error('built asset missing');const js=await (await fetch(origin+'/'+asset)).text();for(const label of ['墙体证据','墙体分类与专业依据','提交专业分类','确认移除已核实非承重墙'])if(!js.includes(label))throw new Error('production UI missing '+label);
 const owner=await req('/api/access','POST',{code});ownerCookie=(owner.r.headers.get('set-cookie')||'').split(';')[0];const professional=await req('/api/access','POST',{code,inviteToken:grant.token});professionalCookie=(professional.r.headers.get('set-cookie')||'').split(';')[0];if(professional.data.role!=='professional')throw new Error('professional role missing');const before=(await req('/api/project','GET',undefined,professionalCookie)).data;
 const classify=await req('/api/professional/walls/classify','POST',{requestId:randomUUID(),expectedRevision:before.revision,wallId:'north',structural:'nonloadbearing',evidenceText:'结构图 S-032 与现场复核确认非承重'},professionalCookie);if(classify.r.status!==200)throw new Error('classify failed '+classify.text);const ownerView=await req('/api/professional/walls','GET',undefined,ownerCookie);const row=ownerView.data.classifications.find((x:any)=>x.wallId==='north');if(!row||row.operatorId!=='engineer-round2'||row.evidenceText!=='结构图 S-032 与现场复核确认非承重')throw new Error('owner audit view mismatch');const access=await req('/api/professional/access','GET',undefined,ownerCookie);if(access.data.grants[0].grantEvidence!=='SERVER-CONFIG-AUTH-032')throw new Error('grant evidence missing');
 await s.app.close();await s.store.close();s=await start();const afterRestart=await req('/api/professional/walls','GET',undefined,ownerCookie);if(afterRestart.data.classifications.length!==1||afterRestart.data.walls.find((w:any)=>w.id==='north').structural!=='nonloadbearing')throw new Error('classification did not persist after restart');await s.app.close();await s.store.close();
 const revokeRaw=execFileSync(tsx,[admin,'revoke',created.project.id,grant.grantId,'server-admin-round2'],{cwd:process.cwd(),env:{...process.env,ALVA_DATA_DIR:root},encoding:'utf8'}),revoke=JSON.parse(revokeRaw);if(!revoke.revoked)throw new Error('admin revoke failed');s=await start();const revokedSession=await req('/api/project','GET',undefined,professionalCookie),revokedLogin=await req('/api/access','POST',{code,inviteToken:grant.token});if(revokedSession.r.status!==401||revokedLogin.r.status!==401)throw new Error('revoked professional still works');const ownerAccess=await req('/api/professional/access','GET',undefined,ownerCookie),grantRow=ownerAccess.data.grants.find((g:any)=>g.id===grant.grantId);if(grantRow.status!=='revoked'||grantRow.revokedBy!=='server-admin-round2')throw new Error('revoke audit missing');const result={ok:true,run,homeStatus:home.status,uiLabelsPresent:true,professionalRole:true,classificationPersisted:true,ownerCanTraceSource:true,grantIsServerConfigured:true,serviceRestartReload:true,revokeAudited:true,revokedSessionStatus:revokedSession.r.status,revokedInviteLoginStatus:revokedLogin.r.status};await writeFile(resolve(evidenceDir,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2))}finally{await s.app.close().catch(()=>{});await s.store.close().catch(()=>{});await rm(root,{recursive:true,force:true})}
