/** Bilingual UI + real main Chat / stage MCP acceptance; synthetic project only. */
import {createServer} from 'node:net';
import assert from 'node:assert/strict';
import {randomUUID,randomBytes} from 'node:crypto';
import {mkdir,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {chromium,expect} from '@playwright/test';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import {seedLivingStage} from '../tests/fixtures/alva/living-stage.js';
const run=new Date().toISOString().replace(/[:.]/g,'')+'-ALVA074-browser',out=resolve('evidence',run),root=resolve('.runtime',run);await mkdir(out,{recursive:true});await mkdir(root,{recursive:true});
process.env.OPENAI_API_KEY||=process.env.NEWAPI_KEY;assert.ok(process.env.OPENAI_API_KEY);process.env.ALVA_AGENT_DIR=resolve(root,'agents');process.env.ALVA_ACCESS_CODE=randomBytes(24).toString('hex');
const store=new AlvaStore(resolve(root,'db'));await store.init();const {project}=await store.create('我的中文项目');await store.ensureAccessCode(project.id);
const port=await new Promise<number>(done=>{const s=createServer();s.listen(0,'127.0.0.1',()=>{const port=(s.address() as {port:number}).port;s.close(()=>done(port))})}),origin=`http://127.0.0.1:${port}`;
const app=await buildAlva(store,{assets:true,automaticRecommendations:false,origin});await app.listen({host:'127.0.0.1',port});const auth=await store.issueInternalSession(project.id);
const browser=await chromium.launch({headless:true,executablePath:'/home/ubuntu/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',args:['--disable-dev-shm-usage','--renderer-process-limit=1','--disable-gpu']});const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addInitScript('globalThis.__name = (v) => v');const page=await context.newPage(),checks:string[]=[],errors:string[]=[],messages:unknown[]=[];page.on('pageerror',e=>errors.push(e.message));
const scan=async(label:string)=>{const text=await page.locator('body').innerText();await writeFile(resolve(out,label+'-text.txt'),text);if(label.endsWith('-en'))assert.doesNotMatch(text.replaceAll('我的中文项目','').replaceAll('合成验收客厅','').replaceAll('ALVA-036 合成测量，非客户户型','').replaceAll('中文',''),/[\u3400-\u9fff]/,'Untranslated interface text: '+label);await page.screenshot({path:resolve(out,label+'.png'),fullPage:true})};
const waitGuide=async(count:number,language:'zh'|'en')=>{
 await expect.poll(async()=>{const p=await store.get(project.id);return p.messages.length>count&&p.messages.at(-1)?.status!=='running'?p.messages.at(-1)?.status:''},{timeout:240000,intervals:[1500]}).toBe('completed');
 const p=await store.get(project.id),m=p.messages.at(-1)!;assert.equal(m.language,language);assert.ok(m.guidanceKey,JSON.stringify(m));assert.ok(m.toolCalls?.some(t=>t.name==='get_stage_guidance'&&!t.isError));await expect(page.locator('.language-switch select')).toBeEnabled({timeout:30000});messages.push(m);return p;
};
try{
 await page.goto(origin);await page.locator('.language-switch select').selectOption('en');await expect(page.locator('html')).toHaveAttribute('lang','en');await scan('login-en');await page.reload();await expect(page.locator('.language-switch select')).toHaveValue('en');checks.push('login language switch persists across reload');
 await context.addCookies([{name:'alva_session',value:auth.token,url:origin}]);await page.reload();let p=await waitGuide(0,'en');assert.match(p.messages.at(-1)!.text,/upload/i);assert.doesNotMatch(p.messages.at(-1)!.text,/[\u3400-\u9fff]/);await expect(page.getByRole('button',{name:'Floorplan import',exact:true})).toBeVisible();await scan('floorplan-en');const floorThread=(await store.chatState(p.id)).threads.floorplan.threadId;
 await page.getByRole('button',{name:'Your Home Vision',exact:true}).click();await expect(page.locator('.hv-dialog')).toBeVisible();await scan('questionnaire-en');await page.locator('.hv-dialog .language-switch select').selectOption('zh');await scan('questionnaire-zh');await page.locator('.hv-dialog .language-switch select').selectOption('en');await page.locator('.hv-dialog').getByRole('button',{name:'Save and close questionnaire',exact:true}).click();checks.push('independent questionnaire supports both languages');
 const draft=page.locator('.composer textarea');const fallback=page.locator('textarea').last();const input=await draft.count()?draft:fallback;await input.fill('我的草稿 stays unchanged');await page.locator('.language-switch select').selectOption('zh');await expect(input).toHaveValue('我的草稿 stays unchanged');await input.fill('');p=await waitGuide(p.messages.length,'zh');assert.equal((await store.chatState(p.id)).threads.floorplan.threadId,floorThread);await scan('floorplan-zh');checks.push('English opening, Chinese resume on same thread; draft and project name unchanged');
 await input.fill('');await store.mutate(p.id,randomUUID(),p.revision,'synthetic-checkpoint',{},p=>seedLivingStage(p));await page.reload();p=await waitGuide(p.messages.length,'zh');await page.locator('.language-switch select').selectOption('en');p=await waitGuide(p.messages.length,'en');await page.getByRole('button',{name:'Living design',exact:true}).click();p=await waitGuide(p.messages.length,'en');assert.ok(p.messages.at(-1)!.toolCalls?.some(t=>t.name==='read_question_context'&&!t.isError));assert.ok(p.messages.at(-1)!.toolCalls?.some(t=>t.name==='ask_question'&&!t.isError));await expect(page.getByTestId('vision-chat-question')).toBeVisible();assert.equal(p.visionQuestions?.at(-1)?.language,'en');await scan('living-en');await page.setViewportSize({width:390,height:844});await page.screenshot({path:resolve(out,'living-en-narrow.png'),fullPage:true});await expect(page.locator('.language-switch select')).toBeVisible();await page.setViewportSize({width:1440,height:1000});checks.push('living Agent actually reads questionnaire and emits English question card');
 const livingThread=(await store.chatState(p.id)).threads.living.threadId;const question=p.visionQuestions!.at(-1)!.questionId;
 await page.locator('.language-switch select').selectOption('zh');p=await waitGuide(p.messages.length,'zh');assert.equal(p.visionQuestions?.at(-1)?.language,'zh');assert.equal(p.visionQuestions?.at(-1)?.questionId,question);assert.equal((await store.chatState(p.id)).threads.living.threadId,livingThread);await scan('living-zh');checks.push('switch language resumes living thread, same unfinished question, no invented answer');
 assert.equal(p.name,'我的中文项目');assert.deepEqual(errors,[]);await writeFile(resolve(out,'result.json'),JSON.stringify({pass:true,checks,errors,messages},null,2));console.log(JSON.stringify({out,checks}));
}catch(error){await writeFile(resolve(out,'failure.json'),JSON.stringify({error:String(error),checks,errors,messages,project:await store.get(project.id)},null,2));await scan('failure').catch(()=>{});throw error}finally{await browser.close();await app.close();await store.close()}
