import {createServer} from 'node:net';
/** Synthetic project; real main Chat, HTTP MCP, generation, PNG rendering and model critic. */
import assert from 'node:assert/strict';
import {randomUUID,randomBytes,createHash} from 'node:crypto';
import {mkdir,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {chromium,expect} from '@playwright/test';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import {runCodex} from '../api/codex.js';
import {furnitureRenderer} from '../api/furniture/render.js';
import {seedLivingStage} from '../tests/fixtures/alva/living-stage.js';
const run=new Date().toISOString().replace(/[:.]/g,'')+'-ALVA071-real',out=resolve('evidence',run),root=resolve('.runtime',run);await mkdir(out,{recursive:true});await mkdir(root,{recursive:true});
process.env.OPENAI_API_KEY||=process.env.NEWAPI_KEY;assert.ok(process.env.OPENAI_API_KEY,'Existing provider credential required');process.env.ALVA_AGENT_DIR=resolve(root,'agents');process.env.ALVA_FURNITURE_AUDIT_DIR=resolve(root,'models');process.env.ALVA_ACCESS_CODE=randomBytes(24).toString('hex');process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE='/home/ubuntu/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome';
const store=new AlvaStore(resolve(root,'db'));await store.init();const created=await store.create('ALVA071 合成模型验收');await store.ensureAccessCode(created.project.id);await store.mutate(created.project.id,randomUUID(),0,'seed',{},p=>seedLivingStage(p));
const port=await new Promise<number>(resolve=>{const server=createServer();server.listen(0,'127.0.0.1',()=>{const address=server.address() as {port:number};server.close(()=>resolve(address.port))})});let origin=`http://127.0.0.1:${port}`,renderIndex=0;const calls:unknown[]=[],checks:string[]=[],errors:string[]=[];const realRender=furnitureRenderer(()=>origin);
const app=await buildAlva(store,{automaticRecommendations:false,assets:true,origin,furnitureCodex:async input=>{calls.push({images:input.images?.length||0,hasOriginal:input.text.includes('右侧抽屉'),hasDesignSummary:input.text.includes('建模设计说明'),threadId:input.session?.threadId});return runCodex(input)},furnitureRender:async(model,dimensions,signal)=>{const rendered=await realRender(model,dimensions,signal);renderIndex++;for(let i=0;i<3;i++)await writeFile(resolve(out,`attempt-${renderIndex}-${rendered.views[i]}.png`),Buffer.from(rendered.images[i].split(',')[1],'base64'));await writeFile(resolve(out,`render-${renderIndex}.json`),JSON.stringify({stats:rendered.stats,modelHash:createHash('sha256').update(JSON.stringify(model)).digest('hex'),views:rendered.views}));return rendered}});
origin=await app.listen({host:'127.0.0.1',port});const session=await store.issueInternalSession(created.project.id),headers={'Content-Type':'application/json',cookie:'alva_session='+session.token};let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
try{
 const before=await store.get(created.project.id);const text='请把当前阅读桌（itemId=table）升级成有真实细节的3D模型：保持1.4米宽、0.65米深、0.75米高，浅木色圆角桌面，四根独立圆柱桌腿，一个右侧抽屉及金属拉手，桌沿和抽屉缝有可见细节。请实际调用generate_furniture_model并完成三视角critic，不通过则修改；只生成待我确认的候选，不移动桌子，也不要保存。';
 const response=await fetch(origin+'/api/chat',{method:'POST',headers,body:JSON.stringify({requestId:randomUUID(),expectedRevision:before.revision,text,roomId:'room',model:'gemini-3.8-flash-high'}),signal:AbortSignal.timeout(620000)});const body=await response.text();await writeFile(resolve(root,'sse.txt'),body);assert.equal(response.status,200);assert.ok(body.includes('event: done'),body.slice(-3500));
 const proposed=await store.get(created.project.id);assert.deepEqual(proposed.scene,before.scene);const message=proposed.messages.at(-1)!;assert.ok(message.toolCalls?.some(t=>t.name==='generate_furniture_model'&&!t.isError),JSON.stringify(message));const proposal=proposed.proposals.find(p=>p.status==='proposed')!;assert.ok(proposal);const reviewed=proposal.changes[0].values.visualModel as any;assert.equal(reviewed.critique.verdict,'pass');assert.equal(reviewed.originalPrompt,text);assert.ok(calls.some((c:any)=>c.images===3&&c.hasOriginal&&c.hasDesignSummary));checks.push('real main Chat invoked living MCP and generated an approved candidate without adopting');
 browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage','--renderer-process-limit=1']});const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addInitScript('globalThis.__name = (v) => v');await context.addCookies([{name:'alva_session',value:session.token,url:origin}]);const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(origin);const card=page.getByTestId('proposal-card-'+proposal.id);await expect(card).toBeVisible({timeout:30000});await expect(card.locator('canvas')).toBeVisible();await card.screenshot({path:resolve(out,'candidate.png')});const accepted=page.waitForResponse(r=>r.url().endsWith('/api/proposals/accept'));await card.getByRole('button',{name:'仅确认勾选范围'}).click();assert.equal((await accepted).status(),200);await expect(card).not.toBeVisible();
 await page.getByRole('button',{name:'全屋',exact:true}).click();const host=page.locator('.canvas-wrap [data-testid="scene-view"]');await expect(host.locator('canvas')).toBeVisible();await page.waitForFunction(()=>!!(document.querySelector('.canvas-wrap [data-testid="scene-view"]') as any)?.alvaView);const count=await host.evaluate((el:any)=>{let count=0;el.alvaView.world.traverse((o:any)=>{if(o.isMesh&&o.userData.id==='table')count++});return count});assert.ok(count>=8);await page.screenshot({path:resolve(out,'adopted-scene.png')});await page.reload();await page.getByRole('button',{name:'全屋',exact:true}).click();await expect(page.locator('.canvas-wrap [data-testid="scene-view"] canvas')).toBeVisible();
 const after=await store.get(created.project.id);assert.equal(after.scene!.items[0].visualModel?.modelHash,reviewed.modelHash);assert.equal(after.scene!.items[0].x,before.scene!.items[0].x);assert.equal(after.savedVersion,before.savedVersion);checks.push('owner preview/confirmation, detailed scene rendering and reload preserve model and placement without autosave');assert.deepEqual(errors,[]);await writeFile(resolve(out,'result.json'),JSON.stringify({pass:true,checks,calls,errors,parts:count,modelHash:reviewed.modelHash,attempts:reviewed.attempts,critique:reviewed.critique,toolCalls:message.toolCalls},null,2));
}catch(error){await writeFile(resolve(out,'failure.json'),JSON.stringify({checks,calls,errors,error:String(error)},null,2));throw error}finally{await browser?.close();await app.close();await store.close()}
