import {mkdir,rm,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import {seedSnapshotProject} from '../tests/fixtures/alva/snapshot.js';
import type {CodexInput} from '../api/codex.js';

const run=process.env.ALVA038_RUN||`alva038-${Date.now()}`,root=resolve('.runtime',run),evidence=resolve('evidence',run),port=Number(process.env.ALVA038_PORT||43138),origin=`http://127.0.0.1:${port}`,code='alva038-round2-code-123456';
await rm(root,{recursive:true,force:true});await mkdir(root,{recursive:true});await mkdir(evidence,{recursive:true});process.env.ALVA_ACCESS_CODE=code;
let releaseBuilding:((value:string)=>void)|null=null;const buildingCodex=async(input:CodexInput)=>new Promise<string>((resolvePromise,reject)=>{releaseBuilding=resolvePromise;input.signal?.addEventListener('abort',()=>reject(new Error('aborted')),{once:true})});
async function start(){const store=new AlvaStore(resolve(root,'db'));await store.init();const app=await buildAlva(store,{origin,buildingCodex});await app.listen({host:'127.0.0.1',port});return {store,app}}
async function req(path:string,method='GET',body?:unknown,cookie=''){const r=await fetch(origin+path,{method,headers:{origin,...(cookie?{cookie}:{}),...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const text=await r.text();let data:any;try{data=JSON.parse(text)}catch{data=text}return {r,data,text}}
let s=await start();let cookie='';
try{
 const created=await s.store.create('ALVA-038 round2');await s.store.ensureAccessCode(created.project.id);let p=await s.store.mutate(created.project.id,randomUUID(),0,'seed',{},seedSnapshotProject);
 const home=await fetch(origin);if(home.status!==200)throw new Error('home not 200');const html=await home.text(),asset=html.match(/assets\/index-[^"']+\.js/)?.[0];if(!asset)throw new Error('built asset missing');const js=await (await fetch(origin+'/'+asset)).text();for(const label of ['明确恢复到工作稿','当前未保存修改会被替换','恢复前不会自动创建备份点','再次手动保存'])if(!js.includes(label))throw new Error('production restore UI missing '+label);
 const login=await req('/api/access','POST',{code});cookie=(login.r.headers.get('set-cookie')||'').split(';')[0];const save=await req('/api/save','POST',{requestId:randomUUID(),expectedRevision:p.revision,confirmed:true},cookie);if(save.r.status!==200)throw new Error('save failed '+save.text);p=save.data;
 const snapshot=await req('/api/versions/1','GET',undefined,cookie);if(snapshot.r.status!==200)throw new Error('snapshot unreadable');const snapshotName=snapshot.data.name;
 const changed=await s.store.mutate(created.project.id,randomUUID(),p.revision,'diverge',{},d=>{d.name='当前未保存工作稿';d.answers=[];d.evidence=[];d.findings=[];d.dirty=true});
 const restore=await req('/api/restore','POST',{requestId:randomUUID(),expectedRevision:changed.revision,version:1,confirmed:true},cookie);if(restore.r.status!==200||restore.data.name!==snapshotName||restore.data.answers.length===0)throw new Error('explicit restore incomplete');if((await req('/api/versions','GET',undefined,cookie)).data.length!==1)throw new Error('restore created automatic snapshot');
 // Start a building generation and verify restore is blocked while old async work is active.
 const afterRestore=restore.data;const generatePromise=req('/api/building/generate','POST',{requestId:randomUUID(),expectedRevision:afterRestore.revision},cookie);
 for(let i=0;i<50;i++){const current=await s.store.get(created.project.id);if(current.buildingState.status==='processing')break;await new Promise(r=>setTimeout(r,20))}
 const processing=await s.store.get(created.project.id);if(processing.buildingState.status!=='processing')throw new Error('building did not enter processing');const blocked=await req('/api/restore','POST',{requestId:randomUUID(),expectedRevision:processing.revision,version:1,confirmed:true},cookie);if(blocked.r.status!==409||!String(blocked.data.error).includes('生成建筑3D'))throw new Error('restore not blocked during building generation');const cancel=await req('/api/building/cancel','POST',{requestId:randomUUID(),expectedRevision:processing.revision},cookie);if(![200,409].includes(cancel.r.status))throw new Error('building cancel failed '+cancel.text);await generatePromise.catch(()=>{});releaseBuilding=null;
 const beforeRestart=await req('/api/versions','GET',undefined,cookie);await s.app.close();await s.store.close();s=await start();const afterRestart=await req('/api/versions','GET',undefined,cookie);if(JSON.stringify(afterRestart.data)!==JSON.stringify(beforeRestart.data))throw new Error('snapshot list changed after restart');const snapAfterRestart=await req('/api/versions/1','GET',undefined,cookie);if(snapAfterRestart.r.status!==200||snapAfterRestart.data.name!==snapshotName)throw new Error('snapshot missing after restart');const currentAfterRestart=await req('/api/project','GET',undefined,cookie);const restoreAgain=await req('/api/restore','POST',{requestId:randomUUID(),expectedRevision:currentAfterRestart.data.revision,version:1,confirmed:true},cookie);if(restoreAgain.r.status!==200||restoreAgain.data.name!==snapshotName)throw new Error('restore after restart failed');if((await req('/api/versions','GET',undefined,cookie)).data.length!==1)throw new Error('restart restore created automatic snapshot');
 const result={ok:true,run,homeStatus:home.status,uiConfirmationCopyPresent:true,explicitRestoreReplacedWholeDraft:true,restoreCreatesNoSnapshot:true,activeBuildingRestoreStatus:blocked.r.status,activeBuildingRestoreBlocked:true,snapshotsPersistAfterRestart:true,restoreWorksAfterRestart:true,versionCount:1};await writeFile(resolve(evidence,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{await s.app.close().catch(()=>{});await s.store.close().catch(()=>{});await rm(root,{recursive:true,force:true})}
