import {runCodex} from '../api/codex.js';
/** True Chat attachment upload and real main-Agent-to-vision MCP, with private isolated state. */
import assert from 'node:assert/strict';
import {createHash,randomUUID} from 'node:crypto';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {resolve,basename} from 'node:path';
import {createServer} from 'node:net';
import {chromium} from '@playwright/test';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import {readFloorplanAttachment} from '../api/import/attachments.js';
const step=process.argv[2];assert.ok(['upload','recognize'].includes(step));const run=new Date().toISOString().replace(/[-:.]/g,'')+'-ALVA066-floorplan-'+step;
const root=process.argv[3]?resolve(process.argv[3]):resolve('.runtime',run),out=resolve('evidence',run);assert.ok(root.startsWith(resolve('.runtime')+'/')&&basename(root).includes('ALVA066-floorplan-'));
await mkdir(root,{recursive:true,mode:0o700});await mkdir(out,{recursive:true});process.env.ALVA_AGENT_DIR=resolve(root,'agents');process.env.ALVA_DATA_DIR=resolve(root,'data');process.env.ALVA_UPLOAD_DIR=resolve(root,'uploads');process.env.ALVA_ACCESS_CODE_FILE=resolve(root,'access-code');process.env.OPENAI_API_KEY||=process.env.NEWAPI_KEY;
const store=new AlvaStore(resolve(root,'db'));await store.init();let state:{projectId:string;attachmentId?:string;sourceSha256?:string};
if(step==='upload'){const created=await store.create('ALVA-066 real reference floorplan acceptance');await store.ensureAccessCode(created.project.id);state={projectId:created.project.id}}else state=JSON.parse(await readFile(resolve(root,'run-state.json'),'utf8'));
const probe=createServer();await new Promise<void>(r=>probe.listen(0,'127.0.0.1',r));const address=probe.address();assert.ok(address&&typeof address==='object');const port=address.port;await new Promise<void>((r,j)=>probe.close(e=>e?j(e):r()));const origin=`http://127.0.0.1:${port}`;process.env.ALVA_PORT=String(port);const app=await buildAlva(store,{origin,visionCodex:async input=>{assert.equal(input.tools,undefined);assert.equal(input.session,undefined);const raw=await runCodex(input);await writeFile(resolve(root,`vision-${randomUUID()}.txt`),raw,{mode:0o600});return raw}});await app.listen({host:'127.0.0.1',port});const access=await store.issueInternalSession(state.projectId);let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
try{
 if(step==='upload'){
  browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:1280,height:800}});page.setDefaultTimeout(20_000);await page.context().addCookies([{name:'alva_session',value:access.token,url:origin,httpOnly:true,sameSite:'Strict'}]);await page.goto(origin);await page.getByLabel('咨询消息').waitFor();await page.getByLabel('添加附件').click();const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'发送户型附件给顾问'}).click();const uploaded=page.waitForResponse(r=>r.url().endsWith('/api/chat/attachments'));await (await chooser).setFiles(resolve('references/room-study-handoff/public/floorplan.png'));const response=await uploaded;assert.equal(response.status(),200);const metadata=await response.json();state.attachmentId=metadata.attachmentId;
  const original=await readFile(resolve('references/room-study-handoff/public/floorplan.png')),stored=await readFloorplanAttachment(state.projectId,state.attachmentId!);state.sourceSha256=createHash('sha256').update(original).digest('hex');assert.equal(stored.metadata.sha256,state.sourceSha256);assert.equal(stored.data,original.toString('base64'));await page.getByText('户型附件：floorplan.png',{exact:false}).waitFor();await page.screenshot({path:resolve(out,'chat-real-attachment.png')});await writeFile(resolve(root,'run-state.json'),JSON.stringify(state,null,2));
 }else{
  assert.ok(process.env.OPENAI_API_KEY);assert.ok(state.attachmentId);const p=await store.get(state.projectId),before=p.messages.length;const response=await fetch(origin+'/api/chat',{method:'POST',headers:{'Content-Type':'application/json',cookie:`alva_session=${access.token}`,origin},body:JSON.stringify({requestId:randomUUID(),expectedRevision:p.revision,attachmentIds:[state.attachmentId],text:'请实际调用 recognize_floorplan 识别本轮上传的原始户型图，生成待校正候选。只执行识图和读取，不校准或确认，不调用界面操作。模型识图失败时如实报告具体错误。',roomId:null,model:'gemini-3.1-flash-lite'}),signal:AbortSignal.timeout(630_000)});const body=await response.text();await writeFile(resolve(root,run+'-sse.txt'),body);assert.equal(response.status,200);const latest=await store.get(state.projectId),assistant=latest.messages.slice(before).find(m=>m.role==='assistant');await writeFile(resolve(out,'tool-calls.json'),JSON.stringify(assistant?.toolCalls||[],null,2));assert.ok(assistant?.toolCalls?.some(t=>t.name==='recognize_floorplan'&&!t.isError),assistant?.text);assert.equal(latest.importState?.status,'succeeded');assert.ok(latest.candidate?.rooms.length);assert.equal(latest.confirmedTopology,undefined);await writeFile(resolve(root,'recognized-candidate.json'),JSON.stringify(latest.candidate,null,2));
 }
 const p=await store.get(state.projectId);const result={pass:true,run,step,privateRun:basename(root),projectId:state.projectId,sourceSha256:state.sourceSha256,trueAttachment:true,realVision:step==='recognize',importState:p.importState,candidateCounts:p.candidate?{walls:p.candidate.walls.length,rooms:p.candidate.rooms.length,openings:p.candidate.openings.length}:undefined,threadId:(await store.chatState(state.projectId)).threads.floorplan.threadId};await writeFile(resolve(out,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}catch(error){await writeFile(resolve(out,'result.json'),JSON.stringify({pass:false,run,step,privateRun:basename(root),error:String(error)},null,2));throw error}
finally{await browser?.close();await app.close();await store.close()}
