import {createServer} from 'node:net';
import assert from 'node:assert/strict';
import {randomUUID,randomBytes} from 'node:crypto';
import {mkdir,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {chromium,expect} from '@playwright/test';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import {publishProposals} from '../api/furniture/proposal-decisions.js';
import {seedLivingStage} from '../tests/fixtures/alva/living-stage.js';
import {createVisionQuestionTools} from '../api/consultation/vision-questions.js';
import {visionQuestionInput} from '../tests/fixtures/alva/vision-question.js';
import type {VisionQuestion} from '../packages/contracts/alva/home-vision/chat.js';
const real=process.argv.includes('--real');
const run=new Date().toISOString().replace(/[:.]/g,'')+'-ALVA078-'+(real?'real-chat':'browser'),out=resolve(process.env.ALVA_ACCEPTANCE_DIR||resolve('.runtime','acceptance',run)),root=resolve(process.env.ALVA_ACCEPTANCE_DIR||resolve('.runtime','acceptance',run),'private');await mkdir(out,{recursive:true});await mkdir(root,{recursive:true});
process.env.OPENAI_API_KEY||=process.env.NEWAPI_KEY;process.env.ALVA_AGENT_DIR=resolve(root,'agents');process.env.ALVA_ACCESS_CODE=randomBytes(24).toString('hex');
const store=new AlvaStore(resolve(root,'db'));await store.init();const {project}=await store.create('Vision sections synthetic verification');await store.ensureAccessCode(project.id);
await store.mutate(project.id,randomUUID(),0,'seed',{},async p=>{seedLivingStage(p);const messageId=randomUUID();p.messages.push({id:messageId,role:'user',text:'喜欢浅木色，但不喜欢每天擦柜子',status:'completed',stage:'living',createdAt:new Date().toISOString()});const queued:VisionQuestion[]=[];const tools=createVisionQuestionTools({readProject:async()=>p,sourceMessageId:messageId,roomId:null,queue:c=>queued.push(c)});const ask=tools.find(t=>t.name==='ask_question')!;await ask.run(visionQuestionInput(messageId));await ask.run({...visionQuestionInput(messageId),questionId:'Q07b',question:'Which accent colour would you enjoy?',options:visionQuestionInput(messageId).options.map((o,i)=>({...o,title:i?'Green accents':'Warm white',value:i?'soft green':'warm white'}))});p.visionQuestions=queued;});
let calls=0;
const port=await new Promise<number>(done=>{const server=createServer();server.listen(0,'127.0.0.1',()=>{const p=(server.address() as {port:number}).port;server.close(()=>done(p))})}),origin='http://127.0.0.1:'+port;
const app=await buildAlva(store,{origin,assets:true,...(real?{}:{chatCodex:async(input:any)=>{calls++;const call=async(name:string,args={})=>input.tools.find((t:any)=>t.name===name).run(args);await call('read_questionnaire_batch');await call('skip_furniture_suggestion',{reason:'Only choosing colours, no furniture needed.'});const ctx=await call('read_question_context',{questionId:'Q07a'});const p=await store.get(project.id),messageId=p.messages.filter(m=>m.role==='user').at(-1)!.id;await call('ask_question',{...visionQuestionInput(messageId,p.messages.find(m=>m.id===messageId)!.text),expectedVersion:ctx.respondent.version,question:'Would you like to refine this palette?'});return 'Your colours work together. Let’s refine the next section.';}})});await app.listen({host:'127.0.0.1',port});const auth=await store.issueInternalSession(project.id);
global.gc?.();
const browser=await chromium.launch({headless:true,executablePath:'/home/ubuntu/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',args:['--disable-dev-shm-usage','--renderer-process-limit=1','--disable-gpu','--single-process','--no-zygote','--js-flags=--max-old-space-size=96']});const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addCookies([{name:'alva_session',value:auth.token,url:origin}]);const page=await context.newPage(),checks:string[]=[],errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(origin);await page.locator('header .language-switch select').selectOption('en');const sidebar=page.getByRole('complementary',{name:'Home Vision questionnaire'});await expect(sidebar.getByTestId('vision-chat-question')).toBeVisible();await expect(sidebar.locator('.tabs')).toHaveCount(0);await page.waitForTimeout(1100);assert.equal((await store.get(project.id)).messages.length,1);checks.push('an existing pending Vision section suppresses duplicate automatic stage guidance');
 await sidebar.locator('.hv-opt').first().click();await sidebar.getByTestId('vision-section-next').click();assert.equal((await store.get(project.id)).homeVision,undefined);await sidebar.locator('.hv-opt').first().click();await page.screenshot({path:resolve(out,'section-before-submit.png')});checks.push('one question at a time; choices are drafts until section Submit; no furniture tabs');
 await sidebar.getByRole('button',{name:'Previous question'}).click();await expect(sidebar.locator('.hv-opt').first()).toHaveAttribute('aria-pressed','true');await sidebar.getByTestId('vision-section-next').click();await sidebar.getByTestId('vision-section-next').click();
 await expect.poll(async()=>(await store.get(project.id)).questionnaireDelivery?.status,{timeout:real?600000:30000,intervals:[1000]}).toBe('completed');let p=await store.get(project.id);assert.equal(p.homeVision!.responses[0].answers.Q07a.value,'Q07a.warm_light_wood');assert.equal(p.homeVision!.responses[0].answers.Q07b.value,'warm white');const m=p.messages.filter(m=>m.role==='assistant').at(-1)!;assert.ok(m.toolCalls?.some(t=>t.name==='read_questionnaire_batch'&&!t.isError));assert.ok(m.toolCalls?.some(t=>t.name==='ask_question'&&!t.isError));assert.equal(p.messages.filter(m=>m.role==='user').length,2);assert.match(p.messages.filter(m=>m.role==='user').at(-1)!.text,/Which accent colour/);await expect(sidebar.getByTestId('vision-chat-question')).toBeVisible();checks.push('one Submit saves both answers, sends one main Chat turn, and displays the Agent’s next section through MCP');
 while(await page.getByRole('dialog',{name:'Your Room Vision'}).count()){await page.getByRole('dialog',{name:'Your Room Vision'}).last().getByRole('button',{name:'Close without applying'}).click()}
 await page.screenshot({path:resolve(out,'next-section-desktop.png')});await page.reload();await expect(sidebar.getByTestId('vision-chat-question')).toBeVisible();assert.equal((await store.get(project.id)).messages.length,p.messages.length);checks.push('refresh restores the next section without sending a duplicate turn');
 if(!real){const previousDelivery=p.questionnaireDelivery!.id;await sidebar.locator('.hv-opt').last().click();await sidebar.getByTestId('vision-section-next').click();await expect.poll(async()=>{const q=await store.get(project.id);return q.questionnaireDelivery?.id!==previousDelivery&&q.questionnaireDelivery?.status==='completed'},{timeout:30000}).toBe(true);p=await store.get(project.id);assert.equal(p.messages.filter(m=>m.role==='user').length,3);assert.equal(calls,2);await expect(sidebar.getByTestId('vision-chat-question')).toBeVisible();checks.push('a second Submit repeats the loop exactly once and generates a third section')}

 await page.setViewportSize({width:390,height:844});await sidebar.scrollIntoViewIfNeeded();await page.screenshot({path:resolve(out,'next-section-mobile.png')});await expect(sidebar.locator('.hv-opt').first()).toBeVisible();checks.push('narrow viewport keeps Vision options usable');
 await page.setViewportSize({width:1440,height:1000});const beforeScene=JSON.stringify((await store.get(project.id)).scene);
 await store.mutate(project.id,randomUUID(),null,'synthetic-proposal-popup',{},p=>publishProposals(p,[{id:randomUUID(),title:'Reading corner',rationale:'Synthetic Room Vision decision',evidenceIds:[],baseRevision:p.revision,changes:[{action:'add',targetId:'room',values:{assetId:'alva-chair',roomId:'room',x:1,y:1,newId:randomUUID()}}],status:'proposed'}],'popup-check'));
 await page.reload();const popup=page.getByRole('dialog',{name:'Your Room Vision'});await expect(popup).toBeVisible();await expect(popup.locator('[data-testid="scene-view"] canvas')).toHaveCount(1);await page.screenshot({path:resolve(out,'room-vision-popup.png')});await popup.getByRole('button',{name:'Close without applying'}).click();await expect(popup).toHaveCount(0);assert.equal(JSON.stringify((await store.get(project.id)).scene),beforeScene);checks.push('Room Vision popup shares the template, renders a real preview and closes without adopting');
 if(!real){
  await store.mutate(project.id,randomUUID(),null,'native-form-fixture',{},p=>{for(const c of p.visionQuestions||[])if(c.status==='awaiting_owner_confirmation')c.status='dismissed';const r=p.homeVision!.responses[0];r.answers={};r.chatAnswers=[];r.cursor='Q01';r.version++});
  await page.reload();await expect(sidebar.locator('.hv-embedded')).toBeVisible();const beforeCalls=calls;
  for(let i=0;i<4;i++){const atEnd=await sidebar.getByRole('button',{name:'Submit',exact:true}).count()>0;await sidebar.getByRole('button',{name:'Skip for now',exact:true}).click();if(atEnd)break}
  await expect(sidebar.getByRole('button',{name:'Submit',exact:true})).toBeEnabled();assert.equal(calls,beforeCalls);await page.screenshot({path:resolve(out,'native-section-submit.png')});await sidebar.getByRole('button',{name:'Submit',exact:true}).click();await expect.poll(()=>calls,{timeout:30000}).toBe(beforeCalls+1);await expect(sidebar.getByTestId('vision-chat-question')).toBeVisible({timeout:30000});checks.push('native conditional form also waits for explicit section Submit, then resumes generated Vision questions');
 }

 assert.deepEqual(errors,[]);await writeFile(resolve(out,'result.json'),JSON.stringify({pass:true,real,checks,errors,calls,toolCalls:m.toolCalls,thread:(await store.chatState(project.id)).threads.living.threadId},null,2));console.log(JSON.stringify({out,checks}));
}catch(error){await writeFile(resolve(out,'failure.json'),JSON.stringify({error:String(error),checks,errors,messages:(await store.get(project.id)).messages},null,2));await page.screenshot({path:resolve(out,'failure.png')}).catch(()=>{});throw error}finally{await browser.close();await app.close();await store.close()}
