import assert from 'node:assert/strict';
import {readFile,mkdir,rm,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
import {chromium} from '@playwright/test';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import type {SceneData} from '../api/model.js';
import {createTopologyVersion} from '../api/topology/calibration.js';
import type {BuildingCodexCall} from '../api/building/generate.js';
import type {BuildingSceneData} from '../api/building/types.js';

const port=4222,origin=`http://127.0.0.1:${port}`,code='alva-012-browser-code-123456';
const runId=`${new Date().toISOString().replace(/[-:.]/g,'').replace('Z','Z')}-ALVA012-real-browser`;
const evidence=resolve('evidence',runId),data=resolve('.runtime',`${runId}-data`);
await mkdir(evidence,{recursive:true});await rm(data,{recursive:true,force:true});await mkdir(data,{recursive:true,mode:0o700});
process.env.ALVA_ACCESS_CODE=code;process.env.ALVA_DATA_DIR=data;process.env.ALVA_ORIGIN=origin;
const png=await readFile(resolve('references/room-study-handoff/public/floorplan.png'));const pngData=png.toString('base64');
const rectangle:SceneData={walls:[
 {id:'wall-a',a:{x:0,y:0},b:{x:6,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]},
 {id:'wall-b',a:{x:6,y:0},b:{x:6,y:4},thickness:.15,height:2.8,structural:'unknown',evidence:[]},
 {id:'wall-c',a:{x:6,y:4},b:{x:0,y:4},thickness:.15,height:2.8,structural:'unknown',evidence:[]},
 {id:'wall-d',a:{x:0,y:4},b:{x:0,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]},
],rooms:[{id:'room-main',name:'客厅',purpose:'生活',polygon:[{x:0,y:0},{x:6,y:0},{x:6,y:4},{x:0,y:4}],locked:false}],openings:[{id:'opening-main',wallId:'wall-c',kind:'window',offset:.5,width:1.4,height:1.2,sill:.9}],items:[],calibration:{wallId:'wall-a',length:6,source:'真实 floorplan.png 现场测量',confirmed:true},geography:{latitude:31,north:0,assumption:'图上方为北'}};
const lShape:SceneData={...rectangle,walls:[...rectangle.walls.slice(0,3),{id:'wall-e',a:{x:4,y:4},b:{x:4,y:3},thickness:.15,height:2.8,structural:'unknown',evidence:[]},{id:'wall-f',a:{x:4,y:3},b:{x:0,y:3},thickness:.15,height:2.8,structural:'unknown',evidence:[]},{id:'wall-g',a:{x:0,y:3},b:{x:0,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]}],rooms:[{id:'room-main',name:'客餐厅',purpose:'生活',polygon:[{x:0,y:0},{x:6,y:0},{x:6,y:4},{x:4,y:4},{x:4,y:3},{x:0,y:3}],locked:false}],openings:[{id:'opening-main',wallId:'wall-c',kind:'window',offset:.25,width:1.2,height:1.2,sill:.9}],calibration:{wallId:'wall-a',length:6,source:'真实 floorplan.png 现场测量',confirmed:true}};
const store=new AlvaStore(resolve(data,'db'));await store.init();const created=await store.create('ALVA-012 真实户型图网页验收');await store.ensureAccessCode(created.project.id);
let seeded=await store.mutate(created.project.id,randomUUID(),0,'real-floorplan-seed',{source:'references/room-study-handoff/public/floorplan.png'},p=>{p.sourceImage={mime:'image/png',data:pngData,originalMime:'image/png',filename:'floorplan.png'};const version=createTopologyVersion(p,rectangle);p.topologyVersions=[version];p.confirmedTopology=version;p.scene=rectangle;p.dirty=true;p.importState={status:'succeeded',message:'Codex 已基于真实附件完成识别，候选已核对。',requestId:randomUUID(),sourceMime:'image/png',filename:'floorplan.png',provider:'codex',model:'gpt-5.5',startedAt:new Date().toISOString(),finishedAt:new Date().toISOString()};});
let activeTopology=rectangle;const codex:BuildingCodexCall=async input=>{const fingerprint=(input.text.match(/来源指纹：([A-Fa-f0-9]{64})/)||[])[1]!;const version=Number((input.text.match(/确认拓扑版本：([0-9]+)/)||[])[1]);return JSON.stringify(buildingFor(activeTopology,version,fingerprint));};
const app=await buildAlva(store,{origin,assets:true,buildingCodex:process.env.ALVA_BROWSER_STUB==='1'?codex:undefined});await app.listen({host:'127.0.0.1',port});
const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||'/home/ubuntu/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});
const page=await browser.newPage({viewport:{width:1600,height:1000}});const checks:Record<string,unknown>={};const responses:number[]=[];const consoleErrors:string[]=[];
page.on('response',response=>{if(response.url().endsWith('/api/building/generate'))responses.push(response.status())});page.on('console',message=>{if(message.type()==='error')consoleErrors.push(message.text())});page.on('pageerror',error=>consoleErrors.push(error.message));
async function clickGenerate(){const responsePromise=page.waitForResponse(response=>response.url().endsWith('/api/building/generate'),{timeout:180000});await page.getByRole('button',{name:/生成建筑3D|重新生成建筑3D/}).click();const response=await responsePromise;assert.equal(response.status(),200,await response.text());await page.getByRole('button',{name:'确认建筑预览'}).waitFor({timeout:30000});await page.getByRole('button',{name:'全屋'}).click();await page.getByTestId('building-view').waitFor({timeout:30000});}
try{
  await page.goto(origin);await page.getByLabel('统一验证码').fill(code);await page.getByRole('button',{name:/验证并进入/}).click();await page.getByText('ALVA-012 真实户型图网页验收').waitFor();assert.equal(await page.getByText(/来源：floorplan\.png/).count(),1);checks.real_attachment=true;
  await clickGenerate();checks.first_generated=await page.getByTestId('building-view').count()===1;checks.first_component_trace=await page.getByText(/输入拓扑 v1/).count()===1;await page.getByRole('button',{name:'确认建筑预览'}).click();await page.getByTestId('building-confirmed').waitFor();checks.first_confirmed=true;await page.reload();await page.getByTestId('building-confirmed').waitFor();checks.first_reload=true;
  activeTopology=lShape;seeded=await store.mutate(created.project.id,randomUUID(),seeded.revision+3,'topology-change',{source:'real-floorplan.png'},p=>{const version=createTopologyVersion(p,lShape);p.topologyVersions=[...p.topologyVersions,version];p.confirmedTopology=version;p.scene=lShape;p.buildingState={...p.buildingState,status:'expired',topologyVersion:version.version,topologyFingerprint:version.sourceFingerprint,updatedAt:new Date().toISOString()};p.dirty=true;});
  await page.reload();await page.getByText(/重新生成建筑3D/).waitFor();checks.expired_visible=await page.getByText(/重新生成建筑3D/).count()===1;await clickGenerate();checks.second_generated=await page.getByTestId('building-view').count()===1;await page.getByRole('button',{name:'确认建筑预览'}).click();await page.getByTestId('building-confirmed').waitFor();checks.second_confirmed=true;await page.reload();await page.getByTestId('building-confirmed').waitFor();checks.second_reload=true;
  await page.screenshot({path:resolve(evidence,'alva-012-real-browser.png'),fullPage:true});
  const unexpectedConsoleErrors=consoleErrors.filter(error=>!/(401|422)/.test(error));checks.console_errors=unexpectedConsoleErrors.length===0;const result={ticket:'ALVA-012',runId,pass:Object.values(checks).every(value=>value===true)&&responses.length===2&&responses.every(status=>status===200)&&unexpectedConsoleErrors.length===0,checks,responses,consoleErrors,source:{filename:'floorplan.png',bytes:png.length}};await writeFile(resolve(evidence,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));if(!result.pass)process.exitCode=1;
}finally{await page.close();await browser.close();await app.close();await store.close();await rm(data,{recursive:true,force:true});}

function buildingFor(topology:SceneData,version:number,fingerprint:string):BuildingSceneData{const components:any[]=[];for(const room of topology.rooms){const xs=room.polygon.map(p=>p.x),zs=room.polygon.map(p=>p.y);components.push({id:`floor-${room.id}`,kind:'floor',topologyId:room.id,position:{x:(Math.min(...xs)+Math.max(...xs))/2,y:0,z:(Math.min(...zs)+Math.max(...zs))/2},size:{x:Math.max(...xs)-Math.min(...xs),y:.08,z:Math.max(...zs)-Math.min(...zs)},rotation:0,material:'floor',color:'#c9b79e'});}for(const wall of topology.walls){const dx=wall.b.x-wall.a.x,dy=wall.b.y-wall.a.y,len=Math.hypot(dx,dy),a=Math.atan2(dy,dx);components.push({id:`wall-${wall.id}`,kind:'wall',topologyId:wall.id,position:{x:(wall.a.x+wall.b.x)/2,y:wall.height/2,z:(wall.a.y+wall.b.y)/2},size:{x:len,y:wall.height,z:wall.thickness},rotation:a,material:'plaster',color:'#ddd8ca'});}for(const opening of topology.openings){const wall=topology.walls.find(w=>w.id===opening.wallId)!,len=Math.hypot(wall.b.x-wall.a.x,wall.b.y-wall.a.y),a=Math.atan2(wall.b.y-wall.a.y,wall.b.x-wall.a.x),x=wall.a.x+Math.cos(a)*opening.offset*len,z=wall.a.y+Math.sin(a)*opening.offset*len,base={position:{x,y:opening.sill+opening.height/2,z},size:{x:opening.width,y:opening.height,z:.12},rotation:a,topologyId:opening.id};components.push({id:`frame-${opening.id}`,kind:'window-frame',...base,material:'wood',color:'#8b6b4a'});components.push({id:`glass-${opening.id}`,kind:'glass',...base,size:{x:opening.width,y:opening.height,z:.03},material:'glass',color:'#9fc4cf'});}return {units:'meters',topologyVersion:version,topologyFingerprint:fingerprint,components,camera:{position:{x:10,y:8,z:12},target:{x:3,y:1,z:2}}};}
