import {chromium,expect} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';

const run=new Date().toISOString().replace(/[:.]/g,'')+'-ALVA054-browser',dir='evidence/'+run;
await mkdir(dir,{recursive:true});process.env.ALVA_ACCESS_CODE='alva054-browser-synthetic-code';
const store=new AlvaStore();await store.init();const {project}=await store.create('ALVA-054 问卷验收 · 合成项目');await store.ensureAccessCode(project.id);
const app=await buildAlva(store,{origin:'http://127.0.0.1:4284'});await app.listen({host:'127.0.0.1',port:4284});
const browser=await chromium.launch({headless:true,args:['--disable-dev-shm-usage']});const context=await browser.newContext({viewport:{width:1440,height:1000}});const session=await store.issueInternalSession(project.id);await context.addCookies([{name:'alva_session',value:session.token,domain:'127.0.0.1',path:'/'}]);const page=await context.newPage();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const checks:string[]=[];
try{
 await page.goto('http://127.0.0.1:4284');await page.getByRole('button',{name:'聊聊你的家',exact:true}).click();const modal=page.getByRole('dialog');await expect(modal).toBeVisible();await expect(modal.getByRole('heading',{name:'聊聊你的家'})).toBeVisible();await expect(page.getByLabel('选择问卷题目')).toHaveValue('Q01');
 await modal.getByRole('button',{name:/先形成可转交设计师/}).click();await page.getByLabel('问卷自由补充').fill('希望能清楚交给设计师');await expect(modal.getByRole('button',{name:'确认此回答',exact:true})).toBeEnabled();
 if((await store.get(project.id)).answers.length)throw new Error('Selecting prematurely created answer');
 await page.getByLabel('关闭问卷').click();await expect(page.getByLabel('关闭前保存')).toBeVisible();await page.getByRole('button',{name:'保存并关闭',exact:true}).click();await expect(modal).toBeHidden();checks.push('selection draft, close protection, save-and-close');
 await page.reload();await page.getByRole('button',{name:'聊聊你的家',exact:true}).click();await expect(page.getByLabel('问卷自由补充')).toHaveValue('希望能清楚交给设计师');await page.screenshot({path:dir+'/desktop.png'});checks.push('saved draft restored after reload');
 await modal.getByRole('button',{name:'确认此回答',exact:true}).click();await expect(page.getByLabel('选择问卷题目')).toHaveValue('Q02');const confirmed=await store.get(project.id);if(confirmed.answers[0]?.questionId!=='Q01'||confirmed.evidence.length!==1)throw new Error('Confirmation not persisted');checks.push('confirmation writes canonical answer and evidence');
 await page.getByLabel('选择问卷题目').selectOption('Q03');await page.getByLabel('问卷自由补充').fill('尚未询问物业');
 await page.route('**/api/intake/progress',route=>route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'模拟保存失败，请重试'})}));await page.getByRole('button',{name:'保存进度',exact:true}).click();await expect(modal.getByRole('alert')).toContainText('模拟保存失败');await expect(page.getByLabel('问卷自由补充')).toHaveValue('尚未询问物业');await page.unroute('**/api/intake/progress');await page.getByRole('button',{name:'保存进度',exact:true}).click();await expect(modal.getByRole('status')).toContainText('进度已保存');checks.push('save failure retains draft and retry succeeds');
 await page.getByLabel('选择问卷题目').selectOption('Q25');await expect(modal.getByText('房间问题需要先确认户型', {exact:false})).toBeVisible();await expect(modal.getByRole('button',{name:'确认此回答',exact:true})).toBeDisabled();checks.push('room questions cannot leak into project scope');
 await page.getByLabel('选择问卷题目').selectOption('Q04');await page.getByRole('button',{name:'暂不确定',exact:true}).click();await page.getByRole('button',{name:'确认此回答',exact:true}).click();await expect(page.getByLabel('选择问卷题目')).toHaveValue('Q05');
 await page.getByRole('button',{name:'按需补充',exact:true}).click();await expect(page.getByLabel('选择问卷题目')).toHaveValue('Q49');await page.getByLabel('选择问卷题目').selectOption('Q52');await page.getByRole('button',{name:'不适用',exact:true}).click();await expect(page.getByRole('button',{name:'确认此回答',exact:true})).toBeDisabled();await page.getByLabel('问卷自由补充').fill('家中没有宠物');await page.getByRole('button',{name:'确认此回答',exact:true}).click();checks.push('unknown and explained not-applicable states; conditional branch');
 await page.getByRole('button',{name:'查看已答小结',exact:true}).click();await expect(modal.getByText('希望能清楚交给设计师',{exact:false})).toBeVisible();checks.push('editable summary');
 await page.getByRole('button',{name:'回到当前问题',exact:true}).click();await page.getByRole('button',{name:'基础问题',exact:true}).click();await page.setViewportSize({width:390,height:844});await page.screenshot({path:dir+'/mobile.png'});const fits=await modal.evaluate(el=>el.scrollWidth<=el.clientWidth+1);if(!fits)throw new Error('dialog horizontal overflow');checks.push('390px responsive dialog');
 await page.getByLabel('选择问卷题目').selectOption('Q02');await page.getByLabel('问卷自由补充').fill('丢弃测试');await page.keyboard.press('Escape');await expect(page.getByLabel('关闭前保存')).toBeVisible();await page.getByRole('button',{name:'放弃未保存修改',exact:true}).click();await expect(modal).toBeHidden();checks.push('Escape and discard');
 await page.setViewportSize({width:1440,height:1000});
 await store.mutate(project.id,randomUUID(),null,'synthetic-rooms',{},p=>{p.scene={walls:[],openings:[],items:[],calibration:null,geography:{latitude:0,north:0,assumption:'synthetic'},rooms:[{id:'room-a',name:'客厅',purpose:'休闲',locked:false,polygon:[{x:0,y:0},{x:4,y:0},{x:4,y:4},{x:0,y:4}]},{id:'room-b',name:'卧室',purpose:'休息',locked:false,polygon:[{x:4,y:0},{x:8,y:0},{x:8,y:4},{x:4,y:4}]}]}});
 await page.reload();await page.getByRole('button',{name:'聊聊你的家',exact:true}).click();await page.getByRole('button',{name:'基础问题',exact:true}).click();await page.getByLabel('选择问卷题目').selectOption('Q25');await page.getByLabel('问卷房间').selectOption('room-a');await page.getByLabel('问卷自由补充').fill('客厅阅读');await page.getByRole('button',{name:'确认此回答',exact:true}).click();await expect(page.getByLabel('选择问卷题目')).toHaveValue('Q26');await page.getByLabel('选择问卷题目').selectOption('Q25');await page.getByLabel('问卷房间').selectOption('room-b');await expect(page.getByLabel('问卷自由补充')).toHaveValue('');await page.getByLabel('问卷自由补充').fill('卧室休息');await page.getByRole('button',{name:'确认此回答',exact:true}).click();await expect(page.getByLabel('选择问卷题目')).toHaveValue('Q26');checks.push('two rooms keep separate answers');
 const state=await store.get(project.id);if((await store.versions(project.id)).length!==0||state.savedVersion!==0)throw new Error('Questionnaire created global snapshot');if(state.answers.filter(a=>a.questionId==='Q25').length!==2)throw new Error('Room answers overwritten');if(errors.length)throw new Error(errors.join('\n'));
 checks.push('no global snapshots; zero page errors');await writeFile(dir+'/result.json',JSON.stringify({ok:true,checks,errors},null,2));console.log(JSON.stringify({ok:true,dir,checks},null,2));
}catch(e){await page.screenshot({path:dir+'/failure.png'});await writeFile(dir+'/result.json',JSON.stringify({ok:false,checks,error:String(e),errors},null,2));console.error(dir);throw e}finally{await browser.close();await app.close();await store.close()}
