import {chromium,expect,devices} from '@playwright/test';import {mkdir,writeFile} from 'node:fs/promises';import {AlvaStore} from '../api/store.js';import {buildAlva} from '../api/api.js';
const dir='evidence/'+new Date().toISOString().replace(/[:.]/g,'')+'-ALVA057-browser';await mkdir(dir,{recursive:true});
process.env.ALVA_ACCESS_CODE='alva057-synthetic-validation-code';const store=new AlvaStore();await store.init();const {project}=await store.create('Synthetic Home Vision acceptance');await store.ensureAccessCode(project.id);const app=await buildAlva(store,{origin:'http://127.0.0.1:4287'});await app.listen({host:'127.0.0.1',port:4287});
const browser=await chromium.launch({headless:true,args:['--disable-dev-shm-usage']});const context=await browser.newContext({viewport:{width:1440,height:900}});const session=await store.issueInternalSession(project.id);await context.addCookies([{name:'alva_session',value:session.token,domain:'127.0.0.1',path:'/'}]);const page=await context.newPage(),errors:string[]=[],checks:string[]=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto('http://127.0.0.1:4287');const entry=page.getByRole('button',{name:/Your Home Vision/});await expect(entry).toBeVisible();await page.screenshot({path:dir+'/entry.png'});await entry.click();const modal=page.getByRole('dialog');await expect(modal.getByRole('heading')).toHaveText('What brings you here?');await expect(modal.getByRole('button',{name:'Continue',exact:true})).toBeDisabled();await page.screenshot({path:dir+'/q01.png'});
 await modal.getByRole('radio',{name:/Moving into a new home/}).click();await expect(modal.getByRole('radio',{name:/Moving into a new home/})).toHaveAttribute('aria-checked','true');await modal.getByRole('button',{name:'Continue',exact:true}).click();await expect(modal.getByRole('heading')).toContainText('Where is the home');await modal.getByRole('button',{name:'Save and close questionnaire'}).click();await expect(modal).toBeHidden();await page.reload();await entry.click();await expect(modal.getByRole('heading')).toContainText('Where is the home');checks.push('prominent entry, ZIP single cards, autosave/close/reload');
 await page.getByLabel('Country',{exact:true}).selectOption('Singapore');await page.getByLabel('City',{exact:true}).fill('Singapore');await modal.getByRole('button',{name:'Continue',exact:true}).click();await modal.getByRole('radio',{name:'HDB flat',exact:true}).click();await modal.getByRole('button',{name:'Continue',exact:true}).click();await modal.getByRole('checkbox',{name:'Pets',exact:true}).click();await modal.getByRole('button',{name:'Continue',exact:true}).click();await expect(modal.getByRole('heading')).toHaveText('Tell us about your pets.');await modal.getByRole('button',{name:'+ Add pet'}).click();await modal.getByRole('radio',{name:'cat',exact:true}).click();await expect(modal.getByRole('checkbox',{name:'Litter box'})).toBeVisible();await expect(modal.getByRole('checkbox',{name:'Somewhere to wash muddy paws'})).toHaveCount(0);await modal.getByRole('button',{name:'Skip for now'}).click();await expect(modal.getByRole('heading')).toHaveText('Which spaces do you plan to design?');checks.push('market localization and pet-dependent fields');
 await modal.getByRole('checkbox',{name:'Living room',exact:true}).click();await modal.getByRole('checkbox',{name:'Kitchen',exact:true}).click();await expect(modal.getByRole('radiogroup',{name:'Which one matters most right now?'})).toBeVisible();await modal.getByRole('radio',{name:'Kitchen',exact:true}).click();await page.screenshot({path:dir+'/q05.png'});await modal.getByRole('button',{name:'Continue',exact:true}).click();await expect(modal.getByRole('heading')).toContainText('summary');await modal.getByRole('button',{name:'Next stage'}).click();await modal.getByRole('button',{name:'Skip for now'}).click();await expect(modal.getByRole('heading')).toHaveText('Which palette appeals most to you?');await modal.getByRole('radio',{name:'Earthy tones',exact:true}).click();await page.screenshot({path:dir+'/q07.png'});checks.push('ZIP multi/grid/priority, stage summary, ZIP palettes');
 await page.route('**/api/intake/vision',async route=>{if(route.request().method()==='POST')await route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'Synthetic save failure'})});else await route.continue()});await modal.getByLabel('Any colors you love, or would never have? (optional)').fill('Sage green');await modal.getByRole('button',{name:'Save now'}).click();await expect(modal.getByRole('alert')).toContainText('Synthetic save failure');await expect(modal.getByLabel('Any colors you love, or would never have? (optional)')).toHaveValue('Sage green');await page.unroute('**/api/intake/vision');await modal.getByRole('button',{name:'Retry save'}).click();await expect(modal.getByRole('status')).toHaveText('All changes saved');checks.push('failed save retains edits; retry persists');
 await page.keyboard.press('Escape');await expect(modal).toBeHidden();
 const mobile=await browser.newContext({...devices['iPhone 13'],storageState:await context.storageState()});
 const phone=await mobile.newPage();phone.on('pageerror',e=>errors.push(e.message));await phone.goto('http://127.0.0.1:4287');await phone.getByRole('button',{name:/Your Home Vision/}).tap();
 const phoneModal=phone.getByRole('dialog',{name:'Your Home Vision'});await expect(phoneModal.getByRole('heading')).toHaveText('Which palette appeals most to you?');await phone.screenshot({path:dir+'/mobile.png'});
 if(!await phoneModal.evaluate(e=>e.scrollWidth<=e.clientWidth+1))throw new Error('Horizontal overflow');
 if(!await phoneModal.evaluate(e=>{const r=e.getBoundingClientRect(),v=window.visualViewport!;return r.left>=v.offsetLeft-1&&r.right<=v.offsetLeft+v.width+1&&r.top>=v.offsetTop-1&&r.bottom<=v.offsetTop+v.height+1}))throw new Error('Modal lies outside the mobile visual viewport');
 await phoneModal.getByRole('button',{name:'Save and close questionnaire'}).tap();await expect(phoneModal).toBeHidden();await mobile.close();
 checks.push('iPhone device-emulated layout, touch controls and desktop Escape save/close');const p=await store.get(project.id);if(!p.homeVision?.responses[0].answers.Q07b)throw new Error('Missing persistent answer');if(p.answers.length||p.savedVersion||(await store.versions(project.id)).length)throw new Error('Legacy answers or snapshots altered');if(errors.length)throw new Error(errors.join('\n'));checks.push('versioned storage, no global snapshot, no page errors');await writeFile(dir+'/result.json',JSON.stringify({ok:true,checks,errors},null,2));console.log(JSON.stringify({ok:true,dir,checks},null,2));
}catch(e){await page.screenshot({path:dir+'/failure.png'});await writeFile(dir+'/result.json',JSON.stringify({ok:false,checks,error:String(e),errors},null,2));console.error(dir);throw e}finally{await browser.close();await app.close();await store.close()}
