import {createHash} from 'node:crypto';
import {mkdir,rm,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import {seedSnapshotProject} from '../tests/fixtures/alva/snapshot.js';
const run=process.env.ALVA037_RUN||`alva037-${Date.now()}`,root=resolve('.runtime',run),evidence=resolve('evidence',run),port=Number(process.env.ALVA037_PORT||43137),origin=`http://127.0.0.1:${port}`,code='alva037-round2-code-123456';
await rm(root,{recursive:true,force:true});await mkdir(root,{recursive:true});await mkdir(evidence,{recursive:true});process.env.ALVA_ACCESS_CODE=code;
const store=new AlvaStore(resolve(root,'db'));await store.init();const {project}=await store.create('ALVA-037 round2');await store.ensureAccessCode(project.id);let seeded=await store.mutate(project.id,randomUUID(),0,'seed',{},seedSnapshotProject);const app=await buildAlva(store,{origin});await app.listen({host:'127.0.0.1',port});
async function req(path:string,method='GET',body?:unknown,cookie=''){const r=await fetch(origin+path,{method,headers:{origin,...(cookie?{cookie}:{}),...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const text=await r.text();let data:any;try{data=JSON.parse(text)}catch{data=text}return {r,data,text}}
const hash=(x:unknown)=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
try{
 const home=await fetch(origin);if(home.status!==200)throw new Error('home not 200');const html=await home.text(),asset=html.match(/assets\/index-[^"']+\.js/)?.[0];if(!asset)throw new Error('built JS asset missing');const js=await (await fetch(origin+'/'+asset)).text();for(const label of ['当前工作稿','只读快照','只读预览','二维','三维','需求与依据','重试这个快照','明确恢复到工作稿','还没有保存快照'])if(!js.includes(label))throw new Error('production UI missing '+label);
 const login=await req('/api/access','POST',{code});const cookie=(login.r.headers.get('set-cookie')||'').split(';')[0];const empty=await req('/api/versions','GET',undefined,cookie);if(empty.r.status!==200||empty.data.length!==0)throw new Error('empty history mismatch');
 const save=await req('/api/save','POST',{requestId:randomUUID(),expectedRevision:seeded.revision,confirmed:true},cookie);if(save.r.status!==200)throw new Error('save failed '+save.text);const saved=save.data,list=await req('/api/versions','GET',undefined,cookie);if(list.data.length!==1||list.data[0].version!==1||!Number.isFinite(Date.parse(list.data[0].created_at)))throw new Error('snapshot list metadata mismatch');const snap=await req('/api/versions/1','GET',undefined,cookie);if(snap.r.status!==200||!snap.data.scene||!snap.data.confirmedBuilding||snap.data.answers.length<1||snap.data.evidence.length<1)throw new Error('snapshot full state missing');
 const changed=await store.mutate(project.id,randomUUID(),saved.revision,'post-save-draft',{},p=>{p.name='当前未保存工作稿';p.answers=[];p.scene!.rooms[0].purpose='当前工作稿用途';p.dirty=true});const currentBefore=await req('/api/project','GET',undefined,cookie),currentHash=hash(currentBefore.data),revision=currentBefore.data.revision,versionsHash=hash((await req('/api/versions','GET',undefined,cookie)).data);
 const previewAgain=await req('/api/versions/1','GET',undefined,cookie);if(previewAgain.r.status!==200||previewAgain.data.name===changed.name)throw new Error('snapshot preview not isolated');const afterPreview=await req('/api/project','GET',undefined,cookie);if(hash(afterPreview.data)!==currentHash||afterPreview.data.revision!==revision)throw new Error('preview mutated working draft');if(hash((await req('/api/versions','GET',undefined,cookie)).data)!==versionsHash)throw new Error('preview mutated version list');
 const missing=await req('/api/versions/999','GET',undefined,cookie);if(missing.r.status!==404)throw new Error('missing snapshot not 404');if(hash((await req('/api/project','GET',undefined,cookie)).data)!==currentHash)throw new Error('failed preview mutated draft');
 const restore=await req('/api/restore','POST',{requestId:randomUUID(),expectedRevision:revision,version:1,confirmed:true},cookie);if(restore.r.status!==200)throw new Error('explicit restore failed '+restore.text);if(restore.data.name!=='ALVA-037 round2'||restore.data.answers.length<1||restore.data.dirty!==true)throw new Error('explicit restore did not replace draft with snapshot content');if((await req('/api/versions','GET',undefined,cookie)).data.length!==1)throw new Error('restore created an automatic snapshot');
 const result={ok:true,run,homeStatus:home.status,uiLabelsPresent:true,emptyStateSupported:true,manualSnapshotTimeIso:list.data[0].created_at,fullStatePreview:true,previewDoesNotMutateDraft:true,failedPreviewDoesNotMutateDraft:true,explicitRestoreOnlyMutation:true,restoreDoesNotCreateSnapshot:true};await writeFile(resolve(evidence,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{await app.close();await store.close();await rm(root,{recursive:true,force:true})}
