import {mkdir,rm,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import type {SceneData} from '../api/model.js';

const run=process.env.ALVA031_RUN||`alva031-${Date.now()}`,root=resolve('.runtime',run),evidenceDir=resolve('evidence',run),port=Number(process.env.ALVA031_PORT||43131),origin=`http://127.0.0.1:${port}`,code='alva031-round2-code-123456';
await rm(root,{recursive:true,force:true});await mkdir(root,{recursive:true});await mkdir(evidenceDir,{recursive:true});process.env.ALVA_ACCESS_CODE=code;
const wall=(id:string,ax:number,ay:number,bx:number,by:number)=>({id,a:{x:ax,y:ay},b:{x:bx,y:by},thickness:.15,height:2.8,structural:'unknown' as const,evidence:[]});const scene:SceneData={walls:[wall('w1',0,0,4,0),wall('w2',4,0,4,3),wall('w3',4,3,0,3),wall('w4',0,3,0,0)],rooms:[{id:'living',name:'客厅',purpose:'生活',polygon:[{x:0,y:0},{x:4,y:0},{x:4,y:3},{x:0,y:3}],locked:false}],openings:[],items:[],calibration:null,geography:{latitude:31,north:0,assumption:'test'}};
async function start(){const store=new AlvaStore(resolve(root,'db'));await store.init();const app=await buildAlva(store,{origin});await app.listen({host:'127.0.0.1',port});return {store,app}}
async function http(path:string,method='GET',body?:unknown,cookie=''){const r=await fetch(origin+path,{method,headers:{origin,...(cookie?{cookie}:{}),...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const text=await r.text();let data:any;try{data=JSON.parse(text)}catch{data=text}return {r,data,text}}
let s=await start();let ownerCookie='',designerCookie='',projectId='',otherId='',token='',linkId='';
try{
 const created=await s.store.create('ALVA-031 round2');projectId=created.project.id;await s.store.ensureAccessCode(projectId);const seeded=await s.store.mutate(projectId,randomUUID(),0,'seed',{},p=>{p.scene=scene});otherId=(await s.store.create('Other project')).project.id;
 const home=await fetch(origin);if(home.status!==200)throw new Error('home not 200');const html=await home.text(),asset=html.match(/assets\/index-[^"']+\.js/)?.[0];if(!asset)throw new Error('built js asset missing');const js=await (await fetch(origin+'/'+asset)).text();for(const label of ['设计师只读访问','生成新的只读邀请','撤销访问','你正在通过只读授权查看这个项目'])if(!js.includes(label))throw new Error('built UI missing '+label);
 const owner=await http('/api/access','POST',{code});if(owner.r.status!==200||owner.data.role!=='owner')throw new Error('owner login failed');ownerCookie=(owner.r.headers.get('set-cookie')||'').split(';')[0];const invite=await http('/api/invites','POST',{},ownerCookie);if(invite.r.status!==200)throw new Error('invite create failed');({token,linkId}=invite.data);
 const noCode=await http('/api/access','POST',{inviteToken:token});if(noCode.r.status!==400)throw new Error('invite bypassed shared code');const designer=await http('/api/access','POST',{code,inviteToken:token});if(designer.r.status!==200||designer.data.role!=='designer')throw new Error('designer login failed');designerCookie=(designer.r.headers.get('set-cookie')||'').split(';')[0];const view=await http('/api/project','GET',undefined,designerCookie);if(view.r.status!==200||view.data.id!==projectId)throw new Error('designer view failed');const save=await http('/api/save','POST',{requestId:randomUUID(),expectedRevision:seeded.revision,confirmed:true},designerCookie);if(save.r.status!==403||!String(save.data.error).includes('只读'))throw new Error('designer write not blocked');const cross=await http(`/api/projects/${otherId}`,'GET',undefined,designerCookie);if(cross.r.status!==403)throw new Error('cross project not blocked');const manage=await http('/api/invites','GET',undefined,designerCookie);if(manage.r.status!==403)throw new Error('designer can manage invites');
 await s.app.close();await s.store.close();s=await start();const afterRestart=await http('/api/project','GET',undefined,designerCookie);if(afterRestart.r.status!==200)throw new Error('designer session did not survive restart');const ownerAfterRestart=await http('/api/session','GET',undefined,ownerCookie);if(ownerAfterRestart.r.status!==200||ownerAfterRestart.data.role!=='owner')throw new Error('owner session did not survive restart');const revoke=await http(`/api/invites/${linkId}/revoke`,'POST',{},ownerCookie);if(revoke.r.status!==200)throw new Error('revoke failed');const revokedSession=await http('/api/project','GET',undefined,designerCookie);if(revokedSession.r.status!==401)throw new Error('revoked session still works');const oldLink=await http('/api/access','POST',{code,inviteToken:token});if(oldLink.r.status!==401)throw new Error('revoked invite reused');const list=await http('/api/invites','GET',undefined,ownerCookie),row=list.data.invites.find((v:any)=>v.id===linkId);if(!row?.revoked)throw new Error('revoke not persisted');const ownerProject=await http('/api/project','GET',undefined,ownerCookie);if(ownerProject.r.status!==200||ownerProject.data.id!==projectId)throw new Error('owner access affected by revoke');
 const result={ok:true,run,homeStatus:home.status,uiLabelsPresent:true,sharedCodeRequired:true,designerRole:true,designerViewStatus:view.r.status,designerWriteStatus:save.r.status,crossProjectStatus:cross.r.status,inviteManagementStatus:manage.r.status,sessionSurvivesRestart:true,revokeStatus:revoke.r.status,revokedSessionStatus:revokedSession.r.status,revokedInviteLoginStatus:oldLink.r.status,ownerUnaffected:true};await writeFile(resolve(evidenceDir,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{await s.app.close().catch(()=>{});await s.store.close().catch(()=>{});await rm(root,{recursive:true,force:true})}
