import {mkdir,rm,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import type {SceneData} from '../api/model.js';
import type {CodexInput} from '../api/codex.js';
const run=process.env.ALVA041_RUN||`alva041-round2-http-${Date.now()}`,root=resolve('.runtime',run),evidence=resolve('evidence',run),port=Number(process.env.ALVA041_PORT||43141),origin=`http://127.0.0.1:${port}`,code='alva041-round2-code-123456',png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';
await rm(root,{recursive:true,force:true});await mkdir(root,{recursive:true});await mkdir(evidence,{recursive:true});process.env.ALVA_ACCESS_CODE=code;
const store=new AlvaStore(resolve(root,'db'));await store.init();const created=await store.create('ALVA-041 HTTP验收');await store.ensureAccessCode(created.project.id);const wall=(id:string,ax:number,ay:number,bx:number,by:number)=>({id,a:{x:ax,y:ay},b:{x:bx,y:by},thickness:.15,height:2.8,structural:'unknown' as const,evidence:[]});const scene:SceneData={walls:[wall('w1',0,0,4,0),wall('w2',4,0,4,3),wall('w3',4,3,0,3),wall('w4',0,3,0,0)],rooms:[{id:'living',name:'客厅',purpose:'生活',polygon:[{x:0,y:0},{x:4,y:0},{x:4,y:3},{x:0,y:3}],locked:false}],openings:[],items:[],calibration:null,geography:{latitude:31,north:0,assumption:'test'}};await store.mutate(created.project.id,randomUUID(),0,'seed',{},p=>{p.scene=scene});
const model=async(input:CodexInput)=>{if(input.tools?.length)throw new Error('HTTP round does not invoke chat');return JSON.stringify({annotations:[{preference:'like',feature:'低饱和浅色和大面积留白'}]})};const app=await buildAlva(store,{origin,chatCodex:model});await app.listen({host:'127.0.0.1',port});
async function json(path:string,method='GET',body?:unknown,cookie=''){const r=await fetch(origin+path,{method,headers:{origin,...(cookie?{cookie}:{}),...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const text=await r.text();let data:any;try{data=JSON.parse(text)}catch{data=text}if(!r.ok)throw new Error(`${method} ${path} ${r.status}: ${text}`);return {r,data}}
try{const home=await fetch(origin);if(home.status!==200)throw new Error('home not 200');const login=await json('/api/access','POST',{code}),cookie=(login.r.headers.get('set-cookie')||'').split(';')[0];if(!cookie)throw new Error('missing session cookie');const before=(await json('/api/project','GET',undefined,cookie)).data;
 const analyzed=(await json('/api/references/analyze','POST',{requestId:randomUUID(),expectedRevision:before.revision,roomId:'living',filename:'living-reference.png',sourceText:'我喜欢浅色留白和低矮家具。',image:{mime:'image/png',data:png}},cookie)).data;if(analyzed.status!=='pending'||analyzed.annotations[0].origin!=='model')throw new Error('model batch mismatch');const image=await fetch(origin+`/api/references/${analyzed.id}/image`,{headers:{cookie}});if(image.status!==200||image.headers.get('content-type')!=='image/png'||Buffer.from(await image.arrayBuffer()).length!==Buffer.from(png,'base64').length)throw new Error('image source mismatch');
 const manual=(await json(`/api/references/${analyzed.id}/manual`,'POST',{requestId:randomUUID(),expectedRevision:before.revision,preference:'dislike',feature:'过于复杂的装饰灯造型'},cookie)).data,manualId=manual.annotations.find((a:any)=>a.origin==='manual')?.id;if(!manualId)throw new Error('manual annotation missing');const chosen=[analyzed.annotations[0].id,manualId];const confirmed=(await json('/api/references/confirm','POST',{requestId:randomUUID(),expectedRevision:before.revision,batchId:analyzed.id,annotationIds:chosen,confirmed:true},cookie)).data;if(confirmed.evidence.filter((e:any)=>e.source==='image'&&e.roomId==='living').length!==2)throw new Error('evidence mismatch');if(confirmed.findings.filter((f:any)=>f.objectIds.includes(`reference:${analyzed.id}`)).length!==2)throw new Error('finding mismatch');const listed=(await json('/api/references','GET',undefined,cookie)).data,batch=listed.find((b:any)=>b.id===analyzed.id);if(batch.status!=='confirmed'||batch.annotations.filter((a:any)=>a.status==='confirmed').length!==2)throw new Error('confirmed batch mismatch');const result={ok:true,run,homeStatus:home.status,imageStatus:image.status,batchStatus:batch.status,modelOrigin:batch.annotations.some((a:any)=>a.origin==='model'),manualOrigin:batch.annotations.some((a:any)=>a.origin==='manual'),confirmedAnnotations:batch.annotations.filter((a:any)=>a.status==='confirmed').length,projectRevision:confirmed.revision,imageEvidence:confirmed.evidence.filter((e:any)=>e.source==='image').length,referenceFindings:confirmed.findings.filter((f:any)=>f.objectIds.includes(`reference:${analyzed.id}`)).length};await writeFile(resolve(evidence,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2))}finally{await app.close();await store.close();await rm(root,{recursive:true,force:true})}
