import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdir,rm,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {createCanvas} from '@napi-rs/canvas';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import type {SceneData} from '../api/model.js';

const runId=process.env.ALVA_RUN_ID||`${new Date().toISOString().replace(/[-:.]/g,'')}-ALVA017-real`,port=Number(process.env.ALVA_PORT||4217),origin=`http://127.0.0.1:${port}`,root=resolve('.runtime',runId),evidence=resolve('evidence',runId),code='alva017-real-code-123456';
assert.ok(process.env.OPENAI_API_KEY,'OPENAI_API_KEY must be supplied by the caller');process.env.ALVA_ACCESS_CODE=code;process.env.ALVA_AGENT_DIR=resolve(root,'agent');await rm(root,{recursive:true,force:true});await mkdir(root,{recursive:true,mode:0o700});await mkdir(evidence,{recursive:true});
const scene:SceneData={walls:[{id:'n',a:{x:0,y:0},b:{x:5,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]}],rooms:[{id:'living',name:'客厅',purpose:'阅读和休息',polygon:[{x:0,y:0},{x:5,y:0},{x:5,y:4},{x:0,y:4}],locked:false}],openings:[],items:[],calibration:{wallId:'n',length:5,source:'ALVA-017 synthetic acceptance',confirmed:true},geography:{latitude:1.3,north:0,assumption:'synthetic'}};
const store=new AlvaStore(resolve(root,'db'));await store.init();const created=await store.create('ALVA-017 Real Chat');await store.ensureAccessCode(created.project.id);await store.mutate(created.project.id,randomUUID(),0,'seed',{},p=>{p.scene=structuredClone(scene)});const other=await store.create('Other project');const app=await buildAlva(store,{assets:false,origin});await app.listen({host:'127.0.0.1',port});
const request=async(path:string,init:RequestInit={})=>fetch(origin+path,init);let cookie='';
async function login(){const r=await request('/api/access',{method:'POST',headers:{'content-type':'application/json',origin},body:JSON.stringify({code})});assert.equal(r.status,200);cookie=(r.headers.get('set-cookie')||'').split(';')[0];assert.ok(cookie)}
async function project(){const r=await request('/api/project',{headers:{cookie}});assert.equal(r.status,200);return r.json() as Promise<any>}
async function chat(payload:any){const r=await request('/api/chat',{method:'POST',headers:{cookie,origin,'content-type':'application/json'},body:JSON.stringify(payload)});assert.equal(r.status,200);const reader=r.body!.getReader(),decoder=new TextDecoder();let buffer='',done=false,errors:string[]=[];const deltas:string[]=[],statuses:string[]=[];while(true){const chunk=await reader.read();if(chunk.done)break;buffer+=decoder.decode(chunk.value,{stream:true});let cut;while((cut=buffer.indexOf('\n\n'))>=0){const frame=buffer.slice(0,cut);buffer=buffer.slice(cut+2);const event=frame.match(/^event: (.+)$/m)?.[1],raw=frame.match(/^data: (.+)$/m)?.[1];if(!event||!raw)continue;const data=JSON.parse(raw);if(event==='delta'&&typeof data.text==='string'&&data.text)deltas.push(data.text);if(event==='status'&&data.text)statuses.push(data.text);if(event==='error')errors.push(data.error||'error');if(event==='done')done=data.ok===true}}return {done,deltas,statuses,errors}}
try{
 await login();const modelResponse=await request('/api/models',{headers:{cookie}});assert.equal(modelResponse.status,200);assert.deepEqual(await modelResponse.json(),{models:['gemini-3-flash']});
 const cross=await request(`/api/projects/${other.project.id}`,{headers:{cookie}});assert.equal(cross.status,403);const raw=await request('/api/codex',{method:'POST',headers:{cookie,origin,'content-type':'application/json'},body:'{}'});assert.equal(raw.status,404);
 const before=await project(),beforeScene=JSON.stringify(before.scene),beforeSaved=before.savedVersion;
 const textRun=await chat({requestId:randomUUID(),expectedRevision:before.revision,text:'请用两三句话概括当前客厅适合阅读休息的一个优点，并提出一个需要我确认的问题。不要修改设计，也不要提交方案。',roomId:'living',model:'gemini-3-flash'});if(!textRun.done)console.error('TEXT_RUN_DIAGNOSTIC',JSON.stringify(textRun));assert.equal(textRun.done,true);assert.deepEqual(textRun.errors,[]);assert.ok(textRun.deltas.length>=2,`text deltas=${textRun.deltas.length}`);
 const afterText=await project();assert.equal(JSON.stringify(afterText.scene),beforeScene);assert.equal(afterText.savedVersion,beforeSaved);assert.equal(afterText.messages.at(-1)?.status,'completed');
 const canvas=createCanvas(320,220),ctx=canvas.getContext('2d');ctx.fillStyle='#f4efe6';ctx.fillRect(0,0,320,220);ctx.fillStyle='#c94b40';ctx.fillRect(50,45,220,120);ctx.fillStyle='#111';ctx.font='24px sans-serif';ctx.fillText('RED SOFA',95,112);const image={mime:'image/png',data:canvas.toBuffer('image/png').toString('base64')};
 const imageRun=await chat({requestId:randomUUID(),expectedRevision:afterText.revision,text:'请只描述参考图片里最显眼的颜色和物体，不要修改设计，也不要提交方案。',roomId:'living',model:'gemini-3-flash',image});assert.equal(imageRun.done,true);assert.deepEqual(imageRun.errors,[]);assert.ok(imageRun.deltas.length>=2,`image deltas=${imageRun.deltas.length}`);
 const afterImage=await project();assert.equal(JSON.stringify(afterImage.scene),beforeScene);assert.equal(afterImage.savedVersion,beforeSaved);assert.equal(afterImage.messages.at(-1)?.status,'completed');assert.equal(JSON.stringify(afterImage).includes(image.data),false,'reference image bytes must not be persisted in project JSON');
 const result={ticket:'ALVA-017',runId,pass:true,model:'gemini-3-flash',checks:{model_catalogue:true,text_real_call:{deltas:textRun.deltas.length,statuses:textRun.statuses.length,completed:true},image_real_call:{deltas:imageRun.deltas.length,statuses:imageRun.statuses.length,completed:true},scene_unchanged:true,saved_snapshot_unchanged:true,cross_project_denied:cross.status,raw_codex_route:raw.status,image_not_persisted:true}};await writeFile(resolve(evidence,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{await app.close();await store.close();await rm(root,{recursive:true,force:true})}
