import assert from 'node:assert/strict';
import {mkdir,rm,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
import {chromium} from '@playwright/test';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import {createTopologyVersion} from '../api/topology/calibration.js';
import type {SceneData} from '../api/model.js';
import type {BuildingSceneData} from '../api/building/types.js';

const port=4277,origin=`http://127.0.0.1:${port}`,code='alva-013-browser-code-123456';
const runId=`${new Date().toISOString().replace(/[-:.]/g,'').replace('Z','Z')}-ALVA013-real-browser`,evidence=resolve('evidence',runId),data=resolve('.runtime',`${runId}-data`);
await mkdir(evidence,{recursive:true});await rm(data,{recursive:true,force:true});await mkdir(data,{recursive:true,mode:0o700});process.env.ALVA_ACCESS_CODE=code;process.env.ALVA_DATA_DIR=data;process.env.ALVA_ORIGIN=origin;

const rectangle:SceneData={walls:[
 {id:'wall-a',a:{x:0,y:0},b:{x:6,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]},{id:'wall-b',a:{x:6,y:0},b:{x:6,y:4},thickness:.15,height:2.8,structural:'unknown',evidence:[]},{id:'wall-c',a:{x:6,y:4},b:{x:0,y:4},thickness:.15,height:2.8,structural:'unknown',evidence:[]},{id:'wall-d',a:{x:0,y:4},b:{x:0,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]}
],rooms:[{id:'room-main',name:'客厅',purpose:'生活',polygon:[{x:0,y:0},{x:6,y:0},{x:6,y:4},{x:0,y:4}],locked:false}],openings:[{id:'opening-main',wallId:'wall-c',kind:'window',offset:.5,width:1.4,height:1.2,sill:.9}],items:[],calibration:{wallId:'wall-a',length:6,source:'真实 floorplan.png 现场测量',confirmed:true},geography:{latitude:31,north:0,assumption:'图上方为北'}};
const second:SceneData={...rectangle,walls:[
 {id:'wall-a',a:{x:0,y:0},b:{x:9,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]},{id:'wall-b',a:{x:9,y:0},b:{x:9,y:5},thickness:.15,height:2.8,structural:'unknown',evidence:[]},{id:'wall-c',a:{x:9,y:5},b:{x:4,y:5},thickness:.15,height:2.8,structural:'unknown',evidence:[]},{id:'wall-e',a:{x:4,y:5},b:{x:4,y:3},thickness:.15,height:2.8,structural:'unknown',evidence:[]},{id:'wall-f',a:{x:4,y:3},b:{x:0,y:3},thickness:.15,height:2.8,structural:'unknown',evidence:[]},{id:'wall-d',a:{x:0,y:3},b:{x:0,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]}
],rooms:[{id:'room-main',name:'客餐厅',purpose:'生活',polygon:[{x:0,y:0},{x:9,y:0},{x:9,y:5},{x:4,y:5},{x:4,y:3},{x:0,y:3}],locked:false}],openings:[{id:'opening-main',wallId:'wall-c',kind:'window',offset:.5,width:1.4,height:1.2,sill:.9}],calibration:{wallId:'wall-a',length:9,source:'真实 floorplan.png 现场测量',confirmed:true}};
const store=new AlvaStore(resolve(data,'db'));await store.init();const created=await store.create('ALVA-013 真实建筑视角验收');await store.ensureAccessCode(created.project.id);
async function seed(topology:SceneData){const current=await store.get(created.project.id);return store.mutate(created.project.id,randomUUID(),current.revision,'seed-building-view',{source:'真实 floorplan.png'},project=>{const version=createTopologyVersion(project,topology),building=buildingFor(topology,version.version,version.sourceFingerprint);project.topologyVersions=[version];project.confirmedTopology=version;project.scene=structuredClone(topology);project.confirmedBuilding=building;project.buildingCandidate=undefined;project.buildingState={status:'confirmed',topologyVersion:version.version,topologyFingerprint:version.sourceFingerprint,attempts:1,updatedAt:new Date().toISOString()};project.dirty=false})}
await seed(rectangle);const app=await buildAlva(store,{origin,assets:true});await app.listen({host:'127.0.0.1',port});
const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||'/home/ubuntu/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:1600,height:1000}});const consoleErrors:string[]=[];page.on('console',message=>{if(message.type()==='error')consoleErrors.push(message.text())});page.on('pageerror',error=>consoleErrors.push(error.message));const checks:Record<string,unknown>={};
try{
 await page.goto(origin);await page.getByLabel('统一验证码').fill(code);await page.getByRole('button',{name:/验证并进入/}).click();await page.getByRole('button',{name:'全屋'}).click();await page.getByTestId('building-view').waitFor();await page.getByTestId('building-controls').waitFor();checks.login=true;
 const canvas=page.getByTestId('building-canvas').locator('canvas');assert.equal(await canvas.count(),1);const initial=await page.evaluate(()=>{const host=document.querySelector('[data-testid="building-canvas"]') as any,v=host.alvaView;return {x:v.camera.position.x,y:v.camera.position.y,z:v.camera.position.z,target:v.controls.target.toArray()}});assert.ok(initial.x>initial.target[0]&&initial.y>initial.target[1]);checks.auto_overview=true;
 await page.getByTestId('building-cutaway').click();checks.cutaway=await page.evaluate(()=>{const host=document.querySelector('[data-testid="building-canvas"]') as any;return host.alvaView.wallMeshes.every((mesh:any)=>mesh.material.clippingPlanes.length===1)})===true;await page.screenshot({path:resolve(evidence,'cutaway.png'),fullPage:true});
 await page.getByRole('button',{name:'完整墙体'}).click();const roomSelect=page.getByLabel('建筑房间视角');await roomSelect.selectOption('room-main');const roomCamera=await page.evaluate(()=>{const host=document.querySelector('[data-testid="building-canvas"]') as any,v=host.alvaView;return {x:v.camera.position.x,z:v.camera.position.z}});assert.ok(roomCamera.x>.2&&roomCamera.x<5.8&&roomCamera.z>.2&&roomCamera.z<3.8);checks.room_view_safe=true;await page.screenshot({path:resolve(evidence,'room-view.png'),fullPage:true});
 await page.getByTestId('building-reset').click();const box=await canvas.boundingBox();assert.ok(box);const before=await page.evaluate(()=>{const v=(document.querySelector('[data-testid="building-canvas"]') as any).alvaView;return v.camera.position.toArray()});await page.mouse.move(box!.x+box!.width/2,box!.y+box!.height/2);await page.mouse.down();await page.mouse.move(box!.x+box!.width/2+90,box!.y+box!.height/2+20);await page.mouse.up();await page.mouse.wheel(0,-260);await page.waitForTimeout(120);const after=await page.evaluate(()=>{const v=(document.querySelector('[data-testid="building-canvas"]') as any).alvaView;return v.camera.position.toArray()});assert.notDeepEqual(after,before);checks.rotate_zoom=true;
 await page.getByTestId('building-reset').click();await assert.equal(await roomSelect.inputValue(),'');const reset=await page.evaluate(()=>{const v=(document.querySelector('[data-testid="building-canvas"]') as any).alvaView;return v.controls.target.toArray()});assert.deepEqual(reset,initial.target);checks.reset=true;
 await page.waitForTimeout(250);const picked=await page.evaluate(()=>(document.querySelector('[data-testid="building-canvas"]') as any).alvaView.selectById('floor-room-main'));await page.waitForTimeout(100);checks.entity_trace=!!picked&&await page.locator('.building-selection').count()===1;
 await page.reload();await page.getByRole('button',{name:'全屋'}).click();await page.getByTestId('building-view').waitFor();checks.reload=await page.getByTestId('building-reset').count()===1;
 await seed(second);await page.reload();await page.getByRole('button',{name:'全屋'}).click();await page.getByTestId('building-view').waitFor();const secondCamera=await page.evaluate(()=>{const v=(document.querySelector('[data-testid="building-canvas"]') as any).alvaView;return {x:v.camera.position.x,target:v.controls.target.toArray()}});assert.notEqual(secondCamera.x,initial.x);checks.second_layout_autoframe=true;await page.screenshot({path:resolve(evidence,'second-layout.png'),fullPage:true});
 const unexpected=consoleErrors.filter(error=>!/(401|422)/.test(error));checks.console_errors=unexpected.length===0;const result={ticket:'ALVA-013',runId,pass:Object.values(checks).every(value=>value===true)&&unexpected.length===0,checks,consoleErrors,source:{fixture:'真实 floorplan.png 的结构化确认拓扑'}};await writeFile(resolve(evidence,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));if(!result.pass)process.exitCode=1;
}finally{await page.close();await browser.close();await app.close();await store.close();await rm(data,{recursive:true,force:true})}

function buildingFor(topology:SceneData,version:number,fingerprint:string):BuildingSceneData{const components:BuildingSceneData['components']=[];for(const room of topology.rooms){const xs=room.polygon.map(p=>p.x),zs=room.polygon.map(p=>p.y);components.push({id:`floor-${room.id}`,kind:'floor',topologyId:room.id,position:{x:(Math.min(...xs)+Math.max(...xs))/2,y:0,z:(Math.min(...zs)+Math.max(...zs))/2},size:{x:Math.max(...xs)-Math.min(...xs),y:.08,z:Math.max(...zs)-Math.min(...zs)},rotation:0,material:'floor',color:'#c9b79e'})}for(const wall of topology.walls){const dx=wall.b.x-wall.a.x,dy=wall.b.y-wall.a.y,len=Math.hypot(dx,dy),angle=Math.atan2(dy,dx);components.push({id:`wall-${wall.id}`,kind:'wall',topologyId:wall.id,position:{x:(wall.a.x+wall.b.x)/2,y:wall.height/2,z:(wall.a.y+wall.b.y)/2},size:{x:len,y:wall.height,z:wall.thickness},rotation:angle,material:'plaster',color:'#ddd8ca'})}for(const opening of topology.openings){const wall=topology.walls.find(w=>w.id===opening.wallId)!;const len=Math.hypot(wall.b.x-wall.a.x,wall.b.y-wall.a.y),angle=Math.atan2(wall.b.y-wall.a.y,wall.b.x-wall.a.x),x=wall.a.x+Math.cos(angle)*opening.offset*len,z=wall.a.y+Math.sin(angle)*opening.offset*len,base={position:{x,y:opening.sill+opening.height/2,z},rotation:angle,topologyId:opening.id};components.push({id:`frame-${opening.id}`,kind:'window-frame',...base,size:{x:opening.width,y:opening.height,z:.12},material:'wood',color:'#8b6b4a'});components.push({id:`glass-${opening.id}`,kind:'glass',...base,size:{x:opening.width,y:opening.height,z:.03},material:'glass',color:'#9fc4cf'})}return {units:'meters',topologyVersion:version,topologyFingerprint:fingerprint,components,camera:{position:{x:10,y:8,z:12},target:{x:3,y:1,z:2}}}}
