import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdir,rm,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {chromium} from '@playwright/test';
import {createCanvas} from '@napi-rs/canvas';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import type {SceneData} from '../api/model.js';

const runId=process.env.ALVA_RUN_ID||`${new Date().toISOString().replace(/[-:.]/g,'')}-ALVA017-browser`,port=Number(process.env.ALVA_PORT||4217),origin=`http://127.0.0.1:${port}`,root=resolve('.runtime',runId),evidence=resolve('evidence',runId),code='alva017-browser-code-123456';
assert.ok(process.env.OPENAI_API_KEY,'OPENAI_API_KEY must be supplied by caller');process.env.ALVA_ACCESS_CODE=code;process.env.ALVA_AGENT_DIR=resolve(root,'agent');await rm(root,{recursive:true,force:true});await mkdir(root,{recursive:true,mode:0o700});await mkdir(evidence,{recursive:true});
const scene:SceneData={walls:[{id:'n',a:{x:0,y:0},b:{x:5,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]}],rooms:[{id:'living',name:'客厅',purpose:'阅读和休息',polygon:[{x:0,y:0},{x:5,y:0},{x:5,y:4},{x:0,y:4}],locked:false}],openings:[],items:[],calibration:{wallId:'n',length:5,source:'ALVA-017 browser fixture',confirmed:true},geography:{latitude:1.3,north:0,assumption:'synthetic'}};
const store=new AlvaStore(resolve(root,'db'));await store.init();const created=await store.create('ALVA-017 Browser');await store.ensureAccessCode(created.project.id);await store.mutate(created.project.id,randomUUID(),0,'seed',{},p=>{p.scene=structuredClone(scene)});const app=await buildAlva(store,{origin});await app.listen({host:'127.0.0.1',port});
const executablePath=process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||'/home/ubuntu/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',browser=await chromium.launch({headless:true,executablePath,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']}),page=await browser.newPage({viewport:{width:1600,height:1000}});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
try{
 await page.goto(origin);await page.getByLabel('统一验证码').fill(code);await page.getByRole('button',{name:/验证并进入/}).click();await page.getByText('ALVA-017 Browser',{exact:true}).waitFor();errors.length=0;
 assert.equal(await page.locator('aside.chat').count(),1);assert.equal(await page.locator('section.stage').count(),1);assert.equal(await page.locator('aside.details').count(),1);assert.ok(await page.locator('[class*="assistant"]').count()>=0);
 const model=page.getByLabel('咨询模型');await page.waitForFunction(()=>document.querySelector<HTMLSelectElement>('select[aria-label="咨询模型"]')?.value==='gemini-3-flash');assert.deepEqual(await model.locator('option').allTextContents(),['gemini-3-flash']);assert.equal(await model.inputValue(),'gemini-3-flash');
 const before=await (await page.request.get(`${origin}/api/project`)).json(),sceneJson=JSON.stringify(before.scene),saved=before.savedVersion;
 const composer=page.getByLabel('咨询消息');await composer.fill('请概括这个客厅适合阅读休息的一个优点，并问我一个澄清问题。不要修改设计。');const assistantBefore=await page.locator('.message.assistant').count();await page.getByRole('button',{name:'发送 ↑'}).click();await page.getByRole('button',{name:'取消'}).waitFor();await page.locator('.message.assistant').nth(assistantBefore).waitFor({state:'visible',timeout:120000});await page.getByRole('button',{name:'发送 ↑'}).waitFor({state:'visible',timeout:120000});const textReply=(await page.locator('.message.assistant').nth(assistantBefore).innerText()).trim();assert.ok(textReply.length>4);
 const afterText=await (await page.request.get(`${origin}/api/project`)).json();assert.equal(JSON.stringify(afterText.scene),sceneJson);assert.equal(afterText.savedVersion,saved);
 const canvas=createCanvas(320,220),ctx=canvas.getContext('2d');ctx.fillStyle='#f4efe6';ctx.fillRect(0,0,320,220);ctx.fillStyle='#c94b40';ctx.fillRect(50,45,220,120);ctx.fillStyle='#111';ctx.font='24px sans-serif';ctx.fillText('RED SOFA',95,112);const png=canvas.toBuffer('image/png');const files=page.locator('input[type="file"]');await files.nth(1).setInputFiles({name:'red-sofa.png',mimeType:'image/png',buffer:png});await page.getByText('已附参考图').waitFor();await composer.fill('请描述参考图片里最显眼的颜色和物体，不要修改设计。');const imageAssistantBefore=await page.locator('.message.assistant').count();await page.getByRole('button',{name:'发送 ↑'}).click();await page.getByRole('button',{name:'取消'}).waitFor();await page.locator('.message.assistant').nth(imageAssistantBefore).waitFor({state:'visible',timeout:120000});await page.getByRole('button',{name:'发送 ↑'}).waitFor({state:'visible',timeout:120000});const imageReply=(await page.locator('.message.assistant').nth(imageAssistantBefore).innerText()).trim();assert.ok(imageReply.length>4);
 const afterImage=await (await page.request.get(`${origin}/api/project`)).json();assert.equal(JSON.stringify(afterImage.scene),sceneJson);assert.equal(afterImage.savedVersion,saved);assert.equal(JSON.stringify(afterImage).includes(png.toString('base64')),false);assert.deepEqual(errors,[]);
 await page.screenshot({path:resolve(evidence,'chat-workspace.png'),fullPage:true});const result={ticket:'ALVA-017',runId,pass:true,checks:{assistant_ui_three_columns:true,model_option:'gemini-3-flash',text_ui_real_call:true,image_ui_real_call:true,loading_state_visible:true,completed_state_visible:true,scene_unchanged:true,image_not_persisted:true,console_errors:errors}};await writeFile(resolve(evidence,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{await browser.close();await app.close();await store.close();await rm(root,{recursive:true,force:true})}
