import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdir,rm,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import type {SceneData} from '../api/model.js';

const runId=process.env.ALVA_RUN_ID||`${Date.now()}-ALVA015-round1`,port=Number(process.env.ALVA_PORT||4215),origin=`http://127.0.0.1:${port}`,root=resolve('.runtime',runId),evidence=resolve('evidence',runId),code='alva015-real-code-123456';
assert.ok(process.env.OPENAI_API_KEY);process.env.ALVA_ACCESS_CODE=code;process.env.ALVA_AGENT_DIR=resolve(root,'agent');await rm(root,{recursive:true,force:true});await mkdir(root,{recursive:true,mode:0o700});await mkdir(evidence,{recursive:true});
const scene:SceneData={walls:[{id:'n',a:{x:0,y:0},b:{x:5,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]}],rooms:[{id:'living',name:'客厅',purpose:'生活',polygon:[{x:0,y:0},{x:5,y:0},{x:5,y:4},{x:0,y:4}],locked:false}],openings:[],items:[],calibration:null,geography:{latitude:1.3,north:0,assumption:'synthetic'}};
const store=new AlvaStore(resolve(root,'db'));await store.init();const created=await store.create('ALVA-015 Round1');await store.ensureAccessCode(created.project.id);await store.mutate(created.project.id,randomUUID(),0,'seed',{},p=>{p.scene=structuredClone(scene)});const app=await buildAlva(store,{assets:false,origin});await app.listen({host:'127.0.0.1',port});let cookie='';
async function json(path:string,method='GET',body?:any){const r=await fetch(origin+path,{method,headers:{...(cookie?{cookie}:{}),...(method!=='GET'?{origin,'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()}}
async function chat(body:any){const r=await fetch(origin+'/api/chat',{method:'POST',headers:{cookie,origin,'content-type':'application/json'},body:JSON.stringify(body)});assert.equal(r.status,200);const reader=r.body!.getReader(),decoder=new TextDecoder();let buf='';let project:any=null;const deltas:string[]=[];let done=false;while(true){const c=await reader.read();if(c.done)break;buf+=decoder.decode(c.value,{stream:true});let i;while((i=buf.indexOf('\n\n'))>=0){const frame=buf.slice(0,i);buf=buf.slice(i+2);const event=frame.match(/^event: (.+)$/m)?.[1],raw=frame.match(/^data: (.+)$/m)?.[1];if(!raw)continue;const d=JSON.parse(raw);if(event==='project')project=d;if(event==='delta'&&d.text)deltas.push(d.text);if(event==='error')throw new Error(d.error);if(event==='done')done=d.ok===true}}assert.ok(done);return {project,deltas}}
try{
 const login=await json('/api/access','POST',{code});assert.equal(login.status,200);cookie=(await fetch(origin+'/api/access',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({code})})).headers.get('set-cookie')!.split(';')[0];const models=await json('/api/models');const model=models.data.models[0];assert.ok(model);
 let p=(await json('/api/project')).data;const quote='我平时主要在客厅读书和休息';const first=await chat({requestId:randomUUID(),expectedRevision:p.revision,text:`针对Q25，这句话就是我的回答：“${quote}”。请提取为待确认答案，不要直接写入问卷。`,roomId:'living',model});assert.ok(first.deltas.length>=2);p=first.project;assert.equal(p.answers.some((a:any)=>a.questionId==='Q25'),false);const pending=p.pendingAnswers?.find((a:any)=>a.questionId==='Q25'&&a.roomId==='living');assert.ok(pending);assert.equal(pending.quote,quote);
 const confirmed=await json('/api/pending-answers/confirm','POST',{requestId:randomUUID(),expectedRevision:p.revision,id:pending.id,confirmed:true});assert.equal(confirmed.status,200);p=confirmed.data;const a=p.answers.find((a:any)=>a.questionId==='Q25'&&a.roomId==='living');assert.equal(a.text,pending.text);const ev=p.evidence.find((e:any)=>e.id===a.evidenceId);assert.equal(ev.quote,quote);assert.equal(ev.source,'chat');
 const duplicate=await json('/api/pending-answers/confirm','POST',{requestId:randomUUID(),expectedRevision:p.revision,id:pending.id,confirmed:true});assert.equal(duplicate.status,422);
 const manualToken='MANUAL-ALVA015-9284';const manual=await json('/api/answers','POST',{requestId:randomUUID(),expectedRevision:p.revision,answer:{questionId:'Q01',roomId:null,text:manualToken,state:'answered',locked:false,confirmed:true}});assert.equal(manual.status,200);p=manual.data;const second=await chat({requestId:randomUUID(),expectedRevision:p.revision,text:'读取项目快照，Q01已经确认的回答是什么？请在回复中完整包含该回答。',roomId:'living',model});assert.ok(second.deltas.length>=2);assert.ok(second.deltas.join('').includes(manualToken),second.deltas.join(''));
 const result={ticket:'ALVA-015',runId,pass:true,model,checks:{real_codex_pending:true,first_deltas:first.deltas.length,unconfirmed_did_not_write:true,exact_quote_preserved:true,evidence_source_chat:true,duplicate_confirm_status:duplicate.status,manual_answer_visible_to_later_chat:true,second_deltas:second.deltas.length}};await writeFile(resolve(evidence,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{await app.close();await store.close();await rm(root,{recursive:true,force:true})}
