import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdir,rm,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import type {SceneData} from '../api/model.js';
const runId=process.env.ALVA_RUN_ID||`${Date.now()}-ALVA016-round1`,port=Number(process.env.ALVA_PORT||4216),origin=`http://127.0.0.1:${port}`,root=resolve('.runtime',runId),evidenceDir=resolve('evidence',runId),code='alva016-real-code-123456',goodBase=process.env.OPENAI_BASE_URL,goodKey=process.env.OPENAI_API_KEY;assert.ok(goodKey);
process.env.ALVA_ACCESS_CODE=code;process.env.ALVA_AGENT_DIR=resolve(root,'agent');await rm(root,{recursive:true,force:true});await mkdir(root,{recursive:true,mode:0o700});await mkdir(evidenceDir,{recursive:true});
const scene:SceneData={walls:[{id:'n',a:{x:0,y:0},b:{x:6,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]}],rooms:[{id:'living',name:'客厅',purpose:'生活',polygon:[{x:0,y:0},{x:3,y:0},{x:3,y:3},{x:0,y:3}],locked:false},{id:'study',name:'书房',purpose:'工作',polygon:[{x:3,y:0},{x:6,y:0},{x:6,y:3},{x:3,y:3}],locked:false}],openings:[],items:[],calibration:null,geography:{latitude:1.3,north:0,assumption:'synthetic'}};
const store=new AlvaStore(resolve(root,'db'));await store.init();const created=await store.create('ALVA-016 Round1');await store.ensureAccessCode(created.project.id);let seeded=await store.mutate(created.project.id,randomUUID(),0,'seed',{},p=>{p.scene=structuredClone(scene);p.evidence=[{id:'old',quote:'旧信息：喜欢安静',source:'manual',createdAt:new Date().toISOString()},{id:'new',quote:'新增信息：书房偶尔也要视频会议',source:'manual',roomId:'study',createdAt:new Date().toISOString()}];p.lastAnalysisEvidence=1;(p as any).questionCards=[{questionId:'Q25',reason:'已有待处理问题',roomId:'living'}]});const app=await buildAlva(store,{assets:false,origin});await app.listen({host:'127.0.0.1',port});let cookie='';
async function call(path:string,body?:any){const r=await fetch(origin+path,{method:body?'POST':'GET',headers:{...(cookie?{cookie}:{}),...(body?{origin,'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});let data:any={};try{data=await r.json()}catch{}return {status:r.status,data}}
try{let r=await call('/api/access',{code});assert.equal(r.status,200);const login=await fetch(origin+'/api/access',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({code})});cookie=login.headers.get('set-cookie')!.split(';')[0];
 process.env.OPENAI_BASE_URL='http://127.0.0.1:1/v1';r=await call('/api/analyze',{requestId:randomUUID(),expectedRevision:seeded.revision});assert.ok(r.status>=500);let afterFail=await store.get(created.project.id);assert.equal(afterFail.lastAnalysisEvidence,1);assert.equal(afterFail.revision,seeded.revision);
 if(goodBase)process.env.OPENAI_BASE_URL=goodBase;else delete process.env.OPENAI_BASE_URL;process.env.OPENAI_API_KEY=goodKey!;r=await call('/api/analyze',{requestId:randomUUID(),expectedRevision:afterFail.revision});assert.equal(r.status,200);let analyzed=r.data;assert.equal(analyzed.lastAnalysisEvidence,analyzed.evidence.length);const cards=(analyzed as any).questionCards||[],keys=cards.map((c:any)=>`${c.questionId}:${c.roomId??'project'}`);assert.equal(new Set(keys).size,keys.length);assert.equal(keys.filter((k:string)=>k==='Q25:living').length,1);
 const revision=analyzed.revision;r=await call('/api/analyze',{requestId:randomUUID(),expectedRevision:revision});assert.equal(r.status,200);assert.equal(r.data.revision,revision);assert.equal(r.data.lastAnalysisEvidence,analyzed.lastAnalysisEvidence);
 const result={ticket:'ALVA-016',runId,pass:true,checks:{failure_keeps_cursor:true,retry_succeeds:true,new_evidence_only_cursor:analyzed.lastAnalysisEvidence,repeated_exit_no_revision_change:true,no_duplicate_question_scope:true,cards:keys}};await writeFile(resolve(evidenceDir,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{if(goodBase)process.env.OPENAI_BASE_URL=goodBase;else delete process.env.OPENAI_BASE_URL;if(goodKey)process.env.OPENAI_API_KEY=goodKey;await app.close();await store.close();await rm(root,{recursive:true,force:true})}
