import {runCodex} from '../api/codex.js';
import {appendFileSync} from 'node:fs';
/** Real living MCP and browser acceptance on an existing isolated project. */
import assert from 'node:assert/strict';
import {resolve,basename} from 'node:path';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {createHash,randomUUID} from 'node:crypto';
import {createServer} from 'node:net';
import {unzipSync,strFromU8} from 'fflate';
import {chromium} from '@playwright/test';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
const root=resolve(process.argv[2]||''),step=process.argv[3];assert.ok(root.startsWith(resolve('.runtime')+'/')&&basename(root).includes('-ALVA066-'));
assert.ok(['living-reread','purpose-model','purpose-confirm','reference-model','ui-view','compact','diagnose','answer','retry-answer','adopt','style-model','style-confirm','context-model','context-confirm','review-model','save-model','save-confirm','delivery','cancel-delivery','floor-return','reopen-model','reopen-confirm'].includes(step));
const run=new Date().toISOString().replace(/[-:.]/g,'')+'-ALVA066-'+step,out=resolve('evidence',run);await mkdir(out,{recursive:true});
process.env.ALVA_AGENT_DIR=resolve(root,'agents');process.env.ALVA_DATA_DIR=resolve(root,'data');process.env.ALVA_UPLOAD_DIR=resolve(root,'uploads');process.env.OPENAI_API_KEY||=process.env.NEWAPI_KEY;process.env.OPENAI_MODEL='gemini-3.1-flash-lite';
const store=new AlvaStore(resolve(root,'db'));await store.init();const rows=(await store.db.query<{id:string}>('SELECT id FROM alva_projects')).rows;assert.equal(rows.length,1);const id=rows[0].id;
const probe=createServer();await new Promise<void>(r=>probe.listen(0,'127.0.0.1',r));const addr=probe.address();assert.ok(addr&&typeof addr==='object');const port=addr.port;await new Promise<void>((r,j)=>probe.close(e=>e?j(e):r()));const origin=`http://127.0.0.1:${port}`;process.env.ALVA_PORT=String(port);
const app=await buildAlva(store,{origin,chatCodex:input=>runCodex({...input,onEvent:event=>{appendFileSync(resolve(root,run+'-protocol.ndjson'),JSON.stringify(event)+'\n',{mode:0o600});input.onEvent?.(event)}})});await app.listen({host:'127.0.0.1',port});const access=await store.issueInternalSession(id);const headers={'Content-Type':'application/json',cookie:`alva_session=${access.token}`,origin};
let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;const checks:Record<string,unknown>={};
async function model(text:string,names:string[],image?:{mime:string;data:string}){const p=await store.get(id);const response=await fetch(origin+'/api/chat',{method:'POST',headers,body:JSON.stringify({requestId:randomUUID(),expectedRevision:p.revision,text,...(image?{image}:{}),roomId:null,model:'gemini-3.1-flash-lite'}),signal:AbortSignal.timeout(150_000)});const body=await response.text();await writeFile(resolve(root,run+'-sse.txt'),body);assert.equal(response.status,200);const latest=await store.get(id),assistant=latest.messages.slice(p.messages.length).find(m=>m.role==='assistant');assert.equal(assistant?.status,'completed',assistant?.text);for(const name of names)assert.ok(assistant?.toolCalls?.some(t=>t.name===name&&!t.isError),`missing ${name}: ${assistant?.text}`);checks.toolCalls=assistant?.toolCalls;return latest}
async function page(){browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:1280,height:800}});page.setDefaultTimeout(30_000);await page.context().addCookies([{name:'alva_session',value:access.token,url:origin,httpOnly:true,sameSite:'Strict'}]);await page.goto(origin);await page.getByLabel('咨询消息').waitFor();return page}
try{
 const before=await store.get(id);assert.ok(before.name.startsWith('ALVA-066 '));const initial=await store.chatState(id);
 if(step==='living-reread'){
  assert.equal(initial.active,'living');assert.equal(initial.threads.living.threadId,'01a0da7b-a43f-7530-9c79-d217333cf2b3');const handoff=initial.handoffs.filter(h=>h.to==='living').at(-1)!;assert.match(handoff.summary,/失效/);assert.ok(initial.threads.living.deliveredIds.includes(handoff.id));
  await model('请必须通过 mcp_call_tool({name:"get_snapshot",arguments:{}}) 实际读取当前快照，再说明重新修改拓扑后哪些旧家具候选、样式和审查已经失效；只讨论，不恢复旧设计或修改项目。',['get_snapshot']);assert.deepEqual((await store.get(id)).scene,before.scene);checks.originalLivingThreadResumed=true;checks.invalidationHandoff=handoff;
 }
 if(step==='purpose-model'){
  const room=before.scene!.rooms.find(r=>/客|living/i.test(r.name))||before.scene!.rooms[0];await model(`请通过propose_room_purpose为房间 ${room.id} 提出“阅读与会客”用途确认卡，这是隔离验收合成需求。不要替我确认，也不要改变家具。`,['propose_room_purpose']);assert.deepEqual((await store.get(id)).scene,before.scene);
 }
 if(step==='purpose-confirm'){
  const p=await page(),response=p.waitForResponse(r=>r.url().endsWith('/api/chat/actions/confirm'));await p.locator('[data-action-kind="confirm_purpose"] button:not([disabled])').filter({hasText:/^确认/}).click();const r=await response;assert.equal(r.status(),200,await r.text());const current=await store.get(id);assert.ok(current.scene!.rooms.some(r=>r.purpose==='阅读与会客'));assert.deepEqual(current.scene!.items,before.scene!.items);await p.reload();await p.getByLabel('咨询消息').waitFor();checks.purposeOnly=true;
 }
 if(step==='reference-model'){
  const data=(await readFile('references/room-study-handoff/public/floorplan.png')).toString('base64');await model('这是隔离验收参考图片，我喜欢图中的浅色背景，仅记录视觉偏好，不把它作为尺寸或材料性能依据。请通过 propose_reference_preferences 提出待确认候选，不代我确认。',['propose_reference_preferences'],{mime:'image/png',data});assert.deepEqual((await store.get(id)).scene,before.scene);const batches=await (await fetch(origin+'/api/references',{headers})).json();checks.referenceBatches=batches;
 }
 if(step==='ui-view'){
  const p=await page(),room=before.scene!.rooms.find(r=>/客|living/i.test(r.name))||before.scene!.rooms[0];const receipts:{status:number;body:any}[]=[];p.on('response',r=>{if(r.url().endsWith('/api/chat/ui-receipts'))receipts.push({status:r.status(),body:r.request().postDataJSON()})});
  await p.getByLabel('咨询消息').fill(`请实际调用 set_view 将太阳时设为9、年内日期设为100，然后聚焦房间 ${room.id}。逐项等待页面 applied 回执，不改变布局或保存。`);
  const response=p.waitForResponse(r=>r.url().endsWith('/api/chat')&&r.request().method()==='POST',{timeout:150_000});await p.getByRole('button',{name:'发送 ↑',exact:true}).click();const r=await response;assert.equal(r.status(),200);await r.finished();
  const current=await store.get(id),assistant=current.messages.slice(before.messages.length).find(m=>m.role==='assistant');assert.equal(assistant?.status,'completed',assistant?.text);assert.ok(assistant?.toolCalls?.filter(t=>t.name==='set_view'&&!t.isError).length!>=2);
  for(const kind of ['sunlight','focus_room'])assert.ok(receipts.some(r=>r.status===200&&r.body.status==='applied'&&r.body.applied.kind===kind));assert.equal(await p.getByLabel('太阳时').inputValue(),'9');assert.equal(await p.getByLabel('季节日期').inputValue(),'100');assert.deepEqual(current.scene,before.scene);assert.equal(current.savedVersion,before.savedVersion);checks.receipts=receipts;await p.screenshot({path:resolve(out,'ui-applied.png')});
 }
 if(step==='compact'){const threadId=initial.threads.living.threadId;assert.ok(threadId);const events:string[]=[];const actual=await runCodex({compactOnly:true,text:'',model:'gemini-3.1-flash-lite',timeoutMs:300_000,session:{key:`${id}:living`,threadId,onThread:async current=>{assert.equal(current,threadId)}},onEvent:(event:any)=>{appendFileSync(resolve(root,run+'-protocol.ndjson'),JSON.stringify(event)+'\n',{mode:0o600});if(event.method==='item/completed')events.push(event.params.item?.type)}});assert.equal(actual,threadId);assert.ok(events.includes('contextCompaction'));assert.equal((await store.get(id)).revision,before.revision);checks.sameThreadCompacted=true}
 if(step==='diagnose'){await writeFile(resolve(root,run+'-project.json'),JSON.stringify(before,null,2));console.log(JSON.stringify(before.messages.slice(-2).map(m=>({role:m.role,text:m.text,status:m.status,toolCalls:m.toolCalls}))));checks.jobs=before.answerRecommendations}
 if(step==='context-model')await model('我的生活习惯是每天晚上在客厅阅读半小时。请引用我这句话的真实来源，通过MCP propose_user_context 将其分类为habits的待确认条目；不要替我确认。这是隔离验收的合成生活信息。',['propose_user_context']);
 if(step==='context-confirm'){const p=await page(),response=p.waitForResponse(r=>r.url().endsWith('/api/user-context/decide'));await p.getByRole('button',{name:'确认分类',exact:true}).last().click();assert.equal((await response).status(),200);assert.ok((await store.get(id)).userContextEntries?.some(e=>e.status==='confirmed'));await p.screenshot({path:resolve(out,'confirmed-context.png')})}
 if(step==='review-model')await model('请通过MCP read_user_context实际读取当前Markdown，然后run_layout_review复核；没有待确认取舍时request_save出示保存卡，有待确认取舍时据实解释并停止，不代我确认。',['read_user_context','run_layout_review','request_save']);
 if(step==='save-model')await model('请读取最新项目和当前审查，以服务端保存门禁为准调用 request_save 出示保存确认卡。保留 needs_information 与全部审查限制，不把信息缺口称为已解决；现在不执行保存，由我在页面确认。',['request_save']);
 if(step==='save-confirm'){const p=await page(),response=p.waitForResponse(r=>r.url().endsWith('/api/chat/actions/confirm'));await p.locator('[data-action-kind="save_design"] button:not([disabled])').filter({hasText:/^确认/}).click();const r=await response;assert.equal(r.status(),200,await r.text());const current=await store.get(id);assert.equal(current.savedVersion,before.savedVersion+1);assert.ok(current.layoutReviewAdoption);await p.reload();await p.getByLabel('咨询消息').waitFor();assert.equal((await store.get(id)).savedVersion,current.savedVersion);checks.savedVersion=current.savedVersion;checks.adoption=current.layoutReviewAdoption;await p.screenshot({path:resolve(out,'saved.png')})}
 if(step==='retry-answer'){
  const p=await page(),response=p.waitForResponse(r=>r.url().endsWith('/api/chat')&&r.request().method()==='POST',{timeout:150_000});await p.getByRole('button',{name:'重试家具建议',exact:true}).last().click();const r=await response;assert.equal(r.status(),200);await r.finished();const current=await store.get(id),job=current.answerRecommendations!.at(-1)!;checks.job=job;
  assert.equal(job.id,before.answerRecommendations!.at(-1)!.id);assert.equal(job.status,'completed');assert.ok(job.proposalIds?.length);assert.ok(current.messages.slice(before.messages.length).some(m=>m.toolCalls?.some(t=>t.name==='suggest_furniture'&&!t.isError)));assert.deepEqual(current.scene?.items,before.scene?.items);checks.pendingOwner=true;await p.screenshot({path:resolve(out,'automatic-furniture-retry.png')});
 }
 if(step==='adopt'){
  const proposal=before.proposals.find(v=>v.status==='proposed');assert.ok(proposal);const p=await page(),card=p.getByTestId('proposal-card-'+proposal.id);await card.getByTestId('proposal-3d-'+proposal.id).waitFor();await p.screenshot({path:resolve(out,'furniture-preview.png')});const response=p.waitForResponse(r=>r.url().endsWith('/api/proposals/accept'));await card.getByRole('button',{name:'仅确认勾选范围',exact:true}).click();const adopted=await response;assert.equal(adopted.status(),200,await adopted.text());const current=await store.get(id);assert.ok(current.scene!.items.length>before.scene!.items.length);assert.equal(current.proposals.find(v=>v.id===proposal.id)?.status,'accepted');await p.reload();await p.getByLabel('咨询消息').waitFor();assert.deepEqual((await store.get(id)).scene?.items,current.scene?.items);checks.adoptedFurniture=current.scene!.items.map(i=>({id:i.id,assetId:i.assetId,roomId:i.roomId}));
 }
 if(step==='style-model'){assert.ok(before.scene);const room=before.scene.rooms.find(r=>/客|living/i.test(r.name))||before.scene.rooms[0];await model(`请为房间 ${room.id} 提出温暖简约样式候选：墙面 #e8dcc8 paint；地面 #a87b51 wood。使用 propose_room_style，读取最新revision，不确认不改几何。`,['propose_room_style']);checks.roomId=room.id}
 if(step==='style-confirm'){const p=await page(),geometry=JSON.stringify(before.scene),lastCard=p.locator('[data-style-candidate]').last(),candidateId=await lastCard.getAttribute('data-style-candidate'),card=p.locator(`[data-style-candidate="${candidateId}"]`);await card.getByRole('button',{name:'在画面预览'}).click();await p.getByRole('button',{name:'平面',exact:true}).click();await p.screenshot({path:resolve(out,'style-2d.png')});await p.getByRole('button',{name:'全屋',exact:true}).click();await p.locator('[data-testid="building-canvas"]').waitFor();await p.screenshot({path:resolve(out,'style-3d.png')});const response=p.waitForResponse(r=>r.url().includes('/api/room-styles/')&&r.request().method()==='POST');await card.getByRole('button',{name:'确认采用样式'}).click();const decided=await response;assert.equal(decided.status(),200,await decided.text());await card.waitFor({state:'hidden'});await p.reload();await p.getByLabel('咨询消息').waitFor();const current=await store.get(id);assert.equal(JSON.stringify(current.scene),geometry);assert.ok(Object.values(current.roomStyles||{}).some(s=>s.floor.color==='#a87b51'));checks.geometryUnchanged=true}
 if(step==='answer'){
  const p=await page(),room=before.scene!.rooms.find(r=>/客|living/i.test(r.name))||before.scene!.rooms[0];const intake=await (await fetch(origin+'/api/intake',{headers})).json();const q=intake.questions.find((q:any)=>q.scope==='room'&&!q.conditional);assert.ok(q);
  await p.getByRole('button',{name:'聊聊你的家',exact:true}).click();await p.getByLabel('选择问卷题目').selectOption(q.id);await p.getByLabel('问卷房间').selectOption(room.id);await p.getByLabel('问卷自由补充').fill(before.scene!.items.length?'现有阅读椅保留，希望再增加一张许可家具库里的边桌放书，放在这个房间的合法空位。仅为隔离验收的合成生活需求。':'每天晚上在这个房间阅读，希望有一把许可家具库里的阅读椅。仅为隔离验收的合成生活习惯。');
  const saved=p.waitForResponse(r=>r.url().endsWith('/api/intake/progress'));await p.getByRole('button',{name:'保存进度',exact:true}).click();assert.equal((await saved).status(),200);assert.equal((await store.get(id)).answerRecommendations?.length||0,before.answerRecommendations?.length||0,'Draft must not trigger furniture suggestions');checks.draftNoRecommendation=true;
  const confirmed=p.waitForResponse(r=>r.url().endsWith('/api/intake/confirm'));await p.getByRole('button',{name:'确认此回答',exact:true}).click();const result=await confirmed;assert.equal(result.status(),200,await result.text());await browser!.close();browser=undefined;
  const deadline=Date.now()+150_000;let current=await store.get(id);while(Date.now()<deadline){const job=current.answerRecommendations?.at(-1);if(job&&['completed','failed','invalidated'].includes(job.status))break;await new Promise(r=>setTimeout(r,500));current=await store.get(id)}
  const job=current.answerRecommendations?.at(-1);checks.job=job;assert.ok(current.messages.slice(before.messages.length).some(m=>m.toolCalls?.some(t=>t.name==='suggest_furniture'&&!t.isError)));assert.ok(current.proposals.some(v=>v.status==='proposed'&&v.evidenceIds.includes(job!.evidenceId)));assert.deepEqual(current.scene?.items,before.scene?.items,'Suggestion alone must not adopt furniture');checks.awaitingOwner=true;
 }
 if(step==='cancel-delivery'){
  assert.ok(before.savedVersion);const response=await fetch(origin+'/api/chat',{method:'POST',headers,body:JSON.stringify({requestId:randomUUID(),expectedRevision:before.revision,text:`请实际调用 prepare_delivery 生成保存版本 ${before.savedVersion} 的交付包。`,roomId:null,model:'gemini-3.1-flash-lite'}),signal:AbortSignal.timeout(150_000)});assert.equal(response.status,200);const reader=response.body!.getReader(),decoder=new TextDecoder();let body='',cancelled=false;
  for(;;){const {done,value}=await reader.read();if(done)break;body+=decoder.decode(value,{stream:true});if(!cancelled&&body.includes('的交付包…')){await new Promise(r=>setTimeout(r,1500));const r=await fetch(origin+'/api/chat/cancel',{method:'POST',headers,body:'{}'});assert.equal(r.status,200);assert.equal((await r.json()).cancelled,true);cancelled=true}}
  await writeFile(resolve(root,run+'-sse.txt'),body);assert.ok(cancelled,'Must cancel after delivery generation actually starts');const current=await store.get(id),assistant=current.messages.slice(before.messages.length).find(m=>m.role==='assistant');assert.equal(assistant?.status,'cancelled');assert.equal(current.savedVersion,before.savedVersion);assert.deepEqual(current.scene,before.scene);checks.cancelledAfterDeliveryStart=true;
 }
 if(step==='delivery'){
  assert.ok(before.savedVersion);await model(`请实际调用 prepare_delivery 为已保存版本 ${before.savedVersion} 生成交付ZIP，并给出下载链接。`,['prepare_delivery']);const response=await fetch(origin+`/api/export/${before.savedVersion}`,{headers});assert.equal(response.status,200);const buffer=Buffer.from(await response.arrayBuffer());const files=unzipSync(buffer),manifest=JSON.parse(strFromU8(files['manifest.json']));assert.equal(manifest.version,before.savedVersion);for(const [name,meta] of Object.entries(manifest.files) as [string,{sha256:string;bytes:number}][]){assert.equal(files[name].length,meta.bytes);assert.equal(createHash('sha256').update(files[name]).digest('hex'),meta.sha256)}for(const name of ['owner.pdf','designer.docx','scene.json','sidecar.json','whole-home.png','floorplan.png'])assert.ok(files[name]?.length);checks.archive={bytes:buffer.length,sha256:createHash('sha256').update(buffer).digest('hex'),files:Object.keys(files)};await writeFile(resolve(root,run+'.zip'),buffer);
 }
 if(step==='floor-return'){
  const response=await fetch(origin+'/api/chat/stages/switch',{method:'POST',headers,body:JSON.stringify({stage:'floorplan',expectedRevision:before.revision})});assert.equal(response.status,200,await response.text());const state=await store.chatState(id);assert.equal(state.threads.floorplan.threadId,initial.threads.floorplan.threadId);assert.deepEqual((await store.get(id)).scene,before.scene);assert.ok(state.handoffs.filter(h=>h.to==='floorplan').every(h=>state.threads.floorplan.deliveredIds.includes(h.id)));await model('只读取并讨论现在的户型状态，不修改，也不请求返回修改。',['get_snapshot']);assert.deepEqual((await store.get(id)).scene,before.scene);checks.discussionPreservesDesign=true;
 }
 if(step==='reopen-model'){await model('我准备修改已确认户型，请用 request_topology_reopen 出示明确确认卡，我知道会清除依赖旧拓扑的后续设计。现在不要替我确认。',['request_topology_reopen']);assert.ok((await store.get(id)).confirmedBuilding)}
 if(step==='reopen-confirm'){const p=await page(),response=p.waitForResponse(r=>r.url().endsWith('/api/chat/actions/confirm'));await p.locator('[data-action-kind="reopen_topology"]').getByRole('button',{name:/确认/}).click();const r=await response;assert.equal(r.status(),200,await r.text());const current=await store.get(id);assert.equal(current.confirmedBuilding,undefined);assert.equal(current.scene,null);assert.deepEqual(current.proposals,[]);assert.deepEqual(current.roomStyles,{});assert.equal(current.layoutReview,undefined);assert.ok(current.answerRecommendations?.every(j=>j.status==='invalidated')??true);checks.downstreamInvalidated=true;await p.screenshot({path:resolve(out,'reopened.png')})}
 const current=await store.get(id);await writeFile(resolve(out,'result.json'),JSON.stringify({pass:true,run,step,privateRun:basename(root),checks,revision:current.revision,stageState:await store.chatState(id)},null,2));console.log(JSON.stringify({pass:true,run,step}));
}catch(error){await writeFile(resolve(root,run+'-failure-project.json'),JSON.stringify(await store.get(id),null,2));await writeFile(resolve(out,'result.json'),JSON.stringify({pass:false,run,step,checks,error:String(error)},null,2));throw error}
finally{await browser?.close();await app.close();await store.close()}
