import {mkdir,rm,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
import {chromium} from 'playwright';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import {seedSnapshotProject} from '../tests/fixtures/alva/snapshot.js';
const run=process.env.ALVA039_RUN||`alva039-${Date.now()}`,root=resolve('.runtime',run),evidence=resolve('evidence',run),port=Number(process.env.ALVA039_PORT||43139),origin=`http://127.0.0.1:${port}`,code='alva039-round2-code-123456';
await rm(root,{recursive:true,force:true});await mkdir(root,{recursive:true});await mkdir(evidence,{recursive:true});process.env.ALVA_ACCESS_CODE=code;
const store=new AlvaStore(resolve(root,'db'));await store.init();const {project}=await store.create('ALVA-039 browser');await store.ensureAccessCode(project.id);await store.mutate(project.id,randomUUID(),0,'seed',{},seedSnapshotProject);const app=await buildAlva(store,{origin});await app.listen({host:'127.0.0.1',port});
const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const context=await browser.newContext({viewport:{width:1440,height:1000}});const consoleErrors:string[]=[];const page=await context.newPage();page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});page.on('pageerror',e=>consoleErrors.push(`pageerror: ${e.message}`));
try{
 const auth=await context.request.post(origin+'/api/access',{data:{code},headers:{origin}});if(!auth.ok())throw new Error('login failed '+await auth.text());await page.goto(origin,{waitUntil:'networkidle'});
 await page.getByRole('button',{name:'漫游',exact:true}).click();await page.locator('[data-testid="building-canvas"] canvas').waitFor({state:'visible'});await page.getByTestId('walkthrough-status').waitFor();await page.waitForFunction(()=>!!(document.querySelector('[data-testid="building-canvas"]') as any)?.alvaWalk);
 const canvas=page.locator('[data-testid="building-canvas"] canvas');await canvas.click({position:{x:300,y:500}});await page.waitForTimeout(120);let locked=await page.evaluate(()=>!!document.pointerLockElement);if(!locked){await page.evaluate(()=>{const c=document.querySelector('[data-testid="building-canvas"] canvas') as HTMLCanvasElement;return c.requestPointerLock()});await page.waitForTimeout(120);locked=await page.evaluate(()=>!!document.pointerLockElement)}if(!locked)throw new Error('pointer lock did not activate');
 const before=await page.evaluate(()=>{const h=document.querySelector('[data-testid="building-canvas"]') as any;return {x:h.alvaView.camera.position.x,z:h.alvaView.camera.position.z,yaw:h.alvaView.camera.rotation.y}});await page.keyboard.down('w');await page.waitForTimeout(80);const during=await page.evaluate(()=>{const h=document.querySelector('[data-testid="building-canvas"]') as any,c=h.alvaView.camera;return {keys:[...h.alvaWalk.keys],x:c.position.x,z:c.position.z,yaw:c.rotation.y,locked:h.alvaWalk.isLocked(),next:h.alvaWalk.canWalkAt(c.position.x,c.position.z-.2)}});await page.waitForTimeout(240);await page.keyboard.up('w');const afterMove=await page.evaluate(()=>{const h=document.querySelector('[data-testid="building-canvas"]') as any;return {x:h.alvaView.camera.position.x,z:h.alvaView.camera.position.z}});if(Math.hypot(afterMove.x-before.x,afterMove.z-before.z)<.05)throw new Error('WASD did not move camera: '+JSON.stringify({before,during,afterMove}));
 await page.evaluate(()=>{const e=new MouseEvent('mousemove',{bubbles:true});Object.defineProperty(e,'movementX',{value:120});Object.defineProperty(e,'movementY',{value:-20});window.dispatchEvent(e)});await page.waitForTimeout(100);const yaw=await page.evaluate(()=>{const h=document.querySelector('[data-testid="building-canvas"]') as any;return h.alvaView.camera.rotation.y});if(Math.abs(yaw-before.yaw)<.05)throw new Error('mouse did not change view yaw');
 const collision=await page.evaluate(()=>{const h=document.querySelector('[data-testid="building-canvas"]') as any;return {wall:h.alvaWalk.canWalkAt(0,1),door:h.alvaWalk.canWalkAt(2.5,4),furniture:h.alvaWalk.canWalkAt(2,2),free:h.alvaWalk.canWalkAt(4,2)}});if(collision.wall!==false||collision.door!==true||collision.furniture!==false||collision.free!==true)throw new Error('collision result mismatch '+JSON.stringify(collision));
 // Input focus clears keys and prevents drift.
 await page.evaluate(()=>{const c=document.querySelector('[data-testid=\"building-canvas\"] canvas') as HTMLCanvasElement;return c.requestPointerLock()});await page.waitForTimeout(100);await page.keyboard.down('w');await page.waitForTimeout(80);const textarea=page.locator('textarea[aria-label="咨询消息"]');await textarea.focus();await page.waitForTimeout(120);const focused=await page.evaluate(()=>{const h=document.querySelector('[data-testid="building-canvas"]') as any;return {keys:h.alvaWalk.keys.size,pos:{x:h.alvaView.camera.position.x,z:h.alvaView.camera.position.z}}});await page.waitForTimeout(220);const focusedLater=await page.evaluate(()=>{const h=document.querySelector('[data-testid="building-canvas"]') as any;return {keys:h.alvaWalk.keys.size,pos:{x:h.alvaView.camera.position.x,z:h.alvaView.camera.position.z}}});await page.keyboard.up('w');if(focused.keys!==0||focusedLater.keys!==0||Math.hypot(focusedLater.pos.x-focused.pos.x,focusedLater.pos.z-focused.pos.z)>.03)throw new Error('input focus did not stop movement');
 // Window blur also clears movement state.
 await page.evaluate(()=>{const c=document.querySelector('[data-testid=\"building-canvas\"] canvas') as HTMLCanvasElement;return c.requestPointerLock()});await page.waitForTimeout(100);await page.keyboard.down('d');await page.waitForTimeout(70);await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await page.waitForTimeout(100);const blurKeys=await page.evaluate(()=>{const h=document.querySelector('[data-testid="building-canvas"]') as any;return h.alvaWalk.keys.size});await page.keyboard.up('d');if(blurKeys!==0)throw new Error('window blur did not clear keys');
 // Escape exits pointer lock and clears movement; re-entering never resumes old motion.
 await page.evaluate(()=>{const c=document.querySelector('[data-testid=\"building-canvas\"] canvas') as HTMLCanvasElement;return c.requestPointerLock()});await page.waitForTimeout(100);await page.keyboard.down('w');await page.waitForTimeout(80);await page.keyboard.press('Escape');await page.waitForTimeout(120);await page.keyboard.up('w');const escaped=await page.evaluate(()=>{const h=document.querySelector('[data-testid="building-canvas"]') as any;return {keys:h.alvaWalk.keys.size,locked:h.alvaWalk.isLocked(),pos:{x:h.alvaView.camera.position.x,z:h.alvaView.camera.position.z}}});await page.waitForTimeout(220);const escapedLater=await page.evaluate(()=>{const h=document.querySelector('[data-testid="building-canvas"]') as any;return {pos:{x:h.alvaView.camera.position.x,z:h.alvaView.camera.position.z}}});if(escaped.keys!==0||escaped.locked||Math.hypot(escapedLater.pos.x-escaped.pos.x,escapedLater.pos.z-escaped.pos.z)>.03)throw new Error('Esc pause failed');
 // Room / whole-home navigation stays available.
 const roomSelect=page.getByLabel('建筑房间视角');await roomSelect.selectOption('room');if(await roomSelect.inputValue()!=='room')throw new Error('room navigation failed');await page.getByTestId('building-reset').click();if(await roomSelect.inputValue()!=='')throw new Error('whole-home reset failed');
 await page.screenshot({path:resolve(evidence,'walkthrough-desktop.png'),fullPage:true});const result={ok:true,run,pointerLock:true,wasdDistance:Math.hypot(afterMove.x-before.x,afterMove.z-before.z),mouseYawChanged:true,collision,inputFocusClearsKeys:true,windowBlurClearsKeys:true,escapePausesWithoutDrift:true,roomNavigation:true,wholeHomeReturn:true,consoleErrors};await writeFile(resolve(evidence,'result.json'),JSON.stringify(result,null,2));await writeFile(resolve(evidence,'console.json'),JSON.stringify(consoleErrors,null,2));if(consoleErrors.length)throw new Error('console errors: '+consoleErrors.join(' | '));console.log(JSON.stringify(result,null,2));
}finally{await browser.close();await app.close();await store.close();await rm(root,{recursive:true,force:true})}
