import assert from 'node:assert/strict';
import {randomUUID,randomBytes} from 'node:crypto';
import {mkdir,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {createServer} from 'node:net';
import {chromium,expect} from '@playwright/test';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import {applyAnswer} from '../api/business.js';
import {seedLivingStage} from '../tests/fixtures/alva/living-stage.js';
import {createScopeRequest,confirmScope} from '../api/scope.js';
const real=process.argv.includes('--real'),run=new Date().toISOString().replace(/[:.]/g,'')+'-ALVA080-'+(real?'real':'browser'),out=resolve(process.env.ALVA_ACCEPTANCE_DIR||resolve('.runtime','acceptance',run)),root=resolve(process.env.ALVA_ACCEPTANCE_DIR||resolve('.runtime','acceptance',run),'private');await mkdir(out,{recursive:true});await mkdir(root,{recursive:true});
process.env.OPENAI_API_KEY||=process.env.NEWAPI_KEY;process.env.ALVA_AGENT_DIR=resolve(root,'agents');process.env.ALVA_ACCESS_CODE=randomBytes(24).toString('hex');
const store=new AlvaStore(resolve(root,'db'));await store.init();const {project}=await store.create('Scope furniture synthetic');await store.ensureAccessCode(project.id);
await store.mutate(project.id,randomUUID(),0,'seed',{},p=>{seedLivingStage(p);applyAnswer(p,{questionId:'Q01',roomId:null,text:'希望有阅读角',state:'answered',confirmed:true,locked:false});p.scene!.items=[];const id=randomUUID();p.messages.push({id,role:'user',text:'请为客厅摆放一张阅读椅，使用现有许可目录家具即可；保留现有房间和墙体，生成两种不同位置的方案供我比较。不要生成问卷。',status:'completed',stage:'living',createdAt:new Date().toISOString()});p.scopeRequests=[createScopeRequest(p,{roomIds:['room'],itemIds:[],reason:'阅读椅摆放范围',sourceMessageId:id})];});
let calls=0;
const port=await new Promise<number>(done=>{const s=createServer();s.listen(0,'127.0.0.1',()=>{const p=(s.address() as {port:number}).port;s.close(()=>done(p))})}),origin='http://127.0.0.1:'+port;
const app=await buildAlva(store,{assets:true,origin,...(real?{}:{chatCodex:async(input:any)=>{calls++;if(calls===1)return '接下来会为你摆放家具';await input.tools.find((t:any)=>t.name==='propose_changes').run({variants:[1,3].map(x=>({title:'Reading '+x,rationale:'synthetic alternatives',changes:[{action:'add',targetId:'room',values:{assetId:'alva-chair',roomId:'room',x,y:1}}]}))});return '家具候选已生成，等待你采用';}})});await app.listen({host:'127.0.0.1',port});const auth=await store.issueInternalSession(project.id);global.gc?.();
const browser=await chromium.launch({headless:true,executablePath:'/home/ubuntu/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage','--single-process','--no-zygote','--renderer-process-limit=1','--js-flags=--max-old-space-size=96']});const context=await browser.newContext({viewport:{width:1280,height:900}});await context.addInitScript('globalThis.__name=(v)=>v');await context.addCookies([{name:'alva_session',value:auth.token,url:origin}]);const page=await context.newPage(),checks:string[]=[],errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(origin);const scope=page.getByTestId('scope-confirmation');await expect(scope).toBeVisible();await expect(scope.getByRole('button',{name:'确认范围并继续'})).toBeEnabled();await scope.getByRole('button',{name:'确认范围并继续'}).click();
 await expect(scope).toHaveCount(0);await expect.poll(async()=>(await store.get(project.id)).messages.filter(m=>m.role==='assistant').length).toBeGreaterThan(0);checks.push('scope confirmation immediately starts main Chat without another user message');
 if(!real){await expect.poll(async()=>(await store.get(project.id)).scopeRequests![0].generation?.status).toBe('failed');await expect(page.getByTestId('scope-generation-status').getByRole('alert')).toContainText('没有生成');await page.reload();await expect(page.getByTestId('resume-scope')).toBeEnabled();await page.getByTestId('resume-scope').click();checks.push('no-op response is a visible persisted failure; refresh offers retry');}
 await expect.poll(async()=>(await store.get(project.id)).scopeRequests![0].generation?.status,{timeout:300000,intervals:[1000]}).toBe('completed');let p=await store.get(project.id);assert.equal(p.scene!.items.length,0);assert.ok(p.proposals.length>=2);const callsBefore=p.messages.filter(m=>m.role==='assistant').length;const message=p.messages.at(-1)!;assert.ok(message.toolCalls?.some(t=>t.name==='propose_changes'&&!t.isError));checks.push('MCP returns scoped real candidates without adopting or saving');
 const card=page.locator('.proposal-group .proposal').first();await expect(card).toBeVisible();await expect(card.locator('canvas')).toHaveCount(1);await page.screenshot({path:resolve(out,'candidates.png')});const button=card.getByRole('button',{name:'采用这个整组候选的勾选范围'});await expect(button).toBeEnabled();await button.click();await expect.poll(async()=>(await store.get(project.id)).scene!.items.length).toBe(1);await expect(page.locator('.proposal-group')).toHaveCount(0);
 await page.getByRole('button',{name:'全屋',exact:true}).click();await page.waitForFunction(()=>{const v=(document.querySelector('.canvas-wrap [data-testid="scene-view"]') as any)?.alvaView;return v?.scene.items.length===1&&v.world.children.some((o:any)=>o.userData.id===v.scene.items[0].id)});await page.screenshot({path:resolve(out,'adopted.png')});await page.reload();await page.getByRole('button',{name:'全屋',exact:true}).click();await page.waitForFunction(()=>((document.querySelector('.canvas-wrap [data-testid="scene-view"]') as any)?.alvaView?.scene.items.length)===1);p=await store.get(project.id);assert.equal(p.savedVersion,0);assert.equal(p.messages.filter(m=>m.role==='assistant').length,callsBefore);checks.push('adoption inserts furniture into rendered main scene; reload persists without duplicate generation or snapshot');
 if(!real){await store.mutate(project.id,randomUUID(),null,'legacy-confirmed',{},p=>{const id=p.messages.find(m=>m.role==='user')!.id;const s=createScopeRequest(p,{roomIds:['room'],itemIds:[],reason:'legacy recovery',sourceMessageId:id});p.scopeRequests!.push(s);confirmScope(p,s.id,['room'],[]);delete p.scopeRequests!.at(-1)!.generation});await page.reload();await expect(page.getByTestId('resume-scope')).toBeEnabled();checks.push('legacy confirmed scope without generation state remains resumable');}
 assert.deepEqual(errors,[]);await writeFile(resolve(out,'result.json'),JSON.stringify({pass:true,real,checks,errors,toolCalls:message.toolCalls,scopeGeneration:p.scopeRequests![0].generation,items:p.scene!.items.length},null,2));console.log(JSON.stringify({out,checks}));
}catch(e){await writeFile(resolve(out,'failure.json'),JSON.stringify({error:String(e),checks,errors,messages:(await store.get(project.id)).messages},null,2));await page.screenshot({path:resolve(out,'failure.png')}).catch(()=>{});throw e}finally{await browser.close();await app.close();await store.close()}
