import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdir,rm,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {chromium} from '@playwright/test';
import {createCanvas} from '@napi-rs/canvas';
import {AlvaStore} from '../api/store.js';
import {buildAlva} from '../api/api.js';
import {runCodex} from '../api/codex.js';
import type {SceneData} from '../api/model.js';
const runId=process.env.ALVA_RUN_ID||`${Date.now()}-ALVA018-round2`,port=Number(process.env.ALVA_PORT||4218),origin=`http://127.0.0.1:${port}`,root=resolve('.runtime',runId),evidence=resolve('evidence',runId),code='alva018-browser-code-123456';
assert.ok(process.env.OPENAI_API_KEY);process.env.ALVA_ACCESS_CODE=code;process.env.ALVA_AGENT_DIR=resolve(root,'agent');await rm(root,{recursive:true,force:true});await mkdir(root,{recursive:true,mode:0o700});await mkdir(evidence,{recursive:true});
const scene:SceneData={walls:[{id:'n',a:{x:0,y:0},b:{x:5,y:0},thickness:.15,height:2.8,structural:'unknown',evidence:[]}],rooms:[{id:'living',name:'客厅',purpose:'生活',polygon:[{x:0,y:0},{x:5,y:0},{x:5,y:4},{x:0,y:4}],locked:false}],openings:[],items:[],calibration:null,geography:{latitude:1.3,north:0,assumption:'synthetic'}};
const store=new AlvaStore(resolve(root,'db'));await store.init();const created=await store.create('ALVA-018 Browser');await store.ensureAccessCode(created.project.id);await store.mutate(created.project.id,randomUUID(),0,'seed',{},p=>{p.scene=structuredClone(scene)});let modelCalls=0;const app=await buildAlva(store,{origin,chatCodex:input=>{modelCalls++;return runCodex(modelCalls===1?{...input,model:'alva-definitely-unavailable-model'}:input)}});await app.listen({host:'127.0.0.1',port});
const executablePath=process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||'/home/ubuntu/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',browser=await chromium.launch({headless:true,executablePath,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']}),page=await browser.newPage({viewport:{width:1600,height:1000}});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
try{
 await page.goto(origin);await page.getByLabel('统一验证码').fill(code);await page.getByRole('button',{name:/验证并进入/}).click();await page.getByText('ALVA-018 Browser',{exact:true}).waitFor();errors.length=0;await page.waitForFunction(()=>!!document.querySelector<HTMLSelectElement>('select[aria-label="咨询模型"]')?.value);
 const canvas=createCanvas(240,160),ctx=canvas.getContext('2d');ctx.fillStyle='#eee';ctx.fillRect(0,0,240,160);ctx.fillStyle='#b33';ctx.fillRect(50,35,140,90);const png=canvas.toBuffer('image/png');const fileInputs=page.locator('input[type="file"]');await fileInputs.nth(1).setInputFiles({name:'retry-reference.png',mimeType:'image/png',buffer:png});await page.getByText('已附参考图').waitFor();const composer=page.getByLabel('咨询消息'),text='请描述这张参考图最显眼的颜色和物体，不要修改设计。';await composer.fill(text);const before=await page.request.get(`${origin}/api/project`).then(r=>r.json()),sceneJson=JSON.stringify(before.scene);
await page.getByRole('button',{name:'发送 ↑'}).click();await page.getByRole('button',{name:'取消'}).waitFor();await page.getByRole('alert').waitFor({timeout:120000});await page.getByRole('button',{name:/重试上一条消息/}).waitFor();assert.equal(await composer.inputValue(),text);await page.getByText('已附参考图').waitFor();const failureText=await page.getByRole('alert').innerText();assert.ok(failureText.includes('模型当前不可用或处理失败'),failureText);
 let failed=await page.request.get(`${origin}/api/project`).then(r=>r.json());assert.equal(failed.messages.at(-1)?.status,'failed');assert.equal(JSON.stringify(failed.scene),sceneJson);assert.equal(failed.proposals.filter((p:any)=>p.status==='accepted').length,0);
 await page.getByRole('button',{name:/重试上一条消息/}).click();await page.getByRole('button',{name:'取消'}).waitFor();await page.getByRole('button',{name:'发送 ↑'}).waitFor({timeout:120000});await page.getByRole('button',{name:/重试上一条消息/}).waitFor({state:'detached'});assert.equal(await composer.inputValue(),'');assert.equal(await page.getByText('已附参考图').count(),0);const after=await page.request.get(`${origin}/api/project`).then(r=>r.json());assert.equal(after.messages.at(-1)?.status,'completed');assert.equal(JSON.stringify(after.scene),sceneJson);assert.equal(after.proposals.filter((p:any)=>p.status==='accepted').length,0);assert.equal(JSON.stringify(after).includes(png.toString('base64')),false);assert.deepEqual(errors,[]);
 await page.screenshot({path:resolve(evidence,'cancel-retry.png'),fullPage:true});const result={ticket:'ALVA-018',runId,pass:true,checks:{provider_failure_visible:true,text_restored:true,attachment_restored:true,retry_button_visible:true,retry_completed:true,input_cleared_after_success:true,attachment_cleared_after_success:true,scene_unchanged:true,no_auto_accept:true,image_not_persisted:true,console_errors:errors}};await writeFile(resolve(evidence,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{await browser.close();await app.close();await store.close();await rm(root,{recursive:true,force:true})}
