import {chromium,expect} from '@playwright/test';import assert from 'node:assert/strict';import {readFile,writeFile,mkdir} from 'node:fs/promises';import {createHash} from 'node:crypto';
const origin='https://prod.huiyuanxp.com',out='evidence/'+new Date().toISOString().replace(/[:.]/g,'')+'-ALVA076-public';await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:'/home/ubuntu/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',args:['--disable-dev-shm-usage','--renderer-process-limit=1','--disable-gpu']});const page=await browser.newPage({viewport:{width:1440,height:950}});page.setDefaultTimeout(20000);const errors=[],checks=[],timings=[];page.on('pageerror',e=>errors.push(e.message));
const read=path=>page.evaluate(async path=>{const r=await fetch(path);if(!r.ok)throw new Error('HTTP '+r.status);return r.json()},path);
const signature=p=>createHash('sha256').update(JSON.stringify({scene:p.scene,candidate:p.candidate,confirmedTopology:p.confirmedTopology,confirmedBuilding:p.confirmedBuilding,savedVersion:p.savedVersion,answers:p.answers})).digest('hex');
const block=route=>route.fulfill({json:{needed:false}});
try{
 await page.route('**/api/chat/guidance*',block);await page.goto(origin);const code=(await readFile('.runtime/alva076-live/access-code','utf8')).trim();assert.equal(await page.evaluate(async code=>(await fetch('/api/access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})})).status,code),200);await page.reload();await page.locator('.chat-stages').waitFor();const before=await read('/api/project'),state=await read('/api/chat/stages');const original=state.active,threads=Object.fromEntries(Object.entries(state.threads).map(([k,v])=>[k,v.threadId]));
 const tab=stage=>page.locator('.chat-stages button').nth(stage==='floorplan'?0:1);
 await expect(tab(original)).toHaveAttribute('aria-current','step');await page.locator('header .language-switch select').selectOption('en');
 for(const target of ['living','floorplan','living','floorplan']){const start=Date.now();await tab(target).click();await expect(tab(target)).toHaveAttribute('aria-current','step');await expect(tab(target)).toBeEnabled();timings.push({target,ms:Date.now()-start});assert.equal((await read('/api/chat/stages')).active,target)}checks.push('production English tabs alternate both directions without model handoff blocking');
 await page.unroute('**/api/chat/guidance*',block);await page.reload();await expect(page.getByRole('button',{name:/^(Cancel|取消)$/,exact:true})).toBeVisible({timeout:45000});const start=Date.now();await tab('living').click();await expect(tab('living')).toHaveAttribute('aria-current','step',{timeout:20000});timings.push({target:'living while automatic Chat active',ms:Date.now()-start});checks.push('production automatic guidance interrupted by direct stage navigation');
 await page.route('**/api/chat/guidance*',block);await tab(original).click();await expect(tab(original)).toHaveAttribute('aria-current','step',{timeout:20000});await expect(tab(original)).toBeEnabled();
 const after=await read('/api/project'),final=await read('/api/chat/stages');assert.equal(signature(after),signature(before));assert.deepEqual(Object.fromEntries(Object.entries(final.threads).map(([k,v])=>[k,v.threadId])),threads);assert.equal(final.active,original);checks.push('original stage and both original threads restored; design, answers and saved version unchanged');
 const release=(await readFile('.runtime/alva076-deploy/latest','utf8')).trim();const expected=JSON.parse(await readFile('evidence/'+release.split('/').at(-1)+'/result.json','utf8')).assets;
 for(const [name,hash] of Object.entries(expected)){const actual=await page.evaluate(async name=>{const r=await fetch('/assets/'+name);return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await r.arrayBuffer())),v=>v.toString(16).padStart(2,'0')).join('')},name);assert.equal(actual,hash)}checks.push('public assets match verified release');assert.deepEqual(errors,[]);
 await writeFile(out+'/result.json',JSON.stringify({pass:true,checks,timings,errors,designUnchanged:true,originalStage:original},null,2));console.log(JSON.stringify({out,checks,timings,errors}));
}catch(error){await writeFile(out+'/failure.json',JSON.stringify({error:String(error),checks,timings,errors},null,2));await page.screenshot({path:'.runtime/alva076-live/verify-failure.png'}).catch(()=>{});throw error}finally{await browser.close()}
