import {surfaceRoughness,wallSideStyles,type RoomStyles} from './room-style/surfaces.js';
import {applyWallMaterials} from './room-style/materials.js';
import React,{useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import type {SceneData} from '../../api/model.js';
import type {BuildingSceneData} from '../../api/building/types.js';
import {overviewPose,roomPose} from './scene/building-camera.js';

type BuildingViewProps={roomStyles?:RoomStyles;building:BuildingSceneData;topology?:SceneData|null;focusRoom?:string;selected?:string;time?:number;day?:number;onSelect?:(id:string)=>void;onFocusRoom?:(id:string)=>void};
type SelectionInfo={id:string;topologyId:string;kind:string};

const colors:Record<string,string>={floor:'#c8b99d',wall:'#d7d5ca','door-frame':'#8b684d','window-frame':'#65787c',glass:'#9fc9d7'};
const labels:Record<string,string>={floor:'地面',wall:'墙体','door-frame':'门框','window-frame':'窗框',glass:'玻璃'};

function materialFor(component:BuildingSceneData['components'][number]){
 const isGlass=component.kind==='glass';
 return new THREE.MeshStandardMaterial({color:colors[component.kind]||component.color,roughness:isGlass?.12:component.material==='metal'?.28:.72,metalness:component.material==='metal'?.55:0,transparent:isGlass,opacity:isGlass?.42:1});
}

export function BuildingView({roomStyles={},building,topology=null,focusRoom='',selected='',time=14,day=172,onSelect,onFocusRoom}:BuildingViewProps){
 const root=useRef<HTMLDivElement>(null),[displayMode,setDisplayMode]=useState<'full'|'cutaway'>('full'),[roomSelection,setRoomSelection]=useState(focusRoom),[resetVersion,setResetVersion]=useState(0),[selectionInfo,setSelectionInfo]=useState<SelectionInfo>();
 useEffect(()=>setRoomSelection(focusRoom||''),[focusRoom]);
 useEffect(()=>{
  const host=root.current!;const world=new THREE.Scene();world.background=new THREE.Color('#e7e5da');
  const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.localClippingEnabled=true;host.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Codex建筑三维场景');
  const camera=new THREE.PerspectiveCamera(45,1,.05,200);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.minDistance=.35;controls.maxDistance=200;controls.enablePan=true;
  const boundsPose=overviewPose(building,1),cutHeight=Math.min(boundsPose.target.y+1.35,Math.max(boundsPose.target.y+.9,boundsPose.position.y*.35)),cutPlane=new THREE.Plane(new THREE.Vector3(0,-1,0),cutHeight),wallMeshes:THREE.Mesh[]=[];
  const selectable:THREE.Object3D[]=[];const meshById=new Map<string,THREE.Mesh>();
  const box=(component:BuildingSceneData['components'][number])=>{const mesh=new THREE.Mesh(new THREE.BoxGeometry(component.size.x,component.size.y,component.size.z),materialFor(component));mesh.position.set(component.position.x,component.position.y,component.position.z);mesh.rotation.y=-component.rotation;mesh.castShadow=component.kind!=='floor';mesh.receiveShadow=true;mesh.userData={id:component.id,topologyId:component.topologyId,kind:component.kind};if(component.kind==='wall'){wallMeshes.push(mesh);(mesh.material as THREE.MeshStandardMaterial).clippingPlanes=displayMode==='cutaway'?[cutPlane]:[]}if(component.id===selected){const material=mesh.material as THREE.MeshStandardMaterial;material.emissive.set('#2478b2');material.emissiveIntensity=.65}world.add(mesh);selectable.push(mesh);meshById.set(component.id,mesh);return mesh};
  for(const component of building.components){
   const mesh=box(component);
   const floorStyle=component.kind==='floor'?roomStyles[component.topologyId]?.floor:undefined;
   if(floorStyle){const material=mesh.material as THREE.MeshStandardMaterial;material.color.set(floorStyle.color);material.roughness=surfaceRoughness(floorStyle);material.userData.surfaceStyle=floorStyle}
   if(component.kind==='wall'&&topology)applyWallMaterials(mesh,wallSideStyles(topology,roomStyles,component.position.x,component.position.z,component.rotation,component.size.z));
  }
  const overview=overviewPose(building,Math.max(host.clientWidth/Math.max(host.clientHeight,1),.2)),pose=roomSelection&&topology?roomPose(topology,roomSelection,Math.max(host.clientWidth/Math.max(host.clientHeight,1),.2))||overview:overview;camera.position.set(pose.position.x,pose.position.y,pose.position.z);controls.target.set(pose.target.x,pose.target.y,pose.target.z);camera.far=Math.max(200,Math.hypot(building.camera.position.x-building.camera.target.x,building.camera.position.y-building.camera.target.y,building.camera.position.z-building.camera.target.z)*12);camera.updateProjectionMatrix();
  world.add(new THREE.HemisphereLight('#fff9e8','#6f7168',1.8));const sun=new THREE.DirectionalLight('#fff0ca',3.2);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-40;sun.shadow.camera.right=40;sun.shadow.camera.top=40;sun.shadow.camera.bottom=-40;world.add(sun);world.add(sun.target);sun.target.position.set(overview.target.x,0,overview.target.z);const geography=topology?.geography||{latitude:31,north:0,assumption:'日照为默认地理假设'};const rad=Math.PI/180,latitude=geography.latitude*rad,declination=23.44*rad*Math.sin(2*Math.PI*(284+day)/365),hour=(time-12)*15*rad,altitude=Math.asin(Math.sin(latitude)*Math.sin(declination)+Math.cos(latitude)*Math.cos(declination)*Math.cos(hour)),azimuth=Math.atan2(Math.sin(hour),Math.cos(hour)*Math.sin(latitude)-Math.tan(declination)*Math.cos(latitude))+geography.north*rad;sun.position.set(overview.target.x+Math.sin(azimuth)*35*Math.cos(altitude),Math.max(4,Math.sin(altitude)*35),overview.target.z+Math.cos(azimuth)*35*Math.cos(altitude));sun.intensity=Math.max(.35,Math.max(0,Math.sin(altitude))*3.5);
  const resize=()=>{const rect=host.getBoundingClientRect();renderer.setSize(rect.width,rect.height);camera.aspect=rect.width/Math.max(rect.height,1);camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(host);resize();
  const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();const selectObject=(mesh:THREE.Object3D)=>{const data=mesh.userData as SelectionInfo;setSelectionInfo(data);onSelect?.(data.id);return data};const pick=(clientX:number,clientY:number)=>{const rect=renderer.domElement.getBoundingClientRect();pointer.set((clientX-rect.left)/Math.max(rect.width,1)*2-1,-(clientY-rect.top)/Math.max(rect.height,1)*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(selectable,false)[0];if(!hit)return;return selectObject(hit.object)};const selectById=(id:string)=>{const mesh=meshById.get(id);return mesh?selectObject(mesh):undefined};const click=(event:PointerEvent)=>{pick(event.clientX,event.clientY)};renderer.domElement.addEventListener('pointerup',click);
  let frame=0;const animate=()=>{controls.update();renderer.render(world,camera);frame=requestAnimationFrame(animate)};frame=requestAnimationFrame(animate);
  (host as any).alvaView={camera,controls,scene:world,renderer,wallMeshes,meshById,pick,selectById,capture:()=>renderer.domElement.toDataURL('image/png'),reset:()=>{const next=overviewPose(building,Math.max(host.clientWidth/Math.max(host.clientHeight,1),.2));camera.position.set(next.position.x,next.position.y,next.position.z);controls.target.set(next.target.x,next.target.y,next.target.z);controls.update()}};
  return()=>{cancelAnimationFrame(frame);observer.disconnect();controls.dispose();renderer.domElement.removeEventListener('pointerup',click);world.traverse(object=>{if(object instanceof THREE.Mesh){object.geometry.dispose();const materials=Array.isArray(object.material)?object.material:[object.material];materials.forEach(material=>material.dispose())}});renderer.dispose();host.removeChild(renderer.domElement);delete (host as any).alvaView};
 },[building,topology,roomStyles,roomSelection,displayMode,selected,time,day,resetVersion,onSelect]);
 const chooseRoom=(value:string)=>{setRoomSelection(value);onFocusRoom?.(value)};
 const reset=()=>{setRoomSelection('');onFocusRoom?.('');setResetVersion(version=>version+1)};
 return <div className="building-view" data-testid="building-view"><div className="building-controls" data-testid="building-controls"><div className="segmented" role="group" aria-label="墙体显示"><button type="button" className={displayMode==='full'?'active':''} aria-pressed={displayMode==='full'} onClick={()=>setDisplayMode('full')}>完整墙体</button><button type="button" className={displayMode==='cutaway'?'active':''} aria-pressed={displayMode==='cutaway'} data-testid="building-cutaway" onClick={()=>setDisplayMode('cutaway')}>剖切显示</button></div><label>房间视角<select aria-label="建筑房间视角" value={roomSelection} onChange={event=>chooseRoom(event.target.value)}><option value="">总览</option>{topology?.rooms.map(room=><option value={room.id} key={room.id}>{room.name}</option>)}</select></label><button type="button" onClick={reset} data-testid="building-reset">复位总览</button><small>{displayMode==='cutaway'?'剖切仅影响显示，已确认拓扑和建筑构件保持不变。':'可旋转、缩放并点击构件查看拓扑关联。'}</small></div><div className="building-canvas" ref={root} data-testid="building-canvas"/>{selectionInfo&&<div className="building-selection" role="status"><strong>{labels[selectionInfo.kind]||selectionInfo.kind}</strong><span>构件 {selectionInfo.id}</span><span>拓扑实体 {selectionInfo.topologyId}</span></div>}</div>;
}
