import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {AssistantRuntimeProvider,useExternalStoreRuntime,ThreadPrimitive,MessagePrimitive} from '@assistant-ui/react';
import type {Project,SceneData,Message,XY} from '../../api/model.js';
import {SceneView} from './SceneView.js';
import {WorkspacePanel,ProposalCard,QuestionCard} from './Panels.js';
import {toWav} from './audio.js';
import './style.css';
export async function api(path:string,body?:unknown){const response=await fetch('/api'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=await response.json();if(!response.ok)throw new Error(data.error||'请求失败');return data}
async function stream(path:string,body:unknown,receive:(type:string,data:any)=>void){const r=await fetch('/api'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error((await r.json()).error);const reader=r.body!.getReader(),decoder=new TextDecoder();let pending='';while(true){const {done,value}=await reader.read();if(done)break;pending+=decoder.decode(value,{stream:true});let end;while((end=pending.indexOf('\n\n'))>=0){const frame=pending.slice(0,end);pending=pending.slice(end+2);const kind=frame.match(/^event: (.+)$/m)?.[1];const data=frame.match(/^data: (.+)$/m)?.[1];if(kind&&data)receive(kind,JSON.parse(data))}}}
function UserMessage(){return <MessagePrimitive.Root className="message user"><small>你</small><MessagePrimitive.Parts/></MessagePrimitive.Root>}
function AssistantMessage(){return <MessagePrimitive.Root className="message assistant"><small>alva · 空间顾问</small><MessagePrimitive.Parts/></MessagePrimitive.Root>}
function Conversation({messages,children}:{messages:Message[];children:React.ReactNode}){const runtime=useExternalStoreRuntime<Message>({messages,isRunning:messages.some(m=>m.status==='running'),convertMessage:m=>({id:m.id,role:m.role,content:[{type:'text',text:m.text}],createdAt:new Date(m.createdAt)}),onNew:async()=>{}});return <AssistantRuntimeProvider runtime={runtime}><ThreadPrimitive.Root className="conversation"><ThreadPrimitive.Viewport className="messages"><ThreadPrimitive.Empty><div className="welcome-copy"><span className="eyebrow">从生活出发</span><h2>一起想清楚<br/>家的样子。</h2><p>先给我一张户型图。我会把墙、门窗和房间整理成候选，你可以修正，并用一条已知墙长校准比例。</p><p>之后，我们再聊生活习惯、期待和那些容易忽略的小麻烦。</p></div></ThreadPrimitive.Empty><ThreadPrimitive.Messages components={{UserMessage,AssistantMessage}}/></ThreadPrimitive.Viewport>{children}</ThreadPrimitive.Root></AssistantRuntimeProvider>}
function Plan({scene,selected,onSelect,onChange,onItemMove,image}:{scene:SceneData;selected:string;onSelect:(id:string)=>void;onChange?:(s:SceneData)=>void;onItemMove?:(id:string,x:number,y:number)=>void;image?:Project['sourceImage']}){
 const svg=useRef<SVGSVGElement>(null),itemDrag=useRef<string|null>(null);const drag=useRef<{wall:string;end:'a'|'b';old:XY}|null>(null);const [preview,setPreview]=useState<SceneData|null>(null);const s=preview||scene;
 const points=scene.walls.flatMap(w=>[w.a,w.b]),minX=Math.min(...points.map(p=>p.x))-.5,minY=Math.min(...points.map(p=>p.y))-.5,width=Math.max(...points.map(p=>p.x))-minX+.5,height=Math.max(...points.map(p=>p.y))-minY+.5;
 const position=(e:React.PointerEvent)=>{const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.current!.getScreenCTM()!.inverse());return {x:Math.round(p.x*100)/100,y:Math.round(p.y*100)/100}};
 const move=(e:React.PointerEvent)=>{if(itemDrag.current&&onItemMove){const next=structuredClone(scene),i=next.items.find(i=>i.id===itemDrag.current)!,point=position(e);i.x=point.x;i.y=point.y;setPreview(next);return}if(!drag.current||!onChange)return;const next=structuredClone(scene),wall=next.walls.find(w=>w.id===drag.current!.wall)!,point=position(e),old=drag.current.old;wall[drag.current.end]=point;for(const w of next.walls)for(const end of ['a','b'] as const)if(Math.hypot(w[end].x-old.x,w[end].y-old.y)<.01)w[end]={...point};for(const r of next.rooms)for(let i=0;i<r.polygon.length;i++)if(Math.hypot(r.polygon[i].x-old.x,r.polygon[i].y-old.y)<.01)r.polygon[i]={...point};setPreview(next)};
 return <svg ref={svg} className="plan" viewBox={`${minX} ${minY} ${width} ${height}`} onPointerMove={move} onPointerUp={()=>{if(itemDrag.current&&preview){const i=preview.items.find(i=>i.id===itemDrag.current)!;onItemMove?.(i.id,Math.round(i.x*20)/20,Math.round(i.y*20)/20)}itemDrag.current=null;if(drag.current&&preview)onChange?.(preview);drag.current=null;setPreview(null)}} aria-label="可校正二维户型图">
 {image&&<image href={`data:${image.mime};base64,${image.data}`} x={minX+.5} y={minY+.5} width={width-1} height={height-1} opacity=".16" preserveAspectRatio="none"/>}
 {s.rooms.map(r=><g key={r.id}><polygon points={r.polygon.map(p=>`${p.x},${p.y}`).join(' ')} fill={r.id===selected?'#c7d7d9':'#e2dbc9'} fillOpacity=".65" stroke="none" onClick={()=>onSelect(r.id)}/><text x={r.polygon.reduce((a,p)=>a+p.x,0)/r.polygon.length} y={r.polygon.reduce((a,p)=>a+p.y,0)/r.polygon.length} fontSize=".19" textAnchor="middle">{r.name}</text></g>)}
 {s.walls.map(w=><g key={w.id}><line x1={w.a.x} y1={w.a.y} x2={w.b.x} y2={w.b.y} stroke={selected===w.id?'#2478b2':'#6f7168'} strokeWidth={w.thickness} onClick={()=>onSelect(w.id)}/>{selected===w.id&&onChange&&(['a','b'] as const).map(end=><circle key={end} cx={w[end].x} cy={w[end].y} r=".13" fill="#2478b2" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag.current={wall:w.id,end,old:{...w[end]}}}}/>)}</g>)}
 {s.openings.map(o=>{const w=s.walls.find(w=>w.id===o.wallId)!;const x=w.a.x+(w.b.x-w.a.x)*o.offset,y=w.a.y+(w.b.y-w.a.y)*o.offset,angle=Math.atan2(w.b.y-w.a.y,w.b.x-w.a.x)*180/Math.PI;return <rect key={o.id} x={x-o.width/2} y={y-.08} width={o.width} height=".16" fill={o.kind==='door'?'#f5f3ea':'#7faeb5'} transform={`rotate(${angle} ${x} ${y})`} onClick={()=>onSelect(o.id)}/>})}
 {s.items.map(i=><rect key={i.id} x={i.x-i.width/2} y={i.y-i.depth/2} width={i.width} height={i.depth} transform={`rotate(${i.rotation} ${i.x} ${i.y})`} fill={i.color} stroke={selected===i.id?'#2478b2':'#8f8f7f'} strokeWidth=".04" onClick={()=>onSelect(i.id)} onPointerDown={e=>{if(onItemMove&&!i.locked){e.currentTarget.setPointerCapture(e.pointerId);itemDrag.current=i.id;onSelect(i.id)}}}/>)}
 </svg>
}
function importSourceLabel(source:Project['sourceImage']){if(!source)return '';if(source.originalMime==='application/pdf')return `${source.filename} · PDF 第${source.page||1}页${source.pages?` / 共${source.pages}页`:''}`;return `${source.filename} · ${source.originalMime}`}
function importStatusLabel(state:Project['importState']){if(!state)return '';return `${state.message}${state.status==='failed'||state.status==='cancelled'?'（原工作稿未被覆盖）':''}`}
function App(){
 const [project,setProject]=useState<Project|null>(null),[role,setRole]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[selected,setSelected]=useState(''),[mode,setMode]=useState<'2d'|'3d'|'walk'>('2d'),[wallLength,setWallLength]=useState(''),[lengthSource,setLengthSource]=useState('现场测量'),[time,setTime]=useState(14),[day,setDay]=useState(172),[room,setRoom]=useState(''),[versions,setVersions]=useState<{version:number;summary:string}[]>([]),[link,setLink]=useState('');
 const upload=useRef<HTMLInputElement>(null),referenceUpload=useRef<HTMLInputElement>(null),audioUpload=useRef<HTMLInputElement>(null),recorder=useRef<MediaRecorder|null>(null),recordTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const [accessCode,setAccessCode]=useState(''),[inviteToken,setInviteToken]=useState<string>();
 const [text,setText]=useState(''),[recording,setRecording]=useState(false),[reference,setReference]=useState<{mime:string;data:string}|null>(null),[questions,setQuestions]=useState<any[]>([]);
 useEffect(()=>()=>{recorder.current?.stream.getTracks().forEach(t=>t.stop());if(recordTimer.current)clearTimeout(recordTimer.current)},[]);
 useEffect(()=>{if(project)void api('/questions').then(setQuestions).catch(()=>{})},[!!project]);

 useEffect(()=>{void(async()=>{const params=new URLSearchParams(location.hash.slice(1)),legacy=params.get('access');if(legacy){setInviteToken(legacy);history.replaceState(null,'',location.pathname);setError('检测到旧邀请链接，请同时输入统一验证码；旧链接不能单独进入。')}try{const session=await api('/session');setRole(session.role);setProject(await api(new URLSearchParams(location.search).has('version')?'/versions/'+new URLSearchParams(location.search).get('version'):'/project'))}catch{}})()},[]);
 const login=async()=>{setError('');setBusy(true);try{const session=await api('/access',{code:accessCode,...(inviteToken?{inviteToken}:{})});setRole(session.role);setProject(await api(new URLSearchParams(location.search).has('version')?'/versions/'+new URLSearchParams(location.search).get('version'):'/project'));setAccessCode('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const logout=async()=>{try{await api('/logout')}catch{}setProject(null);setRole('');setAccessCode('');setInviteToken(undefined);setLink('');setError('已退出，请重新输入统一验证码。')};
 const command=()=>({requestId:crypto.randomUUID(),expectedRevision:project!.revision});
 const mutate=async(path:string,body:Record<string,unknown>)=>{setError('');setBusy(true);try{const p=await api(path,{...command(),...body});setProject(p);return p}catch(e){setError((e as Error).message);throw e}finally{setBusy(false)}};
 const scene=project?.candidate||project?.scene,candidate=!!project?.candidate,wall=scene?.walls.find(w=>w.id===selected),readOnly=role!=='owner';
 const runImport=async(file:File)=>{setError('');setBusy(true);try{if(file.size>12_000_000)throw new Error('文件最大12MB');const data=await new Promise<string>((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]);r.onerror=no;r.readAsDataURL(file)});await stream('/import',{...command(),mime:file.type,data,filename:file.name},(type,p)=>{if(type==='status')setStatus(p.text);if(type==='project'){setProject(p);setMode('2d');setSelected(p.candidate?.walls[0]?.id||'')}if(type==='error')setError(p.error)})}catch(e){setError((e as Error).message)}finally{setBusy(false);setStatus('')}};
 const send=async(value=text)=>{if((!value.trim()&&!reference)||busy)return;setBusy(true);setError('');setText('');try{await stream('/chat',{...command(),text:value||'请帮我理解这张参考图片，并先与我确认偏好。',roomId:room||project!.scene?.rooms[0]?.id||null,model:'gpt-5.5',...(reference?{image:reference}:{})},(type,data)=>{if(type==='project')setProject(data);if(type==='delta')setProject(p=>p?{...p,messages:p.messages.map(m=>m.id===data.id?{...m,text:m.text+data.text}:m)}:p);if(type==='error')setError(data.error);if(type==='status')setStatus(data.text)});setReference(null)}catch(e){setError((e as Error).message);setText(value)}finally{setBusy(false);setStatus('')}};
 const transcribe=async(blob:Blob)=>{setBusy(true);setError('');setStatus('正在转成可编辑文字…');try{const wav=blob.type==='audio/wav'?blob:await toWav(blob);const data=await new Promise<string>((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]);r.onerror=no;r.readAsDataURL(wav)});const result=await api('/transcribe',{data,format:'wav'});setText(old=>old?old+'\n'+result.text:result.text);setStatus('转写已放入输入框，请检查后发送；录音不留档。')}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const toggleRecording=async()=>{if(recording){recorder.current?.stop();return}try{const media=await navigator.mediaDevices.getUserMedia({audio:true});const r=new MediaRecorder(media);recorder.current=r;let parts:Blob[]=[];r.ondataavailable=e=>parts.push(e.data);r.onstop=()=>{media.getTracks().forEach(t=>t.stop());if(recordTimer.current)clearTimeout(recordTimer.current);setRecording(false);const blob=new Blob(parts,{type:r.mimeType});parts=[];recorder.current=null;void transcribe(blob)};r.start();setRecording(true);recordTimer.current=setTimeout(()=>{if(r.state==='recording')r.stop()},60000)}catch(e){setError('无法使用麦克风，请允许权限或上传WAV录音。')}};
 if(!project)return <main className="entrance"><a className="brand">alva<span>生活，先于设计</span></a><section><span className="eyebrow">统一访问验证</span><h1>输入验证码，<br/>进入授权项目。</h1><p>请向项目发起人获取统一验证码。它可在多个设备重复使用，每台设备都会建立独立的限时会话。</p><label>统一验证码<input autoFocus value={accessCode} onChange={e=>setAccessCode(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void login()}} placeholder="输入项目发起人提供的验证码" autoComplete="off"/></label><button disabled={busy||accessCode.length<16} onClick={()=>void login()}>{busy?'验证中…':'验证并进入 →'}</button>{inviteToken&&<small>这是只读邀请链接，仍需统一验证码；只读身份不会升级为可编辑权限。</small>}{error&&<p className="error" role="alert">{error}</p>}</section></main>;
 if(location.pathname==='/render'&&project.scene)return <div style={{height:'100vh',position:'relative'}}><SceneView scene={project.scene} focusRoom={new URLSearchParams(location.search).get('room')||undefined}/></div>;
 return <div className="app"><header><a className="brand">alva<span>生活，先于设计</span></a><span className="project-name">{project.name}</span><span className={`save-state ${project.dirty?'dirty':''}`}>{project.dirty?'未保存工作稿':project.savedVersion?`已保存 · v${project.savedVersion}`:'尚未保存'}</span><button disabled={busy||readOnly||!project.scene} onClick={()=>void mutate('/save',{confirmed:true}).then(()=>setStatus('已保存到服务器')).catch(()=>{})}>保存版本</button><button onClick={()=>void api('/versions').then(setVersions).catch(e=>setError(e.message))}>历史</button><button disabled={busy||!project.savedVersion} onClick={()=>{setStatus('正在生成同版本交付包…');void fetch(`/api/export/${project.savedVersion}`).then(async r=>{if(!r.ok)throw new Error((await r.json()).error);const u=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=u;a.download=`alva-v${project.savedVersion}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);setStatus('交付包已生成')}).catch(e=>setError(e.message))}}>交付包</button><button disabled={readOnly} onClick={()=>void api('/invites',{}).then(r=>{setLink(`${location.origin}/#access=${r.token}`);setStatus('只读邀请已生成；对方仍需统一验证码')}).catch(e=>setError(e.message))}>分享</button><button onClick={()=>void logout()}>退出</button></header>
 {error&&<div className="error banner" role="alert">{error}<button onClick={()=>setError('')}>关闭</button></div>}
 {project.importState&&<div className="status banner" role="status">导入状态：{importStatusLabel(project.importState)}{project.sourceImage&&project.importState.status==='succeeded'&&<> · 来源：{importSourceLabel(project.sourceImage)}</>}</div>}
 {status&&<div className="status banner" role="status">{status}</div>}
 <main className={scene?'workspace':'workspace onboarding'}><aside className="chat"><div className="panel-heading"><span className="eyebrow">咨询</span><span>{readOnly?'只读视图':'你的生活需求'}</span></div><Conversation messages={project.messages}>
 <div className="conversation-cards">{(project as any).questionCards?.map((card:any)=>{const def=questions.find(q=>q.id===card.questionId);return def?<details key={card.questionId} open><summary>{card.reason}</summary><QuestionCard definition={def} project={project} roomId={room||project.scene?.rooms[0]?.id||''} mutate={mutate} readOnly={readOnly||busy}/></details>:null})}
 {(project as any).pendingAnswers?.map((a:any)=><article key={a.id}><small>待你确认 · {a.questionId}</small><p>原话：{a.quote}</p><p>拟记录：{a.text}</p><button disabled={busy||readOnly} onClick={()=>void mutate('/pending-answers/confirm',{id:a.id,confirmed:true}).catch(()=>{})}>确认写入问卷</button></article>)}
 {project.proposals.filter(p=>p.status==='proposed').map(p=><ProposalCard key={p.id} proposal={p} onAccept={selectedIds=>{if(!readOnly&&!busy)void mutate('/proposals/accept',{id:p.id,selectedIds,confirmed:true}).catch(()=>{})}}/>)}</div>
 <div className="composer expanded"><textarea aria-label="咨询消息" placeholder={project.scene?'聊聊生活习惯，或想调整的地方…':'可以先聊期待，或添加户型图…'} value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send()}}}/>{reference&&<small>已附参考图 <button onClick={()=>setReference(null)}>移除</button></small>}
 <div className="composer-actions"><input ref={upload} type="file" accept="image/png,image/jpeg,application/pdf" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void runImport(f);e.currentTarget.value=''}}/><input ref={referenceUpload} type="file" accept="image/png,image/jpeg" hidden onChange={e=>{const f=e.target.files?.[0];if(f){if(f.size>9000000){setError('参考图最大9MB');return}const r=new FileReader();r.onload=()=>setReference({mime:f.type,data:String(r.result).split(',')[1]});r.readAsDataURL(f)}e.currentTarget.value=''}}/><input ref={audioUpload} type="file" accept="audio/wav,.wav" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void transcribe(f);e.currentTarget.value=''}}/>
 <details className="add-menu"><summary aria-label="添加附件">＋</summary><div><button disabled={busy||readOnly} onClick={()=>upload.current?.click()}>户型图 / PDF</button><button disabled={busy||readOnly} onClick={()=>referenceUpload.current?.click()}>参考图片</button><button disabled={busy||readOnly} onClick={()=>audioUpload.current?.click()}>WAV录音</button></div></details><select aria-label="咨询模型"><option>gpt-5.5</option></select><button disabled={busy||readOnly} aria-label={recording?'停止录音':'开始录音'} onClick={()=>void toggleRecording()}>{recording?'结束录音':'语音'}</button>{busy?<button onClick={()=>void api('/cancel',{})}>取消</button>:<button disabled={readOnly||(!text.trim()&&!reference)} onClick={()=>void send()}>发送 ↑</button>}</div></div>
 {project.messages.some(m=>m.status==='failed'||m.status==='cancelled')&&<button disabled={busy||readOnly} onClick={()=>void send(project.messages.filter(m=>m.role==='user').at(-1)?.text||'')}>重试上一条消息</button>}
 <small className="footnote">语音先转为可编辑文字。建议由你确认后采用。</small></Conversation></aside>
 {scene?<section className="stage"><div className="stage-toolbar"><div className="segmented">{(['2d','3d','walk'] as const).map(m=><button key={m} className={mode===m?'active':''} onClick={()=>setMode(m)}>{m==='2d'?'平面':m==='3d'?'全屋':'漫游'}</button>)}</div><select aria-label="定位房间" value={room} onChange={e=>setRoom(e.target.value)}><option value="">全屋</option>{scene.rooms.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><span className="eyebrow">{candidate?'待你校正的候选':'当前工作稿'}</span></div>
 <div className="canvas-wrap">{mode==='2d'?<Plan onItemMove={!candidate&&!readOnly&&!busy?(id,x,y)=>void mutate('/commands',{changes:[{action:'update',targetId:id,values:{x,y}}],confirmed:true,reason:'二维拖动家具'}).catch(()=>{}):undefined} scene={scene} selected={selected} onSelect={setSelected} image={candidate?project.sourceImage:undefined} onChange={candidate&&!readOnly?s=>void mutate('/candidate/correct',{scene:s}).catch(()=>{}):undefined}/>:<SceneView onMove={!candidate&&!readOnly&&!busy?(id,x,y)=>void mutate('/commands',{changes:[{action:'update',targetId:id,values:{x,y}}],confirmed:true,reason:'三维拖动家具'}).catch(()=>{}):undefined} scene={scene} selected={selected} onSelect={setSelected} mode={mode} time={time} day={day} focusRoom={room}/>}</div>
 {mode==='walk'&&<p className="walk-help">点击场景进入 · WASD 移动 · 鼠标环顾 · Esc 暂停</p>}
 <div className="scene-footer"><span>{scene.calibration?`长度依据：${scene.calibration.source}`:'未校准：当前尺寸仅为候选估算'}</span>{mode!=='2d'&&<><label>太阳时 {time}:00<input aria-label="太阳时" type="range" min="0" max="24" step=".5" value={time} onChange={e=>setTime(+e.target.value)}/></label><label>年内第 {day} 天<input aria-label="季节日期" type="range" min="1" max="365" value={day} onChange={e=>setDay(+e.target.value)}/></label></>}</div>{mode!=='2d'&&<small className="geo">{scene.geography.assumption}</small>}
 </section>:<section className="intro-plate"><div className="outline-house"><span>⌂</span></div><span className="eyebrow">01 / 认识你的家</span><h2>一张户型图，<br/>一段关于生活的对话。</h2><p>把房子的轮廓交给 alva，<br/>把家的选择留给你。</p><button disabled={busy||readOnly} onClick={()=>upload.current?.click()}>添加户型图 →</button><small>单层住宅 · 先预览，再确认</small></section>}
 {scene&&<aside className="details"><div className="panel-heading"><span className="eyebrow">{candidate?'导入校核':'房屋资料'}</span><span>{scene.rooms.length} 个空间</span></div>{candidate?<><h2>先让比例准确。</h2><p>对照原图检查墙、门窗与房间。选择墙体后可拖动蓝色端点修正。再输入这条墙的真实长度。</p><label>校准墙<select value={wall?.id||''} onChange={e=>setSelected(e.target.value)}><option value="">选择一条已知长度的墙</option>{scene.walls.map((w,i)=><option value={w.id} key={w.id}>墙 {i+1} · 当前 {Math.hypot(w.b.x-w.a.x,w.b.y-w.a.y).toFixed(2)} m</option>)}</select></label><label>真实长度（米）<input aria-label="真实墙长" type="number" min=".1" step=".01" value={wallLength} onChange={e=>setWallLength(e.target.value)}/></label><label>测量依据<input aria-label="测量依据" value={lengthSource} onChange={e=>setLengthSource(e.target.value)}/></label><button disabled={!wall||!wallLength||busy||readOnly} onClick={()=>void mutate('/candidate/calibrate',{wallId:wall!.id,length:+wallLength,source:lengthSource}).catch(()=>{})}>按这条长度校准</button><button className="primary" disabled={!scene.calibration?.confirmed||busy||readOnly} onClick={()=>void mutate('/candidate/confirm',{confirmed:true}).then(()=>setMode('3d')).catch(()=>{})}>确认户型，开始规划 →</button></>:<WorkspacePanel project={project} roomId={room||scene.rooms[0]?.id||''} selected={selected} onSelect={setSelected} mutate={mutate} readOnly={readOnly||busy}/>}</aside>}
 </main>
 {versions.length>0&&<div className="modal"><section><h2>保存版本</h2>{versions.map(v=><div className="version-row" key={v.version}><span>v{v.version} · {v.summary}</span><button disabled={readOnly||busy} onClick={()=>void mutate('/restore',{version:v.version,confirmed:true}).then(()=>setVersions([])).catch(()=>{})}>整版恢复到工作稿</button></div>)}<button onClick={()=>setVersions([])}>关闭</button></section></div>}
 {link&&role&&<div className="modal"><section><h2>设计师只读邀请</h2><p>对方必须先输入统一验证码；邀请只保留只读身份，不能修改设计。</p><textarea readOnly value={link}/><button onClick={()=>void navigator.clipboard.writeText(link).then(()=>setStatus('链接已复制'))}>复制链接</button><button onClick={()=>setLink('')}>关闭</button></section></div>}
 </div>
}
createRoot(document.getElementById('root')!).render(<App/>);
