import {surfaceRoughness,wallSideStyles,type RoomStyles} from './room-style/surfaces.js';
import {applyWallMaterials} from './room-style/materials.js';
import React,{useEffect,useRef} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import type {SceneData} from '../../api/model.js';
export function SceneView({roomStyles={},scene,selected,onSelect,onMove,mode='3d',time=14,day=172,focusRoom}: {roomStyles?:RoomStyles;scene:SceneData;selected?:string;onSelect?:(id:string)=>void;onMove?:(id:string,x:number,y:number)=>void|Promise<void>;mode?:'3d'|'walk';time?:number;day?:number;focusRoom?:string}){
 const root=useRef<HTMLDivElement>(null),latest=useRef({onSelect,onMove});latest.current={onSelect,onMove};
 useEffect(()=>{
  const host=root.current!;const world=new THREE.Scene();world.background=new THREE.Color('#e7e5da');
  const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;host.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','全屋三维场景');
  const camera=new THREE.PerspectiveCamera(45,1,.05,150);const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;
  const points=scene.walls.flatMap(w=>[w.a,w.b]);const minX=Math.min(...points.map(p=>p.x)),maxX=Math.max(...points.map(p=>p.x)),minY=Math.min(...points.map(p=>p.y)),maxY=Math.max(...points.map(p=>p.y));const cx=(minX+maxX)/2,cy=(minY+maxY)/2,extent=Math.max(maxX-minX,maxY-minY,5);
  camera.position.set(cx+extent*.85,extent*1.1,cy+extent*.95);orbit.target.set(cx,0,cy);
  const ambient=new THREE.HemisphereLight('#fffae8','#797762',2);world.add(ambient);const sun=new THREE.DirectionalLight('#fff0ca',3);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-30,right:30,top:30,bottom:-30,near:.1,far:120});sun.shadow.bias=-.0004;world.add(sun);world.add(sun.target);sun.target.position.set(cx,0,cy);
  const rad=Math.PI/180,lat=scene.geography.latitude*rad,dec=23.44*rad*Math.sin(2*Math.PI*(284+day)/365),hour=(time-12)*15*rad;
  const altitude=Math.asin(Math.sin(lat)*Math.sin(dec)+Math.cos(lat)*Math.cos(dec)*Math.cos(hour));const azimuth=Math.atan2(Math.sin(hour),Math.cos(hour)*Math.sin(lat)-Math.tan(dec)*Math.cos(lat))+scene.geography.north*rad;
  sun.position.set(cx+Math.sin(azimuth)*35*Math.cos(altitude),Math.sin(altitude)*35,cy+Math.cos(azimuth)*35*Math.cos(altitude));sun.intensity=Math.max(0,Math.sin(altitude))*3.5;ambient.intensity=altitude>0?1.5:.25;world.background=new THREE.Color(altitude>0?'#e7e5da':'#282f39');
  const selectable:THREE.Object3D[]=[],wallBoxes:THREE.Box3[]=[];
  const box=(w:number,h:number,d:number,x:number,y:number,z:number,color:string,id?:string,rotation=0)=>{const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.75,metalness:0}));mesh.position.set(x,y,z);mesh.rotation.y=-rotation*rad;mesh.castShadow=true;mesh.receiveShadow=true;if(id){mesh.userData.id=id;selectable.push(mesh);if(id===selected){const edges=new THREE.LineSegments(new THREE.EdgesGeometry(mesh.geometry),new THREE.LineBasicMaterial({color:'#2478b2'}));mesh.add(edges)}}world.add(mesh);return mesh};
  for(const room of scene.rooms){const shape=new THREE.Shape(room.polygon.map(p=>new THREE.Vector2(p.x,-p.y)));const mesh=new THREE.Mesh(new THREE.ShapeGeometry(shape),new THREE.MeshStandardMaterial({color:roomStyles[room.id]?.floor.color||(room.id===focusRoom?'#d4d2b7':'#c7b69a'),roughness:roomStyles[room.id]?surfaceRoughness(roomStyles[room.id].floor):.8,side:THREE.DoubleSide}));mesh.rotation.x=-Math.PI/2;mesh.position.y=.005;mesh.receiveShadow=true;world.add(mesh)}
  for(const wall of scene.walls){const dx=wall.b.x-wall.a.x,dy=wall.b.y-wall.a.y,len=Math.hypot(dx,dy),angle=Math.atan2(dy,dx);const openings=scene.openings.filter(o=>o.wallId===wall.id).sort((a,b)=>a.offset-b.offset);let cursor=0;
   const segment=(start:number,end:number,bottom:number,height:number,color='#d9d5c5')=>{if(end-start<.001||height<=0)return;const middle=(start+end)/2;const m=box(end-start,height,wall.thickness,wall.a.x+Math.cos(angle)*middle,bottom+height/2,wall.a.y+Math.sin(angle)*middle,color,wall.id,angle/rad);applyWallMaterials(m,wallSideStyles(scene,roomStyles,m.position.x,m.position.z,angle,wall.thickness));if(bottom<1.7&&bottom+height>.1)wallBoxes.push(new THREE.Box3().setFromObject(m))};
   for(const o of openings){const a=o.offset*len-o.width/2,b=a+o.width;segment(cursor,a,0,wall.height);if(o.kind==='window'){segment(a,b,0,o.sill);const pane=box(o.width,o.height,.025,wall.a.x+Math.cos(angle)*(a+b)/2,o.sill+o.height/2,wall.a.y+Math.sin(angle)*(a+b)/2,'#adc7d0',o.id,angle/rad);(pane.material as THREE.MeshStandardMaterial).transparent=true;(pane.material as THREE.MeshStandardMaterial).opacity=.28}segment(a,b,o.sill+o.height,wall.height-o.sill-o.height);cursor=b}segment(cursor,len,0,wall.height);
  }
  for(const i of scene.items){const mesh=box(i.width,i.height,i.depth,i.x,i.height/2,i.y,i.color,i.id,i.rotation);const mat=mesh.material as THREE.MeshStandardMaterial;mat.roughness=i.material==='metal'?.25:i.material==='glass'?.1:.8;mat.metalness=i.material==='metal'?.65:0;if(i.material==='glass'){mat.transparent=true;mat.opacity=.6}}
  const grid=new THREE.GridHelper(extent*1.5,Math.ceil(extent*1.5),0xbcb9ad,0xd1cfc3);grid.position.set(cx,-.01,cy);world.add(grid);
  const resize=()=>{const {width,height}=host.getBoundingClientRect();renderer.setSize(width,height);camera.aspect=width/Math.max(height,1);camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(host);resize();
  const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let moving:THREE.Object3D|null=null,movingOrigin:THREE.Vector3|null=null,moved=false;let pointerDown:{x:number;y:number}|null=null,yaw=0,pitch=0,walking=false;const keys=new Set<string>();
  const paused=()=>document.activeElement instanceof HTMLElement&&!!document.activeElement.closest('input,textarea,select,[contenteditable=true]');
  const reset=()=>{keys.clear();walking=false;if(document.pointerLockElement===renderer.domElement)document.exitPointerLock()};
  const down=(e:PointerEvent)=>{pointerDown={x:e.clientX,y:e.clientY};moved=false;if(mode==='3d'&&latest.current.onMove){const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(selectable,false)[0];if(hit?.object.userData.id===selected&&scene.items.some(i=>i.id===selected&&!i.locked)){moving=hit.object;movingOrigin=hit.object.position.clone();orbit.enabled=false;renderer.domElement.setPointerCapture(e.pointerId)}}if(mode==='walk'&&!paused()){walking=true;void renderer.domElement.requestPointerLock()}};
  const click=(e:PointerEvent)=>{if(moving){const object=moving,origin=movingOrigin?.clone();moving=null;movingOrigin=null;orbit.enabled=true;if(moved){const result=latest.current.onMove?.(object.userData.id,Math.round(object.position.x*20)/20,Math.round(object.position.z*20)/20);if(result&&typeof (result as Promise<void>).catch==='function')void (result as Promise<void>).catch(()=>{if(origin)object.position.copy(origin)})}return}if(mode==='walk'||!pointerDown||Math.hypot(e.clientX-pointerDown.x,e.clientY-pointerDown.y)>5)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(selectable,false)[0];if(hit)latest.current.onSelect?.(hit.object.userData.id)};
  const dragMove=(e:PointerEvent)=>{if(!moving||!pointerDown)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const point=new THREE.Vector3();if(ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),point)){moving.position.x=point.x;moving.position.z=point.z;moved=true}};
  const keydown=(e:KeyboardEvent)=>{if(e.key==='Escape'){reset();return}if(mode==='walk'&&!paused()&&walking&&['w','a','s','d','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();keys.add(e.key.toLowerCase())}};
  const keyup=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase());
  const mouse=(e:MouseEvent)=>{if(mode==='walk'&&walking&&document.pointerLockElement===renderer.domElement&&!paused()){yaw-=e.movementX*.002;pitch=Math.max(-1.3,Math.min(1.3,pitch-e.movementY*.002))}};
  const lock=()=>{if(document.pointerLockElement!==renderer.domElement){walking=false;keys.clear()}};
  renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointerup',click);renderer.domElement.addEventListener('pointermove',dragMove);window.addEventListener('keydown',keydown);window.addEventListener('keyup',keyup);window.addEventListener('mousemove',mouse);window.addEventListener('blur',reset);document.addEventListener('focusin',reset);document.addEventListener('pointerlockchange',lock);
  if(mode==='walk'){orbit.enabled=false;const room=scene.rooms.find(r=>r.id===focusRoom)||scene.rooms[0];const p=room?.polygon||[{x:cx,y:cy}];camera.position.set(p.reduce((s,v)=>s+v.x,0)/p.length,1.62,p.reduce((s,v)=>s+v.y,0)/p.length);camera.rotation.order='YXZ'}else if(focusRoom){const room=scene.rooms.find(r=>r.id===focusRoom);if(room){const x=room.polygon.reduce((s,p)=>s+p.x,0)/room.polygon.length,y=room.polygon.reduce((s,p)=>s+p.y,0)/room.polygon.length;orbit.target.set(x,0,y);camera.position.set(x+4,6,y+5)}}
  const canStand=(x:number,z:number)=>{if(wallBoxes.some(b=>x>b.min.x-.17&&x<b.max.x+.17&&z>b.min.z-.17&&z<b.max.z+.17))return false;return !scene.items.some(i=>{const angle=i.rotation*rad,dx=x-i.x,dy=z-i.y,lx=dx*Math.cos(angle)+dy*Math.sin(angle),ly=-dx*Math.sin(angle)+dy*Math.cos(angle);return Math.abs(lx)<i.width/2+.17&&Math.abs(ly)<i.depth/2+.17&&i.height>.15})};
  let frame=0,last=performance.now(),lastCamera='',firstFrame=true;const animate=(now:number)=>{const dt=Math.min((now-last)/1000,.04);last=now;if(mode==='walk'){if(walking&&!paused()){const forward=Number(keys.has('w')||keys.has('arrowup'))-Number(keys.has('s')||keys.has('arrowdown')),side=Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft'));const step=2*dt/Math.max(1,Math.hypot(forward,side)),dx=(-Math.sin(yaw)*forward+Math.cos(yaw)*side)*step,dz=(-Math.cos(yaw)*forward-Math.sin(yaw)*side)*step;if(canStand(camera.position.x+dx,camera.position.z))camera.position.x+=dx;if(canStand(camera.position.x,camera.position.z+dz))camera.position.z+=dz}camera.rotation.set(pitch,yaw,0,'YXZ')}else orbit.update();const cameraKey=camera.position.toArray().join(',')+camera.quaternion.toArray().join(',');if(firstFrame||cameraKey!==lastCamera||moving){renderer.render(world,camera);firstFrame=false;lastCamera=cameraKey}frame=requestAnimationFrame(animate)};frame=requestAnimationFrame(animate);
  // Read-only instrumentation and capture are tied to the exact rendered scene.
  (host as any).alvaView={camera,canStand,sun,scene,world,pick:(clientX:number,clientY:number)=>{const rect=renderer.domElement.getBoundingClientRect();pointer.set((clientX-rect.left)/rect.width*2-1,-(clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);return ray.intersectObjects(selectable,false).map(hit=>hit.object.userData.id||'').filter(Boolean)},capture:()=>renderer.domElement.toDataURL('image/png')};
  return()=>{cancelAnimationFrame(frame);reset();observer.disconnect();orbit.dispose();window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);window.removeEventListener('mousemove',mouse);window.removeEventListener('blur',reset);document.removeEventListener('focusin',reset);document.removeEventListener('pointerlockchange',lock);world.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose())}});renderer.dispose();host.removeChild(renderer.domElement);delete (host as any).alvaView};
 },[scene,roomStyles,selected,mode,time,day,focusRoom]);
 return <div className="scene-host" ref={root} data-testid="scene-view"/>;
}
