import type {FastifyInstance} from 'fastify';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import type {BusinessTool} from '../codex.js';
import {DomainError,reject,type Project} from '../model.js';
import type {AlvaStore,Session} from '../store.js';
import {applyTopologyCommand} from './commands.js';

const Command=z.object({requestId:z.string().min(1).max(200),expectedRevision:z.number().int().min(0)});
const Structural=z.enum(['unknown','loadbearing','protected','nonloadbearing']);

export type ProfessionalGrant={id:string;projectId:string;linkId:string;operatorId:string;authority:string;grantEvidence:string;status:'active'|'revoked';grantedBy:string;grantedAt:string;revokedBy?:string;revokedAt?:string};
export type WallClassification={id:string;projectId:string;wallId:string;structural:z.infer<typeof Structural>;evidenceText:string;operatorId:string;authority:string;grantId:string;createdAt:string};

export function assertFormalWallChangeAllowed(wall:{structural:string;evidence:string[]},professional:boolean){
 if(wall.structural!=='nonloadbearing')reject('未知、承重或受保护墙禁止正式拆改；只有有专业依据的非承重墙可继续',403);
 if(!wall.evidence.some(e=>e.startsWith('professional-classification:')))reject('墙体缺少可追溯的专业分类证据；比例校准不构成拆改许可',403);
 if(!professional)reject('墙体正式拆改仅限已授权专业角色',403);
}

export async function listProfessionalGrants(store:AlvaStore,projectId:string){return (await store.db.query<any>(`SELECT id,project_id,link_id,operator_id,authority,grant_evidence,status,granted_by,granted_at,revoked_by,revoked_at FROM alva_professional_grants WHERE project_id=$1 ORDER BY granted_at DESC`,[projectId])).rows.map((r:any)=>({id:r.id,projectId:r.project_id,linkId:r.link_id,operatorId:r.operator_id,authority:r.authority,grantEvidence:r.grant_evidence,status:r.status,grantedBy:r.granted_by,grantedAt:new Date(r.granted_at).toISOString(),...(r.revoked_by?{revokedBy:r.revoked_by}:{}),...(r.revoked_at?{revokedAt:new Date(r.revoked_at).toISOString()}:{})}))}
export async function listWallClassifications(store:AlvaStore,projectId:string){return (await store.db.query<any>(`SELECT id,project_id,wall_id,structural,evidence_text,operator_id,authority,grant_id,created_at FROM alva_wall_classifications WHERE project_id=$1 ORDER BY created_at DESC`,[projectId])).rows.map((r:any)=>({id:r.id,projectId:r.project_id,wallId:r.wall_id,structural:r.structural,evidenceText:r.evidence_text,operatorId:r.operator_id,authority:r.authority,grantId:r.grant_id,createdAt:new Date(r.created_at).toISOString()})) as WallClassification[]}

export function professionalWallReadTools(store:AlvaStore,projectId:string):BusinessTool[]{return [{name:'get_wall_professional_evidence',description:'只读查询墙体专业分类、操作者与依据。不得创建专业授权、不得替专业人员分类、不得把比例校准当成拆改许可。',inputSchema:{type:'object',properties:{wallId:{type:'string'}},required:['wallId'],additionalProperties:false},run:async args=>{const {wallId}=z.object({wallId:z.string().min(1)}).parse(args),project=await store.get(projectId),wall=project.scene?.walls.find(w=>w.id===wallId);if(!wall)reject('墙体不存在',404);const current=wall!,history=(await listWallClassifications(store,projectId)).filter(c=>c.wallId===wallId);return {wall:{id:current.id,structural:current.structural,evidence:[...current.evidence]},classifications:history,formalRemovalAllowed:current.structural==='nonloadbearing'&&current.evidence.some(e=>e.startsWith('professional-classification:')),rule:'unknown/loadbearing/protected禁止正式拆改；校准不授予许可；主Chat不得伪造专业分类或授权'}}}]}

export function registerProfessionalWalls(app:FastifyInstance,store:AlvaStore,session:(req:object)=>Session){
 const activeGrant=async(s:Session)=>{if(s.role!=='professional'||!s.linkId)reject('仅已授权专业角色可执行此操作',403);const row=(await store.db.query<any>(`SELECT g.id,g.operator_id,g.authority FROM alva_professional_grants g JOIN alva_links l ON l.id=g.link_id WHERE g.project_id=$1 AND g.link_id=$2 AND g.status='active' AND l.revoked=false`,[s.projectId,s.linkId])).rows[0];if(!row)reject('专业授权已撤销或不存在',403);return {id:row.id,operatorId:row.operator_id,authority:row.authority}};
 app.get('/api/professional/access',async req=>{const s=session(req);if(s.role==='designer')reject('设计师只读角色不包含专业授权详情',403);const grants=await listProfessionalGrants(store,s.projectId);return {role:s.role,grants:s.role==='professional'?grants.filter(g=>g.linkId===s.linkId):grants}});
 app.get('/api/professional/walls',async req=>{const s=session(req);if(s.role==='designer')reject('设计师只读角色不包含专业分类来源',403);const project=await store.get(s.projectId),classifications=await listWallClassifications(store,s.projectId);return {walls:(project.scene?.walls||[]).map(w=>({...w,classifications:classifications.filter(c=>c.wallId===w.id)})),classifications}});
 app.post('/api/professional/walls/classify',async req=>{const s=session(req),grant=await activeGrant(s),b=Command.extend({wallId:z.string().min(1),structural:Structural,evidenceText:z.string().trim().min(3).max(2000)}).parse(req.body),classificationId=randomUUID(),now=new Date().toISOString();return store.mutate(s.projectId,b.requestId,b.expectedRevision,'professional-wall-classify',b,async(p:Project,tx:any)=>{if(p.candidate||!p.scene||!p.confirmedTopology)reject('请先完成并确认户型，再进行专业墙体分类');const scene=p.scene!,topology=p.confirmedTopology!,wall=scene.walls.find(w=>w.id===b.wallId);if(!wall)reject('墙体不存在');const currentWall=wall!;currentWall.structural=b.structural;currentWall.evidence=[...currentWall.evidence.filter(e=>!e.startsWith('professional-classification:')),`professional-classification:${classificationId}`];const topWall=topology.scene.walls.find(w=>w.id===b.wallId);if(topWall){topWall.structural=b.structural;topWall.evidence=[...topWall.evidence.filter(e=>!e.startsWith('professional-classification:')),`professional-classification:${classificationId}`]}const version=p.topologyVersions.find(v=>v.id===topology.id),versionWall=version?.scene.walls.find(w=>w.id===b.wallId);if(versionWall){versionWall.structural=b.structural;versionWall.evidence=[...versionWall.evidence.filter(e=>!e.startsWith('professional-classification:')),`professional-classification:${classificationId}`]}await tx.query(`INSERT INTO alva_wall_classifications(id,project_id,wall_id,structural,evidence_text,operator_id,authority,grant_id,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[classificationId,s.projectId,b.wallId,b.structural,b.evidenceText,grant.operatorId,grant.authority,grant.id,now]);p.changes.push({id:randomUUID(),description:`专业墙体分类：${b.wallId} → ${b.structural}`,evidenceIds:[],context:[`操作者 ${grant.operatorId}`,`授权 ${grant.authority}`,`依据 ${b.evidenceText}`,`classification ${classificationId}`],createdAt:now})})});
 app.post('/api/professional/walls/remove',async req=>{const s=session(req),grant=await activeGrant(s),b=Command.extend({wallId:z.string().min(1),reason:z.string().trim().min(3).max(1000),confirmed:z.literal(true)}).parse(req.body);return store.mutate(s.projectId,b.requestId,b.expectedRevision,'professional-wall-remove',b,p=>{if(p.candidate||!p.scene||!p.confirmedTopology)reject('请先完成并确认户型，再进行正式墙体拆改');const scene=p.scene!,wall=scene.walls.find(w=>w.id===b.wallId);if(!wall)reject('墙体不存在');assertFormalWallChangeAllowed(wall!,true);const result=applyTopologyCommand(scene,{kind:'remove-wall',wallId:b.wallId});p.scene=result.scene;p.confirmedTopology=undefined;p.confirmedBuilding=undefined;p.buildingCandidate=undefined;p.buildingState={status:'idle',attempts:0,updatedAt:new Date().toISOString()};p.proposals=[];p.zones=[];p.findings=p.findings.filter(f=>f.stage!=='review');p.changes.push({id:randomUUID(),description:`专业确认移除非承重墙：${b.wallId}`,evidenceIds:[],context:[`操作者 ${grant.operatorId}`,`授权 ${grant.authority}`,`原因 ${b.reason}`,'原确认拓扑及其下游设计已失效，需重新确认户型后再继续'],createdAt:new Date().toISOString()})})});
}
