import {createHash,randomUUID} from 'node:crypto';
import {z} from 'zod';
import type {FastifyInstance} from 'fastify';
import type {BusinessTool} from '../codex.js';
import {DomainError,reject,validateScene,pointInPolygon,type Project,type SceneData,type XY} from '../model.js';
import type {AlvaStore,Session} from '../store.js';
import {createTopologyVersion} from './calibration.js';

const Child=z.object({name:z.string().trim().min(1).max(80),purpose:z.string().trim().max(120),locked:z.boolean()}).strict();
const Assignment=z.object({kind:z.enum(['item','opening','answer','evidence','finding','context','purpose','scope','zone','recommendation','vision','draft','style']),id:z.string().min(1),childIndex:z.number().int().min(0).max(1)}).strict();
export const RoomSplitPreviewInput=z.object({expectedRevision:z.number().int().min(0),sourceRoomId:z.string().min(1),splitLine:z.object({a:z.object({x:z.number().finite(),y:z.number().finite()}),b:z.object({x:z.number().finite(),y:z.number().finite()})}).strict(),children:z.array(Child).length(2),assignments:z.array(Assignment).max(500).default([])}).strict();
export const RoomSplitConfirmInput=RoomSplitPreviewInput.extend({requestId:z.string().uuid(),baseTopologyId:z.string().min(1),previewFingerprint:z.string().regex(/^[a-f0-9]{64}$/),reason:z.string().trim().min(3).max(1000),confirmed:z.literal(true)}).strict();
type PreviewInput=z.infer<typeof RoomSplitPreviewInput>;type AssignmentInput=z.infer<typeof Assignment>;
type Requirement={kind:AssignmentInput['kind'];id:string;label:string;childIndex?:number;suggestedChildIndex?:number;options:{index:number;label:string;locked?:boolean}[]};
function previewFields(input:z.infer<typeof RoomSplitConfirmInput>):PreviewInput{return {expectedRevision:input.expectedRevision,sourceRoomId:input.sourceRoomId,splitLine:input.splitLine,children:input.children,assignments:input.assignments}}
const digest=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
const area=(p:XY[])=>Math.abs(p.reduce((s,q,i)=>{const n=p[(i+1)%p.length];return s+q.x*n.y-n.x*q.y},0))/2;
const side=(p:XY,a:XY,b:XY)=>(b.x-a.x)*(p.y-a.y)-(b.y-a.y)*(p.x-a.x);
const distance=(a:XY,b:XY)=>Math.hypot(a.x-b.x,a.y-b.y);
function clip(poly:XY[],a:XY,b:XY,positive:boolean){const out:XY[]=[];const inside=(p:XY)=>positive?side(p,a,b)>=-1e-7:side(p,a,b)<=1e-7;for(let i=0;i<poly.length;i++){const current=poly[i],next=poly[(i+1)%poly.length],ci=inside(current),ni=inside(next);if(ci)out.push({...current});if(ci!==ni){const s1=side(current,a,b),s2=side(next,a,b),t=s1/(s1-s2);out.push({x:current.x+(next.x-current.x)*t,y:current.y+(next.y-current.y)*t})}}return out}
function splitPolygon(poly:XY[],line:PreviewInput['splitLine']){if(distance(line.a,line.b)<.05)reject('拆分线长度过短，请重新选择分割位置');const left=clip(poly,line.a,line.b,true),right=clip(poly,line.a,line.b,false);if(left.length<3||right.length<3||area(left)<.1||area(right)<.1)reject('拆分线必须穿过空间并生成两个有效子空间');return [left,right] as [XY[],XY[]]}
function nearSegment(p:XY,a:XY,b:XY){const len=distance(a,b);if(len<1e-8)return distance(p,a)<.05;const t=Math.max(0,Math.min(1,((p.x-a.x)*(b.x-a.x)+(p.y-a.y)*(b.y-a.y))/(len*len)));return distance(p,{x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t})<.06}
function sourceOpenings(scene:SceneData,room:SceneData['rooms'][number]){return scene.openings.filter(o=>{const wall=scene.walls.find(w=>w.id===o.wallId);if(!wall)return false;return room.polygon.some((p,i)=>nearSegment(p,wall.a,wall.b)||nearSegment(room.polygon[i],wall.a,wall.b))||pointInPolygon(wall.a,room.polygon)||pointInPolygon(wall.b,room.polygon)})}
function childId(project:Project,source:string,line:PreviewInput['splitLine'],index:number){return 'room-split-'+digest({topology:project.confirmedTopology?.id,source,line,index}).slice(0,12)+'-'+index}
function requirements(project:Project,source:string,children:{id:string;name:string;locked:boolean}[]):Requirement[]{const opts=children.map((c,index)=>({index,label:c.name,locked:c.locked}));const out:Requirement[]=[];for(const a of project.answers.filter(x=>x.roomId===source))out.push({kind:'answer',id:a.questionId,label:'问卷：'+a.questionId+' · '+(a.text||a.state),options:opts});for(const e of project.evidence.filter(x=>x.roomId===source))out.push({kind:'evidence',id:e.id,label:'原话：'+e.quote,options:opts});for(const f of project.findings.filter(x=>x.roomIds.includes(source)))out.push({kind:'finding',id:f.id,label:'需求：'+f.title,options:opts});for(const e of project.userContextEntries?.filter(x=>x.roomIds.includes(source))||[])out.push({kind:'context',id:e.id,label:'上下文：'+e.text,options:opts});for(const p of project.purposeConfirmations?.filter(x=>x.roomId===source)||[])out.push({kind:'purpose',id:p.id,label:'用途确认：'+p.purpose,options:opts});for(const s of project.scopeRequests?.filter(x=>x.roomIds.includes(source)||x.excludedRoomIds.includes(source))||[])out.push({kind:'scope',id:s.id,label:'作用范围：'+s.reason,options:opts});for(const z of project.zones?.filter(x=>x.roomId===source)||[])out.push({kind:'zone',id:z.id,label:'功能分区：'+z.name,options:opts});for(const r of project.answerRecommendations?.filter(x=>x.roomId===source)||[])out.push({kind:'recommendation',id:r.id,label:'回答建议：'+r.questionId,options:opts});for(const q of project.visionQuestions?.filter(x=>x.roomId===source)||[])out.push({kind:'vision',id:q.id,label:'视觉问题：'+q.id,options:opts});for(const d of project.intakeProgress?.drafts.filter(x=>x.roomId===source)||[])out.push({kind:'draft',id:d.questionId,label:'问卷草稿：'+d.questionId,options:opts});if(project.roomStyles?.[source])out.push({kind:'style',id:source,label:'房间样式：'+source,options:opts});return out}
function assignmentMap(assignments:AssignmentInput[]){const map=new Map<string,number>();for(const a of assignments){const key=a.kind+':'+a.id;if(map.has(key))reject('拆分分配中存在重复对象：'+key);map.set(key,a.childIndex)}return map}
function suggested(point:XY,polygons:XY[][]){const hits=polygons.map((p,i)=>pointInPolygon(point,p)?i:-1).filter(i=>i>=0);return hits.length===1?hits[0]:undefined}
export function buildRoomSplitPreview(project:Project,raw:unknown){
  const input=RoomSplitPreviewInput.parse(raw);const scene=project.scene!;const topology=project.confirmedTopology!;
 if(!scene||!topology)reject('请先完成并确认户型拓扑');
  const source=scene.rooms.find(r=>r.id===input.sourceRoomId)!;if(!source)reject('待拆分空间不存在，请重新读取项目');
 if(source.locked&&input.children.some(c=>!c.locked))reject('锁定空间拆分后所有子空间必须继续锁定');
 const polygons=splitPolygon(source.polygon,input.splitLine),ids=polygons.map((_,i)=>childId(project,source.id,input.splitLine,i));
 const children=input.children.map((c,i)=>({id:ids[i],name:c.name,purpose:c.purpose,polygon:polygons[i],locked:c.locked}));
 const itemRows=scene.items.filter(i=>i.roomId===source.id).map(i=>({kind:'item' as const,id:i.id,label:'家具：'+i.name,point:{x:i.x,y:i.y},options:children.map((c,index)=>({index,label:c.name,locked:c.locked})),suggestedChildIndex:suggested({x:i.x,y:i.y},polygons)}));
 const openingRows=sourceOpenings(scene,source).map(o=>{const w=scene.walls.find(x=>x.id===o.wallId)!;const point={x:w.a.x+(w.b.x-w.a.x)*o.offset,y:w.a.y+(w.b.y-w.a.y)*o.offset};return {kind:'opening' as const,id:o.id,label:'门窗：'+o.id+' · '+o.kind,point,options:children.map((c,index)=>({index,label:c.name,locked:c.locked})),suggestedChildIndex:suggested(point,polygons)}});
 const req=requirements(project,source.id,children),map=assignmentMap(input.assignments),rows=[...itemRows,...openingRows,...req].map(r=>({...r,selectedChildIndex:map.get(r.kind+':'+r.id)})),missing=rows.filter(r=>r.selectedChildIndex===undefined),nextScene=structuredClone(scene);
 nextScene.rooms=[...nextScene.rooms.filter(r=>r.id!==source.id),...children];for(const item of nextScene.items.filter(i=>i.roomId===source.id)){const row=rows.find(r=>r.kind==='item'&&r.id===item.id)!;item.roomId=ids[row.selectedChildIndex??row.suggestedChildIndex??0]}
 validateScene(nextScene);const assignments={items:itemRows.map(r=>({id:r.id,childIndex:map.get('item:'+r.id)??r.suggestedChildIndex})),openings:openingRows.map(r=>({id:r.id,childIndex:map.get('opening:'+r.id)??r.suggestedChildIndex})),requirements:req.map(r=>({kind:r.kind,id:r.id,childIndex:map.get(r.kind+':'+r.id)}))},previewFingerprint=digest({baseTopologyId:topology.id,input,scene:nextScene,rows});
 return {scene:nextScene,sourceRoom:{id:source.id,name:source.name,purpose:source.purpose,locked:source.locked},children,assignments,assignmentRequirements:rows.map(r=>({kind:r.kind,id:r.id,label:r.label,options:r.options,suggestedChildIndex:r.suggestedChildIndex,selectedChildIndex:r.selectedChildIndex})),missing:missing.map(r=>({kind:r.kind,id:r.id,label:r.label})),readyToConfirm:missing.length===0,baseRevision:project.revision,baseTopologyId:topology.id,baseTopologyVersion:topology.version,previewFingerprint};
}
function selected(assignments:AssignmentInput[],kind:AssignmentInput['kind'],id:string,source:string,ids:string[]){const found=assignments.find(a=>a.kind===kind&&a.id===id);return ids[found?.childIndex??0]}
function replaceRoom(id:string,source:string,child:string){return id===source?child:id}
function migrateProject(project:Project,input:PreviewInput,preview:ReturnType<typeof buildRoomSplitPreview>){if(!preview.readyToConfirm)reject('仍有家具、门窗或需求未明确分配，请逐项选择子空间');const ids=preview.children.map(c=>c.id),source=input.sourceRoomId,assignments=input.assignments;const map=(kind:AssignmentInput['kind'],id:string)=>selected(assignments,kind,id,source,ids),roomFor=(kind:AssignmentInput['kind'],id:string)=>map(kind,id);project.scene=structuredClone(preview.scene);project.candidate=null;project.answers=project.answers.map(a=>a.roomId===source?{...a,roomId:roomFor('answer',a.questionId)}:a);project.evidence=project.evidence.map(e=>e.roomId===source?{...e,roomId:roomFor('evidence',e.id)}:e);project.findings=project.findings.map(f=>({...f,roomIds:f.roomIds.map(id=>replaceRoom(id,source,roomFor('finding',f.id)))}));project.userContextEntries=project.userContextEntries?.map(e=>({...e,roomIds:e.roomIds.map(id=>replaceRoom(id,source,roomFor('context',e.id)))}));project.purposeConfirmations=(project.purposeConfirmations||[]).map(p=>p.roomId===source?{...p,roomId:roomFor('purpose',p.id)}:p);project.scopeRequests=(project.scopeRequests||[]).map(s=>({...s,roomIds:s.roomIds.map(id=>replaceRoom(id,source,roomFor('scope',s.id))),excludedRoomIds:s.excludedRoomIds.map(id=>replaceRoom(id,source,roomFor('scope',s.id)))}));project.zones=(project.zones||[]).map(z=>z.roomId===source?{...z,roomId:roomFor('zone',z.id)}:z);project.answerRecommendations=project.answerRecommendations?.map(r=>r.roomId===source?{...r,roomId:roomFor('recommendation',r.id)}:r);project.visionQuestions=project.visionQuestions?.map(q=>q.roomId===source?{...q,roomId:roomFor('vision',q.id)}:q);if(project.homeVision)for(const response of project.homeVision.responses)if(response.chatAnswers)response.chatAnswers=response.chatAnswers.map(a=>a.roomId===source?{...a,roomId:ids[0]}:a);if(project.intakeProgress){project.intakeProgress.drafts=project.intakeProgress.drafts.map(d=>d.roomId===source?{...d,roomId:roomFor('draft',d.questionId)}:d);if(project.intakeProgress.cursor?.roomId===source)project.intakeProgress.cursor={...project.intakeProgress.cursor,roomId:ids[0]}}
 if(project.roomStyles?.[source]){const styleTarget=roomFor('style',source),styles={...project.roomStyles};delete styles[source];styles[styleTarget]=project.roomStyles[source];project.roomStyles=styles}project.roomStyleCandidates=project.roomStyleCandidates?.map(c=>c.roomId===source?{...c,roomId:ids[0],status:c.status==='pending'?'expired':c.status}:c);const labels={...(project.roomLabelPositions||{})};delete labels[source];preview.children.forEach(c=>{labels[c.id]={x:c.polygon.reduce((s,p)=>s+p.x,0)/c.polygon.length,y:c.polygon.reduce((s,p)=>s+p.y,0)/c.polygon.length}});project.roomLabelPositions=labels;project.proposals=project.proposals.map(p=>({...p,changes:p.changes.map(c=>({...c,targetId:c.targetId===source?ids[0]:c.targetId})),referenceIds:p.referenceIds?.map(id=>id===source?ids[0]:id)}));const oldTopology=project.confirmedTopology!,nextTopology=createTopologyVersion(project,project.scene!);project.topologyVersions=[...(project.topologyVersions||[]),nextTopology];project.confirmedTopology=nextTopology;project.buildingCandidate=undefined;project.confirmedBuilding=undefined;project.buildingState={status:'expired',topologyVersion:nextTopology.version,topologyFingerprint:nextTopology.sourceFingerprint,attempts:project.buildingState.attempts,updatedAt:new Date().toISOString(),error:'空间拆分已确认，旧建筑3D引用旧房间ID，已作废；请重新生成建筑3D'};project.roomSplitHistory=[...(project.roomSplitHistory||[]),{id:randomUUID(),sourceRoomId:source,sourceRoomName:preview.sourceRoom.name,childRoomIds:ids,childRoomNames:preview.children.map(c=>c.name),splitLine:input.splitLine,itemAssignments:preview.assignments.items.map(x=>({itemId:x.id,childRoomId:ids[x.childIndex??0]})),openingAssignments:preview.assignments.openings.map(x=>({openingId:x.id,childRoomId:ids[x.childIndex??0]})),requirementAssignments:preview.assignments.requirements.map(x=>({kind:x.kind,id:x.id,childRoomId:ids[x.childIndex??0]})),createdAt:new Date().toISOString()}];project.changes.push({id:randomUUID(),description:'拆分空间：'+preview.sourceRoom.name+' → '+preview.children.map(c=>c.name).join('、'),evidenceIds:project.evidence.filter(e=>e.roomId===ids[0]||e.roomId===ids[1]).map(e=>e.id),context:['来源空间ID：'+source+'；子空间ID：'+ids.join('、'),'家具、门窗、问卷、原话和房间引用均按用户逐项分配','旧建筑3D因引用旧房间ID已作废，需重新生成'] ,createdAt:new Date().toISOString()})}
async function migrateExternal(tx:any,projectId:string,source:string,target:string){await tx.query('UPDATE alva_reference_batches SET room_id=$3 WHERE project_id=$1 AND room_id=$2',[projectId,source,target]);const actions=(await tx.query('SELECT id,state FROM alva_chat_actions WHERE project_id=$1',[projectId])).rows;for(const row of actions){const state=row.state;if(state?.details?.roomId===source){state.details.roomId=target;await tx.query('UPDATE alva_chat_actions SET state=$3 WHERE project_id=$1 AND id=$2',[projectId,row.id,JSON.stringify(state)])}}}
export function registerRoomSplit(app:FastifyInstance,store:AlvaStore,session:(req:object)=>Session){const owner=(req:object)=>{const s=session(req);if(s.role!=='owner')reject('仅业主可预览和确认空间拆分',403);return s};app.post('/api/rooms/split/preview',async req=>{const s=owner(req),input=RoomSplitPreviewInput.parse(req.body),p=await store.get(s.projectId);if(p.revision!==input.expectedRevision)reject('项目已更新，请重新读取后预览',409);return buildRoomSplitPreview(p,input)});app.post('/api/rooms/split/confirm',async req=>{const s=owner(req),input=RoomSplitConfirmInput.parse(req.body);return store.mutate(s.projectId,input.requestId,input.expectedRevision,'room-split',input,async(p,tx)=>{if(p.confirmedTopology?.id!==input.baseTopologyId)reject('确认拓扑已变化，请重新生成空间拆分预览',409);const preview=buildRoomSplitPreview(p,previewFields(input));if(preview.previewFingerprint!==input.previewFingerprint)reject('空间拆分预览已变化，请重新核对后确认',409);migrateProject(p,previewFields(input),preview);await migrateExternal(tx,s.projectId,input.sourceRoomId,preview.children[0].id)})})}
export function roomSplitTools(store:AlvaStore,projectId:string):BusinessTool[]{return [{name:'preview_room_split',description:'预览一个空间拆分为两个子空间，返回新旧来源、家具/门窗/问卷/原话逐项分配要求；只读，不保存。',inputSchema:z.toJSONSchema(RoomSplitPreviewInput),run:async args=>{const input=RoomSplitPreviewInput.parse(args),p=await store.get(projectId);if(p.revision!==input.expectedRevision)throw new DomainError(409,'项目已更新，请先重新调用 get_snapshot');return buildRoomSplitPreview(p,input)}},{name:'confirm_room_split',description:'仅在用户明确确认拆分预览及所有对象分配后原子保存，保留来源记录并使旧建筑3D失效。不得代替用户确认。',inputSchema:z.toJSONSchema(RoomSplitConfirmInput),run:async args=>{const input=RoomSplitConfirmInput.parse(args),p=await store.get(projectId);if(p.revision!==input.expectedRevision)throw new DomainError(409,'项目已更新，请先重新调用 get_snapshot');return store.mutate(projectId,input.requestId,input.expectedRevision,'room-split',input,async(state,tx)=>{if(state.confirmedTopology?.id!==input.baseTopologyId)reject('确认拓扑已变化，请重新预览',409);const preview=buildRoomSplitPreview(state,previewFields(input));if(preview.previewFingerprint!==input.previewFingerprint)reject('空间拆分预览已变化，请重新核对后确认',409);migrateProject(state,previewFields(input),preview);await migrateExternal(tx,projectId,input.sourceRoomId,preview.children[0].id)})}}]}
