import {createHash,randomUUID} from 'node:crypto';
import polygonClipping from 'polygon-clipping';
import {z} from 'zod';
import type {FastifyInstance} from 'fastify';
import type {BusinessTool} from '../codex.js';
import {DomainError,reject,validateScene,type Project,type SceneData,type XY} from '../model.js';
import type {AlvaStore,Session} from '../store.js';
import {createTopologyVersion} from './calibration.js';

const Resolution=z.object({questionId:z.string().min(1),sourceRoomId:z.string().min(1)}).strict();
export const RoomMergePreviewInput=z.object({expectedRevision:z.number().int().min(0),sourceRoomIds:z.array(z.string().min(1)).min(2).max(12),name:z.string().trim().min(1).max(80),purpose:z.string().trim().min(1).max(120),locked:z.boolean(),roomStyleSourceRoomId:z.string().nullable().optional(),questionResolutions:z.array(Resolution).max(120).default([])}).strict();
export const RoomMergeConfirmInput=RoomMergePreviewInput.extend({requestId:z.string().uuid(),baseTopologyId:z.string().min(1),previewFingerprint:z.string().regex(/^[a-f0-9]{64}$/),reason:z.string().trim().min(3).max(1000),confirmed:z.literal(true)}).strict();
type PreviewInput=z.infer<typeof RoomMergePreviewInput>; type QuestionResolution=z.infer<typeof Resolution>;
type Conflict={kind:'question'|'room-style';key:string;message:string;options:{sourceRoomId:string;label:string;locked?:boolean}[]};

const digest=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
const unique=<T>(values:T[])=>[...new Set(values)];
const remap=(ids:string[],sources:Set<string>,target:string)=>unique(ids.map(id=>sources.has(id)?target:id));
const same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
const centroid=(polygon:XY[])=>polygon.reduce((s,p)=>({x:s.x+p.x/polygon.length,y:s.y+p.y/polygon.length}),{x:0,y:0});

function unionRooms(rooms:SceneData['rooms']):XY[]{
 const polygons=rooms.map(room=>[room.polygon.map(p=>[p.x,p.y] as [number,number])]);const result=(polygonClipping.union as any)(...polygons) as ReturnType<typeof polygonClipping.union>;
 if(result.length!==1||result[0].length!==1)reject('所选空间没有形成一个连续且无内洞的合并区域；请先处理边界或重新选择来源空间');
 const ring=result[0][0].map(([x,y])=>({x,y}));if(ring.length>1&&Math.hypot(ring[0].x-ring.at(-1)!.x,ring[0].y-ring.at(-1)!.y)<1e-8)ring.pop();if(ring.length<3)reject('合并后的房间边界无效');return ring;
}
function questionConflicts(project:Project,sourceIds:Set<string>,resolutions:QuestionResolution[]):Conflict[]{
 const conflicts:Conflict[]=[],resolution=new Map(resolutions.map(r=>[r.questionId,r.sourceRoomId]));
 const inspect=(rows:{questionId:string;roomId:string|null;locked?:boolean;text:string;state:string}[],label:string)=>{const by=new Map<string,typeof rows>();for(const row of rows)if(row.roomId&&sourceIds.has(row.roomId))by.set(row.questionId,[...(by.get(row.questionId)||[]),row]);for(const [questionId,group] of by)if(group.length>1){const variants=unique(group.map(row=>JSON.stringify({text:row.text,state:row.state,locked:!!row.locked})));if(variants.length<=1)continue;const chosen=resolution.get(questionId),locked=group.filter(row=>row.locked);if(chosen&&group.some(row=>row.roomId===chosen)&&(!locked.length||locked.every(row=>row.roomId===chosen)))continue;conflicts.push({kind:'question',key:questionId,message:label+' '+questionId+' 在来源空间中不一致，请明确保留哪一个来源；锁定回答不能被静默丢弃。',options:group.map(row=>({sourceRoomId:row.roomId!,label:row.roomId+': '+(row.state==='answered'?row.text:row.state),locked:!!row.locked}))})}};
 inspect(project.answers,'已确认问卷');inspect((project.intakeProgress?.drafts||[]) as any[],'问卷草稿');return conflicts;
}
function styleConflict(project:Project,sourceIds:string[],chosen?:string|null):Conflict[]{const styles=sourceIds.filter(id=>project.roomStyles?.[id]).map(id=>({id,style:project.roomStyles![id]}));if(styles.length<2||styles.every(x=>same(x.style,styles[0].style))||!!chosen&&styles.some(x=>x.id===chosen))return [];return [{kind:'room-style',key:'roomStyle',message:'来源空间存在不同的已确认房间样式，请明确合并后沿用哪一个来源空间的样式。',options:styles.map(x=>({sourceRoomId:x.id,label:x.id}))}]}
function mergedRoomId(project:Project,sourceRoomIds:string[]){return 'room-merge-'+digest({topology:project.confirmedTopology?.id,rooms:[...sourceRoomIds].sort()}).slice(0,12)}
function previewFields(input:z.infer<typeof RoomMergeConfirmInput>|PreviewInput):PreviewInput{return {expectedRevision:input.expectedRevision,sourceRoomIds:input.sourceRoomIds,name:input.name,purpose:input.purpose,locked:input.locked,roomStyleSourceRoomId:input.roomStyleSourceRoomId,questionResolutions:input.questionResolutions}}

export function buildRoomMergePreview(project:Project,raw:unknown){
 const input=RoomMergePreviewInput.parse(raw);if(!project.scene||!project.confirmedTopology)reject('请先完成并确认户型拓扑');const scene=project.scene!,topology=project.confirmedTopology!;
 const sourceRoomIds=unique(input.sourceRoomIds);if(sourceRoomIds.length!==input.sourceRoomIds.length)reject('来源空间不能重复');const sourceSet=new Set(sourceRoomIds),rooms=sourceRoomIds.map(id=>scene.rooms.find(r=>r.id===id));if(rooms.some(r=>!r))reject('至少一个来源空间已不存在，请重新读取项目');if(rooms.some(r=>r!.locked)&&!input.locked)reject('来源中包含锁定房间；合并后必须继续保持房间锁定，若要解除请先单独解锁');
 const id=mergedRoomId(project,sourceRoomIds),polygon=unionRooms(rooms as SceneData['rooms']),next=structuredClone(scene),merged={id,name:input.name,purpose:input.purpose,polygon,locked:input.locked};next.rooms=[...next.rooms.filter(r=>!sourceSet.has(r.id)),merged];for(const item of next.items)if(sourceSet.has(item.roomId))item.roomId=id;validateScene(next);
 const conflicts=[...questionConflicts(project,sourceSet,input.questionResolutions),...styleConflict(project,sourceRoomIds,input.roomStyleSourceRoomId)],openingContinuity=next.openings.map(o=>({openingId:o.id,wallId:o.wallId,unchanged:true})),previewFingerprint=digest({baseTopologyId:topology.id,input:{...input,sourceRoomIds},scene:next,conflicts});
 return {scene:next,mergedRoom:merged,sourceRooms:(rooms as SceneData['rooms']).map(r=>({id:r.id,name:r.name,purpose:r.purpose,locked:r.locked})),openingContinuity,conflicts,readyToConfirm:conflicts.length===0,baseRevision:project.revision,baseTopologyId:topology.id,baseTopologyVersion:topology.version,previewFingerprint};
}
function pickScoped<T extends {questionId:string;roomId:string|null}>(rows:T[],sourceSet:Set<string>,target:string,resolutions:QuestionResolution[],signature:(row:T)=>unknown):T[]{const out=rows.filter(row=>!row.roomId||!sourceSet.has(row.roomId)),groups=new Map<string,T[]>(),choice=new Map(resolutions.map(r=>[r.questionId,r.sourceRoomId]));for(const row of rows)if(row.roomId&&sourceSet.has(row.roomId))groups.set(row.questionId,[...(groups.get(row.questionId)||[]),row]);for(const [questionId,group] of groups){let chosen=group[0];if(group.length>1&&!group.every(row=>same(signature(row),signature(group[0])))){const room=choice.get(questionId);chosen=group.find(row=>row.roomId===room)!;if(!chosen)reject('问题 '+questionId+' 的来源选择已失效，请重新预览',409)}out.push({...chosen,roomId:target})}return out}
function migrateProject(project:Project,input:PreviewInput,preview:ReturnType<typeof buildRoomMergePreview>){
 if(!preview.readyToConfirm)reject('仍有未解决的来源冲突，请先明确问卷或房间样式的保留来源');const sourceSet=new Set(input.sourceRoomIds),target=preview.mergedRoom.id,now=new Date().toISOString();project.scene=structuredClone(preview.scene);project.candidate=null;
 project.answers=pickScoped(project.answers,sourceSet,target,input.questionResolutions,row=>({text:row.text,state:row.state,locked:row.locked,confirmed:row.confirmed}));project.evidence=project.evidence.map(e=>e.roomId&&sourceSet.has(e.roomId)?{...e,roomId:target}:e);project.findings=project.findings.map(f=>({...f,roomIds:remap(f.roomIds,sourceSet,target)}));project.userContextEntries=project.userContextEntries?.map(e=>({...e,roomIds:remap(e.roomIds,sourceSet,target)}));project.zones=(project.zones||[]).map(z=>sourceSet.has(z.roomId)?{...z,roomId:target}:z);project.purposeConfirmations=(project.purposeConfirmations||[]).map(c=>sourceSet.has(c.roomId)?{...c,roomId:target}:c);project.scopeRequests=(project.scopeRequests||[]).map(s=>({...s,roomIds:remap(s.roomIds,sourceSet,target),excludedRoomIds:remap(s.excludedRoomIds,sourceSet,target)}));project.answerRecommendations=project.answerRecommendations?.map(r=>r.roomId&&sourceSet.has(r.roomId)?{...r,roomId:target,status:r.status==='pending'||r.status==='running'?'invalidated':r.status}:r);project.visionQuestions=project.visionQuestions?.map(q=>q.roomId&&sourceSet.has(q.roomId)?{...q,roomId:target,status:q.status==='awaiting_owner_confirmation'?'dismissed':q.status}:q);
 if(project.homeVision)for(const response of project.homeVision.responses)if(response.chatAnswers)response.chatAnswers=response.chatAnswers.map(a=>a.roomId&&sourceSet.has(a.roomId)?{...a,roomId:target}:a);if(project.intakeProgress){project.intakeProgress.drafts=pickScoped(project.intakeProgress.drafts,sourceSet,target,input.questionResolutions,row=>({text:row.text,state:row.state}));if(project.intakeProgress.cursor?.roomId&&sourceSet.has(project.intakeProgress.cursor.roomId))project.intakeProgress.cursor={...project.intakeProgress.cursor,roomId:target}}
 project.proposals=project.proposals.map(p=>({...p,changes:p.changes.map(c=>sourceSet.has(c.targetId)?{...c,targetId:target}:c),referenceIds:p.referenceIds?.map(id=>sourceSet.has(id)?target:id)}));const styleRooms=input.sourceRoomIds.filter(id=>project.roomStyles?.[id]),styleSource=input.roomStyleSourceRoomId&&styleRooms.includes(input.roomStyleSourceRoomId)?input.roomStyleSourceRoomId:styleRooms[0];if(project.roomStyles){const next={...project.roomStyles};for(const id of input.sourceRoomIds)delete next[id];if(styleSource)next[target]=project.roomStyles[styleSource];project.roomStyles=next}project.roomStyleCandidates=project.roomStyleCandidates?.map(c=>sourceSet.has(c.roomId)?{...c,roomId:target,status:c.status==='pending'?'expired':c.status}:c);const labels={...(project.roomLabelPositions||{})};for(const id of input.sourceRoomIds)delete labels[id];labels[target]=centroid(preview.mergedRoom.polygon);project.roomLabelPositions=labels;project.layoutReview=undefined;project.layoutReviewAdoption=undefined;
 const oldTopology=project.confirmedTopology!,nextTopology=createTopologyVersion(project,project.scene!);project.topologyVersions=[...(project.topologyVersions||[]),nextTopology];project.confirmedTopology=nextTopology;project.buildingCandidate=undefined;project.confirmedBuilding=undefined;project.buildingState={status:'expired',topologyVersion:nextTopology.version,topologyFingerprint:nextTopology.sourceFingerprint,attempts:project.buildingState.attempts,updatedAt:now,error:'空间合并已确认，旧建筑3D引用旧房间ID，已作废；请重新生成建筑3D'};project.roomMergeHistory=[...(project.roomMergeHistory||[]),{id:randomUUID(),mergedRoomId:target,sourceRoomIds:[...input.sourceRoomIds],sourceRoomNames:preview.sourceRooms.map(r=>r.name),name:input.name,purpose:input.purpose,createdAt:now}];project.changes.push({id:randomUUID(),description:'合并空间：'+preview.sourceRooms.map(r=>r.name).join(' + ')+' → '+input.name,evidenceIds:[],context:['来源房间ID：'+input.sourceRoomIds.join('、')+'；新房间ID：'+target,'家具、问卷、原话、功能分区与已确认偏好引用已迁移到新房间；原拓扑 v'+oldTopology.version+' → 新拓扑 v'+nextTopology.version,'旧建筑3D因引用旧房间ID已作废，需重新生成'],createdAt:now});assertNoDanglingRoomReferences(project,sourceSet);
}
export function assertNoDanglingRoomReferences(project:Project,sourceSet:Set<string>){const bad:string[]=[];const hit=(label:string,id:string|null|undefined)=>{if(id&&sourceSet.has(id))bad.push(label+':'+id)};const hits=(label:string,ids:string[])=>ids.forEach(id=>hit(label,id));project.scene?.items.forEach(i=>hit('item',i.roomId));project.answers.forEach(a=>hit('answer',a.roomId));project.evidence.forEach(e=>hit('evidence',e.roomId));project.findings.forEach(f=>hits('finding',f.roomIds));project.userContextEntries?.forEach(e=>hits('context',e.roomIds));project.zones?.forEach(z=>hit('zone',z.roomId));project.purposeConfirmations?.forEach(c=>hit('purpose',c.roomId));project.scopeRequests?.forEach(s=>{hits('scope',s.roomIds);hits('scope-excluded',s.excludedRoomIds)});project.answerRecommendations?.forEach(r=>hit('recommendation',r.roomId));project.visionQuestions?.forEach(q=>hit('vision-question',q.roomId));project.homeVision?.responses.forEach(r=>r.chatAnswers?.forEach(a=>hit('vision-answer',a.roomId)));project.intakeProgress?.drafts.forEach(d=>hit('draft',d.roomId));hit('cursor',project.intakeProgress?.cursor?.roomId);Object.keys(project.roomStyles||{}).forEach(id=>hit('room-style',id));project.roomStyleCandidates?.forEach(c=>hit('style-candidate',c.roomId));project.proposals.forEach(p=>{p.changes.forEach(c=>hit('proposal-change',c.targetId));(p.referenceIds||[]).forEach(id=>hit('proposal-ref',id))});if(bad.length)reject('空间合并后仍有旧房间引用：'+bad.join('、'),500)}
async function migrateExternalRoomReferences(tx:any,projectId:string,sourceRoomIds:string[],target:string){for(const source of sourceRoomIds)await tx.query('UPDATE alva_reference_batches SET room_id=$3 WHERE project_id=$1 AND room_id=$2',[projectId,source,target]);const actions=(await tx.query('SELECT id,state FROM alva_chat_actions WHERE project_id=$1',[projectId])).rows;for(const row of actions){const state=row.state;if(state?.details?.roomId&&sourceRoomIds.includes(state.details.roomId)){state.details.roomId=target;await tx.query('UPDATE alva_chat_actions SET state=$3 WHERE project_id=$1 AND id=$2',[projectId,row.id,JSON.stringify(state)])}}}
export function registerRoomMerge(app:FastifyInstance,store:AlvaStore,session:(req:object)=>Session){const owner=(req:object)=>{const s=session(req);if(s.role!=='owner')reject('仅业主可预览和确认空间合并',403);return s};app.post('/api/rooms/merge/preview',async req=>{const s=owner(req),input=RoomMergePreviewInput.parse(req.body),project=await store.get(s.projectId);if(project.revision!==input.expectedRevision)reject('项目已更新，请重新读取后预览',409);return buildRoomMergePreview(project,input)});app.post('/api/rooms/merge/confirm',async req=>{const s=owner(req),input=RoomMergeConfirmInput.parse(req.body);return store.mutate(s.projectId,input.requestId,input.expectedRevision,'room-merge',input,async(p,tx)=>{if(p.confirmedTopology?.id!==input.baseTopologyId)reject('确认拓扑已变化，请重新生成空间合并预览',409);const preview=buildRoomMergePreview(p,previewFields(input));if(preview.previewFingerprint!==input.previewFingerprint)reject('空间合并预览已变化，请重新核对后确认',409);migrateProject(p,input,preview);await migrateExternalRoomReferences(tx,s.projectId,input.sourceRoomIds,preview.mergedRoom.id)})})}
export function roomMergeTools(store:AlvaStore,projectId:string):BusinessTool[]{return [{name:'preview_room_merge',description:'预览两个或以上连续空间的合并。返回新边界、新房间ID、来源关系、门窗连续性和问卷/样式冲突；只读，不保存。若 conflicts 非空必须先询问用户选择来源。',inputSchema:z.toJSONSchema(RoomMergePreviewInput),run:async args=>{const input=RoomMergePreviewInput.parse(args),p=await store.get(projectId);if(p.revision!==input.expectedRevision)throw new DomainError(409,'项目已更新，请先重新调用 get_snapshot');return buildRoomMergePreview(p,input)}},{name:'confirm_room_merge',description:'仅在用户明确确认无冲突的空间合并预览后原子保存，并迁移家具、问卷、原话、锁定状态及其他房间引用。旧建筑3D会失效。不得代替用户确认。',inputSchema:z.toJSONSchema(RoomMergeConfirmInput),run:async args=>{const input=RoomMergeConfirmInput.parse(args),p=await store.get(projectId);if(p.revision!==input.expectedRevision)throw new DomainError(409,'项目已更新，请先重新调用 get_snapshot');return store.mutate(projectId,input.requestId,input.expectedRevision,'room-merge',input,async(state,tx)=>{if(state.confirmedTopology?.id!==input.baseTopologyId)reject('确认拓扑已变化，请重新预览',409);const preview=buildRoomMergePreview(state,previewFields(input));if(preview.previewFingerprint!==input.previewFingerprint)reject('空间合并预览已变化，请重新核对',409);migrateProject(state,input,preview);await migrateExternalRoomReferences(tx,projectId,input.sourceRoomIds,preview.mergedRoom.id)})}}]}
