import {chromium} from '@playwright/test';import {readFile,mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const origin='https://prod.huiyuanxp.com',run=new Date().toISOString().replace(/[-:.]/g,'')+'-ALVA066-production-mcp',out='evidence/'+run;await mkdir(out,{recursive:true});const result:any={run,origin,pass:false,checks:[]};const errors:string[]=[];
const browser=await chromium.launch({headless:true,args:['--disable-dev-shm-usage','--renderer-process-limit=1','--disable-extensions','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1280,height:900}});page.setDefaultTimeout(45000);page.on('pageerror',e=>errors.push(e.message));
const state=()=>page.evaluate(async()=>await(await fetch('/api/chat/stages')).json());
async function switchTo(stage:string){const s=await state();if(s.active===stage)return;await page.getByRole('region',{name:'设计阶段'}).getByRole('button',{name:stage==='living'?'生活设计':'户型导入',exact:true}).click();await page.waitForFunction(stage=>document.querySelector('.chat-stages button[aria-current="step"]')?.textContent===(stage==='living'?'生活设计':'户型导入'),stage);}
async function readStage(stage:string){const tool=stage==='living'?'get_topology_diagnostics':'inspect_topology';await page.getByLabel('咨询消息').fill(`生产发布只读验收：请先调用 mcp_list_tools 读取当前阶段工具目录，再实际调用 ${tool} 读取户型诊断。只回复诊断读取是否成功及告警数量；不要修改任何设计，不生成候选或确认卡，不保存，不记录用户需求。`);const waiting=page.waitForResponse(r=>r.url().endsWith('/api/chat')&&r.request().method()==='POST',{timeout:180000});await page.getByRole('button',{name:'发送 ↑',exact:true}).click();const response=await waiting;await response.finished();assert.equal(response.status(),200);await page.getByRole('button',{name:'发送 ↑',exact:true}).waitFor();const last=await page.evaluate(async()=>{const p=await(await fetch('/api/project')).json(),m=p.messages.filter((m:any)=>m.role==='assistant').at(-1);return {status:m?.status,tools:m?.toolCalls,stage:m?.stage}});assert.equal(last.status,'completed');assert.ok(last.tools?.some((t:any)=>t.name===tool&&!t.isError),`Expected ${tool} execution`);assert.ok(last.tools.every((t:any)=>t.stage===stage));result.checks.push({stage,tool,completed:true,actualTools:last.tools});return state();}
let original:string|undefined;
try{
 await page.goto(origin);await page.getByLabel('统一验证码').fill((await readFile('.runtime/alva066-release/access-code','utf8')).trim());await page.getByRole('button',{name:'验证并进入 →'}).click();await page.getByLabel('咨询消息').waitFor();original=(await state()).active;assert.equal(original,'living');
 await page.evaluate(async()=>{const p=await(await fetch('/api/project')).json();const keys=['scene','candidate','confirmedTopology','confirmedBuilding','buildingCandidate','answers','roomStyles','userContextEntries','savedVersion','proposals'];(window as any).__alvaCheckKeys=keys;(window as any).__alvaCheckBefore=JSON.stringify(keys.map(k=>p[k]));});
 const living=await readStage('living');assert.ok(living.threads.living.threadId);await switchTo('floorplan');const floor=await readStage('floorplan');assert.ok(floor.threads.floorplan.threadId);await switchTo('living');const resumed=await state();assert.equal(resumed.threads.living.threadId,living.threads.living.threadId);await switchTo('floorplan');assert.equal((await state()).threads.floorplan.threadId,floor.threads.floorplan.threadId);await switchTo('living');
 result.originalThreadsResumed=true;result.designUnchanged=await page.evaluate(async()=>{const p=await(await fetch('/api/project')).json();return (window as any).__alvaCheckBefore===JSON.stringify((window as any).__alvaCheckKeys.map((k:string)=>p[k]));});assert.equal(result.designUnchanged,true);assert.deepEqual(errors,[]);result.errors=errors;result.restoredOriginalStage=true;result.pass=true;
}catch(e){result.error=String(e);throw e}finally{if(original){try{await switchTo(original);result.restoredOriginalStage=(await state()).active===original}catch{result.restoredOriginalStage=false}}await browser.close();await writeFile(out+'/result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result))}
