import {currentLanguage,localize} from './i18n/context.js';
import {DomainError} from './model.js';
import type {FastifyInstance} from 'fastify';import {chromium} from '@playwright/test';import {zipSync,strToU8} from 'fflate';import {createHash} from 'node:crypto';import {createCanvas,loadImage} from '@napi-rs/canvas';
import type {AlvaStore,Session} from './store.js';import type {Project} from './model.js';import {catalogue} from './business.js';import {confirmedReferencePreferencesFromProject} from './references.js';import {deliverySections,financialContentExcluded} from './delivery-content.js';
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));
export function planSvg(p:Project){const s=p.scene!,points=s.walls.flatMap(w=>[w.a,w.b]);const minX=Math.min(...points.map(p=>p.x))-.6,minY=Math.min(...points.map(p=>p.y))-.6,width=Math.max(...points.map(p=>p.x))-minX+.6,height=Math.max(...points.map(p=>p.y))-minY+.6;return `<svg xmlns="http://www.w3.org/2000/svg" width="3000" height="2200" viewBox="${minX} ${minY} ${width} ${height}"><rect x="${minX}" y="${minY}" width="${width}" height="${height}" fill="#f5f3ea"/>${s.rooms.map(r=>`<polygon points="${r.polygon.map(p=>`${p.x},${p.y}`).join(' ')}" fill="${p.roomStyles?.[r.id]?.floor.color||'#e5dfcf'}"/><text x="${r.polygon.reduce((s,p)=>s+p.x,0)/r.polygon.length}" y="${r.polygon.reduce((s,p)=>s+p.y,0)/r.polygon.length}" text-anchor="middle" font-size=".18" fill="#4e5645">${esc(r.name)}</text>`).join('')}${s.walls.map(w=>`<line x1="${w.a.x}" y1="${w.a.y}" x2="${w.b.x}" y2="${w.b.y}" stroke="#747869" stroke-width="${w.thickness}"/>`).join('')}${s.openings.map(o=>{const w=s.walls.find(w=>w.id===o.wallId)!,x=w.a.x+(w.b.x-w.a.x)*o.offset,y=w.a.y+(w.b.y-w.a.y)*o.offset,angle=Math.atan2(w.b.y-w.a.y,w.b.x-w.a.x)*180/Math.PI;return `<rect x="${x-o.width/2}" y="${y-.08}" width="${o.width}" height=".16" fill="${o.kind==='door'?'#f5f3ea':'#83a6b2'}" transform="rotate(${angle} ${x} ${y})"/>`}).join('')}${s.items.map(i=>`<rect x="${i.x-i.width/2}" y="${i.y-i.depth/2}" width="${i.width}" height="${i.depth}" transform="rotate(${i.rotation} ${i.x} ${i.y})" fill="${i.color}" stroke="#777" stroke-width=".02"/>`).join('')}<text x="${minX+.1}" y="${minY+.25}" font-size=".16">alva · v${p.savedVersion} · ${localize('单位')} m · ${esc(s.calibration?.source||localize('未校准'))}</text></svg>`}
export const sections=deliverySections;

export function docx(title:string,parts:ReturnType<typeof sections>){const paragraph=(t:string,heading=false)=>`<w:p>${heading?'<w:pPr><w:pStyle w:val="Heading1"/></w:pPr>':''}<w:r><w:t xml:space="preserve">${esc(t)}</w:t></w:r></w:p>`;const content=paragraph(title,true)+parts.map(([name,lines])=>paragraph(name as string,true)+(lines as string[]).map(l=>paragraph(l)).join('')).join('');return zipSync({'[Content_Types].xml':strToU8('<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>'),'_rels/.rels':strToU8('<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>'),'word/document.xml':strToU8(`<?xml version="1.0" encoding="UTF-8"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${content}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1000" w:bottom="1000" w:left="1000" w:right="1000"/></w:sectPr></w:body></w:document>`),'word/_rels/document.xml.rels':strToU8('<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>'),'word/styles.xml':strToU8('<?xml version="1.0"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:rPr><w:rFonts w:eastAsia="Microsoft YaHei"/><w:sz w:val="22"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:basedOn w:val="Normal"/><w:rPr><w:b/><w:sz w:val="30"/></w:rPr></w:style></w:styles>')})}
export function ownerHtml(p:Project,version:number,wholeHomePng:Uint8Array,svg:string){const owner=sections(p,'owner');return `<!doctype html><html lang="${currentLanguage()==='en'?'en':'zh-CN'}"><meta charset="utf-8"><style>body{font:14px "WenQuanYi Zen Hei",sans-serif;color:#394233;line-height:1.8}h1{font-size:25px}h2{font-size:19px;border-bottom:1px solid #ccc;padding-top:20px}img,svg{width:100%;height:auto}section{break-inside:avoid}</style><h1>${esc(p.name)} · alva v${version}</h1><p>${localize('业主需求与方案交付 · 同一保存版本 · 待专业核实项独立列出')}</p><img src="data:image/png;base64,${Buffer.from(wholeHomePng).toString('base64')}"/>${owner.map(([name,lines])=>`<section><h2>${esc(name)}</h2>${(lines as string[]).map(t=>`<p>${esc(t)}</p>`).join('')}</section>`).join('')}<h2>${localize('同版本高清平面图')}</h2>${svg}</html>`}
function snapshotFingerprint(p:Project){return createHash('sha256').update(JSON.stringify(p)).digest('hex')}
function safeFilename(name:string){const base=name.split(/[\\/]/).pop()||'source';return base.replace(/[^\w.\-\u4e00-\u9fff]/g,'_').slice(0,120)||'source'}
function sourceReference(p:Project,version:number){const source=p.sourceImage;if(!source)return {version,available:false,items:[] as Record<string,unknown>[]};const originalMime=source.originalMime||source.mime,filename=safeFilename(source.filename),extension=originalMime==='application/pdf'?'.pdf':originalMime==='image/jpeg'?'.jpg':'.png',path=`references/${filename.toLowerCase().endsWith(extension)?filename:`${filename}${extension}`}`,data=source.originalData||source.data;return {version,available:true,policy:'仅作为参考图保留，不作为已保存场景的权威几何；原图来源和PDF页码显式标注。',items:[{path,filename:source.filename,mime:originalMime,page:source.page,pages:source.pages,isReference:true,authoritative:false}],file:{path,data:Buffer.from(data,'base64')}}}
export function deliveryManifest(p:Project,version:number,fingerprint:string,files:Record<string,Uint8Array>){return {format:'alva-delivery-v1',projectId:p.id,version,sourceSnapshot:{version,snapshotFingerprint:fingerprint},units:'m',imageSource:'Rendered from this exact server snapshot; no reference images substituted',referencePolicy:'references/* are explicitly marked as reference-only and are never substituted for saved scene images',relations:{roomMergeHistory:p.roomMergeHistory||[],roomSplitHistory:p.roomSplitHistory||[],retiredFurniture:p.archivedFurniture||[]},files:Object.fromEntries(Object.entries(files).map(([name,data])=>[name,{role:name.startsWith('references/')?'reference':name==='floorplan.svg'||name==='floorplan.png'?'plan':name.endsWith('.png')?'scene-render':'document',sha256:createHash('sha256').update(data).digest('hex'),bytes:data.length}])) ,manifestSelfChecksum:'excluded: manifest.json cannot contain a non-self-referential checksum'}}
export async function createDeliveryArchive(store:AlvaStore,projectId:string,version:number,signal?:AbortSignal){
 signal?.throwIfAborted();const p=await store.snapshot(projectId,version);if(p.savedVersion!==version)throw new DomainError(409,'保存版本与交付版本不一致，请重新选择快照');if(!p.scene)throw new DomainError(422,'该快照尚无已确认户型，暂不能生成交付包');const svg=planSvg(p),files:Record<string,Uint8Array>={},fingerprint=snapshotFingerprint(p);
  const disabledEvidence=new Set(p.answers.filter(a=>!catalogue.find(q=>q.id===a.questionId)?.enabled).map(a=>a.evidenceId)),enabledAnswers=p.answers.filter(a=>catalogue.find(q=>q.id===a.questionId)?.enabled),json=(v:unknown)=>strToU8(JSON.stringify(v,null,2)),reference=sourceReference(p,version);
  if('file' in reference && reference.file)files[reference.file.path]=reference.file.data;
  files['scene.json']=json({format:'alva-scene-v1',projectId:p.id,version,snapshotFingerprint:fingerprint,units:'m',scene:p.scene,confirmedTopology:p.confirmedTopology?{id:p.confirmedTopology.id,version:p.confirmedTopology.version,sourceFingerprint:p.confirmedTopology.sourceFingerprint,calibration:p.confirmedTopology.calibration,assumptions:p.confirmedTopology.assumptions}:null,confirmedBuilding:p.confirmedBuilding||null});
  files['sidecar.json']=json({format:'alva-delivery-sidecar-v1',version,projectId:p.id,snapshotFingerprint:fingerprint,savedVersion:p.savedVersion,answers:enabledAnswers,evidence:p.evidence.filter(e=>!disabledEvidence.has(e.id)&&financialContentExcluded(e)),findings:p.findings.filter(financialContentExcluded),referencePreferences:confirmedReferencePreferencesFromProject(p).filter(financialContentExcluded),proposals:p.proposals.filter(financialContentExcluded),changes:p.changes.filter(financialContentExcluded),assets:p.assets,roomStyles:p.roomStyles,userContextEntries:p.userContextEntries?.filter(financialContentExcluded),layoutReview:p.layoutReview,layoutReviewAdoption:p.layoutReviewAdoption,roomMergeHistory:p.roomMergeHistory||[],roomSplitHistory:p.roomSplitHistory||[],retiredFurniture:p.archivedFurniture||[],retiredRelations:(p.archivedFurniture||[]).map(record=>({id:record.id,kind:'retired-furniture',targetId:record.item.id,reason:record.reason,createdAt:record.removedAt})),documentSourceVersion:version,deliverySections:{designer:sections(p,'designer'),owner:sections(p,'owner')}});
  files['references.json']=json({format:'alva-reference-index-v1',projectId:p.id,snapshotFingerprint:fingerprint,...reference});files['floorplan.svg']=strToU8(svg);
  console.log('[alva export] plan');const canvas=createCanvas(3000,2200);canvas.getContext('2d').drawImage(await loadImage(Buffer.from(svg)),0,0);files['floorplan.png']=canvas.toBuffer('image/png');files['designer.docx']=docx(`${p.name} · alva v${version} ${localize('设计师任务书')}`,sections(p,'designer'));
  console.log('[alva export] browser');signal?.throwIfAborted();const access=await store.issueInternalSession(p.id);let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;const abort=()=>{void browser?.close().catch(()=>{})};
  try{browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});signal?.addEventListener('abort',abort,{once:true});signal?.throwIfAborted();
   const origin=`http://127.0.0.1:${process.env.ALVA_PORT||4180}`;const context=await browser.newContext({viewport:{width:2000,height:1400}});await context.addCookies([{name:'alva_session',value:access.token,url:origin,httpOnly:true,sameSite:'Strict'}]);const page=await context.newPage();
   for(const [index,roomId] of ['',...p.scene!.rooms.map(r=>r.id)].entries()){signal?.throwIfAborted();console.log('[alva export] scene',index);await page.goto(`${origin}/render?version=${version}&room=${encodeURIComponent(roomId)}`);await page.waitForFunction(()=>!!(document.querySelector('[data-testid="scene-view"]') as any)?.alvaView,{},{timeout:30000});files[roomId?`room-${roomId}.png`:'whole-home.png']=await page.screenshot()}
   console.log('[alva export] pdf');const html=ownerHtml(p,version,files['whole-home.png'],svg);await page.setContent(html,{waitUntil:'load'});await page.evaluate(()=>document.fonts.ready);files['owner.pdf']=await page.pdf({format:'A4',printBackground:true,margin:{top:'15mm',bottom:'15mm',left:'15mm',right:'15mm'}});
  }catch(error){signal?.throwIfAborted();throw error}finally{signal?.removeEventListener('abort',abort);try{await browser?.close()}finally{await store.logout(access.token)}}
  signal?.throwIfAborted();console.log('[alva export] manifest');files['manifest.json']=json(deliveryManifest(p,version,fingerprint,files));return Buffer.from(zipSync(files));
}

const deliveries=new WeakMap<AlvaStore,Map<string,Promise<Buffer>>>();
export async function getDeliveryArchive(store:AlvaStore,projectId:string,version:number,signal?:AbortSignal){
 signal?.throwIfAborted();
 let cache=deliveries.get(store);if(!cache){cache=new Map();deliveries.set(store,cache)}const key=projectId+':'+version+':'+currentLanguage();
 let pending=cache.get(key);if(!pending){pending=createDeliveryArchive(store,projectId,version,signal);cache.set(key,pending);while(cache.size>2)cache.delete(cache.keys().next().value!)}
 try{const data=await pending;signal?.throwIfAborted();if(data.length>32*1024*1024)cache.delete(key);return data}catch(error){cache.delete(key);throw error}
}
export function registerExports(app:FastifyInstance,store:AlvaStore,session:(r:object)=>Session){
 app.get('/api/export/:version',async(req,reply)=>{const user=session(req),version=Number((req.params as {version:string}).version),archive=await getDeliveryArchive(store,user.projectId,version);reply.header('Content-Type','application/zip').header('Content-Disposition',`attachment; filename="alva-v${version}.zip"`);return archive});
}
