import type {FastifyInstance} from 'fastify';import {chromium} from '@playwright/test';import {zipSync,strToU8} from 'fflate';import {createHash} from 'node:crypto';import {createCanvas,loadImage} from '@napi-rs/canvas';
import type {AlvaStore,Session} from './store.js';import type {Project} from './model.js';import {catalogue} from './business.js';
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));
export function planSvg(p:Project){const s=p.scene!,points=s.walls.flatMap(w=>[w.a,w.b]);const minX=Math.min(...points.map(p=>p.x))-.6,minY=Math.min(...points.map(p=>p.y))-.6,width=Math.max(...points.map(p=>p.x))-minX+.6,height=Math.max(...points.map(p=>p.y))-minY+.6;return `<svg xmlns="http://www.w3.org/2000/svg" width="3000" height="2200" viewBox="${minX} ${minY} ${width} ${height}"><rect x="${minX}" y="${minY}" width="${width}" height="${height}" fill="#f5f3ea"/>${s.rooms.map(r=>`<polygon points="${r.polygon.map(p=>`${p.x},${p.y}`).join(' ')}" fill="#e5dfcf"/><text x="${r.polygon.reduce((s,p)=>s+p.x,0)/r.polygon.length}" y="${r.polygon.reduce((s,p)=>s+p.y,0)/r.polygon.length}" text-anchor="middle" font-size=".18" fill="#4e5645">${esc(r.name)}</text>`).join('')}${s.walls.map(w=>`<line x1="${w.a.x}" y1="${w.a.y}" x2="${w.b.x}" y2="${w.b.y}" stroke="#747869" stroke-width="${w.thickness}"/>`).join('')}${s.openings.map(o=>{const w=s.walls.find(w=>w.id===o.wallId)!,x=w.a.x+(w.b.x-w.a.x)*o.offset,y=w.a.y+(w.b.y-w.a.y)*o.offset,angle=Math.atan2(w.b.y-w.a.y,w.b.x-w.a.x)*180/Math.PI;return `<rect x="${x-o.width/2}" y="${y-.08}" width="${o.width}" height=".16" fill="${o.kind==='door'?'#f5f3ea':'#83a6b2'}" transform="rotate(${angle} ${x} ${y})"/>`}).join('')}${s.items.map(i=>`<rect x="${i.x-i.width/2}" y="${i.y-i.depth/2}" width="${i.width}" height="${i.depth}" transform="rotate(${i.rotation} ${i.x} ${i.y})" fill="${i.color}" stroke="#777" stroke-width=".02"/>`).join('')}<text x="${minX+.1}" y="${minY+.25}" font-size=".16">alva · v${p.savedVersion} · 单位 m · ${esc(s.calibration?.source||'未校准')}</text></svg>`}
export function sections(p:Project,audience:'owner'|'designer'){
 const enabledAnswers=p.answers.filter(a=>catalogue.find(q=>q.id===a.questionId)?.enabled),disabledEvidence=new Set(p.answers.filter(a=>!catalogue.find(q=>q.id===a.questionId)?.enabled).map(a=>a.evidenceId)),answers=enabledAnswers.map(a=>`${a.questionId} ${catalogue.find(q=>q.id===a.questionId)?.question||''}：${a.state==='answered'?a.text:a.state}（${a.confirmed?'业主已确认':'待确认'}）`),raw=p.evidence.filter(e=>(e.source==='chat'||e.source==='questionnaire')&&!disabledEvidence.has(e.id)).map(e=>`[${e.id}] ${e.quote}`),rooms=p.scene!.rooms.map(r=>`${r.name}：${r.purpose||'未调研'}；${r.locked?'已锁定':'可调整'}`),items=p.scene!.items.map(i=>`${i.name} [${i.id}]，房间${p.scene!.rooms.find(r=>r.id===i.roomId)?.name}，${i.width}×${i.depth}×${i.height}m，${i.material} ${i.color}；预览参数，非厂家认证值`),decisions=p.proposals.map(v=>`${v.title}：${v.status}；理由：${v.rationale}`),risks=p.findings.map(f=>`${f.title}（${f.kind}/${f.status}）：${f.reason}；${f.suggestion}`),next=['现场测量：责任人待指定；输入原图及现场尺寸，出口为核对后的尺寸记录。','方案深化：设计师待指定；依赖需求确认与专业核实，出口为可比较方案。','询价与材料确认：责任人待指定；依赖材料清单，费用与工期以实际报价为准。'],pending=catalogue.filter(q=>q.enabled&&!p.answers.some(a=>a.questionId===q.id)).map(q=>`${q.id} ${q.question}：未回答`);
 return audience==='designer'?[['D01 项目摘要',[p.name,...answers]],['D02 现状与尺寸依据',[`校准依据：${p.scene!.calibration?.source||'待确认'}；其他长度为比例换算；门窗/机电与结构状态需现场核实。`]],['D03 房间任务书',rooms],['D04 家具、设备与材料',items],['D05 用户原话与证据',raw],['D06 方案决策与取舍',decisions],['D08 实现计划',next],['D09 待核实与风险',[...risks,...pending]],['D10 交付与权限',[`同一保存版本v${p.savedVersion}；scene.json+sidecar.json+manifest.json；平面图及全屋/房间截图；设计师只读。`,`资产许可：${[...new Set(p.assets.map(a=>a.license))].join('；')}。本包不声明施工图、BIM或重新导入验收。`]]]:[['U01 我们听到的你',raw],['U02 全屋功能与空间角色',rooms],['U03 生活片段',['回家、工作、相处和夜间的细节以以下原话为依据；未提及的场景仍待你补充。',...answers]],['U04 细节、理由与取舍',[...decisions,...risks]],['U05 三张清单与下一步',[`已确认：${enabledAnswers.filter(a=>a.confirmed).length}条回答；保存版本v${p.savedVersion}。`,...pending,...risks.filter(r=>r.includes('professional')),...next]]];
}
function docx(title:string,parts:ReturnType<typeof sections>){const paragraph=(t:string,heading=false)=>`<w:p>${heading?'<w:pPr><w:pStyle w:val="Heading1"/></w:pPr>':''}<w:r><w:t xml:space="preserve">${esc(t)}</w:t></w:r></w:p>`;const content=paragraph(title,true)+parts.map(([name,lines])=>paragraph(name as string,true)+(lines as string[]).map(l=>paragraph(l)).join('')).join('');return zipSync({'[Content_Types].xml':strToU8('<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>'),'_rels/.rels':strToU8('<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>'),'word/document.xml':strToU8(`<?xml version="1.0" encoding="UTF-8"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${content}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1000" w:bottom="1000" w:left="1000" w:right="1000"/></w:sectPr></w:body></w:document>`),'word/_rels/document.xml.rels':strToU8('<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>'),'word/styles.xml':strToU8('<?xml version="1.0"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:rPr><w:rFonts w:eastAsia="Microsoft YaHei"/><w:sz w:val="22"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:basedOn w:val="Normal"/><w:rPr><w:b/><w:sz w:val="30"/></w:rPr></w:style></w:styles>')})}
export function registerExports(app:FastifyInstance,store:AlvaStore,session:(r:object)=>Session){
 app.get('/api/export/:version',async(req,reply)=>{
  const s=session(req),version=Number((req.params as {version:string}).version),p=await store.snapshot(s.projectId,version);const svg=planSvg(p),files:Record<string,Uint8Array>={};
  const disabledEvidence=new Set(p.answers.filter(a=>!catalogue.find(q=>q.id===a.questionId)?.enabled).map(a=>a.evidenceId)),enabledAnswers=p.answers.filter(a=>catalogue.find(q=>q.id===a.questionId)?.enabled),json=(v:unknown)=>strToU8(JSON.stringify(v,null,2));files['scene.json']=json({version,units:'m',scene:p.scene});files['sidecar.json']=json({version,projectId:p.id,answers:enabledAnswers,evidence:p.evidence.filter(e=>!disabledEvidence.has(e.id)),findings:p.findings,proposals:p.proposals,changes:p.changes,assets:p.assets});files['floorplan.svg']=strToU8(svg);
  console.log('[alva export] plan');const canvas=createCanvas(3000,2200);canvas.getContext('2d').drawImage(await loadImage(Buffer.from(svg)),0,0);files['floorplan.png']=canvas.toBuffer('image/png');files['designer.docx']=docx(`${p.name} · alva v${version}设计师任务书`,sections(p,'designer'));
  console.log('[alva export] browser');const access=await store.issueInternalSession(p.id);const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});
  try{
   const origin=`http://127.0.0.1:${process.env.ALVA_PORT||4180}`;const context=await browser.newContext({viewport:{width:2000,height:1400}});await context.addCookies([{name:'alva_session',value:access.token,url:origin,httpOnly:true,sameSite:'Strict'}]);const page=await context.newPage();
   for(const [index,roomId] of ['',...p.scene!.rooms.map(r=>r.id)].entries()){console.log('[alva export] scene',index);await page.goto(`${origin}/render?version=${version}&room=${encodeURIComponent(roomId)}`);await page.waitForFunction(()=>!!(document.querySelector('[data-testid="scene-view"]') as any)?.alvaView,{},{timeout:30000});files[roomId?`room-${roomId}.png`:'whole-home.png']=await page.screenshot()}
   console.log('[alva export] pdf');const owner=sections(p,'owner');const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><style>body{font:14px "WenQuanYi Zen Hei",sans-serif;color:#394233;line-height:1.8}h1{font-size:25px}h2{font-size:19px;border-bottom:1px solid #ccc;padding-top:20px}img,svg{width:100%;height:auto}section{break-inside:avoid}</style><h1>${esc(p.name)} · alva v${version}</h1><p>业主需求与方案交付 · 同版本场景图，待专业核实项独立列出</p><img src="data:image/png;base64,${Buffer.from(files['whole-home.png']).toString('base64')}"/>${owner.map(([name,lines])=>`<section><h2>${esc(name)}</h2>${(lines as string[]).map(t=>`<p>${esc(t)}</p>`).join('')}</section>`).join('')}<h2>同版本高清平面图</h2>${svg}</html>`;await page.setContent(html,{waitUntil:'load'});await page.evaluate(()=>document.fonts.ready);files['owner.pdf']=await page.pdf({format:'A4',printBackground:true,margin:{top:'15mm',bottom:'15mm',left:'15mm',right:'15mm'}});
  }finally{await browser.close()}
  console.log('[alva export] manifest');const manifest={projectId:p.id,version,units:'m',imageSource:'Rendered from this exact server snapshot; no reference images substituted',files:Object.fromEntries(Object.entries(files).map(([name,data])=>[name,{sha256:createHash('sha256').update(data).digest('hex'),bytes:data.length}]))};files['manifest.json']=json(manifest);reply.header('Content-Type','application/zip').header('Content-Disposition',`attachment; filename="alva-v${version}.zip"`);return Buffer.from(zipSync(files));
 });
}
