import type {FastifyInstance} from 'fastify';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {runCodex,type BusinessTool,type CodexInput} from './codex.js';
import {DomainError,reject,type Project} from './model.js';
import {AlvaStore,type Session} from './store.js';

export type ReferenceOrigin='model'|'manual';
export type ReferencePreference='like'|'dislike';
export type ReferenceAnnotation={id:string;batchId:string;origin:ReferenceOrigin;preference:ReferencePreference;feature:string;status:'pending'|'confirmed'|'cancelled';createdAt:string;confirmedAt?:string};
export type ReferenceBatch={id:string;projectId:string;roomId:string|null;filename:string;mime:'image/png'|'image/jpeg';sourceText:string;status:'pending'|'confirmed'|'cancelled';createdAt:string;annotations:ReferenceAnnotation[]};
type ImageInput={mime:'image/png'|'image/jpeg';data:string};
type Candidate={origin:ReferenceOrigin;preference:ReferencePreference;feature:string};
const Command=z.object({requestId:z.string().min(1).max(200),expectedRevision:z.number().int().min(0)});
const CandidateSchema=z.object({preference:z.enum(['like','dislike']),feature:z.string().trim().min(1).max(160)}).strict();
const forbiddenEvidence=/承重|结构安全|结构强度|防火性能|隔音性能|保温性能|耐久性能|\d+(?:\.\d+)?\s*(?:mm|cm|m|毫米|厘米|米)(?:$|[^A-Za-z0-9])/i;
function validateFeature(feature:string){if(forbiddenEvidence.test(feature))reject('参考图偏好不能记录尺寸、结构或材料性能结论');return feature.trim()}
export function validateReferenceImage(image:ImageInput){const data=image.data.trim();if(!data||data.length>12_000_000||!/^[A-Za-z0-9+/]+={0,2}$/.test(data)||data.length%4===1)reject('参考图内容无效');const bytes=Buffer.from(data,'base64');if(bytes.length>9_000_000)reject('参考图最大9MB');const png=bytes.length>=8&&bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])),jpeg=bytes.length>=3&&bytes[0]===255&&bytes[1]===216&&bytes[2]===255;if((image.mime==='image/png'&&!png)||(image.mime==='image/jpeg'&&!jpeg))reject('参考图内容与类型不匹配');return {...image,data}}
function extractJson(raw:string){let text=raw.trim();const fence=text.match(/^```(?:json)?\s*([\s\S]*?)\s*```$/i);if(fence)text=fence[1].trim();const start=text.indexOf('{'),end=text.lastIndexOf('}');return start>=0&&end>start?text.slice(start,end+1):text}
export function parseReferenceAnalysis(raw:string):Omit<Candidate,'origin'>[]{const value=JSON.parse(extractJson(raw));const parsed=z.object({annotations:z.array(CandidateSchema).max(6)}).strict().parse(value);return parsed.annotations.map(a=>({...a,feature:validateFeature(a.feature)}))}
export async function referenceModelAnalysis(image:ImageInput,sourceText:string,roomName:string|null,call:(input:CodexInput)=>Promise<string>=runCodex){const raw=await call({model:process.env.OPENAI_REFERENCE_MODEL?.trim()||process.env.OPENAI_MODEL?.trim()||'gemini-3.1-flash-lite',images:[`data:${image.mime};base64,${image.data}`],text:`你是室内设计参考图偏好分析器。只生成待用户确认的视觉偏好候选，不把图片当成事实证据。\n用户原话：${sourceText}\n作用房间：${roomName||'全屋'}\n输出纯JSON：{"annotations":[{"preference":"like|dislike","feature":"视觉特征"}]}，最多6项。只能描述视觉风格、色彩观感、家具造型、空间氛围、布置倾向等。禁止输出具体尺寸、承重/结构判断、材料真实成分或任何材料性能结论。用户没有表达喜欢或不喜欢时，只提取中性的可确认视觉特征并谨慎判断 preference；这些仍是模型候选，不是已确认需求。`});return parseReferenceAnalysis(raw)}

export type ConfirmedReferencePreference={batchId:string;annotationId:string;roomId:string|null;roomName:string|null;filename:string;sourceText:string;origin:ReferenceOrigin;preference:ReferencePreference;feature:string;confirmedAt:string|null;evidenceIds:string[];sourceLabel:'reference-image-confirmed'};

export function confirmedReferencePreferencesFromProject(project:Project){
 const findings=project.findings.filter(f=>f.objectIds.some(id=>id.startsWith('reference:'))&&f.evidenceIds.length>0);
 return findings.map(f=>({findingId:f.id,batchId:f.objectIds.find(id=>id.startsWith('reference:'))!.slice('reference:'.length),roomIds:[...f.roomIds],title:f.title,reason:f.reason,suggestion:f.suggestion,evidence:f.evidenceIds.map(id=>project.evidence.find(e=>e.id===id)).filter((e):e is NonNullable<typeof e>=>!!e),sourceLabel:'reference-image-confirmed' as const}));
}

export async function listConfirmedReferencePreferences(store:AlvaStore,projectId:string,roomId?:string|null):Promise<ConfirmedReferencePreference[]>{
 const project=await store.get(projectId),batches=await listReferenceBatches(store,projectId),findingByBatch=new Map<string,typeof project.findings>();
 for(const finding of project.findings){for(const id of finding.objectIds.filter(id=>id.startsWith('reference:'))){const batchId=id.slice('reference:'.length),list=findingByBatch.get(batchId)||[];list.push(finding);findingByBatch.set(batchId,list)}}
 const result:ConfirmedReferencePreference[]=[];
 for(const batch of batches.filter(b=>b.status==='confirmed'&&(roomId===undefined||b.roomId===roomId))){for(const annotation of batch.annotations.filter(a=>a.status==='confirmed')){const findings=(findingByBatch.get(batch.id)||[]).filter(f=>f.title.includes(annotation.feature));const evidenceIds=[...new Set(findings.flatMap(f=>f.evidenceIds))];result.push({batchId:batch.id,annotationId:annotation.id,roomId:batch.roomId,roomName:batch.roomId?project.scene?.rooms.find(r=>r.id===batch.roomId)?.name||null:null,filename:batch.filename,sourceText:batch.sourceText,origin:annotation.origin,preference:annotation.preference,feature:annotation.feature,confirmedAt:annotation.confirmedAt||null,evidenceIds,sourceLabel:'reference-image-confirmed'})}}
 return result;
}

export function confirmedReferencePreferencesTool(store:AlvaStore,projectId:string,roomId?:string|null):BusinessTool{return {name:'get_confirmed_reference_preferences',description:'读取业主已确认的参考图片视觉偏好及来源。只返回 confirmed 项，绝不返回 pending/cancelled；参考图不能证明尺寸、结构、真实材料身份或材料性能。',inputSchema:{type:'object',properties:{roomId:{type:['string','null']}},additionalProperties:false},run:async args=>{const parsed=z.object({roomId:z.string().nullable().optional()}).parse(args),scope=parsed.roomId===undefined?roomId:parsed.roomId,preferences=await listConfirmedReferencePreferences(store,projectId,scope);return {status:'confirmed_only',preferences,rule:'仅作为视觉偏好参考；不得作为尺寸、结构、真实材料身份或材料性能证据'}}}}

function rowBatch(row:any):ReferenceBatch{return {id:row.id,projectId:row.project_id,roomId:row.room_id,filename:row.filename,mime:row.mime,sourceText:row.source_text,status:row.status,createdAt:new Date(row.created_at).toISOString(),annotations:[]}}
function rowAnnotation(row:any):ReferenceAnnotation{return {id:row.id,batchId:row.batch_id,origin:row.origin,preference:row.preference,feature:row.feature,status:row.status,createdAt:new Date(row.created_at).toISOString(),...(row.confirmed_at?{confirmedAt:new Date(row.confirmed_at).toISOString()}:{})}}
export async function listReferenceBatches(store:AlvaStore,projectId:string){const batches=(await store.db.query<any>('SELECT id,project_id,room_id,filename,mime,source_text,status,created_at FROM alva_reference_batches WHERE project_id=$1 ORDER BY created_at DESC',[projectId])).rows.map(rowBatch),annotations=(await store.db.query<any>('SELECT id,batch_id,origin,preference,feature,status,created_at,confirmed_at FROM alva_reference_annotations WHERE project_id=$1 ORDER BY created_at',[projectId])).rows.map(rowAnnotation);for(const batch of batches)batch.annotations=annotations.filter(a=>a.batchId===batch.id);return batches}
export async function createReferenceBatch(store:AlvaStore,input:{projectId:string;requestId:string;roomId:string|null;filename:string;image:ImageInput;sourceText:string;candidates:Candidate[]}){const prior=(await store.db.query<any>('SELECT id FROM alva_reference_batches WHERE project_id=$1 AND request_id=$2',[input.projectId,input.requestId])).rows[0];if(prior)return (await listReferenceBatches(store,input.projectId)).find(b=>b.id===prior.id)!;const id=randomUUID(),now=new Date().toISOString();await store.db.transaction(async tx=>{await tx.query('INSERT INTO alva_reference_batches(id,project_id,request_id,room_id,filename,mime,image_data,source_text,status,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[id,input.projectId,input.requestId,input.roomId,input.filename,input.image.mime,input.image.data,input.sourceText,'pending',now]);for(const candidate of input.candidates){await tx.query('INSERT INTO alva_reference_annotations(id,batch_id,project_id,origin,preference,feature,status,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[randomUUID(),id,input.projectId,candidate.origin,candidate.preference,validateFeature(candidate.feature),'pending',now])}});return (await listReferenceBatches(store,input.projectId)).find(b=>b.id===id)!}
export async function createChatReferenceCandidates(store:AlvaStore,input:{projectId:string;requestId:string;roomId:string|null;image:ImageInput;sourceText:string;annotations:{preference:ReferencePreference;feature:string}[]}){return createReferenceBatch(store,{...input,filename:'Chat参考图',candidates:input.annotations.map(a=>({...a,origin:'model' as const}))})}

export function registerReferences(app:FastifyInstance,store:AlvaStore,session:(r:object)=>Session,modelCall:(input:CodexInput)=>Promise<string>=runCodex){const owner=(r:object)=>{const s=session(r);if(s.role!=='owner')reject('仅业主可修改参考偏好',403);return s.projectId};
 app.get('/api/references',async req=>listReferenceBatches(store,session(req).projectId));
 app.get('/api/references/confirmed',async req=>{const s=session(req),query=z.object({roomId:z.string().nullable().optional()}).parse(req.query);return {status:'confirmed_only',preferences:await listConfirmedReferencePreferences(store,s.projectId,query.roomId)}});
 app.get('/api/references/:id/image',async(req,reply)=>{const s=session(req),id=(req.params as {id:string}).id,row=(await store.db.query<any>('SELECT mime,image_data FROM alva_reference_batches WHERE id=$1 AND project_id=$2',[id,s.projectId])).rows[0];if(!row)reject('参考图不存在',404);reply.type(row.mime).send(Buffer.from(row.image_data,'base64'))});
 app.post('/api/references/analyze',async req=>{const b=Command.extend({roomId:z.string().nullable(),filename:z.string().trim().min(1).max(255),sourceText:z.string().trim().min(1).max(3000),image:z.object({mime:z.enum(['image/png','image/jpeg']),data:z.string().max(12_000_000)})}).parse(req.body),projectId=owner(req),project=await store.get(projectId);if(project.revision!==b.expectedRevision)reject('项目已更新，请重新读取后再分析',409);if(b.roomId&&!project.scene?.rooms.some(r=>r.id===b.roomId))reject('作用房间不存在');const image=validateReferenceImage(b.image),roomName=b.roomId?project.scene?.rooms.find(r=>r.id===b.roomId)?.name||null:null,analysis=await referenceModelAnalysis(image,b.sourceText,roomName,modelCall);return createReferenceBatch(store,{projectId,requestId:b.requestId,roomId:b.roomId,filename:b.filename,image,sourceText:b.sourceText,candidates:analysis.map(a=>({...a,origin:'model'}))})});
 app.post('/api/references/:id/manual',async req=>{const b=Command.extend({preference:z.enum(['like','dislike']),feature:z.string().trim().min(1).max(160)}).parse(req.body),projectId=owner(req),project=await store.get(projectId);if(project.revision!==b.expectedRevision)reject('项目已更新，请重新读取后再标注',409);const batchId=(req.params as {id:string}).id,batch=(await store.db.query<any>('SELECT status FROM alva_reference_batches WHERE id=$1 AND project_id=$2',[batchId,projectId])).rows[0];if(!batch||batch.status!=='pending')reject('参考图候选已处理或不存在');await store.db.query('INSERT INTO alva_reference_annotations(id,batch_id,project_id,origin,preference,feature,status) VALUES($1,$2,$3,$4,$5,$6,$7)',[randomUUID(),batchId,projectId,'manual',b.preference,validateFeature(b.feature),'pending']);return (await listReferenceBatches(store,projectId)).find(x=>x.id===batchId)});
 app.post('/api/references/:id/cancel',async req=>{const b=Command.parse(req.body),projectId=owner(req),project=await store.get(projectId);if(project.revision!==b.expectedRevision)reject('项目已更新，请重新读取后再取消',409);const batchId=(req.params as {id:string}).id;await store.db.transaction(async tx=>{const row=(await tx.query<any>('SELECT status FROM alva_reference_batches WHERE id=$1 AND project_id=$2 FOR UPDATE',[batchId,projectId])).rows[0];if(!row)reject('参考图候选不存在');if(row.status==='confirmed')reject('已确认偏好不能作为未确认候选取消');await tx.query("UPDATE alva_reference_batches SET status='cancelled' WHERE id=$1 AND project_id=$2",[batchId,projectId]);await tx.query("UPDATE alva_reference_annotations SET status='cancelled' WHERE batch_id=$1 AND status='pending'",[batchId])});return {cancelled:true,revision:project.revision}});
 app.post('/api/references/confirm',async req=>{const b=Command.extend({batchId:z.string(),annotationIds:z.array(z.string()).min(1).max(12),confirmed:z.literal(true)}).parse(req.body),projectId=owner(req),batchRow=(await store.db.query<any>('SELECT id,room_id,filename,source_text,status FROM alva_reference_batches WHERE id=$1 AND project_id=$2',[b.batchId,projectId])).rows[0];if(!batchRow||batchRow.status!=='pending')reject('参考图候选已处理或不存在');const rows=(await store.db.query<any>("SELECT id,origin,preference,feature FROM alva_reference_annotations WHERE batch_id=$1 AND project_id=$2 AND status='pending'",[b.batchId,projectId])).rows,chosen=rows.filter((r:any)=>b.annotationIds.includes(r.id));if(chosen.length!==new Set(b.annotationIds).size)reject('选择的偏好候选无效');const result=await store.mutate(projectId,b.requestId,b.expectedRevision,'reference-preference-confirm',b,(p:Project)=>{if(batchRow.room_id&&!p.scene?.rooms.some(r=>r.id===batchRow.room_id))throw new DomainError(409,'参考图原作用房间已变化，请重新选择房间并生成候选');for(const row of chosen){const evidenceId=randomUUID(),liked=row.preference==='like',quote=`参考图 ${batchRow.filename}；用户原话：“${batchRow.source_text}”；用户确认${liked?'喜欢':'不喜欢'}“${row.feature}”`;p.evidence.push({id:evidenceId,quote,source:'image',...(batchRow.room_id?{roomId:batchRow.room_id}:{}),createdAt:new Date().toISOString()});p.findings.push({id:randomUUID(),kind:'requirement',title:`参考图偏好：${liked?'喜欢':'不喜欢'} ${row.feature}`,reason:`该项由${row.origin==='manual'?'用户手动标注':'模型候选经用户确认'}形成，仅表示视觉偏好。`,suggestion:'后续方案可参考这一视觉偏好；参考图不得作为尺寸、结构或材料真实性/性能的证据。',objectIds:[`reference:${b.batchId}`],roomIds:batchRow.room_id?[batchRow.room_id]:[],evidenceIds:[evidenceId],confidence:'high',status:'pending',stage:'intake'})}p.changes.push({id:randomUUID(),description:`确认参考图偏好 ${chosen.length} 项`,evidenceIds:p.evidence.slice(-chosen.length).map(e=>e.id),context:['参考图只作为视觉偏好来源，不作为尺寸、结构或材料性能证据'],createdAt:new Date().toISOString()})});await store.db.transaction(async tx=>{await tx.query("UPDATE alva_reference_batches SET status='confirmed' WHERE id=$1 AND project_id=$2",[b.batchId,projectId]);await tx.query("UPDATE alva_reference_annotations SET status=CASE WHEN id=ANY($2) THEN 'confirmed' ELSE 'cancelled' END,confirmed_at=CASE WHEN id=ANY($2) THEN now() ELSE confirmed_at END WHERE batch_id=$1 AND status='pending'",[b.batchId,b.annotationIds])});return result});
}
