import {projectFetch as fetch} from '../projects/session.js';
import React,{useEffect,useMemo,useState} from 'react';
import type {Project,SceneData} from '../../../api/model.js';
import {SceneView} from '../SceneView.js';
import {BuildingView} from '../BuildingView.js';

type VersionRow={version:number;summary:string;created_at:string};
type Props={open:boolean;workingProject:Project;readOnly:boolean;busy:boolean;onClose:()=>void;onRestore?:(version:number)=>Promise<unknown>};
async function request(path:string){const response=await fetch('/api'+path);const data=await response.json();if(!response.ok)throw new Error(data.error||'请求失败');return data}
const timeLabel=(value:string)=>{const d=new Date(value);return Number.isFinite(d.getTime())?d.toLocaleString():'时间未知'};
function ReadonlyPlan({scene}:{scene:SceneData}){const points=[...scene.walls.flatMap(w=>[w.a,w.b]),...scene.rooms.flatMap(r=>r.polygon)];const xs=points.map(p=>p.x),ys=points.map(p=>p.y),minX=(points.length?Math.min(...xs):0)-.5,minY=(points.length?Math.min(...ys):0)-.5,width=(points.length?Math.max(...xs):4)-minX+.5,height=(points.length?Math.max(...ys):4)-minY+.5;return <svg className="snapshot-plan" viewBox={`${minX} ${minY} ${width} ${height}`} aria-label="快照二维预览">{scene.rooms.map(r=>{const cx=r.polygon.reduce((s,p)=>s+p.x,0)/r.polygon.length,cy=r.polygon.reduce((s,p)=>s+p.y,0)/r.polygon.length;return <g key={r.id}><polygon points={r.polygon.map(p=>`${p.x},${p.y}`).join(' ')} fill="#e2dbc9" fillOpacity=".7"/><text x={cx} y={cy} textAnchor="middle" fontSize=".18" fill="#4e5645">{r.name}</text></g>})}{scene.walls.map(w=><line key={w.id} x1={w.a.x} y1={w.a.y} x2={w.b.x} y2={w.b.y} stroke="#6f7168" strokeWidth={w.thickness}/>)}{scene.openings.map(o=>{const w=scene.walls.find(w=>w.id===o.wallId);if(!w)return null;const x=w.a.x+(w.b.x-w.a.x)*o.offset,y=w.a.y+(w.b.y-w.a.y)*o.offset,angle=Math.atan2(w.b.y-w.a.y,w.b.x-w.a.x)*180/Math.PI;return <rect key={o.id} x={x-o.width/2} y={y-.08} width={o.width} height=".16" fill={o.kind==='door'?'#f5f3ea':'#7faeb5'} transform={`rotate(${angle} ${x} ${y})`}/>})}{scene.items.map(i=><rect key={i.id} x={i.x-i.width/2} y={i.y-i.depth/2} width={i.width} height={i.depth} transform={`rotate(${i.rotation} ${i.x} ${i.y})`} fill={i.color} stroke="#8f8f7f" strokeWidth=".03"/>)}</svg>}
export function SnapshotHistory({open,workingProject,readOnly,busy,onClose,onRestore}:Props){
 const [versions,setVersions]=useState<VersionRow[]>([]),[loading,setLoading]=useState(false),[listError,setListError]=useState(''),[preview,setPreview]=useState<Project|null>(null),[previewVersion,setPreviewVersion]=useState<number|null>(null),[previewError,setPreviewError]=useState(''),[tab,setTab]=useState<'2d'|'3d'|'requirements'>('2d'),[selected,setSelected]=useState(''),[room,setRoom]=useState('');
 const loadList=async()=>{setLoading(true);setListError('');try{setVersions(await request('/versions'))}catch(e){setListError((e as Error).message)}finally{setLoading(false)}};
 useEffect(()=>{if(open){setPreview(null);setPreviewVersion(null);setPreviewError('');void loadList()}},[open]);
 const loadPreview=async(version:number)=>{setLoading(true);setPreviewError('');try{const p=await request('/versions/'+version);setPreview(p);setPreviewVersion(version);setTab('2d');setSelected('');setRoom('')}catch(e){setPreview(null);setPreviewVersion(version);setPreviewError((e as Error).message)}finally{setLoading(false)}};
 const scene=preview?.candidate||preview?.scene,building=preview?.buildingCandidate||preview?.confirmedBuilding;
 const requirements=useMemo(()=>preview?.findings.filter(f=>f.kind==='requirement')||[],[preview]);
 if(!open)return null;
 return <div className="snapshot-history-overlay" role="dialog" aria-modal="true" aria-label="保存快照历史"><section className="snapshot-history-shell"><header><div><span className="eyebrow">只读快照</span><h2>{previewVersion?`预览保存版本 v${previewVersion}`:'保存版本'}</h2><p>{previewVersion?'这是保存时的独立副本。当前未保存工作稿没有被替换。':'这里只有你手动点击保存创建的全局存档点。日常编辑、确认、生成和恢复不会自动出现在这里。'}</p></div><button onClick={onClose}>退出预览</button></header>
  {!preview&&<div className="snapshot-history-list"><div className="snapshot-current-draft"><b>当前工作稿</b><span>{workingProject.dirty?'有未保存修改':'当前与最近一次保存一致'}</span><small>{workingProject.savedVersion?`最近手动保存：v${workingProject.savedVersion}`:'还没有手动保存版本'}</small></div>{loading&&<p>正在读取保存版本…</p>}{listError&&<div className="snapshot-error" role="alert"><p>{listError}</p><button onClick={()=>void loadList()}>重试列表</button></div>}{!loading&&!listError&&versions.length===0&&<div className="snapshot-empty"><h3>还没有保存快照</h3><p>当前工作稿可能已有修改，但只有你明确点击“保存现在”后才会创建这里的存档点。</p></div>}{versions.map(v=><article key={v.version}><div><b>v{v.version} · {v.summary}</b><small>{timeLabel(v.created_at)}</small></div><button disabled={loading} onClick={()=>void loadPreview(v.version)}>只读预览</button></article>)}</div>}
  {previewError&&<div className="snapshot-error" role="alert"><p>快照预览失败：{previewError}</p><button disabled={loading||previewVersion===null} onClick={()=>previewVersion!==null&&void loadPreview(previewVersion)}>重试这个快照</button><button onClick={()=>{setPreviewError('');setPreviewVersion(null)}}>返回列表</button></div>}
  {preview&&<div className="snapshot-preview"><div className="snapshot-preview-meta"><span>保存版本 v{preview.savedVersion}</span><span>项目：{preview.name}</span><span>{preview.dirty?'保存时仍标记为工作稿':'保存时状态已归档'}</span><span>当前页面只读</span></div><nav><button className={tab==='2d'?'active':''} onClick={()=>setTab('2d')}>二维</button><button className={tab==='3d'?'active':''} onClick={()=>setTab('3d')}>三维</button><button className={tab==='requirements'?'active':''} onClick={()=>setTab('requirements')}>需求与依据</button></nav>
   {tab==='2d'&&<div className="snapshot-visual">{scene?<ReadonlyPlan scene={scene}/>:<div className="snapshot-empty"><p>这个快照尚未包含户型场景。</p></div>}</div>}
   {tab==='3d'&&<div className="snapshot-visual snapshot-3d">{scene?(building?<BuildingView building={building} topology={scene} focusRoom={room} selected={selected} time={14} day={172} onSelect={setSelected} onFocusRoom={setRoom}/>:<SceneView scene={scene} selected={selected} onSelect={setSelected} mode="3d" time={14} day={172} focusRoom={room}/>):<div className="snapshot-empty"><p>这个快照尚未包含可预览的 3D 场景。</p></div>}</div>}
   {tab==='requirements'&&<div className="snapshot-requirements"><section><h3>已保存问卷 / 需求</h3>{preview.answers.length?preview.answers.map(a=><article key={`${a.questionId}-${a.roomId||'project'}`}><b>{a.questionId}{a.roomId?` · ${a.roomId}`:''}</b><p>{a.text||a.state}</p><small>{a.confirmed?'已确认':'待确认'} · {a.locked?'已锁定':'未锁定'}</small></article>):<p>这个快照没有问卷答案。</p>}{requirements.map(f=><article key={f.id}><b>{f.title}</b><p>{f.reason}</p><small>{f.status} · {f.confidence}</small></article>)}</section><section><h3>保存时的依据</h3>{preview.evidence.length?preview.evidence.map(e=><article key={e.id}><b>{e.source}{e.roomId?` · ${e.roomId}`:''}</b><p>{e.quote}</p><small>{e.id}</small></article>):<p>这个快照没有来源依据。</p>}</section></div>}
   <footer><button onClick={()=>{setPreview(null);setPreviewVersion(null);setPreviewError('')}}>← 返回版本列表</button>{!readOnly&&onRestore&&<button className="primary" disabled={busy} onClick={()=>{if(previewVersion!==null&&window.confirm(`确认把保存版本 v${previewVersion} 恢复为当前工作稿吗？当前未保存修改会被替换，而且恢复前不会自动创建备份点。恢复完成后如需保留，请再次手动保存。`))void onRestore(previewVersion)}}>明确恢复到工作稿</button>}</footer></div>}
 </section></div>
}
